// vvp_clipper_0_intel_vvp_slave_front_end_2450_zo55rva.v

// This file was auto-generated from intel_vvp_slave_front_end_hw.tcl.  If you edit it your changes
// will probably be lost.
// 
// Generated using ACDS version 25.3 109

`timescale 1 ps / 1 ps
module vvp_clipper_0_intel_vvp_slave_front_end_2450_zo55rva #(
		parameter AV_MAX_PENDING_READS = 2
	) (
		input  wire        main_clock_clk,             //   main_clock.clk,          Clock Input
		input  wire        main_reset_reset,           //   main_reset.reset
		output wire [6:0]  av_mm_master_address,       // av_mm_master.address
		input  wire        av_mm_master_waitrequest,   //             .waitrequest
		output wire        av_mm_master_write,         //             .write
		output wire [31:0] av_mm_master_writedata,     //             .writedata
		output wire [3:0]  av_mm_master_byteenable,    //             .byteenable
		output wire        av_mm_master_read,          //             .read
		input  wire [31:0] av_mm_master_readdata,      //             .readdata
		input  wire        av_mm_master_readdatavalid, //             .readdatavalid
		input  wire [6:0]  av_mm_slave_address,        //  av_mm_slave.address
		input  wire        av_mm_slave_write,          //             .write
		input  wire [3:0]  av_mm_slave_byteenable,     //             .byteenable
		input  wire [31:0] av_mm_slave_writedata,      //             .writedata
		input  wire        av_mm_slave_read,           //             .read
		output wire [31:0] av_mm_slave_readdata,       //             .readdata
		output wire        av_mm_slave_readdatavalid,  //             .readdatavalid
		output wire        av_mm_slave_waitrequest     //             .waitrequest
	);

	wire         main_reset_bridge_out_reset_reset;                  // main_reset_bridge:out_rst -> [mm_interconnect_0:mm_reset_hold_av_mm_master_translator_reset_reset_bridge_in_reset_reset, mm_reset_hold:rst, ro_reg:rst]
	wire         mm_reset_hold_av_mm_master_waitrequest;             // mm_interconnect_0:mm_reset_hold_av_mm_master_waitrequest -> mm_reset_hold:av_mm_master_waitrequest
	wire  [31:0] mm_reset_hold_av_mm_master_readdata;                // mm_interconnect_0:mm_reset_hold_av_mm_master_readdata -> mm_reset_hold:av_mm_master_readdata
	wire   [8:0] mm_reset_hold_av_mm_master_address;                 // mm_reset_hold:av_mm_master_address -> mm_interconnect_0:mm_reset_hold_av_mm_master_address
	wire   [3:0] mm_reset_hold_av_mm_master_byteenable;              // mm_reset_hold:av_mm_master_byteenable -> mm_interconnect_0:mm_reset_hold_av_mm_master_byteenable
	wire         mm_reset_hold_av_mm_master_read;                    // mm_reset_hold:av_mm_master_read -> mm_interconnect_0:mm_reset_hold_av_mm_master_read
	wire         mm_reset_hold_av_mm_master_readdatavalid;           // mm_interconnect_0:mm_reset_hold_av_mm_master_readdatavalid -> mm_reset_hold:av_mm_master_readdatavalid
	wire         mm_reset_hold_av_mm_master_write;                   // mm_reset_hold:av_mm_master_write -> mm_interconnect_0:mm_reset_hold_av_mm_master_write
	wire  [31:0] mm_reset_hold_av_mm_master_writedata;               // mm_reset_hold:av_mm_master_writedata -> mm_interconnect_0:mm_reset_hold_av_mm_master_writedata
	wire  [31:0] mm_interconnect_0_ro_reg_av_mm_slave_readdata;      // ro_reg:av_mm_slave_readdata -> mm_interconnect_0:ro_reg_av_mm_slave_readdata
	wire         mm_interconnect_0_ro_reg_av_mm_slave_waitrequest;   // ro_reg:av_mm_slave_waitrequest -> mm_interconnect_0:ro_reg_av_mm_slave_waitrequest
	wire   [6:0] mm_interconnect_0_ro_reg_av_mm_slave_address;       // mm_interconnect_0:ro_reg_av_mm_slave_address -> ro_reg:av_mm_slave_address
	wire         mm_interconnect_0_ro_reg_av_mm_slave_read;          // mm_interconnect_0:ro_reg_av_mm_slave_read -> ro_reg:av_mm_slave_read
	wire   [3:0] mm_interconnect_0_ro_reg_av_mm_slave_byteenable;    // mm_interconnect_0:ro_reg_av_mm_slave_byteenable -> ro_reg:av_mm_slave_byteenable
	wire         mm_interconnect_0_ro_reg_av_mm_slave_readdatavalid; // ro_reg:av_mm_slave_readdatavalid -> mm_interconnect_0:ro_reg_av_mm_slave_readdatavalid
	wire         mm_interconnect_0_ro_reg_av_mm_slave_write;         // mm_interconnect_0:ro_reg_av_mm_slave_write -> ro_reg:av_mm_slave_write
	wire  [31:0] mm_interconnect_0_ro_reg_av_mm_slave_writedata;     // mm_interconnect_0:ro_reg_av_mm_slave_writedata -> ro_reg:av_mm_slave_writedata

	generate
		// If any of the display statements (or deliberately broken
		// instantiations) within this generate block triggers then this module
		// has been instantiated this module with a set of parameters different
		// from those it was generated for.  This will usually result in a
		// non-functioning system.
		if (AV_MAX_PENDING_READS != 2)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					av_max_pending_reads_check ( .error(1'b1) );
		end
	endgenerate

	intel_vvp_reset_bridge main_reset_bridge (
		.clk     (main_clock_clk),                    //   input,  width = 1,       clk.clk
		.in_rst  (main_reset_reset),                  //   input,  width = 1,  in_reset.reset
		.out_rst (main_reset_bridge_out_reset_reset)  //  output,  width = 1, out_reset.reset
	);

	vvp_clipper_0_intel_vvp_ro_reg_servicer_2450_xkahpyq #(
		.P_VID_PID                 (1794572845),
		.P_VERSION_NUMBER          (403046401),
		.P_AV_MM_SLAVE_ADDR_WIDTH  (7),
		.P_AV_MM_MASTER_ADDR_WIDTH (7)
	) ro_reg (
		.clk                        (main_clock_clk),                                     //   input,   width = 1,   main_clock.clk
		.rst                        (main_reset_bridge_out_reset_reset),                  //   input,   width = 1,   main_reset.reset
		.av_mm_master_address       (av_mm_master_address),                               //  output,   width = 7, av_mm_master.address
		.av_mm_master_waitrequest   (av_mm_master_waitrequest),                           //   input,   width = 1,             .waitrequest
		.av_mm_master_write         (av_mm_master_write),                                 //  output,   width = 1,             .write
		.av_mm_master_writedata     (av_mm_master_writedata),                             //  output,  width = 32,             .writedata
		.av_mm_master_byteenable    (av_mm_master_byteenable),                            //  output,   width = 4,             .byteenable
		.av_mm_master_read          (av_mm_master_read),                                  //  output,   width = 1,             .read
		.av_mm_master_readdata      (av_mm_master_readdata),                              //   input,  width = 32,             .readdata
		.av_mm_master_readdatavalid (av_mm_master_readdatavalid),                         //   input,   width = 1,             .readdatavalid
		.av_mm_slave_address        (mm_interconnect_0_ro_reg_av_mm_slave_address),       //   input,   width = 7,  av_mm_slave.address
		.av_mm_slave_write          (mm_interconnect_0_ro_reg_av_mm_slave_write),         //   input,   width = 1,             .write
		.av_mm_slave_byteenable     (mm_interconnect_0_ro_reg_av_mm_slave_byteenable),    //   input,   width = 4,             .byteenable
		.av_mm_slave_writedata      (mm_interconnect_0_ro_reg_av_mm_slave_writedata),     //   input,  width = 32,             .writedata
		.av_mm_slave_read           (mm_interconnect_0_ro_reg_av_mm_slave_read),          //   input,   width = 1,             .read
		.av_mm_slave_readdata       (mm_interconnect_0_ro_reg_av_mm_slave_readdata),      //  output,  width = 32,             .readdata
		.av_mm_slave_readdatavalid  (mm_interconnect_0_ro_reg_av_mm_slave_readdatavalid), //  output,   width = 1,             .readdatavalid
		.av_mm_slave_waitrequest    (mm_interconnect_0_ro_reg_av_mm_slave_waitrequest)    //  output,   width = 1,             .waitrequest
	);

	intel_vvp_mm_agent_reset_hold #(
		.WORD_ADDR_WIDTH (7)
	) mm_reset_hold (
		.clk                        (main_clock_clk),                           //   input,   width = 1,   main_clock.clk
		.rst                        (main_reset_bridge_out_reset_reset),        //   input,   width = 1,   main_reset.reset
		.av_mm_slave_address        (av_mm_slave_address),                      //   input,   width = 7,  av_mm_slave.address
		.av_mm_slave_write          (av_mm_slave_write),                        //   input,   width = 1,             .write
		.av_mm_slave_byteenable     (av_mm_slave_byteenable),                   //   input,   width = 4,             .byteenable
		.av_mm_slave_writedata      (av_mm_slave_writedata),                    //   input,  width = 32,             .writedata
		.av_mm_slave_read           (av_mm_slave_read),                         //   input,   width = 1,             .read
		.av_mm_slave_readdata       (av_mm_slave_readdata),                     //  output,  width = 32,             .readdata
		.av_mm_slave_readdatavalid  (av_mm_slave_readdatavalid),                //  output,   width = 1,             .readdatavalid
		.av_mm_slave_waitrequest    (av_mm_slave_waitrequest),                  //  output,   width = 1,             .waitrequest
		.av_mm_master_address       (mm_reset_hold_av_mm_master_address),       //  output,   width = 9, av_mm_master.address
		.av_mm_master_waitrequest   (mm_reset_hold_av_mm_master_waitrequest),   //   input,   width = 1,             .waitrequest
		.av_mm_master_write         (mm_reset_hold_av_mm_master_write),         //  output,   width = 1,             .write
		.av_mm_master_writedata     (mm_reset_hold_av_mm_master_writedata),     //  output,  width = 32,             .writedata
		.av_mm_master_byteenable    (mm_reset_hold_av_mm_master_byteenable),    //  output,   width = 4,             .byteenable
		.av_mm_master_read          (mm_reset_hold_av_mm_master_read),          //  output,   width = 1,             .read
		.av_mm_master_readdata      (mm_reset_hold_av_mm_master_readdata),      //   input,  width = 32,             .readdata
		.av_mm_master_readdatavalid (mm_reset_hold_av_mm_master_readdatavalid)  //   input,   width = 1,             .readdatavalid
	);

	vvp_clipper_0_altera_mm_interconnect_1920_epi4vay mm_interconnect_0 (
		.mm_reset_hold_av_mm_master_address                                      (mm_reset_hold_av_mm_master_address),                 //   input,   width = 9,                                        mm_reset_hold_av_mm_master.address
		.mm_reset_hold_av_mm_master_waitrequest                                  (mm_reset_hold_av_mm_master_waitrequest),             //  output,   width = 1,                                                                  .waitrequest
		.mm_reset_hold_av_mm_master_byteenable                                   (mm_reset_hold_av_mm_master_byteenable),              //   input,   width = 4,                                                                  .byteenable
		.mm_reset_hold_av_mm_master_read                                         (mm_reset_hold_av_mm_master_read),                    //   input,   width = 1,                                                                  .read
		.mm_reset_hold_av_mm_master_readdata                                     (mm_reset_hold_av_mm_master_readdata),                //  output,  width = 32,                                                                  .readdata
		.mm_reset_hold_av_mm_master_readdatavalid                                (mm_reset_hold_av_mm_master_readdatavalid),           //  output,   width = 1,                                                                  .readdatavalid
		.mm_reset_hold_av_mm_master_write                                        (mm_reset_hold_av_mm_master_write),                   //   input,   width = 1,                                                                  .write
		.mm_reset_hold_av_mm_master_writedata                                    (mm_reset_hold_av_mm_master_writedata),               //   input,  width = 32,                                                                  .writedata
		.ro_reg_av_mm_slave_address                                              (mm_interconnect_0_ro_reg_av_mm_slave_address),       //  output,   width = 7,                                                ro_reg_av_mm_slave.address
		.ro_reg_av_mm_slave_write                                                (mm_interconnect_0_ro_reg_av_mm_slave_write),         //  output,   width = 1,                                                                  .write
		.ro_reg_av_mm_slave_read                                                 (mm_interconnect_0_ro_reg_av_mm_slave_read),          //  output,   width = 1,                                                                  .read
		.ro_reg_av_mm_slave_readdata                                             (mm_interconnect_0_ro_reg_av_mm_slave_readdata),      //   input,  width = 32,                                                                  .readdata
		.ro_reg_av_mm_slave_writedata                                            (mm_interconnect_0_ro_reg_av_mm_slave_writedata),     //  output,  width = 32,                                                                  .writedata
		.ro_reg_av_mm_slave_byteenable                                           (mm_interconnect_0_ro_reg_av_mm_slave_byteenable),    //  output,   width = 4,                                                                  .byteenable
		.ro_reg_av_mm_slave_readdatavalid                                        (mm_interconnect_0_ro_reg_av_mm_slave_readdatavalid), //   input,   width = 1,                                                                  .readdatavalid
		.ro_reg_av_mm_slave_waitrequest                                          (mm_interconnect_0_ro_reg_av_mm_slave_waitrequest),   //   input,   width = 1,                                                                  .waitrequest
		.mm_reset_hold_av_mm_master_translator_reset_reset_bridge_in_reset_reset (main_reset_bridge_out_reset_reset),                  //   input,   width = 1, mm_reset_hold_av_mm_master_translator_reset_reset_bridge_in_reset.reset
		.main_clk_bridge_out_clk_clk                                             (main_clock_clk)                                      //   input,   width = 1,                                           main_clk_bridge_out_clk.clk
	);

endmodule
