// video_path.v

// Generated using ACDS version 25.3 109

`timescale 1 ps / 1 ps
module video_path (
		input  wire         sys_clk_in_clk,                                 //                         sys_clk_in.clk
		input  wire         sys_rst_in_reset,                               //                         sys_rst_in.reset
		output wire         mm_bus_in_waitrequest,                          //                          mm_bus_in.waitrequest
		output wire [63:0]  mm_bus_in_readdata,                             //                                   .readdata
		output wire         mm_bus_in_readdatavalid,                        //                                   .readdatavalid
		input  wire [0:0]   mm_bus_in_burstcount,                           //                                   .burstcount
		input  wire [63:0]  mm_bus_in_writedata,                            //                                   .writedata
		input  wire [12:0]  mm_bus_in_address,                              //                                   .address
		input  wire         mm_bus_in_write,                                //                                   .write
		input  wire         mm_bus_in_read,                                 //                                   .read
		input  wire [7:0]   mm_bus_in_byteenable,                           //                                   .byteenable
		input  wire         mm_bus_in_debugaccess,                          //                                   .debugaccess
		input  wire [63:0]  vvp_demosaic_axi4s_vid_in_tdata,                //          vvp_demosaic_axi4s_vid_in.tdata
		input  wire         vvp_demosaic_axi4s_vid_in_tvalid,               //                                   .tvalid
		output wire         vvp_demosaic_axi4s_vid_in_tready,               //                                   .tready
		input  wire         vvp_demosaic_axi4s_vid_in_tlast,                //                                   .tlast
		input  wire [7:0]   vvp_demosaic_axi4s_vid_in_tuser,                //                                   .tuser
		output wire [31:0]  vvp_vfw_debug_av_mm_mem_write_host_address,     // vvp_vfw_debug_av_mm_mem_write_host.address
		input  wire         vvp_vfw_debug_av_mm_mem_write_host_waitrequest, //                                   .waitrequest
		output wire [4:0]   vvp_vfw_debug_av_mm_mem_write_host_burstcount,  //                                   .burstcount
		output wire         vvp_vfw_debug_av_mm_mem_write_host_write,       //                                   .write
		output wire [127:0] vvp_vfw_debug_av_mm_mem_write_host_writedata,   //                                   .writedata
		output wire         vvp_vfw_debug_frame_writer_int_irq              //     vvp_vfw_debug_frame_writer_int.irq
	);

	wire         vvp_clipper_axi4s_vid_out_tvalid;                                 // vvp_clipper:axi4s_vid_out_tvalid -> vvp_scaler:axi4s_vid_in_tvalid
	wire  [11:0] vvp_clipper_axi4s_vid_out_tuser;                                  // vvp_clipper:axi4s_vid_out_tuser -> vvp_scaler:axi4s_vid_in_tuser
	wire         vvp_clipper_axi4s_vid_out_tready;                                 // vvp_scaler:axi4s_vid_in_tready -> vvp_clipper:axi4s_vid_out_tready
	wire  [95:0] vvp_clipper_axi4s_vid_out_tdata;                                  // vvp_clipper:axi4s_vid_out_tdata -> vvp_scaler:axi4s_vid_in_tdata
	wire         vvp_clipper_axi4s_vid_out_tlast;                                  // vvp_clipper:axi4s_vid_out_tlast -> vvp_scaler:axi4s_vid_in_tlast
	wire         vvp_scaler_axi4s_vid_out_tvalid;                                  // vvp_scaler:axi4s_vid_out_tvalid -> vvp_csc_0:axi4s_vid_in_tvalid
	wire  [11:0] vvp_scaler_axi4s_vid_out_tuser;                                   // vvp_scaler:axi4s_vid_out_tuser -> vvp_csc_0:axi4s_vid_in_tuser
	wire         vvp_scaler_axi4s_vid_out_tready;                                  // vvp_csc_0:axi4s_vid_in_tready -> vvp_scaler:axi4s_vid_out_tready
	wire  [95:0] vvp_scaler_axi4s_vid_out_tdata;                                   // vvp_scaler:axi4s_vid_out_tdata -> vvp_csc_0:axi4s_vid_in_tdata
	wire         vvp_scaler_axi4s_vid_out_tlast;                                   // vvp_scaler:axi4s_vid_out_tlast -> vvp_csc_0:axi4s_vid_in_tlast
	wire         vvp_csc_0_axi4s_vid_out_tvalid;                                   // vvp_csc_0:axi4s_vid_out_tvalid -> vvp_1d_lut_0:axi4s_vid_in_tvalid
	wire  [11:0] vvp_csc_0_axi4s_vid_out_tuser;                                    // vvp_csc_0:axi4s_vid_out_tuser -> vvp_1d_lut_0:axi4s_vid_in_tuser
	wire         vvp_csc_0_axi4s_vid_out_tready;                                   // vvp_1d_lut_0:axi4s_vid_in_tready -> vvp_csc_0:axi4s_vid_out_tready
	wire  [95:0] vvp_csc_0_axi4s_vid_out_tdata;                                    // vvp_csc_0:axi4s_vid_out_tdata -> vvp_1d_lut_0:axi4s_vid_in_tdata
	wire         vvp_csc_0_axi4s_vid_out_tlast;                                    // vvp_csc_0:axi4s_vid_out_tlast -> vvp_1d_lut_0:axi4s_vid_in_tlast
	wire         vvp_1d_lut_0_axi4s_vid_out_tvalid;                                // vvp_1d_lut_0:axi4s_vid_out_tvalid -> vvp_vfw:axi4s_vid_in_tvalid
	wire  [11:0] vvp_1d_lut_0_axi4s_vid_out_tuser;                                 // vvp_1d_lut_0:axi4s_vid_out_tuser -> vvp_vfw:axi4s_vid_in_tuser
	wire         vvp_1d_lut_0_axi4s_vid_out_tready;                                // vvp_vfw:axi4s_vid_in_tready -> vvp_1d_lut_0:axi4s_vid_out_tready
	wire  [95:0] vvp_1d_lut_0_axi4s_vid_out_tdata;                                 // vvp_1d_lut_0:axi4s_vid_out_tdata -> vvp_vfw:axi4s_vid_in_tdata
	wire         vvp_1d_lut_0_axi4s_vid_out_tlast;                                 // vvp_1d_lut_0:axi4s_vid_out_tlast -> vvp_vfw:axi4s_vid_in_tlast
	wire         vvp_demosaic_axi4s_vid_out_tvalid;                                // vvp_demosaic:axi4s_vid_out_tvalid -> vvp_clipper:axi4s_vid_in_tvalid
	wire  [11:0] vvp_demosaic_axi4s_vid_out_tuser;                                 // vvp_demosaic:axi4s_vid_out_tuser -> vvp_clipper:axi4s_vid_in_tuser
	wire         vvp_demosaic_axi4s_vid_out_tready;                                // vvp_clipper:axi4s_vid_in_tready -> vvp_demosaic:axi4s_vid_out_tready
	wire  [95:0] vvp_demosaic_axi4s_vid_out_tdata;                                 // vvp_demosaic:axi4s_vid_out_tdata -> vvp_clipper:axi4s_vid_in_tdata
	wire         vvp_demosaic_axi4s_vid_out_tlast;                                 // vvp_demosaic:axi4s_vid_out_tlast -> vvp_clipper:axi4s_vid_in_tlast
	wire         cpu_clk_bridge_out_clk_clk;                                       // cpu_clk_bridge:out_clk -> [cpu_rst_bridge:clk, mm_interconnect_0:cpu_clk_bridge_out_clk_clk, rst_controller:clk, vid_mm_bridge:clk, vvp_1d_lut_0:agent_clock_clk, vvp_1d_lut_0:main_clock_clk, vvp_clipper:main_clock_clk, vvp_csc_0:agent_clock_clk, vvp_csc_0:main_clock_clk, vvp_demosaic:agent_clock_clk, vvp_demosaic:main_clock_clk, vvp_scaler:agent_clock_clk, vvp_scaler:main_clock_clk, vvp_vfw:control_clock_clk, vvp_vfw:main_clock_clk, vvp_vfw:mem_clock_clk]
	wire         cpu_rst_bridge_out_reset_reset;                                   // cpu_rst_bridge:out_reset -> [rst_controller:reset_in0, vid_mm_bridge:reset]
	wire         vid_mm_bridge_m0_waitrequest;                                     // mm_interconnect_0:vid_mm_bridge_m0_waitrequest -> vid_mm_bridge:m0_waitrequest
	wire  [63:0] vid_mm_bridge_m0_readdata;                                        // mm_interconnect_0:vid_mm_bridge_m0_readdata -> vid_mm_bridge:m0_readdata
	wire         vid_mm_bridge_m0_debugaccess;                                     // vid_mm_bridge:m0_debugaccess -> mm_interconnect_0:vid_mm_bridge_m0_debugaccess
	wire  [12:0] vid_mm_bridge_m0_address;                                         // vid_mm_bridge:m0_address -> mm_interconnect_0:vid_mm_bridge_m0_address
	wire         vid_mm_bridge_m0_read;                                            // vid_mm_bridge:m0_read -> mm_interconnect_0:vid_mm_bridge_m0_read
	wire   [7:0] vid_mm_bridge_m0_byteenable;                                      // vid_mm_bridge:m0_byteenable -> mm_interconnect_0:vid_mm_bridge_m0_byteenable
	wire         vid_mm_bridge_m0_readdatavalid;                                   // mm_interconnect_0:vid_mm_bridge_m0_readdatavalid -> vid_mm_bridge:m0_readdatavalid
	wire  [63:0] vid_mm_bridge_m0_writedata;                                       // vid_mm_bridge:m0_writedata -> mm_interconnect_0:vid_mm_bridge_m0_writedata
	wire         vid_mm_bridge_m0_write;                                           // vid_mm_bridge:m0_write -> mm_interconnect_0:vid_mm_bridge_m0_write
	wire   [0:0] vid_mm_bridge_m0_burstcount;                                      // vid_mm_bridge:m0_burstcount -> mm_interconnect_0:vid_mm_bridge_m0_burstcount
	wire  [31:0] mm_interconnect_0_vvp_vfw_av_mm_control_agent_readdata;           // vvp_vfw:av_mm_control_agent_readdata -> mm_interconnect_0:vvp_vfw_av_mm_control_agent_readdata
	wire         mm_interconnect_0_vvp_vfw_av_mm_control_agent_waitrequest;        // vvp_vfw:av_mm_control_agent_waitrequest -> mm_interconnect_0:vvp_vfw_av_mm_control_agent_waitrequest
	wire   [6:0] mm_interconnect_0_vvp_vfw_av_mm_control_agent_address;            // mm_interconnect_0:vvp_vfw_av_mm_control_agent_address -> vvp_vfw:av_mm_control_agent_address
	wire         mm_interconnect_0_vvp_vfw_av_mm_control_agent_read;               // mm_interconnect_0:vvp_vfw_av_mm_control_agent_read -> vvp_vfw:av_mm_control_agent_read
	wire   [3:0] mm_interconnect_0_vvp_vfw_av_mm_control_agent_byteenable;         // mm_interconnect_0:vvp_vfw_av_mm_control_agent_byteenable -> vvp_vfw:av_mm_control_agent_byteenable
	wire         mm_interconnect_0_vvp_vfw_av_mm_control_agent_readdatavalid;      // vvp_vfw:av_mm_control_agent_readdatavalid -> mm_interconnect_0:vvp_vfw_av_mm_control_agent_readdatavalid
	wire         mm_interconnect_0_vvp_vfw_av_mm_control_agent_write;              // mm_interconnect_0:vvp_vfw_av_mm_control_agent_write -> vvp_vfw:av_mm_control_agent_write
	wire  [31:0] mm_interconnect_0_vvp_vfw_av_mm_control_agent_writedata;          // mm_interconnect_0:vvp_vfw_av_mm_control_agent_writedata -> vvp_vfw:av_mm_control_agent_writedata
	wire  [31:0] mm_interconnect_0_vvp_scaler_av_mm_control_agent_readdata;        // vvp_scaler:av_mm_control_agent_readdata -> mm_interconnect_0:vvp_scaler_av_mm_control_agent_readdata
	wire         mm_interconnect_0_vvp_scaler_av_mm_control_agent_waitrequest;     // vvp_scaler:av_mm_control_agent_waitrequest -> mm_interconnect_0:vvp_scaler_av_mm_control_agent_waitrequest
	wire   [6:0] mm_interconnect_0_vvp_scaler_av_mm_control_agent_address;         // mm_interconnect_0:vvp_scaler_av_mm_control_agent_address -> vvp_scaler:av_mm_control_agent_address
	wire         mm_interconnect_0_vvp_scaler_av_mm_control_agent_read;            // mm_interconnect_0:vvp_scaler_av_mm_control_agent_read -> vvp_scaler:av_mm_control_agent_read
	wire   [3:0] mm_interconnect_0_vvp_scaler_av_mm_control_agent_byteenable;      // mm_interconnect_0:vvp_scaler_av_mm_control_agent_byteenable -> vvp_scaler:av_mm_control_agent_byteenable
	wire         mm_interconnect_0_vvp_scaler_av_mm_control_agent_readdatavalid;   // vvp_scaler:av_mm_control_agent_readdatavalid -> mm_interconnect_0:vvp_scaler_av_mm_control_agent_readdatavalid
	wire         mm_interconnect_0_vvp_scaler_av_mm_control_agent_write;           // mm_interconnect_0:vvp_scaler_av_mm_control_agent_write -> vvp_scaler:av_mm_control_agent_write
	wire  [31:0] mm_interconnect_0_vvp_scaler_av_mm_control_agent_writedata;       // mm_interconnect_0:vvp_scaler_av_mm_control_agent_writedata -> vvp_scaler:av_mm_control_agent_writedata
	wire  [31:0] mm_interconnect_0_vvp_demosaic_av_mm_control_agent_readdata;      // vvp_demosaic:av_mm_control_agent_readdata -> mm_interconnect_0:vvp_demosaic_av_mm_control_agent_readdata
	wire         mm_interconnect_0_vvp_demosaic_av_mm_control_agent_waitrequest;   // vvp_demosaic:av_mm_control_agent_waitrequest -> mm_interconnect_0:vvp_demosaic_av_mm_control_agent_waitrequest
	wire   [6:0] mm_interconnect_0_vvp_demosaic_av_mm_control_agent_address;       // mm_interconnect_0:vvp_demosaic_av_mm_control_agent_address -> vvp_demosaic:av_mm_control_agent_address
	wire         mm_interconnect_0_vvp_demosaic_av_mm_control_agent_read;          // mm_interconnect_0:vvp_demosaic_av_mm_control_agent_read -> vvp_demosaic:av_mm_control_agent_read
	wire   [3:0] mm_interconnect_0_vvp_demosaic_av_mm_control_agent_byteenable;    // mm_interconnect_0:vvp_demosaic_av_mm_control_agent_byteenable -> vvp_demosaic:av_mm_control_agent_byteenable
	wire         mm_interconnect_0_vvp_demosaic_av_mm_control_agent_readdatavalid; // vvp_demosaic:av_mm_control_agent_readdatavalid -> mm_interconnect_0:vvp_demosaic_av_mm_control_agent_readdatavalid
	wire         mm_interconnect_0_vvp_demosaic_av_mm_control_agent_write;         // mm_interconnect_0:vvp_demosaic_av_mm_control_agent_write -> vvp_demosaic:av_mm_control_agent_write
	wire  [31:0] mm_interconnect_0_vvp_demosaic_av_mm_control_agent_writedata;     // mm_interconnect_0:vvp_demosaic_av_mm_control_agent_writedata -> vvp_demosaic:av_mm_control_agent_writedata
	wire  [31:0] mm_interconnect_0_vvp_clipper_av_mm_control_agent_readdata;       // vvp_clipper:av_mm_control_agent_readdata -> mm_interconnect_0:vvp_clipper_av_mm_control_agent_readdata
	wire         mm_interconnect_0_vvp_clipper_av_mm_control_agent_waitrequest;    // vvp_clipper:av_mm_control_agent_waitrequest -> mm_interconnect_0:vvp_clipper_av_mm_control_agent_waitrequest
	wire   [6:0] mm_interconnect_0_vvp_clipper_av_mm_control_agent_address;        // mm_interconnect_0:vvp_clipper_av_mm_control_agent_address -> vvp_clipper:av_mm_control_agent_address
	wire         mm_interconnect_0_vvp_clipper_av_mm_control_agent_read;           // mm_interconnect_0:vvp_clipper_av_mm_control_agent_read -> vvp_clipper:av_mm_control_agent_read
	wire   [3:0] mm_interconnect_0_vvp_clipper_av_mm_control_agent_byteenable;     // mm_interconnect_0:vvp_clipper_av_mm_control_agent_byteenable -> vvp_clipper:av_mm_control_agent_byteenable
	wire         mm_interconnect_0_vvp_clipper_av_mm_control_agent_readdatavalid;  // vvp_clipper:av_mm_control_agent_readdatavalid -> mm_interconnect_0:vvp_clipper_av_mm_control_agent_readdatavalid
	wire         mm_interconnect_0_vvp_clipper_av_mm_control_agent_write;          // mm_interconnect_0:vvp_clipper_av_mm_control_agent_write -> vvp_clipper:av_mm_control_agent_write
	wire  [31:0] mm_interconnect_0_vvp_clipper_av_mm_control_agent_writedata;      // mm_interconnect_0:vvp_clipper_av_mm_control_agent_writedata -> vvp_clipper:av_mm_control_agent_writedata
	wire  [31:0] mm_interconnect_0_vvp_csc_0_av_mm_control_agent_readdata;         // vvp_csc_0:av_mm_control_agent_readdata -> mm_interconnect_0:vvp_csc_0_av_mm_control_agent_readdata
	wire         mm_interconnect_0_vvp_csc_0_av_mm_control_agent_waitrequest;      // vvp_csc_0:av_mm_control_agent_waitrequest -> mm_interconnect_0:vvp_csc_0_av_mm_control_agent_waitrequest
	wire   [6:0] mm_interconnect_0_vvp_csc_0_av_mm_control_agent_address;          // mm_interconnect_0:vvp_csc_0_av_mm_control_agent_address -> vvp_csc_0:av_mm_control_agent_address
	wire         mm_interconnect_0_vvp_csc_0_av_mm_control_agent_read;             // mm_interconnect_0:vvp_csc_0_av_mm_control_agent_read -> vvp_csc_0:av_mm_control_agent_read
	wire   [3:0] mm_interconnect_0_vvp_csc_0_av_mm_control_agent_byteenable;       // mm_interconnect_0:vvp_csc_0_av_mm_control_agent_byteenable -> vvp_csc_0:av_mm_control_agent_byteenable
	wire         mm_interconnect_0_vvp_csc_0_av_mm_control_agent_readdatavalid;    // vvp_csc_0:av_mm_control_agent_readdatavalid -> mm_interconnect_0:vvp_csc_0_av_mm_control_agent_readdatavalid
	wire         mm_interconnect_0_vvp_csc_0_av_mm_control_agent_write;            // mm_interconnect_0:vvp_csc_0_av_mm_control_agent_write -> vvp_csc_0:av_mm_control_agent_write
	wire  [31:0] mm_interconnect_0_vvp_csc_0_av_mm_control_agent_writedata;        // mm_interconnect_0:vvp_csc_0_av_mm_control_agent_writedata -> vvp_csc_0:av_mm_control_agent_writedata
	wire  [31:0] mm_interconnect_0_vvp_1d_lut_0_av_mm_control_agent_readdata;      // vvp_1d_lut_0:av_mm_control_agent_readdata -> mm_interconnect_0:vvp_1d_lut_0_av_mm_control_agent_readdata
	wire         mm_interconnect_0_vvp_1d_lut_0_av_mm_control_agent_waitrequest;   // vvp_1d_lut_0:av_mm_control_agent_waitrequest -> mm_interconnect_0:vvp_1d_lut_0_av_mm_control_agent_waitrequest
	wire   [9:0] mm_interconnect_0_vvp_1d_lut_0_av_mm_control_agent_address;       // mm_interconnect_0:vvp_1d_lut_0_av_mm_control_agent_address -> vvp_1d_lut_0:av_mm_control_agent_address
	wire         mm_interconnect_0_vvp_1d_lut_0_av_mm_control_agent_read;          // mm_interconnect_0:vvp_1d_lut_0_av_mm_control_agent_read -> vvp_1d_lut_0:av_mm_control_agent_read
	wire   [3:0] mm_interconnect_0_vvp_1d_lut_0_av_mm_control_agent_byteenable;    // mm_interconnect_0:vvp_1d_lut_0_av_mm_control_agent_byteenable -> vvp_1d_lut_0:av_mm_control_agent_byteenable
	wire         mm_interconnect_0_vvp_1d_lut_0_av_mm_control_agent_readdatavalid; // vvp_1d_lut_0:av_mm_control_agent_readdatavalid -> mm_interconnect_0:vvp_1d_lut_0_av_mm_control_agent_readdatavalid
	wire         mm_interconnect_0_vvp_1d_lut_0_av_mm_control_agent_write;         // mm_interconnect_0:vvp_1d_lut_0_av_mm_control_agent_write -> vvp_1d_lut_0:av_mm_control_agent_write
	wire  [31:0] mm_interconnect_0_vvp_1d_lut_0_av_mm_control_agent_writedata;     // mm_interconnect_0:vvp_1d_lut_0_av_mm_control_agent_writedata -> vvp_1d_lut_0:av_mm_control_agent_writedata
	wire         rst_controller_reset_out_reset;                                   // rst_controller:reset_out -> [mm_interconnect_0:vid_mm_bridge_reset_reset_bridge_in_reset_reset, mm_interconnect_0:vvp_vfw_control_reset_reset_bridge_in_reset_reset, vvp_1d_lut_0:agent_reset_reset, vvp_1d_lut_0:main_reset_reset, vvp_clipper:main_reset_reset, vvp_csc_0:agent_reset_reset, vvp_csc_0:main_reset_reset, vvp_demosaic:agent_reset_reset, vvp_demosaic:main_reset_reset, vvp_scaler:agent_reset_reset, vvp_scaler:main_reset_reset, vvp_vfw:control_reset_reset, vvp_vfw:main_reset_reset, vvp_vfw:mem_reset_reset]

	video_path_clock_in cpu_clk_bridge (
		.in_clk  (sys_clk_in_clk),             //   input,  width = 1,  in_clk.clk
		.out_clk (cpu_clk_bridge_out_clk_clk)  //  output,  width = 1, out_clk.clk
	);

	video_path_reset_in cpu_rst_bridge (
		.clk       (cpu_clk_bridge_out_clk_clk),     //   input,  width = 1,       clk.clk
		.in_reset  (sys_rst_in_reset),               //   input,  width = 1,  in_reset.reset
		.out_reset (cpu_rst_bridge_out_reset_reset)  //  output,  width = 1, out_reset.reset
	);

	vid_mm_bridge vid_mm_bridge (
		.clk              (cpu_clk_bridge_out_clk_clk),     //   input,   width = 1,   clk.clk
		.reset            (cpu_rst_bridge_out_reset_reset), //   input,   width = 1, reset.reset
		.s0_waitrequest   (mm_bus_in_waitrequest),          //  output,   width = 1,    s0.waitrequest
		.s0_readdata      (mm_bus_in_readdata),             //  output,  width = 64,      .readdata
		.s0_readdatavalid (mm_bus_in_readdatavalid),        //  output,   width = 1,      .readdatavalid
		.s0_burstcount    (mm_bus_in_burstcount),           //   input,   width = 1,      .burstcount
		.s0_writedata     (mm_bus_in_writedata),            //   input,  width = 64,      .writedata
		.s0_address       (mm_bus_in_address),              //   input,  width = 13,      .address
		.s0_write         (mm_bus_in_write),                //   input,   width = 1,      .write
		.s0_read          (mm_bus_in_read),                 //   input,   width = 1,      .read
		.s0_byteenable    (mm_bus_in_byteenable),           //   input,   width = 8,      .byteenable
		.s0_debugaccess   (mm_bus_in_debugaccess),          //   input,   width = 1,      .debugaccess
		.m0_waitrequest   (vid_mm_bridge_m0_waitrequest),   //   input,   width = 1,    m0.waitrequest
		.m0_readdata      (vid_mm_bridge_m0_readdata),      //   input,  width = 64,      .readdata
		.m0_readdatavalid (vid_mm_bridge_m0_readdatavalid), //   input,   width = 1,      .readdatavalid
		.m0_burstcount    (vid_mm_bridge_m0_burstcount),    //  output,   width = 1,      .burstcount
		.m0_writedata     (vid_mm_bridge_m0_writedata),     //  output,  width = 64,      .writedata
		.m0_address       (vid_mm_bridge_m0_address),       //  output,  width = 13,      .address
		.m0_write         (vid_mm_bridge_m0_write),         //  output,   width = 1,      .write
		.m0_read          (vid_mm_bridge_m0_read),          //  output,   width = 1,      .read
		.m0_byteenable    (vid_mm_bridge_m0_byteenable),    //  output,   width = 8,      .byteenable
		.m0_debugaccess   (vid_mm_bridge_m0_debugaccess)    //  output,   width = 1,      .debugaccess
	);

	vvp_1d_lut_0 vvp_1d_lut_0 (
		.main_clock_clk                    (cpu_clk_bridge_out_clk_clk),                                       //   input,   width = 1,          main_clock.clk
		.main_reset_reset                  (rst_controller_reset_out_reset),                                   //   input,   width = 1,          main_reset.reset
		.axi4s_vid_in_tdata                (vvp_csc_0_axi4s_vid_out_tdata),                                    //   input,  width = 96,        axi4s_vid_in.tdata
		.axi4s_vid_in_tvalid               (vvp_csc_0_axi4s_vid_out_tvalid),                                   //   input,   width = 1,                    .tvalid
		.axi4s_vid_in_tready               (vvp_csc_0_axi4s_vid_out_tready),                                   //  output,   width = 1,                    .tready
		.axi4s_vid_in_tlast                (vvp_csc_0_axi4s_vid_out_tlast),                                    //   input,   width = 1,                    .tlast
		.axi4s_vid_in_tuser                (vvp_csc_0_axi4s_vid_out_tuser),                                    //   input,  width = 12,                    .tuser
		.axi4s_vid_out_tdata               (vvp_1d_lut_0_axi4s_vid_out_tdata),                                 //  output,  width = 96,       axi4s_vid_out.tdata
		.axi4s_vid_out_tvalid              (vvp_1d_lut_0_axi4s_vid_out_tvalid),                                //  output,   width = 1,                    .tvalid
		.axi4s_vid_out_tready              (vvp_1d_lut_0_axi4s_vid_out_tready),                                //   input,   width = 1,                    .tready
		.axi4s_vid_out_tlast               (vvp_1d_lut_0_axi4s_vid_out_tlast),                                 //  output,   width = 1,                    .tlast
		.axi4s_vid_out_tuser               (vvp_1d_lut_0_axi4s_vid_out_tuser),                                 //  output,  width = 12,                    .tuser
		.agent_clock_clk                   (cpu_clk_bridge_out_clk_clk),                                       //   input,   width = 1,         agent_clock.clk
		.agent_reset_reset                 (rst_controller_reset_out_reset),                                   //   input,   width = 1,         agent_reset.reset
		.av_mm_control_agent_address       (mm_interconnect_0_vvp_1d_lut_0_av_mm_control_agent_address),       //   input,  width = 10, av_mm_control_agent.address
		.av_mm_control_agent_write         (mm_interconnect_0_vvp_1d_lut_0_av_mm_control_agent_write),         //   input,   width = 1,                    .write
		.av_mm_control_agent_byteenable    (mm_interconnect_0_vvp_1d_lut_0_av_mm_control_agent_byteenable),    //   input,   width = 4,                    .byteenable
		.av_mm_control_agent_writedata     (mm_interconnect_0_vvp_1d_lut_0_av_mm_control_agent_writedata),     //   input,  width = 32,                    .writedata
		.av_mm_control_agent_read          (mm_interconnect_0_vvp_1d_lut_0_av_mm_control_agent_read),          //   input,   width = 1,                    .read
		.av_mm_control_agent_readdata      (mm_interconnect_0_vvp_1d_lut_0_av_mm_control_agent_readdata),      //  output,  width = 32,                    .readdata
		.av_mm_control_agent_readdatavalid (mm_interconnect_0_vvp_1d_lut_0_av_mm_control_agent_readdatavalid), //  output,   width = 1,                    .readdatavalid
		.av_mm_control_agent_waitrequest   (mm_interconnect_0_vvp_1d_lut_0_av_mm_control_agent_waitrequest)    //  output,   width = 1,                    .waitrequest
	);

	vvp_clipper_0 vvp_clipper (
		.main_clock_clk                    (cpu_clk_bridge_out_clk_clk),                                      //   input,   width = 1,          main_clock.clk
		.main_reset_reset                  (rst_controller_reset_out_reset),                                  //   input,   width = 1,          main_reset.reset
		.axi4s_vid_in_tdata                (vvp_demosaic_axi4s_vid_out_tdata),                                //   input,  width = 96,        axi4s_vid_in.tdata
		.axi4s_vid_in_tvalid               (vvp_demosaic_axi4s_vid_out_tvalid),                               //   input,   width = 1,                    .tvalid
		.axi4s_vid_in_tready               (vvp_demosaic_axi4s_vid_out_tready),                               //  output,   width = 1,                    .tready
		.axi4s_vid_in_tlast                (vvp_demosaic_axi4s_vid_out_tlast),                                //   input,   width = 1,                    .tlast
		.axi4s_vid_in_tuser                (vvp_demosaic_axi4s_vid_out_tuser),                                //   input,  width = 12,                    .tuser
		.axi4s_vid_out_tdata               (vvp_clipper_axi4s_vid_out_tdata),                                 //  output,  width = 96,       axi4s_vid_out.tdata
		.axi4s_vid_out_tvalid              (vvp_clipper_axi4s_vid_out_tvalid),                                //  output,   width = 1,                    .tvalid
		.axi4s_vid_out_tready              (vvp_clipper_axi4s_vid_out_tready),                                //   input,   width = 1,                    .tready
		.axi4s_vid_out_tlast               (vvp_clipper_axi4s_vid_out_tlast),                                 //  output,   width = 1,                    .tlast
		.axi4s_vid_out_tuser               (vvp_clipper_axi4s_vid_out_tuser),                                 //  output,  width = 12,                    .tuser
		.av_mm_control_agent_address       (mm_interconnect_0_vvp_clipper_av_mm_control_agent_address),       //   input,   width = 7, av_mm_control_agent.address
		.av_mm_control_agent_write         (mm_interconnect_0_vvp_clipper_av_mm_control_agent_write),         //   input,   width = 1,                    .write
		.av_mm_control_agent_byteenable    (mm_interconnect_0_vvp_clipper_av_mm_control_agent_byteenable),    //   input,   width = 4,                    .byteenable
		.av_mm_control_agent_writedata     (mm_interconnect_0_vvp_clipper_av_mm_control_agent_writedata),     //   input,  width = 32,                    .writedata
		.av_mm_control_agent_read          (mm_interconnect_0_vvp_clipper_av_mm_control_agent_read),          //   input,   width = 1,                    .read
		.av_mm_control_agent_readdata      (mm_interconnect_0_vvp_clipper_av_mm_control_agent_readdata),      //  output,  width = 32,                    .readdata
		.av_mm_control_agent_readdatavalid (mm_interconnect_0_vvp_clipper_av_mm_control_agent_readdatavalid), //  output,   width = 1,                    .readdatavalid
		.av_mm_control_agent_waitrequest   (mm_interconnect_0_vvp_clipper_av_mm_control_agent_waitrequest)    //  output,   width = 1,                    .waitrequest
	);

	vvp_csc_0 vvp_csc_0 (
		.main_clock_clk                    (cpu_clk_bridge_out_clk_clk),                                    //   input,   width = 1,          main_clock.clk
		.main_reset_reset                  (rst_controller_reset_out_reset),                                //   input,   width = 1,          main_reset.reset
		.axi4s_vid_in_tdata                (vvp_scaler_axi4s_vid_out_tdata),                                //   input,  width = 96,        axi4s_vid_in.tdata
		.axi4s_vid_in_tvalid               (vvp_scaler_axi4s_vid_out_tvalid),                               //   input,   width = 1,                    .tvalid
		.axi4s_vid_in_tready               (vvp_scaler_axi4s_vid_out_tready),                               //  output,   width = 1,                    .tready
		.axi4s_vid_in_tlast                (vvp_scaler_axi4s_vid_out_tlast),                                //   input,   width = 1,                    .tlast
		.axi4s_vid_in_tuser                (vvp_scaler_axi4s_vid_out_tuser),                                //   input,  width = 12,                    .tuser
		.axi4s_vid_out_tdata               (vvp_csc_0_axi4s_vid_out_tdata),                                 //  output,  width = 96,       axi4s_vid_out.tdata
		.axi4s_vid_out_tvalid              (vvp_csc_0_axi4s_vid_out_tvalid),                                //  output,   width = 1,                    .tvalid
		.axi4s_vid_out_tready              (vvp_csc_0_axi4s_vid_out_tready),                                //   input,   width = 1,                    .tready
		.axi4s_vid_out_tlast               (vvp_csc_0_axi4s_vid_out_tlast),                                 //  output,   width = 1,                    .tlast
		.axi4s_vid_out_tuser               (vvp_csc_0_axi4s_vid_out_tuser),                                 //  output,  width = 12,                    .tuser
		.agent_clock_clk                   (cpu_clk_bridge_out_clk_clk),                                    //   input,   width = 1,         agent_clock.clk
		.agent_reset_reset                 (rst_controller_reset_out_reset),                                //   input,   width = 1,         agent_reset.reset
		.av_mm_control_agent_address       (mm_interconnect_0_vvp_csc_0_av_mm_control_agent_address),       //   input,   width = 7, av_mm_control_agent.address
		.av_mm_control_agent_write         (mm_interconnect_0_vvp_csc_0_av_mm_control_agent_write),         //   input,   width = 1,                    .write
		.av_mm_control_agent_byteenable    (mm_interconnect_0_vvp_csc_0_av_mm_control_agent_byteenable),    //   input,   width = 4,                    .byteenable
		.av_mm_control_agent_writedata     (mm_interconnect_0_vvp_csc_0_av_mm_control_agent_writedata),     //   input,  width = 32,                    .writedata
		.av_mm_control_agent_read          (mm_interconnect_0_vvp_csc_0_av_mm_control_agent_read),          //   input,   width = 1,                    .read
		.av_mm_control_agent_readdata      (mm_interconnect_0_vvp_csc_0_av_mm_control_agent_readdata),      //  output,  width = 32,                    .readdata
		.av_mm_control_agent_readdatavalid (mm_interconnect_0_vvp_csc_0_av_mm_control_agent_readdatavalid), //  output,   width = 1,                    .readdatavalid
		.av_mm_control_agent_waitrequest   (mm_interconnect_0_vvp_csc_0_av_mm_control_agent_waitrequest)    //  output,   width = 1,                    .waitrequest
	);

	vvp_demosaic_0 vvp_demosaic (
		.main_clock_clk                    (cpu_clk_bridge_out_clk_clk),                                       //   input,   width = 1,          main_clock.clk
		.main_reset_reset                  (rst_controller_reset_out_reset),                                   //   input,   width = 1,          main_reset.reset
		.axi4s_vid_in_tdata                (vvp_demosaic_axi4s_vid_in_tdata),                                  //   input,  width = 64,        axi4s_vid_in.tdata
		.axi4s_vid_in_tvalid               (vvp_demosaic_axi4s_vid_in_tvalid),                                 //   input,   width = 1,                    .tvalid
		.axi4s_vid_in_tready               (vvp_demosaic_axi4s_vid_in_tready),                                 //  output,   width = 1,                    .tready
		.axi4s_vid_in_tlast                (vvp_demosaic_axi4s_vid_in_tlast),                                  //   input,   width = 1,                    .tlast
		.axi4s_vid_in_tuser                (vvp_demosaic_axi4s_vid_in_tuser),                                  //   input,   width = 8,                    .tuser
		.axi4s_vid_out_tdata               (vvp_demosaic_axi4s_vid_out_tdata),                                 //  output,  width = 96,       axi4s_vid_out.tdata
		.axi4s_vid_out_tvalid              (vvp_demosaic_axi4s_vid_out_tvalid),                                //  output,   width = 1,                    .tvalid
		.axi4s_vid_out_tready              (vvp_demosaic_axi4s_vid_out_tready),                                //   input,   width = 1,                    .tready
		.axi4s_vid_out_tlast               (vvp_demosaic_axi4s_vid_out_tlast),                                 //  output,   width = 1,                    .tlast
		.axi4s_vid_out_tuser               (vvp_demosaic_axi4s_vid_out_tuser),                                 //  output,  width = 12,                    .tuser
		.agent_clock_clk                   (cpu_clk_bridge_out_clk_clk),                                       //   input,   width = 1,         agent_clock.clk
		.agent_reset_reset                 (rst_controller_reset_out_reset),                                   //   input,   width = 1,         agent_reset.reset
		.av_mm_control_agent_address       (mm_interconnect_0_vvp_demosaic_av_mm_control_agent_address),       //   input,   width = 7, av_mm_control_agent.address
		.av_mm_control_agent_write         (mm_interconnect_0_vvp_demosaic_av_mm_control_agent_write),         //   input,   width = 1,                    .write
		.av_mm_control_agent_byteenable    (mm_interconnect_0_vvp_demosaic_av_mm_control_agent_byteenable),    //   input,   width = 4,                    .byteenable
		.av_mm_control_agent_writedata     (mm_interconnect_0_vvp_demosaic_av_mm_control_agent_writedata),     //   input,  width = 32,                    .writedata
		.av_mm_control_agent_read          (mm_interconnect_0_vvp_demosaic_av_mm_control_agent_read),          //   input,   width = 1,                    .read
		.av_mm_control_agent_readdata      (mm_interconnect_0_vvp_demosaic_av_mm_control_agent_readdata),      //  output,  width = 32,                    .readdata
		.av_mm_control_agent_readdatavalid (mm_interconnect_0_vvp_demosaic_av_mm_control_agent_readdatavalid), //  output,   width = 1,                    .readdatavalid
		.av_mm_control_agent_waitrequest   (mm_interconnect_0_vvp_demosaic_av_mm_control_agent_waitrequest)    //  output,   width = 1,                    .waitrequest
	);

	vvp_scaler_debug vvp_scaler (
		.main_clock_clk                    (cpu_clk_bridge_out_clk_clk),                                     //   input,   width = 1,          main_clock.clk
		.main_reset_reset                  (rst_controller_reset_out_reset),                                 //   input,   width = 1,          main_reset.reset
		.axi4s_vid_in_tdata                (vvp_clipper_axi4s_vid_out_tdata),                                //   input,  width = 96,        axi4s_vid_in.tdata
		.axi4s_vid_in_tvalid               (vvp_clipper_axi4s_vid_out_tvalid),                               //   input,   width = 1,                    .tvalid
		.axi4s_vid_in_tready               (vvp_clipper_axi4s_vid_out_tready),                               //  output,   width = 1,                    .tready
		.axi4s_vid_in_tlast                (vvp_clipper_axi4s_vid_out_tlast),                                //   input,   width = 1,                    .tlast
		.axi4s_vid_in_tuser                (vvp_clipper_axi4s_vid_out_tuser),                                //   input,  width = 12,                    .tuser
		.axi4s_vid_out_tdata               (vvp_scaler_axi4s_vid_out_tdata),                                 //  output,  width = 96,       axi4s_vid_out.tdata
		.axi4s_vid_out_tvalid              (vvp_scaler_axi4s_vid_out_tvalid),                                //  output,   width = 1,                    .tvalid
		.axi4s_vid_out_tready              (vvp_scaler_axi4s_vid_out_tready),                                //   input,   width = 1,                    .tready
		.axi4s_vid_out_tlast               (vvp_scaler_axi4s_vid_out_tlast),                                 //  output,   width = 1,                    .tlast
		.axi4s_vid_out_tuser               (vvp_scaler_axi4s_vid_out_tuser),                                 //  output,  width = 12,                    .tuser
		.agent_clock_clk                   (cpu_clk_bridge_out_clk_clk),                                     //   input,   width = 1,         agent_clock.clk
		.agent_reset_reset                 (rst_controller_reset_out_reset),                                 //   input,   width = 1,         agent_reset.reset
		.av_mm_control_agent_address       (mm_interconnect_0_vvp_scaler_av_mm_control_agent_address),       //   input,   width = 7, av_mm_control_agent.address
		.av_mm_control_agent_write         (mm_interconnect_0_vvp_scaler_av_mm_control_agent_write),         //   input,   width = 1,                    .write
		.av_mm_control_agent_byteenable    (mm_interconnect_0_vvp_scaler_av_mm_control_agent_byteenable),    //   input,   width = 4,                    .byteenable
		.av_mm_control_agent_writedata     (mm_interconnect_0_vvp_scaler_av_mm_control_agent_writedata),     //   input,  width = 32,                    .writedata
		.av_mm_control_agent_read          (mm_interconnect_0_vvp_scaler_av_mm_control_agent_read),          //   input,   width = 1,                    .read
		.av_mm_control_agent_readdata      (mm_interconnect_0_vvp_scaler_av_mm_control_agent_readdata),      //  output,  width = 32,                    .readdata
		.av_mm_control_agent_readdatavalid (mm_interconnect_0_vvp_scaler_av_mm_control_agent_readdatavalid), //  output,   width = 1,                    .readdatavalid
		.av_mm_control_agent_waitrequest   (mm_interconnect_0_vvp_scaler_av_mm_control_agent_waitrequest)    //  output,   width = 1,                    .waitrequest
	);

	vvp_vfw_debug vvp_vfw (
		.main_clock_clk                    (cpu_clk_bridge_out_clk_clk),                                  //   input,    width = 1,           main_clock.clk
		.main_reset_reset                  (rst_controller_reset_out_reset),                              //   input,    width = 1,           main_reset.reset
		.mem_clock_clk                     (cpu_clk_bridge_out_clk_clk),                                  //   input,    width = 1,            mem_clock.clk
		.mem_reset_reset                   (rst_controller_reset_out_reset),                              //   input,    width = 1,            mem_reset.reset
		.axi4s_vid_in_tdata                (vvp_1d_lut_0_axi4s_vid_out_tdata),                            //   input,   width = 96,         axi4s_vid_in.tdata
		.axi4s_vid_in_tvalid               (vvp_1d_lut_0_axi4s_vid_out_tvalid),                           //   input,    width = 1,                     .tvalid
		.axi4s_vid_in_tready               (vvp_1d_lut_0_axi4s_vid_out_tready),                           //  output,    width = 1,                     .tready
		.axi4s_vid_in_tlast                (vvp_1d_lut_0_axi4s_vid_out_tlast),                            //   input,    width = 1,                     .tlast
		.axi4s_vid_in_tuser                (vvp_1d_lut_0_axi4s_vid_out_tuser),                            //   input,   width = 12,                     .tuser
		.av_mm_mem_write_host_address      (vvp_vfw_debug_av_mm_mem_write_host_address),                  //  output,   width = 32, av_mm_mem_write_host.address
		.av_mm_mem_write_host_waitrequest  (vvp_vfw_debug_av_mm_mem_write_host_waitrequest),              //   input,    width = 1,                     .waitrequest
		.av_mm_mem_write_host_burstcount   (vvp_vfw_debug_av_mm_mem_write_host_burstcount),               //  output,    width = 5,                     .burstcount
		.av_mm_mem_write_host_write        (vvp_vfw_debug_av_mm_mem_write_host_write),                    //  output,    width = 1,                     .write
		.av_mm_mem_write_host_writedata    (vvp_vfw_debug_av_mm_mem_write_host_writedata),                //  output,  width = 128,                     .writedata
		.control_clock_clk                 (cpu_clk_bridge_out_clk_clk),                                  //   input,    width = 1,        control_clock.clk
		.control_reset_reset               (rst_controller_reset_out_reset),                              //   input,    width = 1,        control_reset.reset
		.av_mm_control_agent_address       (mm_interconnect_0_vvp_vfw_av_mm_control_agent_address),       //   input,    width = 7,  av_mm_control_agent.address
		.av_mm_control_agent_write         (mm_interconnect_0_vvp_vfw_av_mm_control_agent_write),         //   input,    width = 1,                     .write
		.av_mm_control_agent_byteenable    (mm_interconnect_0_vvp_vfw_av_mm_control_agent_byteenable),    //   input,    width = 4,                     .byteenable
		.av_mm_control_agent_writedata     (mm_interconnect_0_vvp_vfw_av_mm_control_agent_writedata),     //   input,   width = 32,                     .writedata
		.av_mm_control_agent_read          (mm_interconnect_0_vvp_vfw_av_mm_control_agent_read),          //   input,    width = 1,                     .read
		.av_mm_control_agent_readdata      (mm_interconnect_0_vvp_vfw_av_mm_control_agent_readdata),      //  output,   width = 32,                     .readdata
		.av_mm_control_agent_readdatavalid (mm_interconnect_0_vvp_vfw_av_mm_control_agent_readdatavalid), //  output,    width = 1,                     .readdatavalid
		.av_mm_control_agent_waitrequest   (mm_interconnect_0_vvp_vfw_av_mm_control_agent_waitrequest),   //  output,    width = 1,                     .waitrequest
		.frame_writer_int_irq              (vvp_vfw_debug_frame_writer_int_irq)                           //  output,    width = 1,     frame_writer_int.irq
	);

	video_path_altera_mm_interconnect_1920_tq2niii mm_interconnect_0 (
		.vid_mm_bridge_m0_address                          (vid_mm_bridge_m0_address),                                         //   input,  width = 13,                            vid_mm_bridge_m0.address
		.vid_mm_bridge_m0_waitrequest                      (vid_mm_bridge_m0_waitrequest),                                     //  output,   width = 1,                                            .waitrequest
		.vid_mm_bridge_m0_burstcount                       (vid_mm_bridge_m0_burstcount),                                      //   input,   width = 1,                                            .burstcount
		.vid_mm_bridge_m0_byteenable                       (vid_mm_bridge_m0_byteenable),                                      //   input,   width = 8,                                            .byteenable
		.vid_mm_bridge_m0_read                             (vid_mm_bridge_m0_read),                                            //   input,   width = 1,                                            .read
		.vid_mm_bridge_m0_readdata                         (vid_mm_bridge_m0_readdata),                                        //  output,  width = 64,                                            .readdata
		.vid_mm_bridge_m0_readdatavalid                    (vid_mm_bridge_m0_readdatavalid),                                   //  output,   width = 1,                                            .readdatavalid
		.vid_mm_bridge_m0_write                            (vid_mm_bridge_m0_write),                                           //   input,   width = 1,                                            .write
		.vid_mm_bridge_m0_writedata                        (vid_mm_bridge_m0_writedata),                                       //   input,  width = 64,                                            .writedata
		.vid_mm_bridge_m0_debugaccess                      (vid_mm_bridge_m0_debugaccess),                                     //   input,   width = 1,                                            .debugaccess
		.vvp_vfw_av_mm_control_agent_address               (mm_interconnect_0_vvp_vfw_av_mm_control_agent_address),            //  output,   width = 7,                 vvp_vfw_av_mm_control_agent.address
		.vvp_vfw_av_mm_control_agent_write                 (mm_interconnect_0_vvp_vfw_av_mm_control_agent_write),              //  output,   width = 1,                                            .write
		.vvp_vfw_av_mm_control_agent_read                  (mm_interconnect_0_vvp_vfw_av_mm_control_agent_read),               //  output,   width = 1,                                            .read
		.vvp_vfw_av_mm_control_agent_readdata              (mm_interconnect_0_vvp_vfw_av_mm_control_agent_readdata),           //   input,  width = 32,                                            .readdata
		.vvp_vfw_av_mm_control_agent_writedata             (mm_interconnect_0_vvp_vfw_av_mm_control_agent_writedata),          //  output,  width = 32,                                            .writedata
		.vvp_vfw_av_mm_control_agent_byteenable            (mm_interconnect_0_vvp_vfw_av_mm_control_agent_byteenable),         //  output,   width = 4,                                            .byteenable
		.vvp_vfw_av_mm_control_agent_readdatavalid         (mm_interconnect_0_vvp_vfw_av_mm_control_agent_readdatavalid),      //   input,   width = 1,                                            .readdatavalid
		.vvp_vfw_av_mm_control_agent_waitrequest           (mm_interconnect_0_vvp_vfw_av_mm_control_agent_waitrequest),        //   input,   width = 1,                                            .waitrequest
		.vvp_scaler_av_mm_control_agent_address            (mm_interconnect_0_vvp_scaler_av_mm_control_agent_address),         //  output,   width = 7,              vvp_scaler_av_mm_control_agent.address
		.vvp_scaler_av_mm_control_agent_write              (mm_interconnect_0_vvp_scaler_av_mm_control_agent_write),           //  output,   width = 1,                                            .write
		.vvp_scaler_av_mm_control_agent_read               (mm_interconnect_0_vvp_scaler_av_mm_control_agent_read),            //  output,   width = 1,                                            .read
		.vvp_scaler_av_mm_control_agent_readdata           (mm_interconnect_0_vvp_scaler_av_mm_control_agent_readdata),        //   input,  width = 32,                                            .readdata
		.vvp_scaler_av_mm_control_agent_writedata          (mm_interconnect_0_vvp_scaler_av_mm_control_agent_writedata),       //  output,  width = 32,                                            .writedata
		.vvp_scaler_av_mm_control_agent_byteenable         (mm_interconnect_0_vvp_scaler_av_mm_control_agent_byteenable),      //  output,   width = 4,                                            .byteenable
		.vvp_scaler_av_mm_control_agent_readdatavalid      (mm_interconnect_0_vvp_scaler_av_mm_control_agent_readdatavalid),   //   input,   width = 1,                                            .readdatavalid
		.vvp_scaler_av_mm_control_agent_waitrequest        (mm_interconnect_0_vvp_scaler_av_mm_control_agent_waitrequest),     //   input,   width = 1,                                            .waitrequest
		.vvp_demosaic_av_mm_control_agent_address          (mm_interconnect_0_vvp_demosaic_av_mm_control_agent_address),       //  output,   width = 7,            vvp_demosaic_av_mm_control_agent.address
		.vvp_demosaic_av_mm_control_agent_write            (mm_interconnect_0_vvp_demosaic_av_mm_control_agent_write),         //  output,   width = 1,                                            .write
		.vvp_demosaic_av_mm_control_agent_read             (mm_interconnect_0_vvp_demosaic_av_mm_control_agent_read),          //  output,   width = 1,                                            .read
		.vvp_demosaic_av_mm_control_agent_readdata         (mm_interconnect_0_vvp_demosaic_av_mm_control_agent_readdata),      //   input,  width = 32,                                            .readdata
		.vvp_demosaic_av_mm_control_agent_writedata        (mm_interconnect_0_vvp_demosaic_av_mm_control_agent_writedata),     //  output,  width = 32,                                            .writedata
		.vvp_demosaic_av_mm_control_agent_byteenable       (mm_interconnect_0_vvp_demosaic_av_mm_control_agent_byteenable),    //  output,   width = 4,                                            .byteenable
		.vvp_demosaic_av_mm_control_agent_readdatavalid    (mm_interconnect_0_vvp_demosaic_av_mm_control_agent_readdatavalid), //   input,   width = 1,                                            .readdatavalid
		.vvp_demosaic_av_mm_control_agent_waitrequest      (mm_interconnect_0_vvp_demosaic_av_mm_control_agent_waitrequest),   //   input,   width = 1,                                            .waitrequest
		.vvp_clipper_av_mm_control_agent_address           (mm_interconnect_0_vvp_clipper_av_mm_control_agent_address),        //  output,   width = 7,             vvp_clipper_av_mm_control_agent.address
		.vvp_clipper_av_mm_control_agent_write             (mm_interconnect_0_vvp_clipper_av_mm_control_agent_write),          //  output,   width = 1,                                            .write
		.vvp_clipper_av_mm_control_agent_read              (mm_interconnect_0_vvp_clipper_av_mm_control_agent_read),           //  output,   width = 1,                                            .read
		.vvp_clipper_av_mm_control_agent_readdata          (mm_interconnect_0_vvp_clipper_av_mm_control_agent_readdata),       //   input,  width = 32,                                            .readdata
		.vvp_clipper_av_mm_control_agent_writedata         (mm_interconnect_0_vvp_clipper_av_mm_control_agent_writedata),      //  output,  width = 32,                                            .writedata
		.vvp_clipper_av_mm_control_agent_byteenable        (mm_interconnect_0_vvp_clipper_av_mm_control_agent_byteenable),     //  output,   width = 4,                                            .byteenable
		.vvp_clipper_av_mm_control_agent_readdatavalid     (mm_interconnect_0_vvp_clipper_av_mm_control_agent_readdatavalid),  //   input,   width = 1,                                            .readdatavalid
		.vvp_clipper_av_mm_control_agent_waitrequest       (mm_interconnect_0_vvp_clipper_av_mm_control_agent_waitrequest),    //   input,   width = 1,                                            .waitrequest
		.vvp_csc_0_av_mm_control_agent_address             (mm_interconnect_0_vvp_csc_0_av_mm_control_agent_address),          //  output,   width = 7,               vvp_csc_0_av_mm_control_agent.address
		.vvp_csc_0_av_mm_control_agent_write               (mm_interconnect_0_vvp_csc_0_av_mm_control_agent_write),            //  output,   width = 1,                                            .write
		.vvp_csc_0_av_mm_control_agent_read                (mm_interconnect_0_vvp_csc_0_av_mm_control_agent_read),             //  output,   width = 1,                                            .read
		.vvp_csc_0_av_mm_control_agent_readdata            (mm_interconnect_0_vvp_csc_0_av_mm_control_agent_readdata),         //   input,  width = 32,                                            .readdata
		.vvp_csc_0_av_mm_control_agent_writedata           (mm_interconnect_0_vvp_csc_0_av_mm_control_agent_writedata),        //  output,  width = 32,                                            .writedata
		.vvp_csc_0_av_mm_control_agent_byteenable          (mm_interconnect_0_vvp_csc_0_av_mm_control_agent_byteenable),       //  output,   width = 4,                                            .byteenable
		.vvp_csc_0_av_mm_control_agent_readdatavalid       (mm_interconnect_0_vvp_csc_0_av_mm_control_agent_readdatavalid),    //   input,   width = 1,                                            .readdatavalid
		.vvp_csc_0_av_mm_control_agent_waitrequest         (mm_interconnect_0_vvp_csc_0_av_mm_control_agent_waitrequest),      //   input,   width = 1,                                            .waitrequest
		.vvp_1d_lut_0_av_mm_control_agent_address          (mm_interconnect_0_vvp_1d_lut_0_av_mm_control_agent_address),       //  output,  width = 10,            vvp_1d_lut_0_av_mm_control_agent.address
		.vvp_1d_lut_0_av_mm_control_agent_write            (mm_interconnect_0_vvp_1d_lut_0_av_mm_control_agent_write),         //  output,   width = 1,                                            .write
		.vvp_1d_lut_0_av_mm_control_agent_read             (mm_interconnect_0_vvp_1d_lut_0_av_mm_control_agent_read),          //  output,   width = 1,                                            .read
		.vvp_1d_lut_0_av_mm_control_agent_readdata         (mm_interconnect_0_vvp_1d_lut_0_av_mm_control_agent_readdata),      //   input,  width = 32,                                            .readdata
		.vvp_1d_lut_0_av_mm_control_agent_writedata        (mm_interconnect_0_vvp_1d_lut_0_av_mm_control_agent_writedata),     //  output,  width = 32,                                            .writedata
		.vvp_1d_lut_0_av_mm_control_agent_byteenable       (mm_interconnect_0_vvp_1d_lut_0_av_mm_control_agent_byteenable),    //  output,   width = 4,                                            .byteenable
		.vvp_1d_lut_0_av_mm_control_agent_readdatavalid    (mm_interconnect_0_vvp_1d_lut_0_av_mm_control_agent_readdatavalid), //   input,   width = 1,                                            .readdatavalid
		.vvp_1d_lut_0_av_mm_control_agent_waitrequest      (mm_interconnect_0_vvp_1d_lut_0_av_mm_control_agent_waitrequest),   //   input,   width = 1,                                            .waitrequest
		.vid_mm_bridge_reset_reset_bridge_in_reset_reset   (rst_controller_reset_out_reset),                                   //   input,   width = 1,   vid_mm_bridge_reset_reset_bridge_in_reset.reset
		.vvp_vfw_control_reset_reset_bridge_in_reset_reset (rst_controller_reset_out_reset),                                   //   input,   width = 1, vvp_vfw_control_reset_reset_bridge_in_reset.reset
		.cpu_clk_bridge_out_clk_clk                        (cpu_clk_bridge_out_clk_clk)                                        //   input,   width = 1,                      cpu_clk_bridge_out_clk.clk
	);

	altera_reset_controller #(
		.NUM_RESET_INPUTS          (1),
		.OUTPUT_RESET_SYNC_EDGES   ("both"),
		.SYNC_DEPTH                (2),
		.RESET_REQUEST_PRESENT     (0),
		.RESET_REQ_WAIT_TIME       (1),
		.MIN_RST_ASSERTION_TIME    (3),
		.RESET_REQ_EARLY_DSRT_TIME (1),
		.USE_RESET_REQUEST_IN0     (0),
		.USE_RESET_REQUEST_IN1     (0),
		.USE_RESET_REQUEST_IN2     (0),
		.USE_RESET_REQUEST_IN3     (0),
		.USE_RESET_REQUEST_IN4     (0),
		.USE_RESET_REQUEST_IN5     (0),
		.USE_RESET_REQUEST_IN6     (0),
		.USE_RESET_REQUEST_IN7     (0),
		.USE_RESET_REQUEST_IN8     (0),
		.USE_RESET_REQUEST_IN9     (0),
		.USE_RESET_REQUEST_IN10    (0),
		.USE_RESET_REQUEST_IN11    (0),
		.USE_RESET_REQUEST_IN12    (0),
		.USE_RESET_REQUEST_IN13    (0),
		.USE_RESET_REQUEST_IN14    (0),
		.USE_RESET_REQUEST_IN15    (0),
		.ADAPT_RESET_REQUEST       (0)
	) rst_controller (
		.reset_in0      (cpu_rst_bridge_out_reset_reset), //   input,  width = 1, reset_in0.reset
		.clk            (cpu_clk_bridge_out_clk_clk),     //   input,  width = 1,       clk.clk
		.reset_out      (rst_controller_reset_out_reset), //  output,  width = 1, reset_out.reset
		.reset_req      (),                               // (terminated),                       
		.reset_req_in0  (1'b0),                           // (terminated),                       
		.reset_in1      (1'b0),                           // (terminated),                       
		.reset_req_in1  (1'b0),                           // (terminated),                       
		.reset_in2      (1'b0),                           // (terminated),                       
		.reset_req_in2  (1'b0),                           // (terminated),                       
		.reset_in3      (1'b0),                           // (terminated),                       
		.reset_req_in3  (1'b0),                           // (terminated),                       
		.reset_in4      (1'b0),                           // (terminated),                       
		.reset_req_in4  (1'b0),                           // (terminated),                       
		.reset_in5      (1'b0),                           // (terminated),                       
		.reset_req_in5  (1'b0),                           // (terminated),                       
		.reset_in6      (1'b0),                           // (terminated),                       
		.reset_req_in6  (1'b0),                           // (terminated),                       
		.reset_in7      (1'b0),                           // (terminated),                       
		.reset_req_in7  (1'b0),                           // (terminated),                       
		.reset_in8      (1'b0),                           // (terminated),                       
		.reset_req_in8  (1'b0),                           // (terminated),                       
		.reset_in9      (1'b0),                           // (terminated),                       
		.reset_req_in9  (1'b0),                           // (terminated),                       
		.reset_in10     (1'b0),                           // (terminated),                       
		.reset_req_in10 (1'b0),                           // (terminated),                       
		.reset_in11     (1'b0),                           // (terminated),                       
		.reset_req_in11 (1'b0),                           // (terminated),                       
		.reset_in12     (1'b0),                           // (terminated),                       
		.reset_req_in12 (1'b0),                           // (terminated),                       
		.reset_in13     (1'b0),                           // (terminated),                       
		.reset_req_in13 (1'b0),                           // (terminated),                       
		.reset_in14     (1'b0),                           // (terminated),                       
		.reset_req_in14 (1'b0),                           // (terminated),                       
		.reset_in15     (1'b0),                           // (terminated),                       
		.reset_req_in15 (1'b0)                            // (terminated),                       
	);

endmodule
