// mipi_broadcaster_0_intel_vvp_axi4s_broadcaster_2430_7vqeuzq.v

// This file was auto-generated from intel_vvp_axi4s_broadcaster_hw.tcl.  If you edit it your changes
// will probably be lost.
// 
// Generated using ACDS version 25.3 109

`timescale 1 ps / 1 ps
module mipi_broadcaster_0_intel_vvp_axi4s_broadcaster_2430_7vqeuzq #(
		parameter DEVICE_FAMILY          = "Agilex 3",
		parameter BPS                    = 10,
		parameter NUMBER_OF_COLOR_PLANES = 1,
		parameter PIXELS_IN_PARALLEL     = 4,
		parameter VVP_INTF_TYPE          = "Lite",
		parameter OUT_0_TREADY           = 1,
		parameter OUT_0_FIFO             = 0,
		parameter OUT_0_FIFO_DEPTH       = 1024,
		parameter OUT_1_TREADY           = 1,
		parameter OUT_1_FIFO             = 1,
		parameter OUT_1_FIFO_DEPTH       = 4096,
		parameter OUT_2_TREADY           = 1,
		parameter OUT_2_FIFO             = 0,
		parameter OUT_2_FIFO_DEPTH       = 1024,
		parameter OUT_3_TREADY           = 1,
		parameter OUT_3_FIFO             = 0,
		parameter OUT_3_FIFO_DEPTH       = 1024,
		parameter OUT_4_TREADY           = 1,
		parameter OUT_4_FIFO             = 0,
		parameter OUT_4_FIFO_DEPTH       = 1024,
		parameter OUT_5_TREADY           = 1,
		parameter OUT_5_FIFO             = 0,
		parameter OUT_5_FIFO_DEPTH       = 1024,
		parameter OUT_6_TREADY           = 1,
		parameter OUT_6_FIFO             = 0,
		parameter OUT_6_FIFO_DEPTH       = 1024,
		parameter OUT_7_TREADY           = 1,
		parameter OUT_7_FIFO             = 0,
		parameter OUT_7_FIFO_DEPTH       = 1024,
		parameter OUT_8_TREADY           = 1,
		parameter OUT_8_FIFO             = 0,
		parameter OUT_8_FIFO_DEPTH       = 1024,
		parameter OUT_9_TREADY           = 1,
		parameter OUT_9_FIFO             = 0,
		parameter OUT_9_FIFO_DEPTH       = 1024,
		parameter OUT_10_TREADY          = 1,
		parameter OUT_10_FIFO            = 0,
		parameter OUT_10_FIFO_DEPTH      = 1024,
		parameter OUT_11_TREADY          = 1,
		parameter OUT_11_FIFO            = 0,
		parameter OUT_11_FIFO_DEPTH      = 1024,
		parameter OUT_12_TREADY          = 1,
		parameter OUT_12_FIFO            = 0,
		parameter OUT_12_FIFO_DEPTH      = 1024,
		parameter OUT_13_TREADY          = 1,
		parameter OUT_13_FIFO            = 0,
		parameter OUT_13_FIFO_DEPTH      = 1024,
		parameter OUT_14_TREADY          = 1,
		parameter OUT_14_FIFO            = 0,
		parameter OUT_14_FIFO_DEPTH      = 1024,
		parameter OUT_15_TREADY          = 1,
		parameter OUT_15_FIFO            = 0,
		parameter OUT_15_FIFO_DEPTH      = 1024,
		parameter OUT_16_TREADY          = 1,
		parameter OUT_16_FIFO            = 0,
		parameter OUT_16_FIFO_DEPTH      = 1024,
		parameter OUT_17_TREADY          = 1,
		parameter OUT_17_FIFO            = 0,
		parameter OUT_17_FIFO_DEPTH      = 1024,
		parameter OUT_18_TREADY          = 1,
		parameter OUT_18_FIFO            = 0,
		parameter OUT_18_FIFO_DEPTH      = 1024,
		parameter OUT_19_TREADY          = 1,
		parameter OUT_19_FIFO            = 0,
		parameter OUT_19_FIFO_DEPTH      = 1024,
		parameter OUT_20_TREADY          = 1,
		parameter OUT_20_FIFO            = 0,
		parameter OUT_20_FIFO_DEPTH      = 1024,
		parameter OUT_21_TREADY          = 1,
		parameter OUT_21_FIFO            = 0,
		parameter OUT_21_FIFO_DEPTH      = 1024,
		parameter OUT_22_TREADY          = 1,
		parameter OUT_22_FIFO            = 0,
		parameter OUT_22_FIFO_DEPTH      = 1024,
		parameter OUT_23_TREADY          = 1,
		parameter OUT_23_FIFO            = 0,
		parameter OUT_23_FIFO_DEPTH      = 1024,
		parameter OUT_24_TREADY          = 1,
		parameter OUT_24_FIFO            = 0,
		parameter OUT_24_FIFO_DEPTH      = 1024,
		parameter OUT_25_TREADY          = 1,
		parameter OUT_25_FIFO            = 0,
		parameter OUT_25_FIFO_DEPTH      = 1024,
		parameter OUT_26_TREADY          = 1,
		parameter OUT_26_FIFO            = 0,
		parameter OUT_26_FIFO_DEPTH      = 1024,
		parameter OUT_27_TREADY          = 1,
		parameter OUT_27_FIFO            = 0,
		parameter OUT_27_FIFO_DEPTH      = 1024,
		parameter OUT_28_TREADY          = 1,
		parameter OUT_28_FIFO            = 0,
		parameter OUT_28_FIFO_DEPTH      = 1024,
		parameter OUT_29_TREADY          = 1,
		parameter OUT_29_FIFO            = 0,
		parameter OUT_29_FIFO_DEPTH      = 1024,
		parameter OUT_30_TREADY          = 1,
		parameter OUT_30_FIFO            = 0,
		parameter OUT_30_FIFO_DEPTH      = 1024,
		parameter OUT_31_TREADY          = 1,
		parameter OUT_31_FIFO            = 0,
		parameter OUT_31_FIFO_DEPTH      = 1024,
		parameter OUTPUTS                = 2,
		parameter IN_TREADY              = 1,
		parameter GLOBAL_STALL           = 0
	) (
		input  wire [63:0] axi4s_vid_in_tdata,     //    axi4s_vid_in.tdata
		input  wire        axi4s_vid_in_tvalid,    //                .tvalid
		output wire        axi4s_vid_in_tready,    //                .tready
		input  wire        axi4s_vid_in_tlast,     //                .tlast
		input  wire [7:0]  axi4s_vid_in_tuser,     //                .tuser
		output wire [63:0] axi4s_vid_out_0_tdata,  // axi4s_vid_out_0.tdata
		output wire        axi4s_vid_out_0_tvalid, //                .tvalid
		input  wire        axi4s_vid_out_0_tready, //                .tready
		output wire        axi4s_vid_out_0_tlast,  //                .tlast
		output wire [7:0]  axi4s_vid_out_0_tuser,  //                .tuser
		output wire [63:0] axi4s_vid_out_1_tdata,  // axi4s_vid_out_1.tdata
		output wire        axi4s_vid_out_1_tvalid, //                .tvalid
		input  wire        axi4s_vid_out_1_tready, //                .tready
		output wire        axi4s_vid_out_1_tlast,  //                .tlast
		output wire [7:0]  axi4s_vid_out_1_tuser,  //                .tuser
		input  wire        vid_clock_clk,          //       vid_clock.clk,   Clock Input
		input  wire        vid_reset_reset         //       vid_reset.reset
	);

	wire    vid_reset_bridge_out_reset_reset; // vid_reset_bridge:out_rst -> core:vid_rst

	generate
		// If any of the display statements (or deliberately broken
		// instantiations) within this generate block triggers then this module
		// has been instantiated this module with a set of parameters different
		// from those it was generated for.  This will usually result in a
		// non-functioning system.
		if (DEVICE_FAMILY != "Agilex 3")
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					device_family_check ( .error(1'b1) );
		end
		if (BPS != 10)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					bps_check ( .error(1'b1) );
		end
		if (NUMBER_OF_COLOR_PLANES != 1)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					number_of_color_planes_check ( .error(1'b1) );
		end
		if (PIXELS_IN_PARALLEL != 4)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					pixels_in_parallel_check ( .error(1'b1) );
		end
		if (VVP_INTF_TYPE != "Lite")
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					vvp_intf_type_check ( .error(1'b1) );
		end
		if (OUT_0_TREADY != 1)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					out_0_tready_check ( .error(1'b1) );
		end
		if (OUT_0_FIFO != 0)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					out_0_fifo_check ( .error(1'b1) );
		end
		if (OUT_0_FIFO_DEPTH != 1024)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					out_0_fifo_depth_check ( .error(1'b1) );
		end
		if (OUT_1_TREADY != 1)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					out_1_tready_check ( .error(1'b1) );
		end
		if (OUT_1_FIFO != 1)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					out_1_fifo_check ( .error(1'b1) );
		end
		if (OUT_1_FIFO_DEPTH != 4096)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					out_1_fifo_depth_check ( .error(1'b1) );
		end
		if (OUT_2_TREADY != 1)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					out_2_tready_check ( .error(1'b1) );
		end
		if (OUT_2_FIFO != 0)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					out_2_fifo_check ( .error(1'b1) );
		end
		if (OUT_2_FIFO_DEPTH != 1024)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					out_2_fifo_depth_check ( .error(1'b1) );
		end
		if (OUT_3_TREADY != 1)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					out_3_tready_check ( .error(1'b1) );
		end
		if (OUT_3_FIFO != 0)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					out_3_fifo_check ( .error(1'b1) );
		end
		if (OUT_3_FIFO_DEPTH != 1024)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					out_3_fifo_depth_check ( .error(1'b1) );
		end
		if (OUT_4_TREADY != 1)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					out_4_tready_check ( .error(1'b1) );
		end
		if (OUT_4_FIFO != 0)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					out_4_fifo_check ( .error(1'b1) );
		end
		if (OUT_4_FIFO_DEPTH != 1024)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					out_4_fifo_depth_check ( .error(1'b1) );
		end
		if (OUT_5_TREADY != 1)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					out_5_tready_check ( .error(1'b1) );
		end
		if (OUT_5_FIFO != 0)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					out_5_fifo_check ( .error(1'b1) );
		end
		if (OUT_5_FIFO_DEPTH != 1024)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					out_5_fifo_depth_check ( .error(1'b1) );
		end
		if (OUT_6_TREADY != 1)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					out_6_tready_check ( .error(1'b1) );
		end
		if (OUT_6_FIFO != 0)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					out_6_fifo_check ( .error(1'b1) );
		end
		if (OUT_6_FIFO_DEPTH != 1024)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					out_6_fifo_depth_check ( .error(1'b1) );
		end
		if (OUT_7_TREADY != 1)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					out_7_tready_check ( .error(1'b1) );
		end
		if (OUT_7_FIFO != 0)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					out_7_fifo_check ( .error(1'b1) );
		end
		if (OUT_7_FIFO_DEPTH != 1024)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					out_7_fifo_depth_check ( .error(1'b1) );
		end
		if (OUT_8_TREADY != 1)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					out_8_tready_check ( .error(1'b1) );
		end
		if (OUT_8_FIFO != 0)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					out_8_fifo_check ( .error(1'b1) );
		end
		if (OUT_8_FIFO_DEPTH != 1024)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					out_8_fifo_depth_check ( .error(1'b1) );
		end
		if (OUT_9_TREADY != 1)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					out_9_tready_check ( .error(1'b1) );
		end
		if (OUT_9_FIFO != 0)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					out_9_fifo_check ( .error(1'b1) );
		end
		if (OUT_9_FIFO_DEPTH != 1024)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					out_9_fifo_depth_check ( .error(1'b1) );
		end
		if (OUT_10_TREADY != 1)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					out_10_tready_check ( .error(1'b1) );
		end
		if (OUT_10_FIFO != 0)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					out_10_fifo_check ( .error(1'b1) );
		end
		if (OUT_10_FIFO_DEPTH != 1024)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					out_10_fifo_depth_check ( .error(1'b1) );
		end
		if (OUT_11_TREADY != 1)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					out_11_tready_check ( .error(1'b1) );
		end
		if (OUT_11_FIFO != 0)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					out_11_fifo_check ( .error(1'b1) );
		end
		if (OUT_11_FIFO_DEPTH != 1024)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					out_11_fifo_depth_check ( .error(1'b1) );
		end
		if (OUT_12_TREADY != 1)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					out_12_tready_check ( .error(1'b1) );
		end
		if (OUT_12_FIFO != 0)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					out_12_fifo_check ( .error(1'b1) );
		end
		if (OUT_12_FIFO_DEPTH != 1024)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					out_12_fifo_depth_check ( .error(1'b1) );
		end
		if (OUT_13_TREADY != 1)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					out_13_tready_check ( .error(1'b1) );
		end
		if (OUT_13_FIFO != 0)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					out_13_fifo_check ( .error(1'b1) );
		end
		if (OUT_13_FIFO_DEPTH != 1024)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					out_13_fifo_depth_check ( .error(1'b1) );
		end
		if (OUT_14_TREADY != 1)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					out_14_tready_check ( .error(1'b1) );
		end
		if (OUT_14_FIFO != 0)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					out_14_fifo_check ( .error(1'b1) );
		end
		if (OUT_14_FIFO_DEPTH != 1024)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					out_14_fifo_depth_check ( .error(1'b1) );
		end
		if (OUT_15_TREADY != 1)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					out_15_tready_check ( .error(1'b1) );
		end
		if (OUT_15_FIFO != 0)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					out_15_fifo_check ( .error(1'b1) );
		end
		if (OUT_15_FIFO_DEPTH != 1024)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					out_15_fifo_depth_check ( .error(1'b1) );
		end
		if (OUT_16_TREADY != 1)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					out_16_tready_check ( .error(1'b1) );
		end
		if (OUT_16_FIFO != 0)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					out_16_fifo_check ( .error(1'b1) );
		end
		if (OUT_16_FIFO_DEPTH != 1024)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					out_16_fifo_depth_check ( .error(1'b1) );
		end
		if (OUT_17_TREADY != 1)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					out_17_tready_check ( .error(1'b1) );
		end
		if (OUT_17_FIFO != 0)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					out_17_fifo_check ( .error(1'b1) );
		end
		if (OUT_17_FIFO_DEPTH != 1024)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					out_17_fifo_depth_check ( .error(1'b1) );
		end
		if (OUT_18_TREADY != 1)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					out_18_tready_check ( .error(1'b1) );
		end
		if (OUT_18_FIFO != 0)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					out_18_fifo_check ( .error(1'b1) );
		end
		if (OUT_18_FIFO_DEPTH != 1024)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					out_18_fifo_depth_check ( .error(1'b1) );
		end
		if (OUT_19_TREADY != 1)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					out_19_tready_check ( .error(1'b1) );
		end
		if (OUT_19_FIFO != 0)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					out_19_fifo_check ( .error(1'b1) );
		end
		if (OUT_19_FIFO_DEPTH != 1024)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					out_19_fifo_depth_check ( .error(1'b1) );
		end
		if (OUT_20_TREADY != 1)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					out_20_tready_check ( .error(1'b1) );
		end
		if (OUT_20_FIFO != 0)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					out_20_fifo_check ( .error(1'b1) );
		end
		if (OUT_20_FIFO_DEPTH != 1024)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					out_20_fifo_depth_check ( .error(1'b1) );
		end
		if (OUT_21_TREADY != 1)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					out_21_tready_check ( .error(1'b1) );
		end
		if (OUT_21_FIFO != 0)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					out_21_fifo_check ( .error(1'b1) );
		end
		if (OUT_21_FIFO_DEPTH != 1024)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					out_21_fifo_depth_check ( .error(1'b1) );
		end
		if (OUT_22_TREADY != 1)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					out_22_tready_check ( .error(1'b1) );
		end
		if (OUT_22_FIFO != 0)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					out_22_fifo_check ( .error(1'b1) );
		end
		if (OUT_22_FIFO_DEPTH != 1024)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					out_22_fifo_depth_check ( .error(1'b1) );
		end
		if (OUT_23_TREADY != 1)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					out_23_tready_check ( .error(1'b1) );
		end
		if (OUT_23_FIFO != 0)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					out_23_fifo_check ( .error(1'b1) );
		end
		if (OUT_23_FIFO_DEPTH != 1024)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					out_23_fifo_depth_check ( .error(1'b1) );
		end
		if (OUT_24_TREADY != 1)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					out_24_tready_check ( .error(1'b1) );
		end
		if (OUT_24_FIFO != 0)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					out_24_fifo_check ( .error(1'b1) );
		end
		if (OUT_24_FIFO_DEPTH != 1024)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					out_24_fifo_depth_check ( .error(1'b1) );
		end
		if (OUT_25_TREADY != 1)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					out_25_tready_check ( .error(1'b1) );
		end
		if (OUT_25_FIFO != 0)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					out_25_fifo_check ( .error(1'b1) );
		end
		if (OUT_25_FIFO_DEPTH != 1024)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					out_25_fifo_depth_check ( .error(1'b1) );
		end
		if (OUT_26_TREADY != 1)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					out_26_tready_check ( .error(1'b1) );
		end
		if (OUT_26_FIFO != 0)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					out_26_fifo_check ( .error(1'b1) );
		end
		if (OUT_26_FIFO_DEPTH != 1024)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					out_26_fifo_depth_check ( .error(1'b1) );
		end
		if (OUT_27_TREADY != 1)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					out_27_tready_check ( .error(1'b1) );
		end
		if (OUT_27_FIFO != 0)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					out_27_fifo_check ( .error(1'b1) );
		end
		if (OUT_27_FIFO_DEPTH != 1024)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					out_27_fifo_depth_check ( .error(1'b1) );
		end
		if (OUT_28_TREADY != 1)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					out_28_tready_check ( .error(1'b1) );
		end
		if (OUT_28_FIFO != 0)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					out_28_fifo_check ( .error(1'b1) );
		end
		if (OUT_28_FIFO_DEPTH != 1024)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					out_28_fifo_depth_check ( .error(1'b1) );
		end
		if (OUT_29_TREADY != 1)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					out_29_tready_check ( .error(1'b1) );
		end
		if (OUT_29_FIFO != 0)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					out_29_fifo_check ( .error(1'b1) );
		end
		if (OUT_29_FIFO_DEPTH != 1024)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					out_29_fifo_depth_check ( .error(1'b1) );
		end
		if (OUT_30_TREADY != 1)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					out_30_tready_check ( .error(1'b1) );
		end
		if (OUT_30_FIFO != 0)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					out_30_fifo_check ( .error(1'b1) );
		end
		if (OUT_30_FIFO_DEPTH != 1024)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					out_30_fifo_depth_check ( .error(1'b1) );
		end
		if (OUT_31_TREADY != 1)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					out_31_tready_check ( .error(1'b1) );
		end
		if (OUT_31_FIFO != 0)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					out_31_fifo_check ( .error(1'b1) );
		end
		if (OUT_31_FIFO_DEPTH != 1024)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					out_31_fifo_depth_check ( .error(1'b1) );
		end
		if (OUTPUTS != 2)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					outputs_check ( .error(1'b1) );
		end
		if (IN_TREADY != 1)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					in_tready_check ( .error(1'b1) );
		end
		if (GLOBAL_STALL != 0)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					global_stall_check ( .error(1'b1) );
		end
	endgenerate

	intel_vvp_axi4s_broadcaster_core #(
		.DEVICE_FAMILY          ("Agilex 3"),
		.BPS                    (10),
		.NUMBER_OF_COLOR_PLANES (1),
		.PIXELS_IN_PARALLEL     (4),
		.VVP_INTF_TYPE          ("Lite"),
		.OUT_0_TREADY           (1),
		.OUT_0_FIFO             (0),
		.OUT_0_FIFO_DEPTH       (1024),
		.OUT_1_TREADY           (1),
		.OUT_1_FIFO             (1),
		.OUT_1_FIFO_DEPTH       (4096),
		.OUT_2_TREADY           (1),
		.OUT_2_FIFO             (0),
		.OUT_2_FIFO_DEPTH       (1024),
		.OUT_3_TREADY           (1),
		.OUT_3_FIFO             (0),
		.OUT_3_FIFO_DEPTH       (1024),
		.OUT_4_TREADY           (1),
		.OUT_4_FIFO             (0),
		.OUT_4_FIFO_DEPTH       (1024),
		.OUT_5_TREADY           (1),
		.OUT_5_FIFO             (0),
		.OUT_5_FIFO_DEPTH       (1024),
		.OUT_6_TREADY           (1),
		.OUT_6_FIFO             (0),
		.OUT_6_FIFO_DEPTH       (1024),
		.OUT_7_TREADY           (1),
		.OUT_7_FIFO             (0),
		.OUT_7_FIFO_DEPTH       (1024),
		.OUT_8_TREADY           (1),
		.OUT_8_FIFO             (0),
		.OUT_8_FIFO_DEPTH       (1024),
		.OUT_9_TREADY           (1),
		.OUT_9_FIFO             (0),
		.OUT_9_FIFO_DEPTH       (1024),
		.OUT_10_TREADY          (1),
		.OUT_10_FIFO            (0),
		.OUT_10_FIFO_DEPTH      (1024),
		.OUT_11_TREADY          (1),
		.OUT_11_FIFO            (0),
		.OUT_11_FIFO_DEPTH      (1024),
		.OUT_12_TREADY          (1),
		.OUT_12_FIFO            (0),
		.OUT_12_FIFO_DEPTH      (1024),
		.OUT_13_TREADY          (1),
		.OUT_13_FIFO            (0),
		.OUT_13_FIFO_DEPTH      (1024),
		.OUT_14_TREADY          (1),
		.OUT_14_FIFO            (0),
		.OUT_14_FIFO_DEPTH      (1024),
		.OUT_15_TREADY          (1),
		.OUT_15_FIFO            (0),
		.OUT_15_FIFO_DEPTH      (1024),
		.OUT_16_TREADY          (1),
		.OUT_16_FIFO            (0),
		.OUT_16_FIFO_DEPTH      (1024),
		.OUT_17_TREADY          (1),
		.OUT_17_FIFO            (0),
		.OUT_17_FIFO_DEPTH      (1024),
		.OUT_18_TREADY          (1),
		.OUT_18_FIFO            (0),
		.OUT_18_FIFO_DEPTH      (1024),
		.OUT_19_TREADY          (1),
		.OUT_19_FIFO            (0),
		.OUT_19_FIFO_DEPTH      (1024),
		.OUT_20_TREADY          (1),
		.OUT_20_FIFO            (0),
		.OUT_20_FIFO_DEPTH      (1024),
		.OUT_21_TREADY          (1),
		.OUT_21_FIFO            (0),
		.OUT_21_FIFO_DEPTH      (1024),
		.OUT_22_TREADY          (1),
		.OUT_22_FIFO            (0),
		.OUT_22_FIFO_DEPTH      (1024),
		.OUT_23_TREADY          (1),
		.OUT_23_FIFO            (0),
		.OUT_23_FIFO_DEPTH      (1024),
		.OUT_24_TREADY          (1),
		.OUT_24_FIFO            (0),
		.OUT_24_FIFO_DEPTH      (1024),
		.OUT_25_TREADY          (1),
		.OUT_25_FIFO            (0),
		.OUT_25_FIFO_DEPTH      (1024),
		.OUT_26_TREADY          (1),
		.OUT_26_FIFO            (0),
		.OUT_26_FIFO_DEPTH      (1024),
		.OUT_27_TREADY          (1),
		.OUT_27_FIFO            (0),
		.OUT_27_FIFO_DEPTH      (1024),
		.OUT_28_TREADY          (1),
		.OUT_28_FIFO            (0),
		.OUT_28_FIFO_DEPTH      (1024),
		.OUT_29_TREADY          (1),
		.OUT_29_FIFO            (0),
		.OUT_29_FIFO_DEPTH      (1024),
		.OUT_30_TREADY          (1),
		.OUT_30_FIFO            (0),
		.OUT_30_FIFO_DEPTH      (1024),
		.OUT_31_TREADY          (1),
		.OUT_31_FIFO            (0),
		.OUT_31_FIFO_DEPTH      (1024),
		.OUTPUTS                (2),
		.IN_TREADY              (1),
		.GLOBAL_STALL           (0)
	) core (
		.vid_clk                 (vid_clock_clk),                    //   input,   width = 1,       vid_clock.clk
		.vid_rst                 (vid_reset_bridge_out_reset_reset), //   input,   width = 1,       vid_reset.reset
		.axi4s_vid_in_tdata      (axi4s_vid_in_tdata),               //   input,  width = 64,    axi4s_vid_in.tdata
		.axi4s_vid_in_tvalid     (axi4s_vid_in_tvalid),              //   input,   width = 1,                .tvalid
		.axi4s_vid_in_tready     (axi4s_vid_in_tready),              //  output,   width = 1,                .tready
		.axi4s_vid_in_tlast      (axi4s_vid_in_tlast),               //   input,   width = 1,                .tlast
		.axi4s_vid_in_tuser      (axi4s_vid_in_tuser),               //   input,   width = 8,                .tuser
		.axi4s_vid_out_0_tdata   (axi4s_vid_out_0_tdata),            //  output,  width = 64, axi4s_vid_out_0.tdata
		.axi4s_vid_out_0_tvalid  (axi4s_vid_out_0_tvalid),           //  output,   width = 1,                .tvalid
		.axi4s_vid_out_0_tready  (axi4s_vid_out_0_tready),           //   input,   width = 1,                .tready
		.axi4s_vid_out_0_tlast   (axi4s_vid_out_0_tlast),            //  output,   width = 1,                .tlast
		.axi4s_vid_out_0_tuser   (axi4s_vid_out_0_tuser),            //  output,   width = 8,                .tuser
		.axi4s_vid_out_1_tdata   (axi4s_vid_out_1_tdata),            //  output,  width = 64, axi4s_vid_out_1.tdata
		.axi4s_vid_out_1_tvalid  (axi4s_vid_out_1_tvalid),           //  output,   width = 1,                .tvalid
		.axi4s_vid_out_1_tready  (axi4s_vid_out_1_tready),           //   input,   width = 1,                .tready
		.axi4s_vid_out_1_tlast   (axi4s_vid_out_1_tlast),            //  output,   width = 1,                .tlast
		.axi4s_vid_out_1_tuser   (axi4s_vid_out_1_tuser),            //  output,   width = 8,                .tuser
		.axi4s_vid_out_2_tdata   (),                                 // (terminated),                              
		.axi4s_vid_out_2_tvalid  (),                                 // (terminated),                              
		.axi4s_vid_out_2_tready  (1'b0),                             // (terminated),                              
		.axi4s_vid_out_2_tlast   (),                                 // (terminated),                              
		.axi4s_vid_out_2_tuser   (),                                 // (terminated),                              
		.axi4s_vid_out_3_tdata   (),                                 // (terminated),                              
		.axi4s_vid_out_3_tvalid  (),                                 // (terminated),                              
		.axi4s_vid_out_3_tready  (1'b0),                             // (terminated),                              
		.axi4s_vid_out_3_tlast   (),                                 // (terminated),                              
		.axi4s_vid_out_3_tuser   (),                                 // (terminated),                              
		.axi4s_vid_out_4_tdata   (),                                 // (terminated),                              
		.axi4s_vid_out_4_tvalid  (),                                 // (terminated),                              
		.axi4s_vid_out_4_tready  (1'b0),                             // (terminated),                              
		.axi4s_vid_out_4_tlast   (),                                 // (terminated),                              
		.axi4s_vid_out_4_tuser   (),                                 // (terminated),                              
		.axi4s_vid_out_5_tdata   (),                                 // (terminated),                              
		.axi4s_vid_out_5_tvalid  (),                                 // (terminated),                              
		.axi4s_vid_out_5_tready  (1'b0),                             // (terminated),                              
		.axi4s_vid_out_5_tlast   (),                                 // (terminated),                              
		.axi4s_vid_out_5_tuser   (),                                 // (terminated),                              
		.axi4s_vid_out_6_tdata   (),                                 // (terminated),                              
		.axi4s_vid_out_6_tvalid  (),                                 // (terminated),                              
		.axi4s_vid_out_6_tready  (1'b0),                             // (terminated),                              
		.axi4s_vid_out_6_tlast   (),                                 // (terminated),                              
		.axi4s_vid_out_6_tuser   (),                                 // (terminated),                              
		.axi4s_vid_out_7_tdata   (),                                 // (terminated),                              
		.axi4s_vid_out_7_tvalid  (),                                 // (terminated),                              
		.axi4s_vid_out_7_tready  (1'b0),                             // (terminated),                              
		.axi4s_vid_out_7_tlast   (),                                 // (terminated),                              
		.axi4s_vid_out_7_tuser   (),                                 // (terminated),                              
		.axi4s_vid_out_8_tdata   (),                                 // (terminated),                              
		.axi4s_vid_out_8_tvalid  (),                                 // (terminated),                              
		.axi4s_vid_out_8_tready  (1'b0),                             // (terminated),                              
		.axi4s_vid_out_8_tlast   (),                                 // (terminated),                              
		.axi4s_vid_out_8_tuser   (),                                 // (terminated),                              
		.axi4s_vid_out_9_tdata   (),                                 // (terminated),                              
		.axi4s_vid_out_9_tvalid  (),                                 // (terminated),                              
		.axi4s_vid_out_9_tready  (1'b0),                             // (terminated),                              
		.axi4s_vid_out_9_tlast   (),                                 // (terminated),                              
		.axi4s_vid_out_9_tuser   (),                                 // (terminated),                              
		.axi4s_vid_out_10_tdata  (),                                 // (terminated),                              
		.axi4s_vid_out_10_tvalid (),                                 // (terminated),                              
		.axi4s_vid_out_10_tready (1'b0),                             // (terminated),                              
		.axi4s_vid_out_10_tlast  (),                                 // (terminated),                              
		.axi4s_vid_out_10_tuser  (),                                 // (terminated),                              
		.axi4s_vid_out_11_tdata  (),                                 // (terminated),                              
		.axi4s_vid_out_11_tvalid (),                                 // (terminated),                              
		.axi4s_vid_out_11_tready (1'b0),                             // (terminated),                              
		.axi4s_vid_out_11_tlast  (),                                 // (terminated),                              
		.axi4s_vid_out_11_tuser  (),                                 // (terminated),                              
		.axi4s_vid_out_12_tdata  (),                                 // (terminated),                              
		.axi4s_vid_out_12_tvalid (),                                 // (terminated),                              
		.axi4s_vid_out_12_tready (1'b0),                             // (terminated),                              
		.axi4s_vid_out_12_tlast  (),                                 // (terminated),                              
		.axi4s_vid_out_12_tuser  (),                                 // (terminated),                              
		.axi4s_vid_out_13_tdata  (),                                 // (terminated),                              
		.axi4s_vid_out_13_tvalid (),                                 // (terminated),                              
		.axi4s_vid_out_13_tready (1'b0),                             // (terminated),                              
		.axi4s_vid_out_13_tlast  (),                                 // (terminated),                              
		.axi4s_vid_out_13_tuser  (),                                 // (terminated),                              
		.axi4s_vid_out_14_tdata  (),                                 // (terminated),                              
		.axi4s_vid_out_14_tvalid (),                                 // (terminated),                              
		.axi4s_vid_out_14_tready (1'b0),                             // (terminated),                              
		.axi4s_vid_out_14_tlast  (),                                 // (terminated),                              
		.axi4s_vid_out_14_tuser  (),                                 // (terminated),                              
		.axi4s_vid_out_15_tdata  (),                                 // (terminated),                              
		.axi4s_vid_out_15_tvalid (),                                 // (terminated),                              
		.axi4s_vid_out_15_tready (1'b0),                             // (terminated),                              
		.axi4s_vid_out_15_tlast  (),                                 // (terminated),                              
		.axi4s_vid_out_15_tuser  (),                                 // (terminated),                              
		.axi4s_vid_out_16_tdata  (),                                 // (terminated),                              
		.axi4s_vid_out_16_tvalid (),                                 // (terminated),                              
		.axi4s_vid_out_16_tready (1'b0),                             // (terminated),                              
		.axi4s_vid_out_16_tlast  (),                                 // (terminated),                              
		.axi4s_vid_out_16_tuser  (),                                 // (terminated),                              
		.axi4s_vid_out_17_tdata  (),                                 // (terminated),                              
		.axi4s_vid_out_17_tvalid (),                                 // (terminated),                              
		.axi4s_vid_out_17_tready (1'b0),                             // (terminated),                              
		.axi4s_vid_out_17_tlast  (),                                 // (terminated),                              
		.axi4s_vid_out_17_tuser  (),                                 // (terminated),                              
		.axi4s_vid_out_18_tdata  (),                                 // (terminated),                              
		.axi4s_vid_out_18_tvalid (),                                 // (terminated),                              
		.axi4s_vid_out_18_tready (1'b0),                             // (terminated),                              
		.axi4s_vid_out_18_tlast  (),                                 // (terminated),                              
		.axi4s_vid_out_18_tuser  (),                                 // (terminated),                              
		.axi4s_vid_out_19_tdata  (),                                 // (terminated),                              
		.axi4s_vid_out_19_tvalid (),                                 // (terminated),                              
		.axi4s_vid_out_19_tready (1'b0),                             // (terminated),                              
		.axi4s_vid_out_19_tlast  (),                                 // (terminated),                              
		.axi4s_vid_out_19_tuser  (),                                 // (terminated),                              
		.axi4s_vid_out_20_tdata  (),                                 // (terminated),                              
		.axi4s_vid_out_20_tvalid (),                                 // (terminated),                              
		.axi4s_vid_out_20_tready (1'b0),                             // (terminated),                              
		.axi4s_vid_out_20_tlast  (),                                 // (terminated),                              
		.axi4s_vid_out_20_tuser  (),                                 // (terminated),                              
		.axi4s_vid_out_21_tdata  (),                                 // (terminated),                              
		.axi4s_vid_out_21_tvalid (),                                 // (terminated),                              
		.axi4s_vid_out_21_tready (1'b0),                             // (terminated),                              
		.axi4s_vid_out_21_tlast  (),                                 // (terminated),                              
		.axi4s_vid_out_21_tuser  (),                                 // (terminated),                              
		.axi4s_vid_out_22_tdata  (),                                 // (terminated),                              
		.axi4s_vid_out_22_tvalid (),                                 // (terminated),                              
		.axi4s_vid_out_22_tready (1'b0),                             // (terminated),                              
		.axi4s_vid_out_22_tlast  (),                                 // (terminated),                              
		.axi4s_vid_out_22_tuser  (),                                 // (terminated),                              
		.axi4s_vid_out_23_tdata  (),                                 // (terminated),                              
		.axi4s_vid_out_23_tvalid (),                                 // (terminated),                              
		.axi4s_vid_out_23_tready (1'b0),                             // (terminated),                              
		.axi4s_vid_out_23_tlast  (),                                 // (terminated),                              
		.axi4s_vid_out_23_tuser  (),                                 // (terminated),                              
		.axi4s_vid_out_24_tdata  (),                                 // (terminated),                              
		.axi4s_vid_out_24_tvalid (),                                 // (terminated),                              
		.axi4s_vid_out_24_tready (1'b0),                             // (terminated),                              
		.axi4s_vid_out_24_tlast  (),                                 // (terminated),                              
		.axi4s_vid_out_24_tuser  (),                                 // (terminated),                              
		.axi4s_vid_out_25_tdata  (),                                 // (terminated),                              
		.axi4s_vid_out_25_tvalid (),                                 // (terminated),                              
		.axi4s_vid_out_25_tready (1'b0),                             // (terminated),                              
		.axi4s_vid_out_25_tlast  (),                                 // (terminated),                              
		.axi4s_vid_out_25_tuser  (),                                 // (terminated),                              
		.axi4s_vid_out_26_tdata  (),                                 // (terminated),                              
		.axi4s_vid_out_26_tvalid (),                                 // (terminated),                              
		.axi4s_vid_out_26_tready (1'b0),                             // (terminated),                              
		.axi4s_vid_out_26_tlast  (),                                 // (terminated),                              
		.axi4s_vid_out_26_tuser  (),                                 // (terminated),                              
		.axi4s_vid_out_27_tdata  (),                                 // (terminated),                              
		.axi4s_vid_out_27_tvalid (),                                 // (terminated),                              
		.axi4s_vid_out_27_tready (1'b0),                             // (terminated),                              
		.axi4s_vid_out_27_tlast  (),                                 // (terminated),                              
		.axi4s_vid_out_27_tuser  (),                                 // (terminated),                              
		.axi4s_vid_out_28_tdata  (),                                 // (terminated),                              
		.axi4s_vid_out_28_tvalid (),                                 // (terminated),                              
		.axi4s_vid_out_28_tready (1'b0),                             // (terminated),                              
		.axi4s_vid_out_28_tlast  (),                                 // (terminated),                              
		.axi4s_vid_out_28_tuser  (),                                 // (terminated),                              
		.axi4s_vid_out_29_tdata  (),                                 // (terminated),                              
		.axi4s_vid_out_29_tvalid (),                                 // (terminated),                              
		.axi4s_vid_out_29_tready (1'b0),                             // (terminated),                              
		.axi4s_vid_out_29_tlast  (),                                 // (terminated),                              
		.axi4s_vid_out_29_tuser  (),                                 // (terminated),                              
		.axi4s_vid_out_30_tdata  (),                                 // (terminated),                              
		.axi4s_vid_out_30_tvalid (),                                 // (terminated),                              
		.axi4s_vid_out_30_tready (1'b0),                             // (terminated),                              
		.axi4s_vid_out_30_tlast  (),                                 // (terminated),                              
		.axi4s_vid_out_30_tuser  (),                                 // (terminated),                              
		.axi4s_vid_out_31_tdata  (),                                 // (terminated),                              
		.axi4s_vid_out_31_tvalid (),                                 // (terminated),                              
		.axi4s_vid_out_31_tready (1'b0),                             // (terminated),                              
		.axi4s_vid_out_31_tlast  (),                                 // (terminated),                              
		.axi4s_vid_out_31_tuser  ()                                  // (terminated),                              
	);

	intel_vvp_reset_sync #(
		.SYNC_LEN (3)
	) vid_reset_bridge (
		.clk     (vid_clock_clk),                    //   input,  width = 1,       clk.clk
		.in_rst  (vid_reset_reset),                  //   input,  width = 1,  in_reset.reset
		.out_rst (vid_reset_bridge_out_reset_reset)  //  output,  width = 1, out_reset.reset
	);

endmodule
