# (C) 2001-2025 Altera Corporation. All rights reserved.
# Your use of Altera Corporation's design tools, logic functions and other 
# software and tools, and its AMPP partner logic functions, and any output 
# files from any of the foregoing (including device programming or simulation 
# files), and any associated documentation or information are expressly subject 
# to the terms and conditions of the Altera Program License Subscription 
# Agreement, Altera IP License Agreement, or other applicable 
# license agreement, including, without limitation, that your use is for the 
# sole purpose of programming logic devices manufactured by Altera and sold by 
# Altera or its authorized distributors.  Please refer to the applicable 
# agreement for further details.


#####################################################################
#
# THIS IS AN AUTO-GENERATED FILE!
# -------------------------------
# If you modify this files, all your changes will be lost if you
# regenerate the core!
#
# FILE DESCRIPTION
# ----------------
# This file specifies the timing properties of the memory device and
# of the memory interface





array set mipi_param {}



set mipi_param(FPGA_FAMILY)				FAMILY_INVALID
set mipi_param(FPGA_SPEEDGRADE)				7
set mipi_param(GUI_NUM_PLL)				1
set mipi_param(GUI_RZQ_SHARING)				false
set mipi_param(GUI_RZQ_ID)				0
set mipi_param(GUI_SKEW_CAL_LEN)				32768
set mipi_param(GUI_ALT_CAL_LEN)				65536
set mipi_param(IS_REVA)				false
set mipi_param(SHOW_8PPI)				false
set mipi_param(GUI_CORE_CLK_DIV_0)				8
set mipi_param(GUI_REF_CLK_FREQ_MHZ_0)				25.0
set mipi_param(GUI_REF_CLK_IO_0)				0
set mipi_param(GUI_VCO_FREQ_MHZ_0)				800.0
set mipi_param(DER_CORE_CLK_FREQ_MHZ_0)				100.0
set mipi_param(DER_REF_CLK_FREQ_0)				25000000
set mipi_param(DER_VCO_FREQ_0)				800000000
set mipi_param(DER_CORE_CLK_FREQ_0)				100000000
set mipi_param(GUI_CORE_CLK_DIV_1)				8
set mipi_param(GUI_REF_CLK_IO_SHARE)				true
set mipi_param(GUI_REF_CLK_FREQ_MHZ_1)				20.0
set mipi_param(GUI_REF_CLK_IO_1)				0
set mipi_param(GUI_VCO_FREQ_MHZ_1)				600.0
set mipi_param(DER_CORE_CLK_FREQ_MHZ_1)				75.0
set mipi_param(DER_REF_CLK_FREQ_1)				20000000
set mipi_param(DER_VCO_FREQ_1)				600000000
set mipi_param(DER_CORE_CLK_FREQ_1)				75000000
set mipi_param(GUI_DPHY_IP_ROLE_0)				0
set mipi_param(DER_LINK_USED_0)				true
set mipi_param(GUI_SKEW_CAL_EN_0)				false
set mipi_param(GUI_SOURCE_PLL_0)				0
set mipi_param(GUI_TM_EN_0)				false
set mipi_param(GUI_TX_VCO_FREQ_MULT_0)				1
set mipi_param(GUI_BIT_RATE_MBPS_RNG_0)				987.0
set mipi_param(DER_VCO_FREQ_MHZ_LINK_0)				800.0
set mipi_param(GUI_RX_BIT_RATE_MBPS_SEL_0)				64
set mipi_param(GUI_PPI_WIDTH_USR_0)				16
set mipi_param(DER_BIT_RATE_MBPS_0)				987.0
set mipi_param(DER_PPI_WIDTH_0)				16
set mipi_param(GUI_ALT_CAL_EN_0)				false
set mipi_param(GUI_PER_SKEW_CAL_EN_0)				false
set mipi_param(GUI_PREAMBLE_EN_0)				false
set mipi_param(GUI_TX_PREAMBLE_LEN_PREAMLBE_LEN_0)				0
set mipi_param(GUI_TX_TM_CONTROL_TX_TM_EN_0)				false
set mipi_param(GUI_RX_TM_CONTROL_RX_TM_EN_0)				false
set mipi_param(GUI_TM_LOOPBACK_MODE_0)				false
set mipi_param(GUI_TX_TM_CONTROL_TX_TM_LOOPBACK_MODE_0)				false
set mipi_param(GUI_RX_TM_CONTROL_RX_TM_LOOPBACK_MODE_0)				false
set mipi_param(GUI_NUM_LANES_0)				2
set mipi_param(GUI_BYTE_LOC_0)				6
set mipi_param(GUI_CONTINUOUS_CLK_0)				false
set mipi_param(GUI_PRBS_INIT_0_0)				255
set mipi_param(GUI_PRBS_INIT_1_0)				255
set mipi_param(GUI_PRBS_INIT_2_0)				255
set mipi_param(GUI_PRBS_INIT_3_0)				255
set mipi_param(GUI_PRBS_INIT_4_0)				255
set mipi_param(GUI_PRBS_INIT_5_0)				255
set mipi_param(GUI_PRBS_INIT_6_0)				255
set mipi_param(GUI_PRBS_INIT_7_0)				255
set mipi_param(DER_PPI_WIDTH_16_0)				true
set mipi_param(DER_FR_CLK_FREQ_MHZ_0)				100.0
set mipi_param(DER_BIT_RATE_0)				987000000
set mipi_param(DER_UI_0)				1.0131712259371835
set mipi_param(DER_LINK_PLL_SRC_0)				false
set mipi_param(GUI_RX_TIMING_RW_0)				1
set mipi_param(DER_DPHY_RX_EN_0)				true
set mipi_param(DER_RXFIFO_LAT_0)				2
set mipi_param(DER_RX_FR_CLK_FREQ_0)				100000000
set mipi_param(DER_RX_CORE_FREQ_0)				61687500
set mipi_param(DER_RX_FR_CLK_PER_0)				10.0
set mipi_param(DER_RX_CORE_PER_0)				16.210739614994935
set mipi_param(DER_RX_FR_CLK_PER_PS_0)				10000
set mipi_param(DER_RX_CORE_PER_PS_0)				16210
set mipi_param(DER_RX_FR_CLK_PER_1K_0)				10240.0
set mipi_param(DER_RX_CORE_PER_1K_0)				16599.797365754814
set mipi_param(DER_RX_FR_CLK_PER_1K_PS_0)				10240000
set mipi_param(DER_RX_CORE_PER_1K_PS_0)				16599797
set mipi_param(DER_RX_PPI_WIDTH_INT_C2P_0)				16
set mipi_param(DER_RX_PPI_WIDTH_16_C2P_0)				true
set mipi_param(DER_RX_TIMING_REG_RW_0)				true
set mipi_param(DER_RX_CLK_LOSS_DETECT_MIN_0)				4
set mipi_param(DER_RX_CLK_LOSS_DETECT_MAX_0)				6
set mipi_param(DER_RX_CLK_LOSS_DETECT_MID_0)				5
set mipi_param(DER_RX_CLK_SETTLE_MIN_0)				1
set mipi_param(DER_RX_CLK_SETTLE_MAX_0)				20
set mipi_param(DER_RX_CLK_SETTLE_MID_0)				10
set mipi_param(DER_RX_HS_SETTLE_MIN_0)				3
set mipi_param(DER_RX_HS_SETTLE_MAX_0)				8
set mipi_param(DER_RX_HS_SETTLE_MID_0)				5
set mipi_param(DER_RX_INIT_MIN_0)				10
set mipi_param(DER_RX_INIT_MAX_0)				20
set mipi_param(DER_RX_INIT_MID_0)				15
set mipi_param(GUI_RX_AUTO_TYPE_0)				2
set mipi_param(GUI_RX_PREP_TIME_TM_0)				0
set mipi_param(GUI_RX_CLK_LOSS_DETECT_0)				5
set mipi_param(GUI_RX_CLK_SETTLE_0)				10
set mipi_param(GUI_RX_HS_SETTLE_0)				5
set mipi_param(GUI_RX_INIT_0)				15
set mipi_param(GUI_RX_CLK_POST_0)				1
set mipi_param(GUI_RX_DLANE_DESKEW_DELAY_0_0)				0
set mipi_param(GUI_RX_DLANE_DESKEW_DELAY_1_0)				0
set mipi_param(GUI_RX_DLANE_DESKEW_DELAY_2_0)				0
set mipi_param(GUI_RX_DLANE_DESKEW_DELAY_3_0)				0
set mipi_param(GUI_RX_DLANE_DESKEW_DELAY_4_0)				0
set mipi_param(GUI_RX_DLANE_DESKEW_DELAY_5_0)				0
set mipi_param(GUI_RX_DLANE_DESKEW_DELAY_6_0)				0
set mipi_param(GUI_RX_DLANE_DESKEW_DELAY_7_0)				0
set mipi_param(DER_RX_CLK_LOSS_DETECT_NS_0)				110.0
set mipi_param(DER_RX_CLK_SETTLE_NS_0)				192.42147922998987
set mipi_param(DER_RX_HS_SETTLE_NS_0)				120.0
set mipi_param(DER_RX_INIT_NS_0)				153600.0
set mipi_param(GUI_RX_CAP_EQ_MODE_0)				0
set mipi_param(GUI_TX_TIMING_RW_0)				1
set mipi_param(DER_DPHY_TX_EN_0)				false
set mipi_param(DER_TXFIFO_LAT_0)				3
set mipi_param(DER_TX_CORE_FREQ_0)				100000000
set mipi_param(DER_TX_CORE_PER_0)				10.0
set mipi_param(DER_TX_CORE_PER_PS_0)				10000
set mipi_param(DER_TX_CORE_PER_1K_0)				10240.0
set mipi_param(DER_TX_CORE_PER_1K_PS_0)				10240000
set mipi_param(DER_TX_TIMING_REG_RW_0)				true
set mipi_param(DER_TX_LPX_MIN_0)				5
set mipi_param(DER_TX_LPX_MAX_0)				10
set mipi_param(DER_TX_LPX_MID_0)				7
set mipi_param(DER_TX_HS_EXIT_MIN_0)				10
set mipi_param(DER_TX_HS_EXIT_MAX_0)				20
set mipi_param(DER_TX_HS_EXIT_MID_0)				15
set mipi_param(DER_TX_LP_EXIT_MIN_0)				10
set mipi_param(DER_TX_LP_EXIT_MAX_0)				20
set mipi_param(DER_TX_LP_EXIT_MID_0)				15
set mipi_param(DER_TX_CLK_PREPARE_MIN_0)				2
set mipi_param(DER_TX_CLK_PREPARE_MAX_0)				7
set mipi_param(DER_TX_CLK_PREPARE_MID_0)				4
set mipi_param(DER_TX_CLK_TRAIL_MIN_0)				7
set mipi_param(DER_TX_CLK_TRAIL_MAX_0)				12
set mipi_param(DER_TX_CLK_TRAIL_MID_0)				9
set mipi_param(DER_TX_CLK_ZERO_MIN_0)				22
set mipi_param(DER_TX_CLK_ZERO_MAX_0)				44
set mipi_param(DER_TX_CLK_ZERO_MID_0)				33
set mipi_param(DER_TX_CLK_POST_MIN_0)				9
set mipi_param(DER_TX_CLK_POST_MAX_0)				18
set mipi_param(DER_TX_CLK_POST_MID_0)				13
set mipi_param(DER_TX_CLK_PRE_MIN_0)				2
set mipi_param(DER_TX_CLK_PRE_MAX_0)				4
set mipi_param(DER_TX_CLK_PRE_MID_0)				3
set mipi_param(DER_TX_HS_PREPARE_MIN_0)				3
set mipi_param(DER_TX_HS_PREPARE_MAX_0)				7
set mipi_param(DER_TX_HS_PREPARE_MID_0)				4
set mipi_param(DER_TX_HS_ZERO_MIN_0)				7
set mipi_param(DER_TX_HS_ZERO_MAX_0)				14
set mipi_param(DER_TX_HS_ZERO_MID_0)				10
set mipi_param(DER_TX_HS_TRAIL_MIN_0)				9
set mipi_param(DER_TX_HS_TRAIL_MAX_0)				13
set mipi_param(DER_TX_HS_TRAIL_MID_0)				10
set mipi_param(DER_TX_INIT_MIN_0)				10
set mipi_param(DER_TX_INIT_MAX_0)				20
set mipi_param(DER_TX_INIT_MID_0)				15
set mipi_param(DER_TX_WAKE_MIN_0)				98
set mipi_param(DER_TX_WAKE_MAX_0)				196
set mipi_param(DER_TX_WAKE_MID_0)				147
set mipi_param(GUI_TX_AUTO_TYPE_0)				2
set mipi_param(GUI_TX_CAP_EQ_MODE_0)				0
set mipi_param(GUI_TX_CLK_LANE_PS_0)				32
set mipi_param(GUI_TX_HS_TM_DESKEW_P_0)				0
set mipi_param(GUI_TX_LPX_0)				7
set mipi_param(GUI_TX_HS_EXIT_0)				15
set mipi_param(GUI_TX_LP_EXIT_0)				15
set mipi_param(GUI_TX_CLK_PREPARE_0)				4
set mipi_param(GUI_TX_CLK_TRAIL_0)				9
set mipi_param(GUI_TX_CLK_ZERO_0)				33
set mipi_param(GUI_TX_CLK_POST_0)				13
set mipi_param(GUI_TX_CLK_PRE_0)				3
set mipi_param(GUI_TX_HS_PREPARE_0)				4
set mipi_param(GUI_TX_HS_ZERO_0)				10
set mipi_param(GUI_TX_HS_TRAIL_0)				10
set mipi_param(GUI_TX_INIT_0)				15
set mipi_param(GUI_TX_WAKE_0)				147
set mipi_param(DER_TX_LPX_NS_0)				70.0
set mipi_param(DER_TX_HS_EXIT_NS_0)				150.0
set mipi_param(DER_TX_LP_EXIT_NS_0)				150.0
set mipi_param(DER_TX_CLK_PREPARE_NS_0)				60.0
set mipi_param(DER_TX_CLK_TRAIL_NS_0)				80.0
set mipi_param(DER_TX_CLK_ZERO_NS_0)				380.0
set mipi_param(DER_TX_CLK_POST_NS_0)				180.0
set mipi_param(DER_TX_CLK_PRE_NS_0)				20.0
set mipi_param(DER_TX_HS_PREPARE_NS_0)				60.0
set mipi_param(DER_TX_HS_ZERO_NS_0)				170.0
set mipi_param(DER_TX_HS_TRAIL_NS_0)				80.0
set mipi_param(DER_TX_INIT_NS_0)				153600.0
set mipi_param(DER_TX_WAKE_NS_0)				1505280.0
set mipi_param(GUI_DPHY_IP_ROLE_1)				2
set mipi_param(DER_LINK_USED_1)				false
set mipi_param(GUI_SKEW_CAL_EN_1)				false
set mipi_param(GUI_SOURCE_PLL_1)				0
set mipi_param(GUI_TM_EN_1)				false
set mipi_param(GUI_TX_VCO_FREQ_MULT_1)				1
set mipi_param(GUI_BIT_RATE_MBPS_RNG_1)				1600.0
set mipi_param(DER_VCO_FREQ_MHZ_LINK_1)				800.0
set mipi_param(GUI_RX_BIT_RATE_MBPS_SEL_1)				64
set mipi_param(GUI_PPI_WIDTH_USR_1)				16
set mipi_param(DER_BIT_RATE_MBPS_1)				1600.0
set mipi_param(DER_PPI_WIDTH_1)				16
set mipi_param(GUI_ALT_CAL_EN_1)				false
set mipi_param(GUI_PER_SKEW_CAL_EN_1)				false
set mipi_param(GUI_PREAMBLE_EN_1)				false
set mipi_param(GUI_TX_PREAMBLE_LEN_PREAMLBE_LEN_1)				0
set mipi_param(GUI_TX_TM_CONTROL_TX_TM_EN_1)				false
set mipi_param(GUI_RX_TM_CONTROL_RX_TM_EN_1)				false
set mipi_param(GUI_TM_LOOPBACK_MODE_1)				false
set mipi_param(GUI_TX_TM_CONTROL_TX_TM_LOOPBACK_MODE_1)				false
set mipi_param(GUI_RX_TM_CONTROL_RX_TM_LOOPBACK_MODE_1)				false
set mipi_param(GUI_NUM_LANES_1)				1
set mipi_param(GUI_BYTE_LOC_1)				1
set mipi_param(GUI_CONTINUOUS_CLK_1)				false
set mipi_param(GUI_PRBS_INIT_0_1)				255
set mipi_param(GUI_PRBS_INIT_1_1)				255
set mipi_param(GUI_PRBS_INIT_2_1)				255
set mipi_param(GUI_PRBS_INIT_3_1)				255
set mipi_param(GUI_PRBS_INIT_4_1)				255
set mipi_param(GUI_PRBS_INIT_5_1)				255
set mipi_param(GUI_PRBS_INIT_6_1)				255
set mipi_param(GUI_PRBS_INIT_7_1)				255
set mipi_param(DER_PPI_WIDTH_16_1)				true
set mipi_param(DER_FR_CLK_FREQ_MHZ_1)				100.0
set mipi_param(DER_BIT_RATE_1)				1600000000
set mipi_param(DER_UI_1)				0.625
set mipi_param(DER_LINK_PLL_SRC_1)				false
set mipi_param(GUI_RX_TIMING_RW_1)				1
set mipi_param(DER_DPHY_RX_EN_1)				false
set mipi_param(DER_RXFIFO_LAT_1)				2
set mipi_param(DER_RX_FR_CLK_FREQ_1)				100000000
set mipi_param(DER_RX_CORE_FREQ_1)				100000000
set mipi_param(DER_RX_FR_CLK_PER_1)				10.0
set mipi_param(DER_RX_CORE_PER_1)				10.0
set mipi_param(DER_RX_FR_CLK_PER_PS_1)				10000
set mipi_param(DER_RX_CORE_PER_PS_1)				10000
set mipi_param(DER_RX_FR_CLK_PER_1K_1)				10240.0
set mipi_param(DER_RX_CORE_PER_1K_1)				10240.0
set mipi_param(DER_RX_FR_CLK_PER_1K_PS_1)				10240000
set mipi_param(DER_RX_CORE_PER_1K_PS_1)				10240000
set mipi_param(DER_RX_PPI_WIDTH_INT_C2P_1)				16
set mipi_param(DER_RX_PPI_WIDTH_16_C2P_1)				true
set mipi_param(DER_RX_TIMING_REG_RW_1)				true
set mipi_param(DER_RX_CLK_LOSS_DETECT_MIN_1)				2
set mipi_param(DER_RX_CLK_LOSS_DETECT_MAX_1)				4
set mipi_param(DER_RX_CLK_LOSS_DETECT_MID_1)				3
set mipi_param(DER_RX_CLK_SETTLE_MIN_1)				2
set mipi_param(DER_RX_CLK_SETTLE_MAX_1)				22
set mipi_param(DER_RX_CLK_SETTLE_MID_1)				12
set mipi_param(DER_RX_HS_SETTLE_MIN_1)				2
set mipi_param(DER_RX_HS_SETTLE_MAX_1)				8
set mipi_param(DER_RX_HS_SETTLE_MID_1)				5
set mipi_param(DER_RX_INIT_MIN_1)				10
set mipi_param(DER_RX_INIT_MAX_1)				20
set mipi_param(DER_RX_INIT_MID_1)				15
set mipi_param(GUI_RX_AUTO_TYPE_1)				2
set mipi_param(GUI_RX_PREP_TIME_TM_1)				0
set mipi_param(GUI_RX_CLK_LOSS_DETECT_1)				3
set mipi_param(GUI_RX_CLK_SETTLE_1)				12
set mipi_param(GUI_RX_HS_SETTLE_1)				5
set mipi_param(GUI_RX_INIT_1)				15
set mipi_param(GUI_RX_CLK_POST_1)				1
set mipi_param(GUI_RX_DLANE_DESKEW_DELAY_0_1)				0
set mipi_param(GUI_RX_DLANE_DESKEW_DELAY_1_1)				0
set mipi_param(GUI_RX_DLANE_DESKEW_DELAY_2_1)				0
set mipi_param(GUI_RX_DLANE_DESKEW_DELAY_3_1)				0
set mipi_param(GUI_RX_DLANE_DESKEW_DELAY_4_1)				0
set mipi_param(GUI_RX_DLANE_DESKEW_DELAY_5_1)				0
set mipi_param(GUI_RX_DLANE_DESKEW_DELAY_6_1)				0
set mipi_param(GUI_RX_DLANE_DESKEW_DELAY_7_1)				0
set mipi_param(DER_RX_CLK_LOSS_DETECT_NS_1)				90.0
set mipi_param(DER_RX_CLK_SETTLE_NS_1)				200.0
set mipi_param(DER_RX_HS_SETTLE_NS_1)				120.0
set mipi_param(DER_RX_INIT_NS_1)				153600.0
set mipi_param(GUI_RX_CAP_EQ_MODE_1)				0
set mipi_param(GUI_TX_TIMING_RW_1)				1
set mipi_param(DER_DPHY_TX_EN_1)				false
set mipi_param(DER_TXFIFO_LAT_1)				3
set mipi_param(DER_TX_CORE_FREQ_1)				100000000
set mipi_param(DER_TX_CORE_PER_1)				10.0
set mipi_param(DER_TX_CORE_PER_PS_1)				10000
set mipi_param(DER_TX_CORE_PER_1K_1)				10240.0
set mipi_param(DER_TX_CORE_PER_1K_PS_1)				10240000
set mipi_param(DER_TX_TIMING_REG_RW_1)				true
set mipi_param(DER_TX_LPX_MIN_1)				5
set mipi_param(DER_TX_LPX_MAX_1)				10
set mipi_param(DER_TX_LPX_MID_1)				7
set mipi_param(DER_TX_HS_EXIT_MIN_1)				10
set mipi_param(DER_TX_HS_EXIT_MAX_1)				20
set mipi_param(DER_TX_HS_EXIT_MID_1)				15
set mipi_param(DER_TX_LP_EXIT_MIN_1)				10
set mipi_param(DER_TX_LP_EXIT_MAX_1)				20
set mipi_param(DER_TX_LP_EXIT_MID_1)				15
set mipi_param(DER_TX_CLK_PREPARE_MIN_1)				2
set mipi_param(DER_TX_CLK_PREPARE_MAX_1)				7
set mipi_param(DER_TX_CLK_PREPARE_MID_1)				4
set mipi_param(DER_TX_CLK_TRAIL_MIN_1)				7
set mipi_param(DER_TX_CLK_TRAIL_MAX_1)				12
set mipi_param(DER_TX_CLK_TRAIL_MID_1)				9
set mipi_param(DER_TX_CLK_ZERO_MIN_1)				22
set mipi_param(DER_TX_CLK_ZERO_MAX_1)				44
set mipi_param(DER_TX_CLK_ZERO_MID_1)				33
set mipi_param(DER_TX_CLK_POST_MIN_1)				7
set mipi_param(DER_TX_CLK_POST_MAX_1)				14
set mipi_param(DER_TX_CLK_POST_MID_1)				10
set mipi_param(DER_TX_CLK_PRE_MIN_1)				2
set mipi_param(DER_TX_CLK_PRE_MAX_1)				4
set mipi_param(DER_TX_CLK_PRE_MID_1)				3
set mipi_param(DER_TX_HS_PREPARE_MIN_1)				3
set mipi_param(DER_TX_HS_PREPARE_MAX_1)				6
set mipi_param(DER_TX_HS_PREPARE_MID_1)				4
set mipi_param(DER_TX_HS_ZERO_MIN_1)				6
set mipi_param(DER_TX_HS_ZERO_MAX_1)				12
set mipi_param(DER_TX_HS_ZERO_MID_1)				9
set mipi_param(DER_TX_HS_TRAIL_MIN_1)				9
set mipi_param(DER_TX_HS_TRAIL_MAX_1)				13
set mipi_param(DER_TX_HS_TRAIL_MID_1)				10
set mipi_param(DER_TX_INIT_MIN_1)				10
set mipi_param(DER_TX_INIT_MAX_1)				20
set mipi_param(DER_TX_INIT_MID_1)				15
set mipi_param(DER_TX_WAKE_MIN_1)				98
set mipi_param(DER_TX_WAKE_MAX_1)				196
set mipi_param(DER_TX_WAKE_MID_1)				147
set mipi_param(GUI_TX_AUTO_TYPE_1)				2
set mipi_param(GUI_TX_CAP_EQ_MODE_1)				0
set mipi_param(GUI_TX_CLK_LANE_PS_1)				32
set mipi_param(GUI_TX_HS_TM_DESKEW_P_1)				0
set mipi_param(GUI_TX_LPX_1)				7
set mipi_param(GUI_TX_HS_EXIT_1)				15
set mipi_param(GUI_TX_LP_EXIT_1)				15
set mipi_param(GUI_TX_CLK_PREPARE_1)				4
set mipi_param(GUI_TX_CLK_TRAIL_1)				9
set mipi_param(GUI_TX_CLK_ZERO_1)				33
set mipi_param(GUI_TX_CLK_POST_1)				10
set mipi_param(GUI_TX_CLK_PRE_1)				3
set mipi_param(GUI_TX_HS_PREPARE_1)				4
set mipi_param(GUI_TX_HS_ZERO_1)				9
set mipi_param(GUI_TX_HS_TRAIL_1)				10
set mipi_param(GUI_TX_INIT_1)				15
set mipi_param(GUI_TX_WAKE_1)				147
set mipi_param(DER_TX_LPX_NS_1)				70.0
set mipi_param(DER_TX_HS_EXIT_NS_1)				150.0
set mipi_param(DER_TX_LP_EXIT_NS_1)				150.0
set mipi_param(DER_TX_CLK_PREPARE_NS_1)				60.0
set mipi_param(DER_TX_CLK_TRAIL_NS_1)				80.0
set mipi_param(DER_TX_CLK_ZERO_NS_1)				380.0
set mipi_param(DER_TX_CLK_POST_NS_1)				150.0
set mipi_param(DER_TX_CLK_PRE_NS_1)				20.0
set mipi_param(DER_TX_HS_PREPARE_NS_1)				60.0
set mipi_param(DER_TX_HS_ZERO_NS_1)				160.0
set mipi_param(DER_TX_HS_TRAIL_NS_1)				80.0
set mipi_param(DER_TX_INIT_NS_1)				153600.0
set mipi_param(DER_TX_WAKE_NS_1)				1505280.0
set mipi_param(GUI_DPHY_IP_ROLE_2)				2
set mipi_param(DER_LINK_USED_2)				false
set mipi_param(GUI_SKEW_CAL_EN_2)				false
set mipi_param(GUI_SOURCE_PLL_2)				0
set mipi_param(GUI_TM_EN_2)				false
set mipi_param(GUI_TX_VCO_FREQ_MULT_2)				1
set mipi_param(GUI_BIT_RATE_MBPS_RNG_2)				1600.0
set mipi_param(DER_VCO_FREQ_MHZ_LINK_2)				800.0
set mipi_param(GUI_RX_BIT_RATE_MBPS_SEL_2)				64
set mipi_param(GUI_PPI_WIDTH_USR_2)				16
set mipi_param(DER_BIT_RATE_MBPS_2)				1600.0
set mipi_param(DER_PPI_WIDTH_2)				16
set mipi_param(GUI_ALT_CAL_EN_2)				false
set mipi_param(GUI_PER_SKEW_CAL_EN_2)				false
set mipi_param(GUI_PREAMBLE_EN_2)				false
set mipi_param(GUI_TX_PREAMBLE_LEN_PREAMLBE_LEN_2)				0
set mipi_param(GUI_TX_TM_CONTROL_TX_TM_EN_2)				false
set mipi_param(GUI_RX_TM_CONTROL_RX_TM_EN_2)				false
set mipi_param(GUI_TM_LOOPBACK_MODE_2)				false
set mipi_param(GUI_TX_TM_CONTROL_TX_TM_LOOPBACK_MODE_2)				false
set mipi_param(GUI_RX_TM_CONTROL_RX_TM_LOOPBACK_MODE_2)				false
set mipi_param(GUI_NUM_LANES_2)				1
set mipi_param(GUI_BYTE_LOC_2)				2
set mipi_param(GUI_CONTINUOUS_CLK_2)				false
set mipi_param(GUI_PRBS_INIT_0_2)				255
set mipi_param(GUI_PRBS_INIT_1_2)				255
set mipi_param(GUI_PRBS_INIT_2_2)				255
set mipi_param(GUI_PRBS_INIT_3_2)				255
set mipi_param(GUI_PRBS_INIT_4_2)				255
set mipi_param(GUI_PRBS_INIT_5_2)				255
set mipi_param(GUI_PRBS_INIT_6_2)				255
set mipi_param(GUI_PRBS_INIT_7_2)				255
set mipi_param(DER_PPI_WIDTH_16_2)				true
set mipi_param(DER_FR_CLK_FREQ_MHZ_2)				100.0
set mipi_param(DER_BIT_RATE_2)				1600000000
set mipi_param(DER_UI_2)				0.625
set mipi_param(DER_LINK_PLL_SRC_2)				false
set mipi_param(GUI_RX_TIMING_RW_2)				1
set mipi_param(DER_DPHY_RX_EN_2)				false
set mipi_param(DER_RXFIFO_LAT_2)				2
set mipi_param(DER_RX_FR_CLK_FREQ_2)				100000000
set mipi_param(DER_RX_CORE_FREQ_2)				100000000
set mipi_param(DER_RX_FR_CLK_PER_2)				10.0
set mipi_param(DER_RX_CORE_PER_2)				10.0
set mipi_param(DER_RX_FR_CLK_PER_PS_2)				10000
set mipi_param(DER_RX_CORE_PER_PS_2)				10000
set mipi_param(DER_RX_FR_CLK_PER_1K_2)				10240.0
set mipi_param(DER_RX_CORE_PER_1K_2)				10240.0
set mipi_param(DER_RX_FR_CLK_PER_1K_PS_2)				10240000
set mipi_param(DER_RX_CORE_PER_1K_PS_2)				10240000
set mipi_param(DER_RX_PPI_WIDTH_INT_C2P_2)				16
set mipi_param(DER_RX_PPI_WIDTH_16_C2P_2)				true
set mipi_param(DER_RX_TIMING_REG_RW_2)				true
set mipi_param(DER_RX_CLK_LOSS_DETECT_MIN_2)				2
set mipi_param(DER_RX_CLK_LOSS_DETECT_MAX_2)				4
set mipi_param(DER_RX_CLK_LOSS_DETECT_MID_2)				3
set mipi_param(DER_RX_CLK_SETTLE_MIN_2)				2
set mipi_param(DER_RX_CLK_SETTLE_MAX_2)				22
set mipi_param(DER_RX_CLK_SETTLE_MID_2)				12
set mipi_param(DER_RX_HS_SETTLE_MIN_2)				2
set mipi_param(DER_RX_HS_SETTLE_MAX_2)				8
set mipi_param(DER_RX_HS_SETTLE_MID_2)				5
set mipi_param(DER_RX_INIT_MIN_2)				10
set mipi_param(DER_RX_INIT_MAX_2)				20
set mipi_param(DER_RX_INIT_MID_2)				15
set mipi_param(GUI_RX_AUTO_TYPE_2)				2
set mipi_param(GUI_RX_PREP_TIME_TM_2)				0
set mipi_param(GUI_RX_CLK_LOSS_DETECT_2)				3
set mipi_param(GUI_RX_CLK_SETTLE_2)				12
set mipi_param(GUI_RX_HS_SETTLE_2)				5
set mipi_param(GUI_RX_INIT_2)				15
set mipi_param(GUI_RX_CLK_POST_2)				1
set mipi_param(GUI_RX_DLANE_DESKEW_DELAY_0_2)				0
set mipi_param(GUI_RX_DLANE_DESKEW_DELAY_1_2)				0
set mipi_param(GUI_RX_DLANE_DESKEW_DELAY_2_2)				0
set mipi_param(GUI_RX_DLANE_DESKEW_DELAY_3_2)				0
set mipi_param(GUI_RX_DLANE_DESKEW_DELAY_4_2)				0
set mipi_param(GUI_RX_DLANE_DESKEW_DELAY_5_2)				0
set mipi_param(GUI_RX_DLANE_DESKEW_DELAY_6_2)				0
set mipi_param(GUI_RX_DLANE_DESKEW_DELAY_7_2)				0
set mipi_param(DER_RX_CLK_LOSS_DETECT_NS_2)				90.0
set mipi_param(DER_RX_CLK_SETTLE_NS_2)				200.0
set mipi_param(DER_RX_HS_SETTLE_NS_2)				120.0
set mipi_param(DER_RX_INIT_NS_2)				153600.0
set mipi_param(GUI_RX_CAP_EQ_MODE_2)				0
set mipi_param(GUI_TX_TIMING_RW_2)				1
set mipi_param(DER_DPHY_TX_EN_2)				false
set mipi_param(DER_TXFIFO_LAT_2)				3
set mipi_param(DER_TX_CORE_FREQ_2)				100000000
set mipi_param(DER_TX_CORE_PER_2)				10.0
set mipi_param(DER_TX_CORE_PER_PS_2)				10000
set mipi_param(DER_TX_CORE_PER_1K_2)				10240.0
set mipi_param(DER_TX_CORE_PER_1K_PS_2)				10240000
set mipi_param(DER_TX_TIMING_REG_RW_2)				true
set mipi_param(DER_TX_LPX_MIN_2)				5
set mipi_param(DER_TX_LPX_MAX_2)				10
set mipi_param(DER_TX_LPX_MID_2)				7
set mipi_param(DER_TX_HS_EXIT_MIN_2)				10
set mipi_param(DER_TX_HS_EXIT_MAX_2)				20
set mipi_param(DER_TX_HS_EXIT_MID_2)				15
set mipi_param(DER_TX_LP_EXIT_MIN_2)				10
set mipi_param(DER_TX_LP_EXIT_MAX_2)				20
set mipi_param(DER_TX_LP_EXIT_MID_2)				15
set mipi_param(DER_TX_CLK_PREPARE_MIN_2)				2
set mipi_param(DER_TX_CLK_PREPARE_MAX_2)				7
set mipi_param(DER_TX_CLK_PREPARE_MID_2)				4
set mipi_param(DER_TX_CLK_TRAIL_MIN_2)				7
set mipi_param(DER_TX_CLK_TRAIL_MAX_2)				12
set mipi_param(DER_TX_CLK_TRAIL_MID_2)				9
set mipi_param(DER_TX_CLK_ZERO_MIN_2)				22
set mipi_param(DER_TX_CLK_ZERO_MAX_2)				44
set mipi_param(DER_TX_CLK_ZERO_MID_2)				33
set mipi_param(DER_TX_CLK_POST_MIN_2)				7
set mipi_param(DER_TX_CLK_POST_MAX_2)				14
set mipi_param(DER_TX_CLK_POST_MID_2)				10
set mipi_param(DER_TX_CLK_PRE_MIN_2)				2
set mipi_param(DER_TX_CLK_PRE_MAX_2)				4
set mipi_param(DER_TX_CLK_PRE_MID_2)				3
set mipi_param(DER_TX_HS_PREPARE_MIN_2)				3
set mipi_param(DER_TX_HS_PREPARE_MAX_2)				6
set mipi_param(DER_TX_HS_PREPARE_MID_2)				4
set mipi_param(DER_TX_HS_ZERO_MIN_2)				6
set mipi_param(DER_TX_HS_ZERO_MAX_2)				12
set mipi_param(DER_TX_HS_ZERO_MID_2)				9
set mipi_param(DER_TX_HS_TRAIL_MIN_2)				9
set mipi_param(DER_TX_HS_TRAIL_MAX_2)				13
set mipi_param(DER_TX_HS_TRAIL_MID_2)				10
set mipi_param(DER_TX_INIT_MIN_2)				10
set mipi_param(DER_TX_INIT_MAX_2)				20
set mipi_param(DER_TX_INIT_MID_2)				15
set mipi_param(DER_TX_WAKE_MIN_2)				98
set mipi_param(DER_TX_WAKE_MAX_2)				196
set mipi_param(DER_TX_WAKE_MID_2)				147
set mipi_param(GUI_TX_AUTO_TYPE_2)				2
set mipi_param(GUI_TX_CAP_EQ_MODE_2)				0
set mipi_param(GUI_TX_CLK_LANE_PS_2)				32
set mipi_param(GUI_TX_HS_TM_DESKEW_P_2)				0
set mipi_param(GUI_TX_LPX_2)				7
set mipi_param(GUI_TX_HS_EXIT_2)				15
set mipi_param(GUI_TX_LP_EXIT_2)				15
set mipi_param(GUI_TX_CLK_PREPARE_2)				4
set mipi_param(GUI_TX_CLK_TRAIL_2)				9
set mipi_param(GUI_TX_CLK_ZERO_2)				33
set mipi_param(GUI_TX_CLK_POST_2)				10
set mipi_param(GUI_TX_CLK_PRE_2)				3
set mipi_param(GUI_TX_HS_PREPARE_2)				4
set mipi_param(GUI_TX_HS_ZERO_2)				9
set mipi_param(GUI_TX_HS_TRAIL_2)				10
set mipi_param(GUI_TX_INIT_2)				15
set mipi_param(GUI_TX_WAKE_2)				147
set mipi_param(DER_TX_LPX_NS_2)				70.0
set mipi_param(DER_TX_HS_EXIT_NS_2)				150.0
set mipi_param(DER_TX_LP_EXIT_NS_2)				150.0
set mipi_param(DER_TX_CLK_PREPARE_NS_2)				60.0
set mipi_param(DER_TX_CLK_TRAIL_NS_2)				80.0
set mipi_param(DER_TX_CLK_ZERO_NS_2)				380.0
set mipi_param(DER_TX_CLK_POST_NS_2)				150.0
set mipi_param(DER_TX_CLK_PRE_NS_2)				20.0
set mipi_param(DER_TX_HS_PREPARE_NS_2)				60.0
set mipi_param(DER_TX_HS_ZERO_NS_2)				160.0
set mipi_param(DER_TX_HS_TRAIL_NS_2)				80.0
set mipi_param(DER_TX_INIT_NS_2)				153600.0
set mipi_param(DER_TX_WAKE_NS_2)				1505280.0
set mipi_param(GUI_DPHY_IP_ROLE_3)				2
set mipi_param(DER_LINK_USED_3)				false
set mipi_param(GUI_SKEW_CAL_EN_3)				false
set mipi_param(GUI_SOURCE_PLL_3)				0
set mipi_param(GUI_TM_EN_3)				false
set mipi_param(GUI_TX_VCO_FREQ_MULT_3)				1
set mipi_param(GUI_BIT_RATE_MBPS_RNG_3)				1600.0
set mipi_param(DER_VCO_FREQ_MHZ_LINK_3)				800.0
set mipi_param(GUI_RX_BIT_RATE_MBPS_SEL_3)				64
set mipi_param(GUI_PPI_WIDTH_USR_3)				16
set mipi_param(DER_BIT_RATE_MBPS_3)				1600.0
set mipi_param(DER_PPI_WIDTH_3)				16
set mipi_param(GUI_ALT_CAL_EN_3)				false
set mipi_param(GUI_PER_SKEW_CAL_EN_3)				false
set mipi_param(GUI_PREAMBLE_EN_3)				false
set mipi_param(GUI_TX_PREAMBLE_LEN_PREAMLBE_LEN_3)				0
set mipi_param(GUI_TX_TM_CONTROL_TX_TM_EN_3)				false
set mipi_param(GUI_RX_TM_CONTROL_RX_TM_EN_3)				false
set mipi_param(GUI_TM_LOOPBACK_MODE_3)				false
set mipi_param(GUI_TX_TM_CONTROL_TX_TM_LOOPBACK_MODE_3)				false
set mipi_param(GUI_RX_TM_CONTROL_RX_TM_LOOPBACK_MODE_3)				false
set mipi_param(GUI_NUM_LANES_3)				1
set mipi_param(GUI_BYTE_LOC_3)				3
set mipi_param(GUI_CONTINUOUS_CLK_3)				false
set mipi_param(GUI_PRBS_INIT_0_3)				255
set mipi_param(GUI_PRBS_INIT_1_3)				255
set mipi_param(GUI_PRBS_INIT_2_3)				255
set mipi_param(GUI_PRBS_INIT_3_3)				255
set mipi_param(GUI_PRBS_INIT_4_3)				255
set mipi_param(GUI_PRBS_INIT_5_3)				255
set mipi_param(GUI_PRBS_INIT_6_3)				255
set mipi_param(GUI_PRBS_INIT_7_3)				255
set mipi_param(DER_PPI_WIDTH_16_3)				true
set mipi_param(DER_FR_CLK_FREQ_MHZ_3)				100.0
set mipi_param(DER_BIT_RATE_3)				1600000000
set mipi_param(DER_UI_3)				0.625
set mipi_param(DER_LINK_PLL_SRC_3)				false
set mipi_param(GUI_RX_TIMING_RW_3)				1
set mipi_param(DER_DPHY_RX_EN_3)				false
set mipi_param(DER_RXFIFO_LAT_3)				2
set mipi_param(DER_RX_FR_CLK_FREQ_3)				100000000
set mipi_param(DER_RX_CORE_FREQ_3)				100000000
set mipi_param(DER_RX_FR_CLK_PER_3)				10.0
set mipi_param(DER_RX_CORE_PER_3)				10.0
set mipi_param(DER_RX_FR_CLK_PER_PS_3)				10000
set mipi_param(DER_RX_CORE_PER_PS_3)				10000
set mipi_param(DER_RX_FR_CLK_PER_1K_3)				10240.0
set mipi_param(DER_RX_CORE_PER_1K_3)				10240.0
set mipi_param(DER_RX_FR_CLK_PER_1K_PS_3)				10240000
set mipi_param(DER_RX_CORE_PER_1K_PS_3)				10240000
set mipi_param(DER_RX_PPI_WIDTH_INT_C2P_3)				16
set mipi_param(DER_RX_PPI_WIDTH_16_C2P_3)				true
set mipi_param(DER_RX_TIMING_REG_RW_3)				true
set mipi_param(DER_RX_CLK_LOSS_DETECT_MIN_3)				2
set mipi_param(DER_RX_CLK_LOSS_DETECT_MAX_3)				4
set mipi_param(DER_RX_CLK_LOSS_DETECT_MID_3)				3
set mipi_param(DER_RX_CLK_SETTLE_MIN_3)				2
set mipi_param(DER_RX_CLK_SETTLE_MAX_3)				22
set mipi_param(DER_RX_CLK_SETTLE_MID_3)				12
set mipi_param(DER_RX_HS_SETTLE_MIN_3)				2
set mipi_param(DER_RX_HS_SETTLE_MAX_3)				8
set mipi_param(DER_RX_HS_SETTLE_MID_3)				5
set mipi_param(DER_RX_INIT_MIN_3)				10
set mipi_param(DER_RX_INIT_MAX_3)				20
set mipi_param(DER_RX_INIT_MID_3)				15
set mipi_param(GUI_RX_AUTO_TYPE_3)				2
set mipi_param(GUI_RX_PREP_TIME_TM_3)				0
set mipi_param(GUI_RX_CLK_LOSS_DETECT_3)				3
set mipi_param(GUI_RX_CLK_SETTLE_3)				12
set mipi_param(GUI_RX_HS_SETTLE_3)				5
set mipi_param(GUI_RX_INIT_3)				15
set mipi_param(GUI_RX_CLK_POST_3)				1
set mipi_param(GUI_RX_DLANE_DESKEW_DELAY_0_3)				0
set mipi_param(GUI_RX_DLANE_DESKEW_DELAY_1_3)				0
set mipi_param(GUI_RX_DLANE_DESKEW_DELAY_2_3)				0
set mipi_param(GUI_RX_DLANE_DESKEW_DELAY_3_3)				0
set mipi_param(GUI_RX_DLANE_DESKEW_DELAY_4_3)				0
set mipi_param(GUI_RX_DLANE_DESKEW_DELAY_5_3)				0
set mipi_param(GUI_RX_DLANE_DESKEW_DELAY_6_3)				0
set mipi_param(GUI_RX_DLANE_DESKEW_DELAY_7_3)				0
set mipi_param(DER_RX_CLK_LOSS_DETECT_NS_3)				90.0
set mipi_param(DER_RX_CLK_SETTLE_NS_3)				200.0
set mipi_param(DER_RX_HS_SETTLE_NS_3)				120.0
set mipi_param(DER_RX_INIT_NS_3)				153600.0
set mipi_param(GUI_RX_CAP_EQ_MODE_3)				0
set mipi_param(GUI_TX_TIMING_RW_3)				1
set mipi_param(DER_DPHY_TX_EN_3)				false
set mipi_param(DER_TXFIFO_LAT_3)				3
set mipi_param(DER_TX_CORE_FREQ_3)				100000000
set mipi_param(DER_TX_CORE_PER_3)				10.0
set mipi_param(DER_TX_CORE_PER_PS_3)				10000
set mipi_param(DER_TX_CORE_PER_1K_3)				10240.0
set mipi_param(DER_TX_CORE_PER_1K_PS_3)				10240000
set mipi_param(DER_TX_TIMING_REG_RW_3)				true
set mipi_param(DER_TX_LPX_MIN_3)				5
set mipi_param(DER_TX_LPX_MAX_3)				10
set mipi_param(DER_TX_LPX_MID_3)				7
set mipi_param(DER_TX_HS_EXIT_MIN_3)				10
set mipi_param(DER_TX_HS_EXIT_MAX_3)				20
set mipi_param(DER_TX_HS_EXIT_MID_3)				15
set mipi_param(DER_TX_LP_EXIT_MIN_3)				10
set mipi_param(DER_TX_LP_EXIT_MAX_3)				20
set mipi_param(DER_TX_LP_EXIT_MID_3)				15
set mipi_param(DER_TX_CLK_PREPARE_MIN_3)				2
set mipi_param(DER_TX_CLK_PREPARE_MAX_3)				7
set mipi_param(DER_TX_CLK_PREPARE_MID_3)				4
set mipi_param(DER_TX_CLK_TRAIL_MIN_3)				7
set mipi_param(DER_TX_CLK_TRAIL_MAX_3)				12
set mipi_param(DER_TX_CLK_TRAIL_MID_3)				9
set mipi_param(DER_TX_CLK_ZERO_MIN_3)				22
set mipi_param(DER_TX_CLK_ZERO_MAX_3)				44
set mipi_param(DER_TX_CLK_ZERO_MID_3)				33
set mipi_param(DER_TX_CLK_POST_MIN_3)				7
set mipi_param(DER_TX_CLK_POST_MAX_3)				14
set mipi_param(DER_TX_CLK_POST_MID_3)				10
set mipi_param(DER_TX_CLK_PRE_MIN_3)				2
set mipi_param(DER_TX_CLK_PRE_MAX_3)				4
set mipi_param(DER_TX_CLK_PRE_MID_3)				3
set mipi_param(DER_TX_HS_PREPARE_MIN_3)				3
set mipi_param(DER_TX_HS_PREPARE_MAX_3)				6
set mipi_param(DER_TX_HS_PREPARE_MID_3)				4
set mipi_param(DER_TX_HS_ZERO_MIN_3)				6
set mipi_param(DER_TX_HS_ZERO_MAX_3)				12
set mipi_param(DER_TX_HS_ZERO_MID_3)				9
set mipi_param(DER_TX_HS_TRAIL_MIN_3)				9
set mipi_param(DER_TX_HS_TRAIL_MAX_3)				13
set mipi_param(DER_TX_HS_TRAIL_MID_3)				10
set mipi_param(DER_TX_INIT_MIN_3)				10
set mipi_param(DER_TX_INIT_MAX_3)				20
set mipi_param(DER_TX_INIT_MID_3)				15
set mipi_param(DER_TX_WAKE_MIN_3)				98
set mipi_param(DER_TX_WAKE_MAX_3)				196
set mipi_param(DER_TX_WAKE_MID_3)				147
set mipi_param(GUI_TX_AUTO_TYPE_3)				2
set mipi_param(GUI_TX_CAP_EQ_MODE_3)				0
set mipi_param(GUI_TX_CLK_LANE_PS_3)				32
set mipi_param(GUI_TX_HS_TM_DESKEW_P_3)				0
set mipi_param(GUI_TX_LPX_3)				7
set mipi_param(GUI_TX_HS_EXIT_3)				15
set mipi_param(GUI_TX_LP_EXIT_3)				15
set mipi_param(GUI_TX_CLK_PREPARE_3)				4
set mipi_param(GUI_TX_CLK_TRAIL_3)				9
set mipi_param(GUI_TX_CLK_ZERO_3)				33
set mipi_param(GUI_TX_CLK_POST_3)				10
set mipi_param(GUI_TX_CLK_PRE_3)				3
set mipi_param(GUI_TX_HS_PREPARE_3)				4
set mipi_param(GUI_TX_HS_ZERO_3)				9
set mipi_param(GUI_TX_HS_TRAIL_3)				10
set mipi_param(GUI_TX_INIT_3)				15
set mipi_param(GUI_TX_WAKE_3)				147
set mipi_param(DER_TX_LPX_NS_3)				70.0
set mipi_param(DER_TX_HS_EXIT_NS_3)				150.0
set mipi_param(DER_TX_LP_EXIT_NS_3)				150.0
set mipi_param(DER_TX_CLK_PREPARE_NS_3)				60.0
set mipi_param(DER_TX_CLK_TRAIL_NS_3)				80.0
set mipi_param(DER_TX_CLK_ZERO_NS_3)				380.0
set mipi_param(DER_TX_CLK_POST_NS_3)				150.0
set mipi_param(DER_TX_CLK_PRE_NS_3)				20.0
set mipi_param(DER_TX_HS_PREPARE_NS_3)				60.0
set mipi_param(DER_TX_HS_ZERO_NS_3)				160.0
set mipi_param(DER_TX_HS_TRAIL_NS_3)				80.0
set mipi_param(DER_TX_INIT_NS_3)				153600.0
set mipi_param(DER_TX_WAKE_NS_3)				1505280.0
set mipi_param(GUI_DPHY_IP_ROLE_4)				2
set mipi_param(DER_LINK_USED_4)				false
set mipi_param(GUI_SKEW_CAL_EN_4)				false
set mipi_param(GUI_SOURCE_PLL_4)				0
set mipi_param(GUI_TM_EN_4)				false
set mipi_param(GUI_TX_VCO_FREQ_MULT_4)				1
set mipi_param(GUI_BIT_RATE_MBPS_RNG_4)				1600.0
set mipi_param(DER_VCO_FREQ_MHZ_LINK_4)				800.0
set mipi_param(GUI_RX_BIT_RATE_MBPS_SEL_4)				64
set mipi_param(GUI_PPI_WIDTH_USR_4)				16
set mipi_param(DER_BIT_RATE_MBPS_4)				1600.0
set mipi_param(DER_PPI_WIDTH_4)				16
set mipi_param(GUI_ALT_CAL_EN_4)				false
set mipi_param(GUI_PER_SKEW_CAL_EN_4)				false
set mipi_param(GUI_PREAMBLE_EN_4)				false
set mipi_param(GUI_TX_PREAMBLE_LEN_PREAMLBE_LEN_4)				0
set mipi_param(GUI_TX_TM_CONTROL_TX_TM_EN_4)				false
set mipi_param(GUI_RX_TM_CONTROL_RX_TM_EN_4)				false
set mipi_param(GUI_TM_LOOPBACK_MODE_4)				false
set mipi_param(GUI_TX_TM_CONTROL_TX_TM_LOOPBACK_MODE_4)				false
set mipi_param(GUI_RX_TM_CONTROL_RX_TM_LOOPBACK_MODE_4)				false
set mipi_param(GUI_NUM_LANES_4)				1
set mipi_param(GUI_BYTE_LOC_4)				4
set mipi_param(GUI_CONTINUOUS_CLK_4)				false
set mipi_param(GUI_PRBS_INIT_0_4)				255
set mipi_param(GUI_PRBS_INIT_1_4)				255
set mipi_param(GUI_PRBS_INIT_2_4)				255
set mipi_param(GUI_PRBS_INIT_3_4)				255
set mipi_param(GUI_PRBS_INIT_4_4)				255
set mipi_param(GUI_PRBS_INIT_5_4)				255
set mipi_param(GUI_PRBS_INIT_6_4)				255
set mipi_param(GUI_PRBS_INIT_7_4)				255
set mipi_param(DER_PPI_WIDTH_16_4)				true
set mipi_param(DER_FR_CLK_FREQ_MHZ_4)				100.0
set mipi_param(DER_BIT_RATE_4)				1600000000
set mipi_param(DER_UI_4)				0.625
set mipi_param(DER_LINK_PLL_SRC_4)				false
set mipi_param(GUI_RX_TIMING_RW_4)				1
set mipi_param(DER_DPHY_RX_EN_4)				false
set mipi_param(DER_RXFIFO_LAT_4)				2
set mipi_param(DER_RX_FR_CLK_FREQ_4)				100000000
set mipi_param(DER_RX_CORE_FREQ_4)				100000000
set mipi_param(DER_RX_FR_CLK_PER_4)				10.0
set mipi_param(DER_RX_CORE_PER_4)				10.0
set mipi_param(DER_RX_FR_CLK_PER_PS_4)				10000
set mipi_param(DER_RX_CORE_PER_PS_4)				10000
set mipi_param(DER_RX_FR_CLK_PER_1K_4)				10240.0
set mipi_param(DER_RX_CORE_PER_1K_4)				10240.0
set mipi_param(DER_RX_FR_CLK_PER_1K_PS_4)				10240000
set mipi_param(DER_RX_CORE_PER_1K_PS_4)				10240000
set mipi_param(DER_RX_PPI_WIDTH_INT_C2P_4)				16
set mipi_param(DER_RX_PPI_WIDTH_16_C2P_4)				true
set mipi_param(DER_RX_TIMING_REG_RW_4)				true
set mipi_param(DER_RX_CLK_LOSS_DETECT_MIN_4)				2
set mipi_param(DER_RX_CLK_LOSS_DETECT_MAX_4)				4
set mipi_param(DER_RX_CLK_LOSS_DETECT_MID_4)				3
set mipi_param(DER_RX_CLK_SETTLE_MIN_4)				2
set mipi_param(DER_RX_CLK_SETTLE_MAX_4)				22
set mipi_param(DER_RX_CLK_SETTLE_MID_4)				12
set mipi_param(DER_RX_HS_SETTLE_MIN_4)				2
set mipi_param(DER_RX_HS_SETTLE_MAX_4)				8
set mipi_param(DER_RX_HS_SETTLE_MID_4)				5
set mipi_param(DER_RX_INIT_MIN_4)				10
set mipi_param(DER_RX_INIT_MAX_4)				20
set mipi_param(DER_RX_INIT_MID_4)				15
set mipi_param(GUI_RX_AUTO_TYPE_4)				2
set mipi_param(GUI_RX_PREP_TIME_TM_4)				0
set mipi_param(GUI_RX_CLK_LOSS_DETECT_4)				3
set mipi_param(GUI_RX_CLK_SETTLE_4)				12
set mipi_param(GUI_RX_HS_SETTLE_4)				5
set mipi_param(GUI_RX_INIT_4)				15
set mipi_param(GUI_RX_CLK_POST_4)				1
set mipi_param(GUI_RX_DLANE_DESKEW_DELAY_0_4)				0
set mipi_param(GUI_RX_DLANE_DESKEW_DELAY_1_4)				0
set mipi_param(GUI_RX_DLANE_DESKEW_DELAY_2_4)				0
set mipi_param(GUI_RX_DLANE_DESKEW_DELAY_3_4)				0
set mipi_param(GUI_RX_DLANE_DESKEW_DELAY_4_4)				0
set mipi_param(GUI_RX_DLANE_DESKEW_DELAY_5_4)				0
set mipi_param(GUI_RX_DLANE_DESKEW_DELAY_6_4)				0
set mipi_param(GUI_RX_DLANE_DESKEW_DELAY_7_4)				0
set mipi_param(DER_RX_CLK_LOSS_DETECT_NS_4)				90.0
set mipi_param(DER_RX_CLK_SETTLE_NS_4)				200.0
set mipi_param(DER_RX_HS_SETTLE_NS_4)				120.0
set mipi_param(DER_RX_INIT_NS_4)				153600.0
set mipi_param(GUI_RX_CAP_EQ_MODE_4)				0
set mipi_param(GUI_TX_TIMING_RW_4)				1
set mipi_param(DER_DPHY_TX_EN_4)				false
set mipi_param(DER_TXFIFO_LAT_4)				3
set mipi_param(DER_TX_CORE_FREQ_4)				100000000
set mipi_param(DER_TX_CORE_PER_4)				10.0
set mipi_param(DER_TX_CORE_PER_PS_4)				10000
set mipi_param(DER_TX_CORE_PER_1K_4)				10240.0
set mipi_param(DER_TX_CORE_PER_1K_PS_4)				10240000
set mipi_param(DER_TX_TIMING_REG_RW_4)				true
set mipi_param(DER_TX_LPX_MIN_4)				5
set mipi_param(DER_TX_LPX_MAX_4)				10
set mipi_param(DER_TX_LPX_MID_4)				7
set mipi_param(DER_TX_HS_EXIT_MIN_4)				10
set mipi_param(DER_TX_HS_EXIT_MAX_4)				20
set mipi_param(DER_TX_HS_EXIT_MID_4)				15
set mipi_param(DER_TX_LP_EXIT_MIN_4)				10
set mipi_param(DER_TX_LP_EXIT_MAX_4)				20
set mipi_param(DER_TX_LP_EXIT_MID_4)				15
set mipi_param(DER_TX_CLK_PREPARE_MIN_4)				2
set mipi_param(DER_TX_CLK_PREPARE_MAX_4)				7
set mipi_param(DER_TX_CLK_PREPARE_MID_4)				4
set mipi_param(DER_TX_CLK_TRAIL_MIN_4)				7
set mipi_param(DER_TX_CLK_TRAIL_MAX_4)				12
set mipi_param(DER_TX_CLK_TRAIL_MID_4)				9
set mipi_param(DER_TX_CLK_ZERO_MIN_4)				22
set mipi_param(DER_TX_CLK_ZERO_MAX_4)				44
set mipi_param(DER_TX_CLK_ZERO_MID_4)				33
set mipi_param(DER_TX_CLK_POST_MIN_4)				7
set mipi_param(DER_TX_CLK_POST_MAX_4)				14
set mipi_param(DER_TX_CLK_POST_MID_4)				10
set mipi_param(DER_TX_CLK_PRE_MIN_4)				2
set mipi_param(DER_TX_CLK_PRE_MAX_4)				4
set mipi_param(DER_TX_CLK_PRE_MID_4)				3
set mipi_param(DER_TX_HS_PREPARE_MIN_4)				3
set mipi_param(DER_TX_HS_PREPARE_MAX_4)				6
set mipi_param(DER_TX_HS_PREPARE_MID_4)				4
set mipi_param(DER_TX_HS_ZERO_MIN_4)				6
set mipi_param(DER_TX_HS_ZERO_MAX_4)				12
set mipi_param(DER_TX_HS_ZERO_MID_4)				9
set mipi_param(DER_TX_HS_TRAIL_MIN_4)				9
set mipi_param(DER_TX_HS_TRAIL_MAX_4)				13
set mipi_param(DER_TX_HS_TRAIL_MID_4)				10
set mipi_param(DER_TX_INIT_MIN_4)				10
set mipi_param(DER_TX_INIT_MAX_4)				20
set mipi_param(DER_TX_INIT_MID_4)				15
set mipi_param(DER_TX_WAKE_MIN_4)				98
set mipi_param(DER_TX_WAKE_MAX_4)				196
set mipi_param(DER_TX_WAKE_MID_4)				147
set mipi_param(GUI_TX_AUTO_TYPE_4)				2
set mipi_param(GUI_TX_CAP_EQ_MODE_4)				0
set mipi_param(GUI_TX_CLK_LANE_PS_4)				32
set mipi_param(GUI_TX_HS_TM_DESKEW_P_4)				0
set mipi_param(GUI_TX_LPX_4)				7
set mipi_param(GUI_TX_HS_EXIT_4)				15
set mipi_param(GUI_TX_LP_EXIT_4)				15
set mipi_param(GUI_TX_CLK_PREPARE_4)				4
set mipi_param(GUI_TX_CLK_TRAIL_4)				9
set mipi_param(GUI_TX_CLK_ZERO_4)				33
set mipi_param(GUI_TX_CLK_POST_4)				10
set mipi_param(GUI_TX_CLK_PRE_4)				3
set mipi_param(GUI_TX_HS_PREPARE_4)				4
set mipi_param(GUI_TX_HS_ZERO_4)				9
set mipi_param(GUI_TX_HS_TRAIL_4)				10
set mipi_param(GUI_TX_INIT_4)				15
set mipi_param(GUI_TX_WAKE_4)				147
set mipi_param(DER_TX_LPX_NS_4)				70.0
set mipi_param(DER_TX_HS_EXIT_NS_4)				150.0
set mipi_param(DER_TX_LP_EXIT_NS_4)				150.0
set mipi_param(DER_TX_CLK_PREPARE_NS_4)				60.0
set mipi_param(DER_TX_CLK_TRAIL_NS_4)				80.0
set mipi_param(DER_TX_CLK_ZERO_NS_4)				380.0
set mipi_param(DER_TX_CLK_POST_NS_4)				150.0
set mipi_param(DER_TX_CLK_PRE_NS_4)				20.0
set mipi_param(DER_TX_HS_PREPARE_NS_4)				60.0
set mipi_param(DER_TX_HS_ZERO_NS_4)				160.0
set mipi_param(DER_TX_HS_TRAIL_NS_4)				80.0
set mipi_param(DER_TX_INIT_NS_4)				153600.0
set mipi_param(DER_TX_WAKE_NS_4)				1505280.0
set mipi_param(GUI_DPHY_IP_ROLE_5)				2
set mipi_param(DER_LINK_USED_5)				false
set mipi_param(GUI_SKEW_CAL_EN_5)				false
set mipi_param(GUI_SOURCE_PLL_5)				0
set mipi_param(GUI_TM_EN_5)				false
set mipi_param(GUI_TX_VCO_FREQ_MULT_5)				1
set mipi_param(GUI_BIT_RATE_MBPS_RNG_5)				1600.0
set mipi_param(DER_VCO_FREQ_MHZ_LINK_5)				800.0
set mipi_param(GUI_RX_BIT_RATE_MBPS_SEL_5)				64
set mipi_param(GUI_PPI_WIDTH_USR_5)				16
set mipi_param(DER_BIT_RATE_MBPS_5)				1600.0
set mipi_param(DER_PPI_WIDTH_5)				16
set mipi_param(GUI_ALT_CAL_EN_5)				false
set mipi_param(GUI_PER_SKEW_CAL_EN_5)				false
set mipi_param(GUI_PREAMBLE_EN_5)				false
set mipi_param(GUI_TX_PREAMBLE_LEN_PREAMLBE_LEN_5)				0
set mipi_param(GUI_TX_TM_CONTROL_TX_TM_EN_5)				false
set mipi_param(GUI_RX_TM_CONTROL_RX_TM_EN_5)				false
set mipi_param(GUI_TM_LOOPBACK_MODE_5)				false
set mipi_param(GUI_TX_TM_CONTROL_TX_TM_LOOPBACK_MODE_5)				false
set mipi_param(GUI_RX_TM_CONTROL_RX_TM_LOOPBACK_MODE_5)				false
set mipi_param(GUI_NUM_LANES_5)				1
set mipi_param(GUI_BYTE_LOC_5)				5
set mipi_param(GUI_CONTINUOUS_CLK_5)				false
set mipi_param(GUI_PRBS_INIT_0_5)				255
set mipi_param(GUI_PRBS_INIT_1_5)				255
set mipi_param(GUI_PRBS_INIT_2_5)				255
set mipi_param(GUI_PRBS_INIT_3_5)				255
set mipi_param(GUI_PRBS_INIT_4_5)				255
set mipi_param(GUI_PRBS_INIT_5_5)				255
set mipi_param(GUI_PRBS_INIT_6_5)				255
set mipi_param(GUI_PRBS_INIT_7_5)				255
set mipi_param(DER_PPI_WIDTH_16_5)				true
set mipi_param(DER_FR_CLK_FREQ_MHZ_5)				100.0
set mipi_param(DER_BIT_RATE_5)				1600000000
set mipi_param(DER_UI_5)				0.625
set mipi_param(DER_LINK_PLL_SRC_5)				false
set mipi_param(GUI_RX_TIMING_RW_5)				1
set mipi_param(DER_DPHY_RX_EN_5)				false
set mipi_param(DER_RXFIFO_LAT_5)				2
set mipi_param(DER_RX_FR_CLK_FREQ_5)				100000000
set mipi_param(DER_RX_CORE_FREQ_5)				100000000
set mipi_param(DER_RX_FR_CLK_PER_5)				10.0
set mipi_param(DER_RX_CORE_PER_5)				10.0
set mipi_param(DER_RX_FR_CLK_PER_PS_5)				10000
set mipi_param(DER_RX_CORE_PER_PS_5)				10000
set mipi_param(DER_RX_FR_CLK_PER_1K_5)				10240.0
set mipi_param(DER_RX_CORE_PER_1K_5)				10240.0
set mipi_param(DER_RX_FR_CLK_PER_1K_PS_5)				10240000
set mipi_param(DER_RX_CORE_PER_1K_PS_5)				10240000
set mipi_param(DER_RX_PPI_WIDTH_INT_C2P_5)				16
set mipi_param(DER_RX_PPI_WIDTH_16_C2P_5)				true
set mipi_param(DER_RX_TIMING_REG_RW_5)				true
set mipi_param(DER_RX_CLK_LOSS_DETECT_MIN_5)				2
set mipi_param(DER_RX_CLK_LOSS_DETECT_MAX_5)				4
set mipi_param(DER_RX_CLK_LOSS_DETECT_MID_5)				3
set mipi_param(DER_RX_CLK_SETTLE_MIN_5)				2
set mipi_param(DER_RX_CLK_SETTLE_MAX_5)				22
set mipi_param(DER_RX_CLK_SETTLE_MID_5)				12
set mipi_param(DER_RX_HS_SETTLE_MIN_5)				2
set mipi_param(DER_RX_HS_SETTLE_MAX_5)				8
set mipi_param(DER_RX_HS_SETTLE_MID_5)				5
set mipi_param(DER_RX_INIT_MIN_5)				10
set mipi_param(DER_RX_INIT_MAX_5)				20
set mipi_param(DER_RX_INIT_MID_5)				15
set mipi_param(GUI_RX_AUTO_TYPE_5)				2
set mipi_param(GUI_RX_PREP_TIME_TM_5)				0
set mipi_param(GUI_RX_CLK_LOSS_DETECT_5)				3
set mipi_param(GUI_RX_CLK_SETTLE_5)				12
set mipi_param(GUI_RX_HS_SETTLE_5)				5
set mipi_param(GUI_RX_INIT_5)				15
set mipi_param(GUI_RX_CLK_POST_5)				1
set mipi_param(GUI_RX_DLANE_DESKEW_DELAY_0_5)				0
set mipi_param(GUI_RX_DLANE_DESKEW_DELAY_1_5)				0
set mipi_param(GUI_RX_DLANE_DESKEW_DELAY_2_5)				0
set mipi_param(GUI_RX_DLANE_DESKEW_DELAY_3_5)				0
set mipi_param(GUI_RX_DLANE_DESKEW_DELAY_4_5)				0
set mipi_param(GUI_RX_DLANE_DESKEW_DELAY_5_5)				0
set mipi_param(GUI_RX_DLANE_DESKEW_DELAY_6_5)				0
set mipi_param(GUI_RX_DLANE_DESKEW_DELAY_7_5)				0
set mipi_param(DER_RX_CLK_LOSS_DETECT_NS_5)				90.0
set mipi_param(DER_RX_CLK_SETTLE_NS_5)				200.0
set mipi_param(DER_RX_HS_SETTLE_NS_5)				120.0
set mipi_param(DER_RX_INIT_NS_5)				153600.0
set mipi_param(GUI_RX_CAP_EQ_MODE_5)				0
set mipi_param(GUI_TX_TIMING_RW_5)				1
set mipi_param(DER_DPHY_TX_EN_5)				false
set mipi_param(DER_TXFIFO_LAT_5)				3
set mipi_param(DER_TX_CORE_FREQ_5)				100000000
set mipi_param(DER_TX_CORE_PER_5)				10.0
set mipi_param(DER_TX_CORE_PER_PS_5)				10000
set mipi_param(DER_TX_CORE_PER_1K_5)				10240.0
set mipi_param(DER_TX_CORE_PER_1K_PS_5)				10240000
set mipi_param(DER_TX_TIMING_REG_RW_5)				true
set mipi_param(DER_TX_LPX_MIN_5)				5
set mipi_param(DER_TX_LPX_MAX_5)				10
set mipi_param(DER_TX_LPX_MID_5)				7
set mipi_param(DER_TX_HS_EXIT_MIN_5)				10
set mipi_param(DER_TX_HS_EXIT_MAX_5)				20
set mipi_param(DER_TX_HS_EXIT_MID_5)				15
set mipi_param(DER_TX_LP_EXIT_MIN_5)				10
set mipi_param(DER_TX_LP_EXIT_MAX_5)				20
set mipi_param(DER_TX_LP_EXIT_MID_5)				15
set mipi_param(DER_TX_CLK_PREPARE_MIN_5)				2
set mipi_param(DER_TX_CLK_PREPARE_MAX_5)				7
set mipi_param(DER_TX_CLK_PREPARE_MID_5)				4
set mipi_param(DER_TX_CLK_TRAIL_MIN_5)				7
set mipi_param(DER_TX_CLK_TRAIL_MAX_5)				12
set mipi_param(DER_TX_CLK_TRAIL_MID_5)				9
set mipi_param(DER_TX_CLK_ZERO_MIN_5)				22
set mipi_param(DER_TX_CLK_ZERO_MAX_5)				44
set mipi_param(DER_TX_CLK_ZERO_MID_5)				33
set mipi_param(DER_TX_CLK_POST_MIN_5)				7
set mipi_param(DER_TX_CLK_POST_MAX_5)				14
set mipi_param(DER_TX_CLK_POST_MID_5)				10
set mipi_param(DER_TX_CLK_PRE_MIN_5)				2
set mipi_param(DER_TX_CLK_PRE_MAX_5)				4
set mipi_param(DER_TX_CLK_PRE_MID_5)				3
set mipi_param(DER_TX_HS_PREPARE_MIN_5)				3
set mipi_param(DER_TX_HS_PREPARE_MAX_5)				6
set mipi_param(DER_TX_HS_PREPARE_MID_5)				4
set mipi_param(DER_TX_HS_ZERO_MIN_5)				6
set mipi_param(DER_TX_HS_ZERO_MAX_5)				12
set mipi_param(DER_TX_HS_ZERO_MID_5)				9
set mipi_param(DER_TX_HS_TRAIL_MIN_5)				9
set mipi_param(DER_TX_HS_TRAIL_MAX_5)				13
set mipi_param(DER_TX_HS_TRAIL_MID_5)				10
set mipi_param(DER_TX_INIT_MIN_5)				10
set mipi_param(DER_TX_INIT_MAX_5)				20
set mipi_param(DER_TX_INIT_MID_5)				15
set mipi_param(DER_TX_WAKE_MIN_5)				98
set mipi_param(DER_TX_WAKE_MAX_5)				196
set mipi_param(DER_TX_WAKE_MID_5)				147
set mipi_param(GUI_TX_AUTO_TYPE_5)				2
set mipi_param(GUI_TX_CAP_EQ_MODE_5)				0
set mipi_param(GUI_TX_CLK_LANE_PS_5)				32
set mipi_param(GUI_TX_HS_TM_DESKEW_P_5)				0
set mipi_param(GUI_TX_LPX_5)				7
set mipi_param(GUI_TX_HS_EXIT_5)				15
set mipi_param(GUI_TX_LP_EXIT_5)				15
set mipi_param(GUI_TX_CLK_PREPARE_5)				4
set mipi_param(GUI_TX_CLK_TRAIL_5)				9
set mipi_param(GUI_TX_CLK_ZERO_5)				33
set mipi_param(GUI_TX_CLK_POST_5)				10
set mipi_param(GUI_TX_CLK_PRE_5)				3
set mipi_param(GUI_TX_HS_PREPARE_5)				4
set mipi_param(GUI_TX_HS_ZERO_5)				9
set mipi_param(GUI_TX_HS_TRAIL_5)				10
set mipi_param(GUI_TX_INIT_5)				15
set mipi_param(GUI_TX_WAKE_5)				147
set mipi_param(DER_TX_LPX_NS_5)				70.0
set mipi_param(DER_TX_HS_EXIT_NS_5)				150.0
set mipi_param(DER_TX_LP_EXIT_NS_5)				150.0
set mipi_param(DER_TX_CLK_PREPARE_NS_5)				60.0
set mipi_param(DER_TX_CLK_TRAIL_NS_5)				80.0
set mipi_param(DER_TX_CLK_ZERO_NS_5)				380.0
set mipi_param(DER_TX_CLK_POST_NS_5)				150.0
set mipi_param(DER_TX_CLK_PRE_NS_5)				20.0
set mipi_param(DER_TX_HS_PREPARE_NS_5)				60.0
set mipi_param(DER_TX_HS_ZERO_NS_5)				160.0
set mipi_param(DER_TX_HS_TRAIL_NS_5)				80.0
set mipi_param(DER_TX_INIT_NS_5)				153600.0
set mipi_param(DER_TX_WAKE_NS_5)				1505280.0
set mipi_param(GUI_DPHY_IP_ROLE_6)				2
set mipi_param(DER_LINK_USED_6)				false
set mipi_param(GUI_SKEW_CAL_EN_6)				false
set mipi_param(GUI_SOURCE_PLL_6)				0
set mipi_param(GUI_TM_EN_6)				false
set mipi_param(GUI_TX_VCO_FREQ_MULT_6)				1
set mipi_param(GUI_BIT_RATE_MBPS_RNG_6)				1600.0
set mipi_param(DER_VCO_FREQ_MHZ_LINK_6)				800.0
set mipi_param(GUI_RX_BIT_RATE_MBPS_SEL_6)				64
set mipi_param(GUI_PPI_WIDTH_USR_6)				16
set mipi_param(DER_BIT_RATE_MBPS_6)				1600.0
set mipi_param(DER_PPI_WIDTH_6)				16
set mipi_param(GUI_ALT_CAL_EN_6)				false
set mipi_param(GUI_PER_SKEW_CAL_EN_6)				false
set mipi_param(GUI_PREAMBLE_EN_6)				false
set mipi_param(GUI_TX_PREAMBLE_LEN_PREAMLBE_LEN_6)				0
set mipi_param(GUI_TX_TM_CONTROL_TX_TM_EN_6)				false
set mipi_param(GUI_RX_TM_CONTROL_RX_TM_EN_6)				false
set mipi_param(GUI_TM_LOOPBACK_MODE_6)				false
set mipi_param(GUI_TX_TM_CONTROL_TX_TM_LOOPBACK_MODE_6)				false
set mipi_param(GUI_RX_TM_CONTROL_RX_TM_LOOPBACK_MODE_6)				false
set mipi_param(GUI_NUM_LANES_6)				1
set mipi_param(GUI_BYTE_LOC_6)				6
set mipi_param(GUI_CONTINUOUS_CLK_6)				false
set mipi_param(GUI_PRBS_INIT_0_6)				255
set mipi_param(GUI_PRBS_INIT_1_6)				255
set mipi_param(GUI_PRBS_INIT_2_6)				255
set mipi_param(GUI_PRBS_INIT_3_6)				255
set mipi_param(GUI_PRBS_INIT_4_6)				255
set mipi_param(GUI_PRBS_INIT_5_6)				255
set mipi_param(GUI_PRBS_INIT_6_6)				255
set mipi_param(GUI_PRBS_INIT_7_6)				255
set mipi_param(DER_PPI_WIDTH_16_6)				true
set mipi_param(DER_FR_CLK_FREQ_MHZ_6)				100.0
set mipi_param(DER_BIT_RATE_6)				1600000000
set mipi_param(DER_UI_6)				0.625
set mipi_param(DER_LINK_PLL_SRC_6)				false
set mipi_param(GUI_RX_TIMING_RW_6)				1
set mipi_param(DER_DPHY_RX_EN_6)				false
set mipi_param(DER_RXFIFO_LAT_6)				2
set mipi_param(DER_RX_FR_CLK_FREQ_6)				100000000
set mipi_param(DER_RX_CORE_FREQ_6)				100000000
set mipi_param(DER_RX_FR_CLK_PER_6)				10.0
set mipi_param(DER_RX_CORE_PER_6)				10.0
set mipi_param(DER_RX_FR_CLK_PER_PS_6)				10000
set mipi_param(DER_RX_CORE_PER_PS_6)				10000
set mipi_param(DER_RX_FR_CLK_PER_1K_6)				10240.0
set mipi_param(DER_RX_CORE_PER_1K_6)				10240.0
set mipi_param(DER_RX_FR_CLK_PER_1K_PS_6)				10240000
set mipi_param(DER_RX_CORE_PER_1K_PS_6)				10240000
set mipi_param(DER_RX_PPI_WIDTH_INT_C2P_6)				16
set mipi_param(DER_RX_PPI_WIDTH_16_C2P_6)				true
set mipi_param(DER_RX_TIMING_REG_RW_6)				true
set mipi_param(DER_RX_CLK_LOSS_DETECT_MIN_6)				2
set mipi_param(DER_RX_CLK_LOSS_DETECT_MAX_6)				4
set mipi_param(DER_RX_CLK_LOSS_DETECT_MID_6)				3
set mipi_param(DER_RX_CLK_SETTLE_MIN_6)				2
set mipi_param(DER_RX_CLK_SETTLE_MAX_6)				22
set mipi_param(DER_RX_CLK_SETTLE_MID_6)				12
set mipi_param(DER_RX_HS_SETTLE_MIN_6)				2
set mipi_param(DER_RX_HS_SETTLE_MAX_6)				8
set mipi_param(DER_RX_HS_SETTLE_MID_6)				5
set mipi_param(DER_RX_INIT_MIN_6)				10
set mipi_param(DER_RX_INIT_MAX_6)				20
set mipi_param(DER_RX_INIT_MID_6)				15
set mipi_param(GUI_RX_AUTO_TYPE_6)				2
set mipi_param(GUI_RX_PREP_TIME_TM_6)				0
set mipi_param(GUI_RX_CLK_LOSS_DETECT_6)				3
set mipi_param(GUI_RX_CLK_SETTLE_6)				12
set mipi_param(GUI_RX_HS_SETTLE_6)				5
set mipi_param(GUI_RX_INIT_6)				15
set mipi_param(GUI_RX_CLK_POST_6)				1
set mipi_param(GUI_RX_DLANE_DESKEW_DELAY_0_6)				0
set mipi_param(GUI_RX_DLANE_DESKEW_DELAY_1_6)				0
set mipi_param(GUI_RX_DLANE_DESKEW_DELAY_2_6)				0
set mipi_param(GUI_RX_DLANE_DESKEW_DELAY_3_6)				0
set mipi_param(GUI_RX_DLANE_DESKEW_DELAY_4_6)				0
set mipi_param(GUI_RX_DLANE_DESKEW_DELAY_5_6)				0
set mipi_param(GUI_RX_DLANE_DESKEW_DELAY_6_6)				0
set mipi_param(GUI_RX_DLANE_DESKEW_DELAY_7_6)				0
set mipi_param(DER_RX_CLK_LOSS_DETECT_NS_6)				90.0
set mipi_param(DER_RX_CLK_SETTLE_NS_6)				200.0
set mipi_param(DER_RX_HS_SETTLE_NS_6)				120.0
set mipi_param(DER_RX_INIT_NS_6)				153600.0
set mipi_param(GUI_RX_CAP_EQ_MODE_6)				0
set mipi_param(GUI_TX_TIMING_RW_6)				1
set mipi_param(DER_DPHY_TX_EN_6)				false
set mipi_param(DER_TXFIFO_LAT_6)				3
set mipi_param(DER_TX_CORE_FREQ_6)				100000000
set mipi_param(DER_TX_CORE_PER_6)				10.0
set mipi_param(DER_TX_CORE_PER_PS_6)				10000
set mipi_param(DER_TX_CORE_PER_1K_6)				10240.0
set mipi_param(DER_TX_CORE_PER_1K_PS_6)				10240000
set mipi_param(DER_TX_TIMING_REG_RW_6)				true
set mipi_param(DER_TX_LPX_MIN_6)				5
set mipi_param(DER_TX_LPX_MAX_6)				10
set mipi_param(DER_TX_LPX_MID_6)				7
set mipi_param(DER_TX_HS_EXIT_MIN_6)				10
set mipi_param(DER_TX_HS_EXIT_MAX_6)				20
set mipi_param(DER_TX_HS_EXIT_MID_6)				15
set mipi_param(DER_TX_LP_EXIT_MIN_6)				10
set mipi_param(DER_TX_LP_EXIT_MAX_6)				20
set mipi_param(DER_TX_LP_EXIT_MID_6)				15
set mipi_param(DER_TX_CLK_PREPARE_MIN_6)				2
set mipi_param(DER_TX_CLK_PREPARE_MAX_6)				7
set mipi_param(DER_TX_CLK_PREPARE_MID_6)				4
set mipi_param(DER_TX_CLK_TRAIL_MIN_6)				7
set mipi_param(DER_TX_CLK_TRAIL_MAX_6)				12
set mipi_param(DER_TX_CLK_TRAIL_MID_6)				9
set mipi_param(DER_TX_CLK_ZERO_MIN_6)				22
set mipi_param(DER_TX_CLK_ZERO_MAX_6)				44
set mipi_param(DER_TX_CLK_ZERO_MID_6)				33
set mipi_param(DER_TX_CLK_POST_MIN_6)				7
set mipi_param(DER_TX_CLK_POST_MAX_6)				14
set mipi_param(DER_TX_CLK_POST_MID_6)				10
set mipi_param(DER_TX_CLK_PRE_MIN_6)				2
set mipi_param(DER_TX_CLK_PRE_MAX_6)				4
set mipi_param(DER_TX_CLK_PRE_MID_6)				3
set mipi_param(DER_TX_HS_PREPARE_MIN_6)				3
set mipi_param(DER_TX_HS_PREPARE_MAX_6)				6
set mipi_param(DER_TX_HS_PREPARE_MID_6)				4
set mipi_param(DER_TX_HS_ZERO_MIN_6)				6
set mipi_param(DER_TX_HS_ZERO_MAX_6)				12
set mipi_param(DER_TX_HS_ZERO_MID_6)				9
set mipi_param(DER_TX_HS_TRAIL_MIN_6)				9
set mipi_param(DER_TX_HS_TRAIL_MAX_6)				13
set mipi_param(DER_TX_HS_TRAIL_MID_6)				10
set mipi_param(DER_TX_INIT_MIN_6)				10
set mipi_param(DER_TX_INIT_MAX_6)				20
set mipi_param(DER_TX_INIT_MID_6)				15
set mipi_param(DER_TX_WAKE_MIN_6)				98
set mipi_param(DER_TX_WAKE_MAX_6)				196
set mipi_param(DER_TX_WAKE_MID_6)				147
set mipi_param(GUI_TX_AUTO_TYPE_6)				2
set mipi_param(GUI_TX_CAP_EQ_MODE_6)				0
set mipi_param(GUI_TX_CLK_LANE_PS_6)				32
set mipi_param(GUI_TX_HS_TM_DESKEW_P_6)				0
set mipi_param(GUI_TX_LPX_6)				7
set mipi_param(GUI_TX_HS_EXIT_6)				15
set mipi_param(GUI_TX_LP_EXIT_6)				15
set mipi_param(GUI_TX_CLK_PREPARE_6)				4
set mipi_param(GUI_TX_CLK_TRAIL_6)				9
set mipi_param(GUI_TX_CLK_ZERO_6)				33
set mipi_param(GUI_TX_CLK_POST_6)				10
set mipi_param(GUI_TX_CLK_PRE_6)				3
set mipi_param(GUI_TX_HS_PREPARE_6)				4
set mipi_param(GUI_TX_HS_ZERO_6)				9
set mipi_param(GUI_TX_HS_TRAIL_6)				10
set mipi_param(GUI_TX_INIT_6)				15
set mipi_param(GUI_TX_WAKE_6)				147
set mipi_param(DER_TX_LPX_NS_6)				70.0
set mipi_param(DER_TX_HS_EXIT_NS_6)				150.0
set mipi_param(DER_TX_LP_EXIT_NS_6)				150.0
set mipi_param(DER_TX_CLK_PREPARE_NS_6)				60.0
set mipi_param(DER_TX_CLK_TRAIL_NS_6)				80.0
set mipi_param(DER_TX_CLK_ZERO_NS_6)				380.0
set mipi_param(DER_TX_CLK_POST_NS_6)				150.0
set mipi_param(DER_TX_CLK_PRE_NS_6)				20.0
set mipi_param(DER_TX_HS_PREPARE_NS_6)				60.0
set mipi_param(DER_TX_HS_ZERO_NS_6)				160.0
set mipi_param(DER_TX_HS_TRAIL_NS_6)				80.0
set mipi_param(DER_TX_INIT_NS_6)				153600.0
set mipi_param(DER_TX_WAKE_NS_6)				1505280.0
set mipi_param(GUI_DPHY_IP_ROLE_7)				2
set mipi_param(DER_LINK_USED_7)				false
set mipi_param(GUI_SKEW_CAL_EN_7)				false
set mipi_param(GUI_SOURCE_PLL_7)				0
set mipi_param(GUI_TM_EN_7)				false
set mipi_param(GUI_TX_VCO_FREQ_MULT_7)				1
set mipi_param(GUI_BIT_RATE_MBPS_RNG_7)				1600.0
set mipi_param(DER_VCO_FREQ_MHZ_LINK_7)				800.0
set mipi_param(GUI_RX_BIT_RATE_MBPS_SEL_7)				64
set mipi_param(GUI_PPI_WIDTH_USR_7)				16
set mipi_param(DER_BIT_RATE_MBPS_7)				1600.0
set mipi_param(DER_PPI_WIDTH_7)				16
set mipi_param(GUI_ALT_CAL_EN_7)				false
set mipi_param(GUI_PER_SKEW_CAL_EN_7)				false
set mipi_param(GUI_PREAMBLE_EN_7)				false
set mipi_param(GUI_TX_PREAMBLE_LEN_PREAMLBE_LEN_7)				0
set mipi_param(GUI_TX_TM_CONTROL_TX_TM_EN_7)				false
set mipi_param(GUI_RX_TM_CONTROL_RX_TM_EN_7)				false
set mipi_param(GUI_TM_LOOPBACK_MODE_7)				false
set mipi_param(GUI_TX_TM_CONTROL_TX_TM_LOOPBACK_MODE_7)				false
set mipi_param(GUI_RX_TM_CONTROL_RX_TM_LOOPBACK_MODE_7)				false
set mipi_param(GUI_NUM_LANES_7)				1
set mipi_param(GUI_BYTE_LOC_7)				7
set mipi_param(GUI_CONTINUOUS_CLK_7)				false
set mipi_param(GUI_PRBS_INIT_0_7)				255
set mipi_param(GUI_PRBS_INIT_1_7)				255
set mipi_param(GUI_PRBS_INIT_2_7)				255
set mipi_param(GUI_PRBS_INIT_3_7)				255
set mipi_param(GUI_PRBS_INIT_4_7)				255
set mipi_param(GUI_PRBS_INIT_5_7)				255
set mipi_param(GUI_PRBS_INIT_6_7)				255
set mipi_param(GUI_PRBS_INIT_7_7)				255
set mipi_param(DER_PPI_WIDTH_16_7)				true
set mipi_param(DER_FR_CLK_FREQ_MHZ_7)				100.0
set mipi_param(DER_BIT_RATE_7)				1600000000
set mipi_param(DER_UI_7)				0.625
set mipi_param(DER_LINK_PLL_SRC_7)				false
set mipi_param(GUI_RX_TIMING_RW_7)				1
set mipi_param(DER_DPHY_RX_EN_7)				false
set mipi_param(DER_RXFIFO_LAT_7)				2
set mipi_param(DER_RX_FR_CLK_FREQ_7)				100000000
set mipi_param(DER_RX_CORE_FREQ_7)				100000000
set mipi_param(DER_RX_FR_CLK_PER_7)				10.0
set mipi_param(DER_RX_CORE_PER_7)				10.0
set mipi_param(DER_RX_FR_CLK_PER_PS_7)				10000
set mipi_param(DER_RX_CORE_PER_PS_7)				10000
set mipi_param(DER_RX_FR_CLK_PER_1K_7)				10240.0
set mipi_param(DER_RX_CORE_PER_1K_7)				10240.0
set mipi_param(DER_RX_FR_CLK_PER_1K_PS_7)				10240000
set mipi_param(DER_RX_CORE_PER_1K_PS_7)				10240000
set mipi_param(DER_RX_PPI_WIDTH_INT_C2P_7)				16
set mipi_param(DER_RX_PPI_WIDTH_16_C2P_7)				true
set mipi_param(DER_RX_TIMING_REG_RW_7)				true
set mipi_param(DER_RX_CLK_LOSS_DETECT_MIN_7)				2
set mipi_param(DER_RX_CLK_LOSS_DETECT_MAX_7)				4
set mipi_param(DER_RX_CLK_LOSS_DETECT_MID_7)				3
set mipi_param(DER_RX_CLK_SETTLE_MIN_7)				2
set mipi_param(DER_RX_CLK_SETTLE_MAX_7)				22
set mipi_param(DER_RX_CLK_SETTLE_MID_7)				12
set mipi_param(DER_RX_HS_SETTLE_MIN_7)				2
set mipi_param(DER_RX_HS_SETTLE_MAX_7)				8
set mipi_param(DER_RX_HS_SETTLE_MID_7)				5
set mipi_param(DER_RX_INIT_MIN_7)				10
set mipi_param(DER_RX_INIT_MAX_7)				20
set mipi_param(DER_RX_INIT_MID_7)				15
set mipi_param(GUI_RX_AUTO_TYPE_7)				2
set mipi_param(GUI_RX_PREP_TIME_TM_7)				0
set mipi_param(GUI_RX_CLK_LOSS_DETECT_7)				3
set mipi_param(GUI_RX_CLK_SETTLE_7)				12
set mipi_param(GUI_RX_HS_SETTLE_7)				5
set mipi_param(GUI_RX_INIT_7)				15
set mipi_param(GUI_RX_CLK_POST_7)				1
set mipi_param(GUI_RX_DLANE_DESKEW_DELAY_0_7)				0
set mipi_param(GUI_RX_DLANE_DESKEW_DELAY_1_7)				0
set mipi_param(GUI_RX_DLANE_DESKEW_DELAY_2_7)				0
set mipi_param(GUI_RX_DLANE_DESKEW_DELAY_3_7)				0
set mipi_param(GUI_RX_DLANE_DESKEW_DELAY_4_7)				0
set mipi_param(GUI_RX_DLANE_DESKEW_DELAY_5_7)				0
set mipi_param(GUI_RX_DLANE_DESKEW_DELAY_6_7)				0
set mipi_param(GUI_RX_DLANE_DESKEW_DELAY_7_7)				0
set mipi_param(DER_RX_CLK_LOSS_DETECT_NS_7)				90.0
set mipi_param(DER_RX_CLK_SETTLE_NS_7)				200.0
set mipi_param(DER_RX_HS_SETTLE_NS_7)				120.0
set mipi_param(DER_RX_INIT_NS_7)				153600.0
set mipi_param(GUI_RX_CAP_EQ_MODE_7)				0
set mipi_param(GUI_TX_TIMING_RW_7)				1
set mipi_param(DER_DPHY_TX_EN_7)				false
set mipi_param(DER_TXFIFO_LAT_7)				3
set mipi_param(DER_TX_CORE_FREQ_7)				100000000
set mipi_param(DER_TX_CORE_PER_7)				10.0
set mipi_param(DER_TX_CORE_PER_PS_7)				10000
set mipi_param(DER_TX_CORE_PER_1K_7)				10240.0
set mipi_param(DER_TX_CORE_PER_1K_PS_7)				10240000
set mipi_param(DER_TX_TIMING_REG_RW_7)				true
set mipi_param(DER_TX_LPX_MIN_7)				5
set mipi_param(DER_TX_LPX_MAX_7)				10
set mipi_param(DER_TX_LPX_MID_7)				7
set mipi_param(DER_TX_HS_EXIT_MIN_7)				10
set mipi_param(DER_TX_HS_EXIT_MAX_7)				20
set mipi_param(DER_TX_HS_EXIT_MID_7)				15
set mipi_param(DER_TX_LP_EXIT_MIN_7)				10
set mipi_param(DER_TX_LP_EXIT_MAX_7)				20
set mipi_param(DER_TX_LP_EXIT_MID_7)				15
set mipi_param(DER_TX_CLK_PREPARE_MIN_7)				2
set mipi_param(DER_TX_CLK_PREPARE_MAX_7)				7
set mipi_param(DER_TX_CLK_PREPARE_MID_7)				4
set mipi_param(DER_TX_CLK_TRAIL_MIN_7)				7
set mipi_param(DER_TX_CLK_TRAIL_MAX_7)				12
set mipi_param(DER_TX_CLK_TRAIL_MID_7)				9
set mipi_param(DER_TX_CLK_ZERO_MIN_7)				22
set mipi_param(DER_TX_CLK_ZERO_MAX_7)				44
set mipi_param(DER_TX_CLK_ZERO_MID_7)				33
set mipi_param(DER_TX_CLK_POST_MIN_7)				7
set mipi_param(DER_TX_CLK_POST_MAX_7)				14
set mipi_param(DER_TX_CLK_POST_MID_7)				10
set mipi_param(DER_TX_CLK_PRE_MIN_7)				2
set mipi_param(DER_TX_CLK_PRE_MAX_7)				4
set mipi_param(DER_TX_CLK_PRE_MID_7)				3
set mipi_param(DER_TX_HS_PREPARE_MIN_7)				3
set mipi_param(DER_TX_HS_PREPARE_MAX_7)				6
set mipi_param(DER_TX_HS_PREPARE_MID_7)				4
set mipi_param(DER_TX_HS_ZERO_MIN_7)				6
set mipi_param(DER_TX_HS_ZERO_MAX_7)				12
set mipi_param(DER_TX_HS_ZERO_MID_7)				9
set mipi_param(DER_TX_HS_TRAIL_MIN_7)				9
set mipi_param(DER_TX_HS_TRAIL_MAX_7)				13
set mipi_param(DER_TX_HS_TRAIL_MID_7)				10
set mipi_param(DER_TX_INIT_MIN_7)				10
set mipi_param(DER_TX_INIT_MAX_7)				20
set mipi_param(DER_TX_INIT_MID_7)				15
set mipi_param(DER_TX_WAKE_MIN_7)				98
set mipi_param(DER_TX_WAKE_MAX_7)				196
set mipi_param(DER_TX_WAKE_MID_7)				147
set mipi_param(GUI_TX_AUTO_TYPE_7)				2
set mipi_param(GUI_TX_CAP_EQ_MODE_7)				0
set mipi_param(GUI_TX_CLK_LANE_PS_7)				32
set mipi_param(GUI_TX_HS_TM_DESKEW_P_7)				0
set mipi_param(GUI_TX_LPX_7)				7
set mipi_param(GUI_TX_HS_EXIT_7)				15
set mipi_param(GUI_TX_LP_EXIT_7)				15
set mipi_param(GUI_TX_CLK_PREPARE_7)				4
set mipi_param(GUI_TX_CLK_TRAIL_7)				9
set mipi_param(GUI_TX_CLK_ZERO_7)				33
set mipi_param(GUI_TX_CLK_POST_7)				10
set mipi_param(GUI_TX_CLK_PRE_7)				3
set mipi_param(GUI_TX_HS_PREPARE_7)				4
set mipi_param(GUI_TX_HS_ZERO_7)				9
set mipi_param(GUI_TX_HS_TRAIL_7)				10
set mipi_param(GUI_TX_INIT_7)				15
set mipi_param(GUI_TX_WAKE_7)				147
set mipi_param(DER_TX_LPX_NS_7)				70.0
set mipi_param(DER_TX_HS_EXIT_NS_7)				150.0
set mipi_param(DER_TX_LP_EXIT_NS_7)				150.0
set mipi_param(DER_TX_CLK_PREPARE_NS_7)				60.0
set mipi_param(DER_TX_CLK_TRAIL_NS_7)				80.0
set mipi_param(DER_TX_CLK_ZERO_NS_7)				380.0
set mipi_param(DER_TX_CLK_POST_NS_7)				150.0
set mipi_param(DER_TX_CLK_PRE_NS_7)				20.0
set mipi_param(DER_TX_HS_PREPARE_NS_7)				60.0
set mipi_param(DER_TX_HS_ZERO_NS_7)				160.0
set mipi_param(DER_TX_HS_TRAIL_NS_7)				80.0
set mipi_param(DER_TX_INIT_NS_7)				153600.0
set mipi_param(DER_TX_WAKE_NS_7)				1505280.0
set mipi_param(EX_DESIGN_HDL_FORMAT)				HDL_FORMAT_VERILOG
set mipi_param(EX_DESIGN_GEN_SYNTH)				false
set mipi_param(EX_DESIGN_SYNTH_MIRROR)				false
set mipi_param(EX_DESIGN_GEN_SIM)				true
set mipi_param(EX_DESIGN_TEST_COUNT)				10
set mipi_param(EX_DESIGN_SIM_LOOPBACK)				true
set mipi_param(EX_DESIGN_SIM_CHK_PAR)				false
set mipi_param(EX_DESIGN_GEN_BSI)				false
set mipi_param(EX_DESIGN_GEN_CDC)				false
set mipi_param(EX_DESIGN_OSC_CLK_1_FREQ)				OSC_CLK_1_125MHZ
set mipi_param(EX_DESIGN_USE_TG)				false
set mipi_sys_param(SYS_INFO_DEVICE_IOBANK_REVISION)				 "IO96B_REVB1"
