// csi2_dphy_sys_csi2_tx_altera_mm_interconnect_1920_ttgb2vq.v

// This file was auto-generated from altera_mm_interconnect_hw.tcl.  If you edit it your changes
// will probably be lost.
// 
// Generated using ACDS version 25.3 109

`timescale 1 ps / 1 ps
module csi2_dphy_sys_csi2_tx_altera_mm_interconnect_1920_ttgb2vq (
		input  wire [10:0] ro_reg_servicer_av_mm_master_address,                                      //                                        ro_reg_servicer_av_mm_master.address
		output wire        ro_reg_servicer_av_mm_master_waitrequest,                                  //                                                                    .waitrequest
		input  wire [3:0]  ro_reg_servicer_av_mm_master_byteenable,                                   //                                                                    .byteenable
		input  wire        ro_reg_servicer_av_mm_master_read,                                         //                                                                    .read
		output wire [31:0] ro_reg_servicer_av_mm_master_readdata,                                     //                                                                    .readdata
		output wire        ro_reg_servicer_av_mm_master_readdatavalid,                                //                                                                    .readdatavalid
		input  wire        ro_reg_servicer_av_mm_master_write,                                        //                                                                    .write
		input  wire [31:0] ro_reg_servicer_av_mm_master_writedata,                                    //                                                                    .writedata
		output wire [7:0]  axi2cv_core_av_mm_slave_address,                                           //                                             axi2cv_core_av_mm_slave.address
		output wire        axi2cv_core_av_mm_slave_write,                                             //                                                                    .write
		output wire        axi2cv_core_av_mm_slave_read,                                              //                                                                    .read
		input  wire [31:0] axi2cv_core_av_mm_slave_readdata,                                          //                                                                    .readdata
		output wire [31:0] axi2cv_core_av_mm_slave_writedata,                                         //                                                                    .writedata
		output wire [3:0]  axi2cv_core_av_mm_slave_byteenable,                                        //                                                                    .byteenable
		input  wire        axi2cv_core_av_mm_slave_readdatavalid,                                     //                                                                    .readdatavalid
		input  wire        axi2cv_core_av_mm_slave_waitrequest,                                       //                                                                    .waitrequest
		input  wire        axi2cv_core_main_reset_reset_bridge_in_reset_reset,                        //                        axi2cv_core_main_reset_reset_bridge_in_reset.reset,        Reset Input
		input  wire        ro_reg_servicer_av_mm_master_translator_reset_reset_bridge_in_reset_reset, // ro_reg_servicer_av_mm_master_translator_reset_reset_bridge_in_reset.reset,        Reset Input
		input  wire        csr_clk_bridge_out_clk_clk                                                 //                                              csr_clk_bridge_out_clk.clk,          Clock Input
	);

	wire         ro_reg_servicer_av_mm_master_translator_avalon_universal_master_0_waitrequest;   // axi2cv_core_av_mm_slave_translator:uav_waitrequest -> ro_reg_servicer_av_mm_master_translator:uav_waitrequest
	wire  [31:0] ro_reg_servicer_av_mm_master_translator_avalon_universal_master_0_readdata;      // axi2cv_core_av_mm_slave_translator:uav_readdata -> ro_reg_servicer_av_mm_master_translator:uav_readdata
	wire         ro_reg_servicer_av_mm_master_translator_avalon_universal_master_0_debugaccess;   // ro_reg_servicer_av_mm_master_translator:uav_debugaccess -> axi2cv_core_av_mm_slave_translator:uav_debugaccess
	wire  [10:0] ro_reg_servicer_av_mm_master_translator_avalon_universal_master_0_address;       // ro_reg_servicer_av_mm_master_translator:uav_address -> axi2cv_core_av_mm_slave_translator:uav_address
	wire         ro_reg_servicer_av_mm_master_translator_avalon_universal_master_0_read;          // ro_reg_servicer_av_mm_master_translator:uav_read -> axi2cv_core_av_mm_slave_translator:uav_read
	wire   [3:0] ro_reg_servicer_av_mm_master_translator_avalon_universal_master_0_byteenable;    // ro_reg_servicer_av_mm_master_translator:uav_byteenable -> axi2cv_core_av_mm_slave_translator:uav_byteenable
	wire         ro_reg_servicer_av_mm_master_translator_avalon_universal_master_0_readdatavalid; // axi2cv_core_av_mm_slave_translator:uav_readdatavalid -> ro_reg_servicer_av_mm_master_translator:uav_readdatavalid
	wire         ro_reg_servicer_av_mm_master_translator_avalon_universal_master_0_lock;          // ro_reg_servicer_av_mm_master_translator:uav_lock -> axi2cv_core_av_mm_slave_translator:uav_lock
	wire         ro_reg_servicer_av_mm_master_translator_avalon_universal_master_0_write;         // ro_reg_servicer_av_mm_master_translator:uav_write -> axi2cv_core_av_mm_slave_translator:uav_write
	wire  [31:0] ro_reg_servicer_av_mm_master_translator_avalon_universal_master_0_writedata;     // ro_reg_servicer_av_mm_master_translator:uav_writedata -> axi2cv_core_av_mm_slave_translator:uav_writedata
	wire   [2:0] ro_reg_servicer_av_mm_master_translator_avalon_universal_master_0_burstcount;    // ro_reg_servicer_av_mm_master_translator:uav_burstcount -> axi2cv_core_av_mm_slave_translator:uav_burstcount

	csi2_dphy_sys_csi2_tx_altera_merlin_master_translator_193_lgcew2q #(
		.AV_ADDRESS_W                (11),
		.AV_DATA_W                   (32),
		.AV_BURSTCOUNT_W             (1),
		.AV_BYTEENABLE_W             (4),
		.UAV_ADDRESS_W               (11),
		.UAV_BURSTCOUNT_W            (3),
		.USE_READ                    (1),
		.USE_WRITE                   (1),
		.USE_BEGINBURSTTRANSFER      (0),
		.USE_BEGINTRANSFER           (0),
		.USE_CHIPSELECT              (0),
		.USE_BURSTCOUNT              (0),
		.USE_READDATAVALID           (1),
		.USE_WAITREQUEST             (1),
		.USE_READRESPONSE            (0),
		.USE_WRITERESPONSE           (0),
		.AV_SYMBOLS_PER_WORD         (4),
		.AV_ADDRESS_SYMBOLS          (1),
		.AV_BURSTCOUNT_SYMBOLS       (0),
		.AV_CONSTANT_BURST_BEHAVIOR  (0),
		.UAV_CONSTANT_BURST_BEHAVIOR (0),
		.AV_LINEWRAPBURSTS           (0),
		.AV_REGISTERINCOMINGSIGNALS  (0),
		.SYNC_RESET                  (0),
		.WAITREQUEST_ALLOWANCE       (0),
		.USE_OUTPUTENABLE            (0)
	) ro_reg_servicer_av_mm_master_translator (
		.clk                    (csr_clk_bridge_out_clk_clk),                                                      //   input,   width = 1,                       clk.clk
		.reset                  (ro_reg_servicer_av_mm_master_translator_reset_reset_bridge_in_reset_reset),       //   input,   width = 1,                     reset.reset
		.uav_address            (ro_reg_servicer_av_mm_master_translator_avalon_universal_master_0_address),       //  output,  width = 11, avalon_universal_master_0.address
		.uav_burstcount         (ro_reg_servicer_av_mm_master_translator_avalon_universal_master_0_burstcount),    //  output,   width = 3,                          .burstcount
		.uav_read               (ro_reg_servicer_av_mm_master_translator_avalon_universal_master_0_read),          //  output,   width = 1,                          .read
		.uav_write              (ro_reg_servicer_av_mm_master_translator_avalon_universal_master_0_write),         //  output,   width = 1,                          .write
		.uav_waitrequest        (ro_reg_servicer_av_mm_master_translator_avalon_universal_master_0_waitrequest),   //   input,   width = 1,                          .waitrequest
		.uav_readdatavalid      (ro_reg_servicer_av_mm_master_translator_avalon_universal_master_0_readdatavalid), //   input,   width = 1,                          .readdatavalid
		.uav_byteenable         (ro_reg_servicer_av_mm_master_translator_avalon_universal_master_0_byteenable),    //  output,   width = 4,                          .byteenable
		.uav_readdata           (ro_reg_servicer_av_mm_master_translator_avalon_universal_master_0_readdata),      //   input,  width = 32,                          .readdata
		.uav_writedata          (ro_reg_servicer_av_mm_master_translator_avalon_universal_master_0_writedata),     //  output,  width = 32,                          .writedata
		.uav_lock               (ro_reg_servicer_av_mm_master_translator_avalon_universal_master_0_lock),          //  output,   width = 1,                          .lock
		.uav_debugaccess        (ro_reg_servicer_av_mm_master_translator_avalon_universal_master_0_debugaccess),   //  output,   width = 1,                          .debugaccess
		.av_address             (ro_reg_servicer_av_mm_master_address),                                            //   input,  width = 11,      avalon_anti_master_0.address
		.av_waitrequest         (ro_reg_servicer_av_mm_master_waitrequest),                                        //  output,   width = 1,                          .waitrequest
		.av_byteenable          (ro_reg_servicer_av_mm_master_byteenable),                                         //   input,   width = 4,                          .byteenable
		.av_read                (ro_reg_servicer_av_mm_master_read),                                               //   input,   width = 1,                          .read
		.av_readdata            (ro_reg_servicer_av_mm_master_readdata),                                           //  output,  width = 32,                          .readdata
		.av_readdatavalid       (ro_reg_servicer_av_mm_master_readdatavalid),                                      //  output,   width = 1,                          .readdatavalid
		.av_write               (ro_reg_servicer_av_mm_master_write),                                              //   input,   width = 1,                          .write
		.av_writedata           (ro_reg_servicer_av_mm_master_writedata),                                          //   input,  width = 32,                          .writedata
		.av_burstcount          (1'b1),                                                                            // (terminated),                                        
		.av_beginbursttransfer  (1'b0),                                                                            // (terminated),                                        
		.av_begintransfer       (1'b0),                                                                            // (terminated),                                        
		.av_chipselect          (1'b0),                                                                            // (terminated),                                        
		.av_lock                (1'b0),                                                                            // (terminated),                                        
		.av_debugaccess         (1'b0),                                                                            // (terminated),                                        
		.uav_outputenable       (1'b0),                                                                            // (terminated),                                        
		.uav_clken              (),                                                                                // (terminated),                                        
		.av_clken               (1'b1),                                                                            // (terminated),                                        
		.uav_response           (2'b00),                                                                           // (terminated),                                        
		.av_response            (),                                                                                // (terminated),                                        
		.uav_writeresponsevalid (1'b0),                                                                            // (terminated),                                        
		.av_writeresponsevalid  ()                                                                                 // (terminated),                                        
	);

	csi2_dphy_sys_csi2_tx_altera_merlin_slave_translator_191_xg7rzxi #(
		.AV_ADDRESS_W                   (8),
		.AV_DATA_W                      (32),
		.UAV_DATA_W                     (32),
		.AV_BURSTCOUNT_W                (1),
		.AV_BYTEENABLE_W                (4),
		.UAV_BYTEENABLE_W               (4),
		.UAV_ADDRESS_W                  (11),
		.UAV_BURSTCOUNT_W               (3),
		.AV_READLATENCY                 (0),
		.USE_READDATAVALID              (1),
		.USE_WAITREQUEST                (1),
		.USE_UAV_CLKEN                  (0),
		.USE_READRESPONSE               (0),
		.USE_WRITERESPONSE              (0),
		.AV_SYMBOLS_PER_WORD            (4),
		.AV_ADDRESS_SYMBOLS             (0),
		.AV_BURSTCOUNT_SYMBOLS          (0),
		.AV_CONSTANT_BURST_BEHAVIOR     (0),
		.UAV_CONSTANT_BURST_BEHAVIOR    (0),
		.AV_REQUIRE_UNALIGNED_ADDRESSES (0),
		.CHIPSELECT_THROUGH_READLATENCY (0),
		.AV_READ_WAIT_CYCLES            (0),
		.AV_WRITE_WAIT_CYCLES           (0),
		.AV_SETUP_WAIT_CYCLES           (0),
		.AV_DATA_HOLD_CYCLES            (0),
		.WAITREQUEST_ALLOWANCE          (0),
		.SYNC_RESET                     (0)
	) axi2cv_core_av_mm_slave_translator (
		.clk                    (csr_clk_bridge_out_clk_clk),                                                      //   input,   width = 1,                      clk.clk
		.reset                  (axi2cv_core_main_reset_reset_bridge_in_reset_reset),                              //   input,   width = 1,                    reset.reset
		.uav_address            (ro_reg_servicer_av_mm_master_translator_avalon_universal_master_0_address),       //   input,  width = 11, avalon_universal_slave_0.address
		.uav_burstcount         (ro_reg_servicer_av_mm_master_translator_avalon_universal_master_0_burstcount),    //   input,   width = 3,                         .burstcount
		.uav_read               (ro_reg_servicer_av_mm_master_translator_avalon_universal_master_0_read),          //   input,   width = 1,                         .read
		.uav_write              (ro_reg_servicer_av_mm_master_translator_avalon_universal_master_0_write),         //   input,   width = 1,                         .write
		.uav_waitrequest        (ro_reg_servicer_av_mm_master_translator_avalon_universal_master_0_waitrequest),   //  output,   width = 1,                         .waitrequest
		.uav_readdatavalid      (ro_reg_servicer_av_mm_master_translator_avalon_universal_master_0_readdatavalid), //  output,   width = 1,                         .readdatavalid
		.uav_byteenable         (ro_reg_servicer_av_mm_master_translator_avalon_universal_master_0_byteenable),    //   input,   width = 4,                         .byteenable
		.uav_readdata           (ro_reg_servicer_av_mm_master_translator_avalon_universal_master_0_readdata),      //  output,  width = 32,                         .readdata
		.uav_writedata          (ro_reg_servicer_av_mm_master_translator_avalon_universal_master_0_writedata),     //   input,  width = 32,                         .writedata
		.uav_lock               (ro_reg_servicer_av_mm_master_translator_avalon_universal_master_0_lock),          //   input,   width = 1,                         .lock
		.uav_debugaccess        (ro_reg_servicer_av_mm_master_translator_avalon_universal_master_0_debugaccess),   //   input,   width = 1,                         .debugaccess
		.av_address             (axi2cv_core_av_mm_slave_address),                                                 //  output,   width = 8,      avalon_anti_slave_0.address
		.av_write               (axi2cv_core_av_mm_slave_write),                                                   //  output,   width = 1,                         .write
		.av_read                (axi2cv_core_av_mm_slave_read),                                                    //  output,   width = 1,                         .read
		.av_readdata            (axi2cv_core_av_mm_slave_readdata),                                                //   input,  width = 32,                         .readdata
		.av_writedata           (axi2cv_core_av_mm_slave_writedata),                                               //  output,  width = 32,                         .writedata
		.av_byteenable          (axi2cv_core_av_mm_slave_byteenable),                                              //  output,   width = 4,                         .byteenable
		.av_readdatavalid       (axi2cv_core_av_mm_slave_readdatavalid),                                           //   input,   width = 1,                         .readdatavalid
		.av_waitrequest         (axi2cv_core_av_mm_slave_waitrequest),                                             //   input,   width = 1,                         .waitrequest
		.av_begintransfer       (),                                                                                // (terminated),                                       
		.av_beginbursttransfer  (),                                                                                // (terminated),                                       
		.av_burstcount          (),                                                                                // (terminated),                                       
		.av_writebyteenable     (),                                                                                // (terminated),                                       
		.av_lock                (),                                                                                // (terminated),                                       
		.av_chipselect          (),                                                                                // (terminated),                                       
		.av_clken               (),                                                                                // (terminated),                                       
		.uav_clken              (1'b0),                                                                            // (terminated),                                       
		.av_debugaccess         (),                                                                                // (terminated),                                       
		.av_outputenable        (),                                                                                // (terminated),                                       
		.uav_response           (),                                                                                // (terminated),                                       
		.av_response            (2'b00),                                                                           // (terminated),                                       
		.uav_writeresponsevalid (),                                                                                // (terminated),                                       
		.av_writeresponsevalid  (1'b0)                                                                             // (terminated),                                       
	);

endmodule
