// csi2_dphy_sys_mipi_dphy.v

// Generated using ACDS version 25.3 109

`timescale 1 ps / 1 ps
module csi2_dphy_sys_mipi_dphy (
		input  wire        rzq,                         //                     rzq.rzq
		input  wire        ref_clk_0_p,                 //               ref_clk_0.clk
		input  wire        arst_n,                      //                    arst.reset_n
		output wire        LINK0_link_core_clk,         //     LINK0_link_core_clk.clk
		output wire        LINK0_link_srst_n,           //    LINK0_link_core_srst.reset_n
		output wire        LINK0_link_arst_n,           //    LINK0_link_core_arst.reset_n
		input  wire        axil_clk,                    //                 reg_clk.clk
		input  wire        srst_axil_n,                 //                reg_srst.reset_n
		input  wire [11:0] axi_lite_awaddr,             //                axi_lite.awaddr
		input  wire        axi_lite_awvalid,            //                        .awvalid
		output wire        axi_lite_awready,            //                        .awready
		input  wire [31:0] axi_lite_wdata,              //                        .wdata
		input  wire [3:0]  axi_lite_wstrb,              //                        .wstrb
		input  wire        axi_lite_wvalid,             //                        .wvalid
		output wire        axi_lite_wready,             //                        .wready
		output wire [1:0]  axi_lite_bresp,              //                        .bresp
		output wire        axi_lite_bvalid,             //                        .bvalid
		input  wire        axi_lite_bready,             //                        .bready
		input  wire [11:0] axi_lite_araddr,             //                        .araddr
		input  wire        axi_lite_arvalid,            //                        .arvalid
		output wire        axi_lite_arready,            //                        .arready
		output wire [31:0] axi_lite_rdata,              //                        .rdata
		output wire [1:0]  axi_lite_rresp,              //                        .rresp
		output wire        axi_lite_rvalid,             //                        .rvalid
		input  wire        axi_lite_rready,             //                        .rready
		input  wire [2:0]  axi_lite_arprot,             //                        .arprot
		input  wire [2:0]  axi_lite_awprot,             //                        .awprot
		output wire        LINK0_D0_RxWordClkHS,        //  LINK0_D0_ppi_rx_hs_clk.clk
		output wire        LINK0_D1_RxWordClkHS,        //  LINK0_D1_ppi_rx_hs_clk.clk
		output wire        LINK0_CK_RxWordClkHS,        //  LINK0_CK_ppi_rx_hs_clk.clk
		output wire        LINK0_D0_RxSRst_n,           // LINK0_D0_ppi_rx_hs_srst.reset_n
		output wire        LINK0_D1_RxSRst_n,           // LINK0_D1_ppi_rx_hs_srst.reset_n
		output wire        LINK0_CK_RxSRst_n,           // LINK0_CK_ppi_rx_hs_srst.reset_n
		input  wire [1:0]  LINK0_D0_RxDataWidthHS,      //      LINK0_D0_ppi_rx_hs.RxDataWidthHS
		output wire [15:0] LINK0_D0_RxDataHS,           //                        .RxDataHS
		output wire [1:0]  LINK0_D0_RxValidHS,          //                        .RxValidHS
		output wire        LINK0_D0_RxActiveHS,         //                        .RxActiveHS
		output wire        LINK0_D0_RxSyncHS,           //                        .RxSyncHS
		input  wire        LINK0_D0_RxDetectEobHS,      //                        .RxDetectEobHS
		output wire        LINK0_D0_RxClkActiveHS,      //                        .RxClkActiveHS
		output wire        LINK0_D0_RxDDRClkHS,         //                        .RxDDRClkHS
		output wire        LINK0_D0_RxSkewCalHS,        //                        .RxSkewCalHS
		output wire        LINK0_D0_RxAlternateCalHS,   //                        .RxAlternateCalHS
		output wire        LINK0_D0_RxErrorCalHS,       //                        .RxErrorCalHS
		input  wire [1:0]  LINK0_D1_RxDataWidthHS,      //      LINK0_D1_ppi_rx_hs.RxDataWidthHS
		output wire [15:0] LINK0_D1_RxDataHS,           //                        .RxDataHS
		output wire [1:0]  LINK0_D1_RxValidHS,          //                        .RxValidHS
		output wire        LINK0_D1_RxActiveHS,         //                        .RxActiveHS
		output wire        LINK0_D1_RxSyncHS,           //                        .RxSyncHS
		input  wire        LINK0_D1_RxDetectEobHS,      //                        .RxDetectEobHS
		output wire        LINK0_D1_RxClkActiveHS,      //                        .RxClkActiveHS
		output wire        LINK0_D1_RxDDRClkHS,         //                        .RxDDRClkHS
		output wire        LINK0_D1_RxSkewCalHS,        //                        .RxSkewCalHS
		output wire        LINK0_D1_RxAlternateCalHS,   //                        .RxAlternateCalHS
		output wire        LINK0_D1_RxErrorCalHS,       //                        .RxErrorCalHS
		input  wire [1:0]  LINK0_CK_RxDataWidthHS,      //      LINK0_CK_ppi_rx_hs.RxDataWidthHS
		output wire [15:0] LINK0_CK_RxDataHS,           //                        .RxDataHS
		output wire [1:0]  LINK0_CK_RxValidHS,          //                        .RxValidHS
		output wire        LINK0_CK_RxActiveHS,         //                        .RxActiveHS
		output wire        LINK0_CK_RxSyncHS,           //                        .RxSyncHS
		input  wire        LINK0_CK_RxDetectEobHS,      //                        .RxDetectEobHS
		output wire        LINK0_CK_RxClkActiveHS,      //                        .RxClkActiveHS
		output wire        LINK0_CK_RxDDRClkHS,         //                        .RxDDRClkHS
		output wire        LINK0_CK_RxSkewCalHS,        //                        .RxSkewCalHS
		output wire        LINK0_CK_RxAlternateCalHS,   //                        .RxAlternateCalHS
		output wire        LINK0_CK_RxErrorCalHS,       //                        .RxErrorCalHS
		output wire        LINK0_D0_RxClkEsc,           //      LINK0_D0_ppi_rx_lp.RxClkEsc
		output wire        LINK0_D0_RxLpdtEsc,          //                        .RxLpdtEsc
		output wire        LINK0_D0_RxUlpsEsc,          //                        .RxUlpsEsc
		output wire [3:0]  LINK0_D0_RxTriggerEsc,       //                        .RxTriggerEsc
		output wire        LINK0_D0_RxWakeup,           //                        .RxWakeup
		output wire [7:0]  LINK0_D0_RxDataEsc,          //                        .RxDataEsc
		output wire        LINK0_D0_RxValidEsc,         //                        .RxValidEsc
		output wire        LINK0_D1_RxClkEsc,           //      LINK0_D1_ppi_rx_lp.RxClkEsc
		output wire        LINK0_D1_RxLpdtEsc,          //                        .RxLpdtEsc
		output wire        LINK0_D1_RxUlpsEsc,          //                        .RxUlpsEsc
		output wire [3:0]  LINK0_D1_RxTriggerEsc,       //                        .RxTriggerEsc
		output wire        LINK0_D1_RxWakeup,           //                        .RxWakeup
		output wire [7:0]  LINK0_D1_RxDataEsc,          //                        .RxDataEsc
		output wire        LINK0_D1_RxValidEsc,         //                        .RxValidEsc
		output wire        LINK0_CK_RxClkEsc,           //      LINK0_CK_ppi_rx_lp.RxClkEsc
		output wire        LINK0_CK_RxLpdtEsc,          //                        .RxLpdtEsc
		output wire        LINK0_CK_RxUlpsEsc,          //                        .RxUlpsEsc
		output wire [3:0]  LINK0_CK_RxTriggerEsc,       //                        .RxTriggerEsc
		output wire        LINK0_CK_RxWakeup,           //                        .RxWakeup
		output wire [7:0]  LINK0_CK_RxDataEsc,          //                        .RxDataEsc
		output wire        LINK0_CK_RxValidEsc,         //                        .RxValidEsc
		input  wire        LINK0_D0_TurnRequest,        //       LINK0_D0_ppi_ctrl.TurnRequest
		output wire        LINK0_D0_Direction,          //                        .Direction
		input  wire        LINK0_D0_TurnDisable,        //                        .TurnDisable
		input  wire        LINK0_D0_ForceRxmode,        //                        .ForceRxmode
		input  wire        LINK0_D0_ForceTxStopmode,    //                        .ForceTxStopmode
		output wire        LINK0_D0_Stopstate,          //                        .Stopstate
		input  wire        LINK0_D0_Enable,             //                        .Enable
		input  wire        LINK0_D0_AlpMode,            //                        .AlpMode
		input  wire        LINK0_D0_TxUlpsClk,          //                        .TxUlpsClk
		output wire        LINK0_D0_RxUlpsClkNot,       //                        .RxUlpsClkNot
		output wire        LINK0_D0_UlpsActiveNot,      //                        .UlpsActiveNot
		input  wire        LINK0_D0_TxHSIdleClkHS,      //                        .TxHSIdleClkHS
		output wire        LINK0_D0_TxHSIdleClkReadyHS, //                        .TxHSIdleClkReadyHS
		input  wire        LINK0_D1_TurnRequest,        //       LINK0_D1_ppi_ctrl.TurnRequest
		output wire        LINK0_D1_Direction,          //                        .Direction
		input  wire        LINK0_D1_TurnDisable,        //                        .TurnDisable
		input  wire        LINK0_D1_ForceRxmode,        //                        .ForceRxmode
		input  wire        LINK0_D1_ForceTxStopmode,    //                        .ForceTxStopmode
		output wire        LINK0_D1_Stopstate,          //                        .Stopstate
		input  wire        LINK0_D1_Enable,             //                        .Enable
		input  wire        LINK0_D1_AlpMode,            //                        .AlpMode
		input  wire        LINK0_D1_TxUlpsClk,          //                        .TxUlpsClk
		output wire        LINK0_D1_RxUlpsClkNot,       //                        .RxUlpsClkNot
		output wire        LINK0_D1_UlpsActiveNot,      //                        .UlpsActiveNot
		input  wire        LINK0_D1_TxHSIdleClkHS,      //                        .TxHSIdleClkHS
		output wire        LINK0_D1_TxHSIdleClkReadyHS, //                        .TxHSIdleClkReadyHS
		input  wire        LINK0_CK_TurnRequest,        //       LINK0_CK_ppi_ctrl.TurnRequest
		output wire        LINK0_CK_Direction,          //                        .Direction
		input  wire        LINK0_CK_TurnDisable,        //                        .TurnDisable
		input  wire        LINK0_CK_ForceRxmode,        //                        .ForceRxmode
		input  wire        LINK0_CK_ForceTxStopmode,    //                        .ForceTxStopmode
		output wire        LINK0_CK_Stopstate,          //                        .Stopstate
		input  wire        LINK0_CK_Enable,             //                        .Enable
		input  wire        LINK0_CK_AlpMode,            //                        .AlpMode
		input  wire        LINK0_CK_TxUlpsClk,          //                        .TxUlpsClk
		output wire        LINK0_CK_RxUlpsClkNot,       //                        .RxUlpsClkNot
		output wire        LINK0_CK_UlpsActiveNot,      //                        .UlpsActiveNot
		input  wire        LINK0_CK_TxHSIdleClkHS,      //                        .TxHSIdleClkHS
		output wire        LINK0_CK_TxHSIdleClkReadyHS, //                        .TxHSIdleClkReadyHS
		output wire        LINK0_D0_ErrSotHS,           //     LINK0_D0_ppi_rx_err.ErrSotHS
		output wire        LINK0_D0_ErrSotSyncHS,       //                        .ErrSotSyncHS
		output wire        LINK0_D0_ErrEsc,             //                        .ErrEsc
		output wire        LINK0_D0_ErrSyncEsc,         //                        .ErrSyncEsc
		output wire        LINK0_D0_ErrControl,         //                        .ErrControl
		output wire        LINK0_D0_ErrContentionLP0,   //                        .ErrContentionLP0
		output wire        LINK0_D0_ErrContentionLP1,   //                        .ErrContentionLP1
		output wire        LINK0_D1_ErrSotHS,           //     LINK0_D1_ppi_rx_err.ErrSotHS
		output wire        LINK0_D1_ErrSotSyncHS,       //                        .ErrSotSyncHS
		output wire        LINK0_D1_ErrEsc,             //                        .ErrEsc
		output wire        LINK0_D1_ErrSyncEsc,         //                        .ErrSyncEsc
		output wire        LINK0_D1_ErrControl,         //                        .ErrControl
		output wire        LINK0_D1_ErrContentionLP0,   //                        .ErrContentionLP0
		output wire        LINK0_D1_ErrContentionLP1,   //                        .ErrContentionLP1
		output wire        LINK0_CK_ErrSotHS,           //     LINK0_CK_ppi_rx_err.ErrSotHS
		output wire        LINK0_CK_ErrSotSyncHS,       //                        .ErrSotSyncHS
		output wire        LINK0_CK_ErrEsc,             //                        .ErrEsc
		output wire        LINK0_CK_ErrSyncEsc,         //                        .ErrSyncEsc
		output wire        LINK0_CK_ErrControl,         //                        .ErrControl
		output wire        LINK0_CK_ErrContentionLP0,   //                        .ErrContentionLP0
		output wire        LINK0_CK_ErrContentionLP1,   //                        .ErrContentionLP1
		input  wire [1:0]  LINK0_dphy_link_dp,          //           LINK0_dphy_io.dphy_link_dp
		input  wire [1:0]  LINK0_dphy_link_dn,          //                        .dphy_link_dn
		input  wire        LINK0_dphy_link_cp,          //                        .dphy_link_cp
		input  wire        LINK0_dphy_link_cn,          //                        .dphy_link_cn
		output wire        reg_wr_en_o,                 //                 reg_bus.reg_wr_en_o
		output wire        reg_rd_en_o,                 //                        .reg_rd_en_o
		output wire [10:0] reg_raddr_o,                 //                        .reg_raddr_o
		output wire [10:0] reg_waddr_o,                 //                        .reg_waddr_o
		output wire [3:0]  reg_be_o,                    //                        .reg_be_o
		output wire [31:0] reg_din_o,                   //                        .reg_din_o
		input  wire [31:0] reg_dout_i                   //                        .reg_dout_i
	);

	csi2_dphy_sys_mipi_dphy_mipi_dphy_610_awu3why mipi_dphy (
		.rzq                         (rzq),                         //   input,   width = 1,                     rzq.rzq
		.ref_clk_0_p                 (ref_clk_0_p),                 //   input,   width = 1,               ref_clk_0.clk
		.arst_n                      (arst_n),                      //   input,   width = 1,                    arst.reset_n
		.LINK0_link_core_clk         (LINK0_link_core_clk),         //  output,   width = 1,     LINK0_link_core_clk.clk
		.LINK0_link_srst_n           (LINK0_link_srst_n),           //  output,   width = 1,    LINK0_link_core_srst.reset_n
		.LINK0_link_arst_n           (LINK0_link_arst_n),           //  output,   width = 1,    LINK0_link_core_arst.reset_n
		.axil_clk                    (axil_clk),                    //   input,   width = 1,                 reg_clk.clk
		.srst_axil_n                 (srst_axil_n),                 //   input,   width = 1,                reg_srst.reset_n
		.axi_lite_awaddr             (axi_lite_awaddr),             //   input,  width = 12,                axi_lite.awaddr
		.axi_lite_awvalid            (axi_lite_awvalid),            //   input,   width = 1,                        .awvalid
		.axi_lite_awready            (axi_lite_awready),            //  output,   width = 1,                        .awready
		.axi_lite_wdata              (axi_lite_wdata),              //   input,  width = 32,                        .wdata
		.axi_lite_wstrb              (axi_lite_wstrb),              //   input,   width = 4,                        .wstrb
		.axi_lite_wvalid             (axi_lite_wvalid),             //   input,   width = 1,                        .wvalid
		.axi_lite_wready             (axi_lite_wready),             //  output,   width = 1,                        .wready
		.axi_lite_bresp              (axi_lite_bresp),              //  output,   width = 2,                        .bresp
		.axi_lite_bvalid             (axi_lite_bvalid),             //  output,   width = 1,                        .bvalid
		.axi_lite_bready             (axi_lite_bready),             //   input,   width = 1,                        .bready
		.axi_lite_araddr             (axi_lite_araddr),             //   input,  width = 12,                        .araddr
		.axi_lite_arvalid            (axi_lite_arvalid),            //   input,   width = 1,                        .arvalid
		.axi_lite_arready            (axi_lite_arready),            //  output,   width = 1,                        .arready
		.axi_lite_rdata              (axi_lite_rdata),              //  output,  width = 32,                        .rdata
		.axi_lite_rresp              (axi_lite_rresp),              //  output,   width = 2,                        .rresp
		.axi_lite_rvalid             (axi_lite_rvalid),             //  output,   width = 1,                        .rvalid
		.axi_lite_rready             (axi_lite_rready),             //   input,   width = 1,                        .rready
		.axi_lite_arprot             (axi_lite_arprot),             //   input,   width = 3,                        .arprot
		.axi_lite_awprot             (axi_lite_awprot),             //   input,   width = 3,                        .awprot
		.LINK0_D0_RxWordClkHS        (LINK0_D0_RxWordClkHS),        //  output,   width = 1,  LINK0_D0_ppi_rx_hs_clk.clk
		.LINK0_D1_RxWordClkHS        (LINK0_D1_RxWordClkHS),        //  output,   width = 1,  LINK0_D1_ppi_rx_hs_clk.clk
		.LINK0_CK_RxWordClkHS        (LINK0_CK_RxWordClkHS),        //  output,   width = 1,  LINK0_CK_ppi_rx_hs_clk.clk
		.LINK0_D0_RxSRst_n           (LINK0_D0_RxSRst_n),           //  output,   width = 1, LINK0_D0_ppi_rx_hs_srst.reset_n
		.LINK0_D1_RxSRst_n           (LINK0_D1_RxSRst_n),           //  output,   width = 1, LINK0_D1_ppi_rx_hs_srst.reset_n
		.LINK0_CK_RxSRst_n           (LINK0_CK_RxSRst_n),           //  output,   width = 1, LINK0_CK_ppi_rx_hs_srst.reset_n
		.LINK0_D0_RxDataWidthHS      (LINK0_D0_RxDataWidthHS),      //   input,   width = 2,      LINK0_D0_ppi_rx_hs.RxDataWidthHS
		.LINK0_D0_RxDataHS           (LINK0_D0_RxDataHS),           //  output,  width = 16,                        .RxDataHS
		.LINK0_D0_RxValidHS          (LINK0_D0_RxValidHS),          //  output,   width = 2,                        .RxValidHS
		.LINK0_D0_RxActiveHS         (LINK0_D0_RxActiveHS),         //  output,   width = 1,                        .RxActiveHS
		.LINK0_D0_RxSyncHS           (LINK0_D0_RxSyncHS),           //  output,   width = 1,                        .RxSyncHS
		.LINK0_D0_RxDetectEobHS      (LINK0_D0_RxDetectEobHS),      //   input,   width = 1,                        .RxDetectEobHS
		.LINK0_D0_RxClkActiveHS      (LINK0_D0_RxClkActiveHS),      //  output,   width = 1,                        .RxClkActiveHS
		.LINK0_D0_RxDDRClkHS         (LINK0_D0_RxDDRClkHS),         //  output,   width = 1,                        .RxDDRClkHS
		.LINK0_D0_RxSkewCalHS        (LINK0_D0_RxSkewCalHS),        //  output,   width = 1,                        .RxSkewCalHS
		.LINK0_D0_RxAlternateCalHS   (LINK0_D0_RxAlternateCalHS),   //  output,   width = 1,                        .RxAlternateCalHS
		.LINK0_D0_RxErrorCalHS       (LINK0_D0_RxErrorCalHS),       //  output,   width = 1,                        .RxErrorCalHS
		.LINK0_D1_RxDataWidthHS      (LINK0_D1_RxDataWidthHS),      //   input,   width = 2,      LINK0_D1_ppi_rx_hs.RxDataWidthHS
		.LINK0_D1_RxDataHS           (LINK0_D1_RxDataHS),           //  output,  width = 16,                        .RxDataHS
		.LINK0_D1_RxValidHS          (LINK0_D1_RxValidHS),          //  output,   width = 2,                        .RxValidHS
		.LINK0_D1_RxActiveHS         (LINK0_D1_RxActiveHS),         //  output,   width = 1,                        .RxActiveHS
		.LINK0_D1_RxSyncHS           (LINK0_D1_RxSyncHS),           //  output,   width = 1,                        .RxSyncHS
		.LINK0_D1_RxDetectEobHS      (LINK0_D1_RxDetectEobHS),      //   input,   width = 1,                        .RxDetectEobHS
		.LINK0_D1_RxClkActiveHS      (LINK0_D1_RxClkActiveHS),      //  output,   width = 1,                        .RxClkActiveHS
		.LINK0_D1_RxDDRClkHS         (LINK0_D1_RxDDRClkHS),         //  output,   width = 1,                        .RxDDRClkHS
		.LINK0_D1_RxSkewCalHS        (LINK0_D1_RxSkewCalHS),        //  output,   width = 1,                        .RxSkewCalHS
		.LINK0_D1_RxAlternateCalHS   (LINK0_D1_RxAlternateCalHS),   //  output,   width = 1,                        .RxAlternateCalHS
		.LINK0_D1_RxErrorCalHS       (LINK0_D1_RxErrorCalHS),       //  output,   width = 1,                        .RxErrorCalHS
		.LINK0_CK_RxDataWidthHS      (LINK0_CK_RxDataWidthHS),      //   input,   width = 2,      LINK0_CK_ppi_rx_hs.RxDataWidthHS
		.LINK0_CK_RxDataHS           (LINK0_CK_RxDataHS),           //  output,  width = 16,                        .RxDataHS
		.LINK0_CK_RxValidHS          (LINK0_CK_RxValidHS),          //  output,   width = 2,                        .RxValidHS
		.LINK0_CK_RxActiveHS         (LINK0_CK_RxActiveHS),         //  output,   width = 1,                        .RxActiveHS
		.LINK0_CK_RxSyncHS           (LINK0_CK_RxSyncHS),           //  output,   width = 1,                        .RxSyncHS
		.LINK0_CK_RxDetectEobHS      (LINK0_CK_RxDetectEobHS),      //   input,   width = 1,                        .RxDetectEobHS
		.LINK0_CK_RxClkActiveHS      (LINK0_CK_RxClkActiveHS),      //  output,   width = 1,                        .RxClkActiveHS
		.LINK0_CK_RxDDRClkHS         (LINK0_CK_RxDDRClkHS),         //  output,   width = 1,                        .RxDDRClkHS
		.LINK0_CK_RxSkewCalHS        (LINK0_CK_RxSkewCalHS),        //  output,   width = 1,                        .RxSkewCalHS
		.LINK0_CK_RxAlternateCalHS   (LINK0_CK_RxAlternateCalHS),   //  output,   width = 1,                        .RxAlternateCalHS
		.LINK0_CK_RxErrorCalHS       (LINK0_CK_RxErrorCalHS),       //  output,   width = 1,                        .RxErrorCalHS
		.LINK0_D0_RxClkEsc           (LINK0_D0_RxClkEsc),           //  output,   width = 1,      LINK0_D0_ppi_rx_lp.RxClkEsc
		.LINK0_D0_RxLpdtEsc          (LINK0_D0_RxLpdtEsc),          //  output,   width = 1,                        .RxLpdtEsc
		.LINK0_D0_RxUlpsEsc          (LINK0_D0_RxUlpsEsc),          //  output,   width = 1,                        .RxUlpsEsc
		.LINK0_D0_RxTriggerEsc       (LINK0_D0_RxTriggerEsc),       //  output,   width = 4,                        .RxTriggerEsc
		.LINK0_D0_RxWakeup           (LINK0_D0_RxWakeup),           //  output,   width = 1,                        .RxWakeup
		.LINK0_D0_RxDataEsc          (LINK0_D0_RxDataEsc),          //  output,   width = 8,                        .RxDataEsc
		.LINK0_D0_RxValidEsc         (LINK0_D0_RxValidEsc),         //  output,   width = 1,                        .RxValidEsc
		.LINK0_D1_RxClkEsc           (LINK0_D1_RxClkEsc),           //  output,   width = 1,      LINK0_D1_ppi_rx_lp.RxClkEsc
		.LINK0_D1_RxLpdtEsc          (LINK0_D1_RxLpdtEsc),          //  output,   width = 1,                        .RxLpdtEsc
		.LINK0_D1_RxUlpsEsc          (LINK0_D1_RxUlpsEsc),          //  output,   width = 1,                        .RxUlpsEsc
		.LINK0_D1_RxTriggerEsc       (LINK0_D1_RxTriggerEsc),       //  output,   width = 4,                        .RxTriggerEsc
		.LINK0_D1_RxWakeup           (LINK0_D1_RxWakeup),           //  output,   width = 1,                        .RxWakeup
		.LINK0_D1_RxDataEsc          (LINK0_D1_RxDataEsc),          //  output,   width = 8,                        .RxDataEsc
		.LINK0_D1_RxValidEsc         (LINK0_D1_RxValidEsc),         //  output,   width = 1,                        .RxValidEsc
		.LINK0_CK_RxClkEsc           (LINK0_CK_RxClkEsc),           //  output,   width = 1,      LINK0_CK_ppi_rx_lp.RxClkEsc
		.LINK0_CK_RxLpdtEsc          (LINK0_CK_RxLpdtEsc),          //  output,   width = 1,                        .RxLpdtEsc
		.LINK0_CK_RxUlpsEsc          (LINK0_CK_RxUlpsEsc),          //  output,   width = 1,                        .RxUlpsEsc
		.LINK0_CK_RxTriggerEsc       (LINK0_CK_RxTriggerEsc),       //  output,   width = 4,                        .RxTriggerEsc
		.LINK0_CK_RxWakeup           (LINK0_CK_RxWakeup),           //  output,   width = 1,                        .RxWakeup
		.LINK0_CK_RxDataEsc          (LINK0_CK_RxDataEsc),          //  output,   width = 8,                        .RxDataEsc
		.LINK0_CK_RxValidEsc         (LINK0_CK_RxValidEsc),         //  output,   width = 1,                        .RxValidEsc
		.LINK0_D0_TurnRequest        (LINK0_D0_TurnRequest),        //   input,   width = 1,       LINK0_D0_ppi_ctrl.TurnRequest
		.LINK0_D0_Direction          (LINK0_D0_Direction),          //  output,   width = 1,                        .Direction
		.LINK0_D0_TurnDisable        (LINK0_D0_TurnDisable),        //   input,   width = 1,                        .TurnDisable
		.LINK0_D0_ForceRxmode        (LINK0_D0_ForceRxmode),        //   input,   width = 1,                        .ForceRxmode
		.LINK0_D0_ForceTxStopmode    (LINK0_D0_ForceTxStopmode),    //   input,   width = 1,                        .ForceTxStopmode
		.LINK0_D0_Stopstate          (LINK0_D0_Stopstate),          //  output,   width = 1,                        .Stopstate
		.LINK0_D0_Enable             (LINK0_D0_Enable),             //   input,   width = 1,                        .Enable
		.LINK0_D0_AlpMode            (LINK0_D0_AlpMode),            //   input,   width = 1,                        .AlpMode
		.LINK0_D0_TxUlpsClk          (LINK0_D0_TxUlpsClk),          //   input,   width = 1,                        .TxUlpsClk
		.LINK0_D0_RxUlpsClkNot       (LINK0_D0_RxUlpsClkNot),       //  output,   width = 1,                        .RxUlpsClkNot
		.LINK0_D0_UlpsActiveNot      (LINK0_D0_UlpsActiveNot),      //  output,   width = 1,                        .UlpsActiveNot
		.LINK0_D0_TxHSIdleClkHS      (LINK0_D0_TxHSIdleClkHS),      //   input,   width = 1,                        .TxHSIdleClkHS
		.LINK0_D0_TxHSIdleClkReadyHS (LINK0_D0_TxHSIdleClkReadyHS), //  output,   width = 1,                        .TxHSIdleClkReadyHS
		.LINK0_D1_TurnRequest        (LINK0_D1_TurnRequest),        //   input,   width = 1,       LINK0_D1_ppi_ctrl.TurnRequest
		.LINK0_D1_Direction          (LINK0_D1_Direction),          //  output,   width = 1,                        .Direction
		.LINK0_D1_TurnDisable        (LINK0_D1_TurnDisable),        //   input,   width = 1,                        .TurnDisable
		.LINK0_D1_ForceRxmode        (LINK0_D1_ForceRxmode),        //   input,   width = 1,                        .ForceRxmode
		.LINK0_D1_ForceTxStopmode    (LINK0_D1_ForceTxStopmode),    //   input,   width = 1,                        .ForceTxStopmode
		.LINK0_D1_Stopstate          (LINK0_D1_Stopstate),          //  output,   width = 1,                        .Stopstate
		.LINK0_D1_Enable             (LINK0_D1_Enable),             //   input,   width = 1,                        .Enable
		.LINK0_D1_AlpMode            (LINK0_D1_AlpMode),            //   input,   width = 1,                        .AlpMode
		.LINK0_D1_TxUlpsClk          (LINK0_D1_TxUlpsClk),          //   input,   width = 1,                        .TxUlpsClk
		.LINK0_D1_RxUlpsClkNot       (LINK0_D1_RxUlpsClkNot),       //  output,   width = 1,                        .RxUlpsClkNot
		.LINK0_D1_UlpsActiveNot      (LINK0_D1_UlpsActiveNot),      //  output,   width = 1,                        .UlpsActiveNot
		.LINK0_D1_TxHSIdleClkHS      (LINK0_D1_TxHSIdleClkHS),      //   input,   width = 1,                        .TxHSIdleClkHS
		.LINK0_D1_TxHSIdleClkReadyHS (LINK0_D1_TxHSIdleClkReadyHS), //  output,   width = 1,                        .TxHSIdleClkReadyHS
		.LINK0_CK_TurnRequest        (LINK0_CK_TurnRequest),        //   input,   width = 1,       LINK0_CK_ppi_ctrl.TurnRequest
		.LINK0_CK_Direction          (LINK0_CK_Direction),          //  output,   width = 1,                        .Direction
		.LINK0_CK_TurnDisable        (LINK0_CK_TurnDisable),        //   input,   width = 1,                        .TurnDisable
		.LINK0_CK_ForceRxmode        (LINK0_CK_ForceRxmode),        //   input,   width = 1,                        .ForceRxmode
		.LINK0_CK_ForceTxStopmode    (LINK0_CK_ForceTxStopmode),    //   input,   width = 1,                        .ForceTxStopmode
		.LINK0_CK_Stopstate          (LINK0_CK_Stopstate),          //  output,   width = 1,                        .Stopstate
		.LINK0_CK_Enable             (LINK0_CK_Enable),             //   input,   width = 1,                        .Enable
		.LINK0_CK_AlpMode            (LINK0_CK_AlpMode),            //   input,   width = 1,                        .AlpMode
		.LINK0_CK_TxUlpsClk          (LINK0_CK_TxUlpsClk),          //   input,   width = 1,                        .TxUlpsClk
		.LINK0_CK_RxUlpsClkNot       (LINK0_CK_RxUlpsClkNot),       //  output,   width = 1,                        .RxUlpsClkNot
		.LINK0_CK_UlpsActiveNot      (LINK0_CK_UlpsActiveNot),      //  output,   width = 1,                        .UlpsActiveNot
		.LINK0_CK_TxHSIdleClkHS      (LINK0_CK_TxHSIdleClkHS),      //   input,   width = 1,                        .TxHSIdleClkHS
		.LINK0_CK_TxHSIdleClkReadyHS (LINK0_CK_TxHSIdleClkReadyHS), //  output,   width = 1,                        .TxHSIdleClkReadyHS
		.LINK0_D0_ErrSotHS           (LINK0_D0_ErrSotHS),           //  output,   width = 1,     LINK0_D0_ppi_rx_err.ErrSotHS
		.LINK0_D0_ErrSotSyncHS       (LINK0_D0_ErrSotSyncHS),       //  output,   width = 1,                        .ErrSotSyncHS
		.LINK0_D0_ErrEsc             (LINK0_D0_ErrEsc),             //  output,   width = 1,                        .ErrEsc
		.LINK0_D0_ErrSyncEsc         (LINK0_D0_ErrSyncEsc),         //  output,   width = 1,                        .ErrSyncEsc
		.LINK0_D0_ErrControl         (LINK0_D0_ErrControl),         //  output,   width = 1,                        .ErrControl
		.LINK0_D0_ErrContentionLP0   (LINK0_D0_ErrContentionLP0),   //  output,   width = 1,                        .ErrContentionLP0
		.LINK0_D0_ErrContentionLP1   (LINK0_D0_ErrContentionLP1),   //  output,   width = 1,                        .ErrContentionLP1
		.LINK0_D1_ErrSotHS           (LINK0_D1_ErrSotHS),           //  output,   width = 1,     LINK0_D1_ppi_rx_err.ErrSotHS
		.LINK0_D1_ErrSotSyncHS       (LINK0_D1_ErrSotSyncHS),       //  output,   width = 1,                        .ErrSotSyncHS
		.LINK0_D1_ErrEsc             (LINK0_D1_ErrEsc),             //  output,   width = 1,                        .ErrEsc
		.LINK0_D1_ErrSyncEsc         (LINK0_D1_ErrSyncEsc),         //  output,   width = 1,                        .ErrSyncEsc
		.LINK0_D1_ErrControl         (LINK0_D1_ErrControl),         //  output,   width = 1,                        .ErrControl
		.LINK0_D1_ErrContentionLP0   (LINK0_D1_ErrContentionLP0),   //  output,   width = 1,                        .ErrContentionLP0
		.LINK0_D1_ErrContentionLP1   (LINK0_D1_ErrContentionLP1),   //  output,   width = 1,                        .ErrContentionLP1
		.LINK0_CK_ErrSotHS           (LINK0_CK_ErrSotHS),           //  output,   width = 1,     LINK0_CK_ppi_rx_err.ErrSotHS
		.LINK0_CK_ErrSotSyncHS       (LINK0_CK_ErrSotSyncHS),       //  output,   width = 1,                        .ErrSotSyncHS
		.LINK0_CK_ErrEsc             (LINK0_CK_ErrEsc),             //  output,   width = 1,                        .ErrEsc
		.LINK0_CK_ErrSyncEsc         (LINK0_CK_ErrSyncEsc),         //  output,   width = 1,                        .ErrSyncEsc
		.LINK0_CK_ErrControl         (LINK0_CK_ErrControl),         //  output,   width = 1,                        .ErrControl
		.LINK0_CK_ErrContentionLP0   (LINK0_CK_ErrContentionLP0),   //  output,   width = 1,                        .ErrContentionLP0
		.LINK0_CK_ErrContentionLP1   (LINK0_CK_ErrContentionLP1),   //  output,   width = 1,                        .ErrContentionLP1
		.LINK0_dphy_link_dp          (LINK0_dphy_link_dp),          //   input,   width = 2,           LINK0_dphy_io.dphy_link_dp
		.LINK0_dphy_link_dn          (LINK0_dphy_link_dn),          //   input,   width = 2,                        .dphy_link_dn
		.LINK0_dphy_link_cp          (LINK0_dphy_link_cp),          //   input,   width = 1,                        .dphy_link_cp
		.LINK0_dphy_link_cn          (LINK0_dphy_link_cn),          //   input,   width = 1,                        .dphy_link_cn
		.reg_wr_en_o                 (reg_wr_en_o),                 //  output,   width = 1,                 reg_bus.reg_wr_en_o
		.reg_rd_en_o                 (reg_rd_en_o),                 //  output,   width = 1,                        .reg_rd_en_o
		.reg_raddr_o                 (reg_raddr_o),                 //  output,  width = 11,                        .reg_raddr_o
		.reg_waddr_o                 (reg_waddr_o),                 //  output,  width = 11,                        .reg_waddr_o
		.reg_be_o                    (reg_be_o),                    //  output,   width = 4,                        .reg_be_o
		.reg_din_o                   (reg_din_o),                   //  output,  width = 32,                        .reg_din_o
		.reg_dout_i                  (reg_dout_i)                   //   input,  width = 32,                        .reg_dout_i
	);

endmodule
