// vvp_vfw_debug.v

// Generated using ACDS version 25.3 109

`timescale 1 ps / 1 ps
module vvp_vfw_debug (
		input  wire         main_clock_clk,                    //           main_clock.clk,          Clock Input
		input  wire         main_reset_reset,                  //           main_reset.reset
		input  wire         mem_clock_clk,                     //            mem_clock.clk,          Clock Input
		input  wire         mem_reset_reset,                   //            mem_reset.reset
		input  wire [95:0]  axi4s_vid_in_tdata,                //         axi4s_vid_in.tdata
		input  wire         axi4s_vid_in_tvalid,               //                     .tvalid
		output wire         axi4s_vid_in_tready,               //                     .tready
		input  wire         axi4s_vid_in_tlast,                //                     .tlast
		input  wire [11:0]  axi4s_vid_in_tuser,                //                     .tuser
		output wire [31:0]  av_mm_mem_write_host_address,      // av_mm_mem_write_host.address
		input  wire         av_mm_mem_write_host_waitrequest,  //                     .waitrequest
		output wire [4:0]   av_mm_mem_write_host_burstcount,   //                     .burstcount
		output wire         av_mm_mem_write_host_write,        //                     .write
		output wire [127:0] av_mm_mem_write_host_writedata,    //                     .writedata
		input  wire         control_clock_clk,                 //        control_clock.clk,          Clock Input
		input  wire         control_reset_reset,               //        control_reset.reset
		input  wire [6:0]   av_mm_control_agent_address,       //  av_mm_control_agent.address
		input  wire         av_mm_control_agent_write,         //                     .write
		input  wire [3:0]   av_mm_control_agent_byteenable,    //                     .byteenable
		input  wire [31:0]  av_mm_control_agent_writedata,     //                     .writedata
		input  wire         av_mm_control_agent_read,          //                     .read
		output wire [31:0]  av_mm_control_agent_readdata,      //                     .readdata
		output wire         av_mm_control_agent_readdatavalid, //                     .readdatavalid
		output wire         av_mm_control_agent_waitrequest,   //                     .waitrequest
		output wire         frame_writer_int_irq               //     frame_writer_int.irq
	);

	vvp_vfw_debug_intel_vvp_vfw_2460_k3l6rsa #(
		.MAX_HEIGHT             (2048),
		.MAX_WIDTH              (2048),
		.BPS                    (8),
		.NUMBER_OF_COLOR_PLANES (3),
		.PIXELS_IN_PARALLEL     (4),
		.CLOCKS_ARE_SEPARATE    (1),
		.P_AV_MM_DATA_WIDTH     (128),
		.P_AV_MM_ADDR_WIDTH     (32),
		.WRITE_BURST_TARGET     (16)
	) vvp_vfw_debug (
		.main_clock_clk                    (main_clock_clk),                    //   input,    width = 1,           main_clock.clk
		.main_reset_reset                  (main_reset_reset),                  //   input,    width = 1,           main_reset.reset
		.mem_clock_clk                     (mem_clock_clk),                     //   input,    width = 1,            mem_clock.clk
		.mem_reset_reset                   (mem_reset_reset),                   //   input,    width = 1,            mem_reset.reset
		.axi4s_vid_in_tdata                (axi4s_vid_in_tdata),                //   input,   width = 96,         axi4s_vid_in.tdata
		.axi4s_vid_in_tvalid               (axi4s_vid_in_tvalid),               //   input,    width = 1,                     .tvalid
		.axi4s_vid_in_tready               (axi4s_vid_in_tready),               //  output,    width = 1,                     .tready
		.axi4s_vid_in_tlast                (axi4s_vid_in_tlast),                //   input,    width = 1,                     .tlast
		.axi4s_vid_in_tuser                (axi4s_vid_in_tuser),                //   input,   width = 12,                     .tuser
		.av_mm_mem_write_host_address      (av_mm_mem_write_host_address),      //  output,   width = 32, av_mm_mem_write_host.address
		.av_mm_mem_write_host_waitrequest  (av_mm_mem_write_host_waitrequest),  //   input,    width = 1,                     .waitrequest
		.av_mm_mem_write_host_burstcount   (av_mm_mem_write_host_burstcount),   //  output,    width = 5,                     .burstcount
		.av_mm_mem_write_host_write        (av_mm_mem_write_host_write),        //  output,    width = 1,                     .write
		.av_mm_mem_write_host_writedata    (av_mm_mem_write_host_writedata),    //  output,  width = 128,                     .writedata
		.control_clock_clk                 (control_clock_clk),                 //   input,    width = 1,        control_clock.clk
		.control_reset_reset               (control_reset_reset),               //   input,    width = 1,        control_reset.reset
		.av_mm_control_agent_address       (av_mm_control_agent_address),       //   input,    width = 7,  av_mm_control_agent.address
		.av_mm_control_agent_write         (av_mm_control_agent_write),         //   input,    width = 1,                     .write
		.av_mm_control_agent_byteenable    (av_mm_control_agent_byteenable),    //   input,    width = 4,                     .byteenable
		.av_mm_control_agent_writedata     (av_mm_control_agent_writedata),     //   input,   width = 32,                     .writedata
		.av_mm_control_agent_read          (av_mm_control_agent_read),          //   input,    width = 1,                     .read
		.av_mm_control_agent_readdata      (av_mm_control_agent_readdata),      //  output,   width = 32,                     .readdata
		.av_mm_control_agent_readdatavalid (av_mm_control_agent_readdatavalid), //  output,    width = 1,                     .readdatavalid
		.av_mm_control_agent_waitrequest   (av_mm_control_agent_waitrequest),   //  output,    width = 1,                     .waitrequest
		.frame_writer_int_irq              (frame_writer_int_irq)               //  output,    width = 1,     frame_writer_int.irq
	);

endmodule
