// video_path_reset_in.v

// Generated using ACDS version 25.3 109

`timescale 1 ps / 1 ps
module video_path_reset_in (
		input  wire  clk,       //       clk.clk,   Clock Input
		input  wire  in_reset,  //  in_reset.reset, Reset Input
		output wire  out_reset  // out_reset.reset, Reset Output
	);

	assign out_reset = in_reset;

endmodule
