// csi2_dphy_sys_reset_release_0.v

// Generated using ACDS version 25.3 109

`timescale 1 ps / 1 ps
module csi2_dphy_sys_reset_release_0 (
		output wire  ninit_done  // ninit_done.reset
	);

	intel_user_rst_clkgate reset_release_0 (
		.ninit_done (ninit_done)  //  output,  width = 1, ninit_done.reset
	);

endmodule
