// mipi_broadcaster_0.v

// Generated using ACDS version 25.3 109

`timescale 1 ps / 1 ps
module mipi_broadcaster_0 (
		input  wire [63:0] axi4s_vid_in_tdata,     //    axi4s_vid_in.tdata
		input  wire        axi4s_vid_in_tvalid,    //                .tvalid
		output wire        axi4s_vid_in_tready,    //                .tready
		input  wire        axi4s_vid_in_tlast,     //                .tlast
		input  wire [7:0]  axi4s_vid_in_tuser,     //                .tuser
		output wire [63:0] axi4s_vid_out_0_tdata,  // axi4s_vid_out_0.tdata
		output wire        axi4s_vid_out_0_tvalid, //                .tvalid
		input  wire        axi4s_vid_out_0_tready, //                .tready
		output wire        axi4s_vid_out_0_tlast,  //                .tlast
		output wire [7:0]  axi4s_vid_out_0_tuser,  //                .tuser
		output wire [63:0] axi4s_vid_out_1_tdata,  // axi4s_vid_out_1.tdata
		output wire        axi4s_vid_out_1_tvalid, //                .tvalid
		input  wire        axi4s_vid_out_1_tready, //                .tready
		output wire        axi4s_vid_out_1_tlast,  //                .tlast
		output wire [7:0]  axi4s_vid_out_1_tuser,  //                .tuser
		input  wire        vid_clock_clk,          //       vid_clock.clk,   Clock Input
		input  wire        vid_reset_reset         //       vid_reset.reset
	);

	mipi_broadcaster_0_intel_vvp_axi4s_broadcaster_2430_7vqeuzq #(
		.DEVICE_FAMILY          ("Agilex 3"),
		.BPS                    (10),
		.NUMBER_OF_COLOR_PLANES (1),
		.PIXELS_IN_PARALLEL     (4),
		.VVP_INTF_TYPE          ("Lite"),
		.OUT_0_TREADY           (1),
		.OUT_0_FIFO             (0),
		.OUT_0_FIFO_DEPTH       (1024),
		.OUT_1_TREADY           (1),
		.OUT_1_FIFO             (1),
		.OUT_1_FIFO_DEPTH       (4096),
		.OUT_2_TREADY           (1),
		.OUT_2_FIFO             (0),
		.OUT_2_FIFO_DEPTH       (1024),
		.OUT_3_TREADY           (1),
		.OUT_3_FIFO             (0),
		.OUT_3_FIFO_DEPTH       (1024),
		.OUT_4_TREADY           (1),
		.OUT_4_FIFO             (0),
		.OUT_4_FIFO_DEPTH       (1024),
		.OUT_5_TREADY           (1),
		.OUT_5_FIFO             (0),
		.OUT_5_FIFO_DEPTH       (1024),
		.OUT_6_TREADY           (1),
		.OUT_6_FIFO             (0),
		.OUT_6_FIFO_DEPTH       (1024),
		.OUT_7_TREADY           (1),
		.OUT_7_FIFO             (0),
		.OUT_7_FIFO_DEPTH       (1024),
		.OUT_8_TREADY           (1),
		.OUT_8_FIFO             (0),
		.OUT_8_FIFO_DEPTH       (1024),
		.OUT_9_TREADY           (1),
		.OUT_9_FIFO             (0),
		.OUT_9_FIFO_DEPTH       (1024),
		.OUT_10_TREADY          (1),
		.OUT_10_FIFO            (0),
		.OUT_10_FIFO_DEPTH      (1024),
		.OUT_11_TREADY          (1),
		.OUT_11_FIFO            (0),
		.OUT_11_FIFO_DEPTH      (1024),
		.OUT_12_TREADY          (1),
		.OUT_12_FIFO            (0),
		.OUT_12_FIFO_DEPTH      (1024),
		.OUT_13_TREADY          (1),
		.OUT_13_FIFO            (0),
		.OUT_13_FIFO_DEPTH      (1024),
		.OUT_14_TREADY          (1),
		.OUT_14_FIFO            (0),
		.OUT_14_FIFO_DEPTH      (1024),
		.OUT_15_TREADY          (1),
		.OUT_15_FIFO            (0),
		.OUT_15_FIFO_DEPTH      (1024),
		.OUT_16_TREADY          (1),
		.OUT_16_FIFO            (0),
		.OUT_16_FIFO_DEPTH      (1024),
		.OUT_17_TREADY          (1),
		.OUT_17_FIFO            (0),
		.OUT_17_FIFO_DEPTH      (1024),
		.OUT_18_TREADY          (1),
		.OUT_18_FIFO            (0),
		.OUT_18_FIFO_DEPTH      (1024),
		.OUT_19_TREADY          (1),
		.OUT_19_FIFO            (0),
		.OUT_19_FIFO_DEPTH      (1024),
		.OUT_20_TREADY          (1),
		.OUT_20_FIFO            (0),
		.OUT_20_FIFO_DEPTH      (1024),
		.OUT_21_TREADY          (1),
		.OUT_21_FIFO            (0),
		.OUT_21_FIFO_DEPTH      (1024),
		.OUT_22_TREADY          (1),
		.OUT_22_FIFO            (0),
		.OUT_22_FIFO_DEPTH      (1024),
		.OUT_23_TREADY          (1),
		.OUT_23_FIFO            (0),
		.OUT_23_FIFO_DEPTH      (1024),
		.OUT_24_TREADY          (1),
		.OUT_24_FIFO            (0),
		.OUT_24_FIFO_DEPTH      (1024),
		.OUT_25_TREADY          (1),
		.OUT_25_FIFO            (0),
		.OUT_25_FIFO_DEPTH      (1024),
		.OUT_26_TREADY          (1),
		.OUT_26_FIFO            (0),
		.OUT_26_FIFO_DEPTH      (1024),
		.OUT_27_TREADY          (1),
		.OUT_27_FIFO            (0),
		.OUT_27_FIFO_DEPTH      (1024),
		.OUT_28_TREADY          (1),
		.OUT_28_FIFO            (0),
		.OUT_28_FIFO_DEPTH      (1024),
		.OUT_29_TREADY          (1),
		.OUT_29_FIFO            (0),
		.OUT_29_FIFO_DEPTH      (1024),
		.OUT_30_TREADY          (1),
		.OUT_30_FIFO            (0),
		.OUT_30_FIFO_DEPTH      (1024),
		.OUT_31_TREADY          (1),
		.OUT_31_FIFO            (0),
		.OUT_31_FIFO_DEPTH      (1024),
		.OUTPUTS                (2),
		.IN_TREADY              (1),
		.GLOBAL_STALL           (0)
	) mipi_broadcaster_0 (
		.axi4s_vid_in_tdata     (axi4s_vid_in_tdata),     //   input,  width = 64,    axi4s_vid_in.tdata
		.axi4s_vid_in_tvalid    (axi4s_vid_in_tvalid),    //   input,   width = 1,                .tvalid
		.axi4s_vid_in_tready    (axi4s_vid_in_tready),    //  output,   width = 1,                .tready
		.axi4s_vid_in_tlast     (axi4s_vid_in_tlast),     //   input,   width = 1,                .tlast
		.axi4s_vid_in_tuser     (axi4s_vid_in_tuser),     //   input,   width = 8,                .tuser
		.axi4s_vid_out_0_tdata  (axi4s_vid_out_0_tdata),  //  output,  width = 64, axi4s_vid_out_0.tdata
		.axi4s_vid_out_0_tvalid (axi4s_vid_out_0_tvalid), //  output,   width = 1,                .tvalid
		.axi4s_vid_out_0_tready (axi4s_vid_out_0_tready), //   input,   width = 1,                .tready
		.axi4s_vid_out_0_tlast  (axi4s_vid_out_0_tlast),  //  output,   width = 1,                .tlast
		.axi4s_vid_out_0_tuser  (axi4s_vid_out_0_tuser),  //  output,   width = 8,                .tuser
		.axi4s_vid_out_1_tdata  (axi4s_vid_out_1_tdata),  //  output,  width = 64, axi4s_vid_out_1.tdata
		.axi4s_vid_out_1_tvalid (axi4s_vid_out_1_tvalid), //  output,   width = 1,                .tvalid
		.axi4s_vid_out_1_tready (axi4s_vid_out_1_tready), //   input,   width = 1,                .tready
		.axi4s_vid_out_1_tlast  (axi4s_vid_out_1_tlast),  //  output,   width = 1,                .tlast
		.axi4s_vid_out_1_tuser  (axi4s_vid_out_1_tuser),  //  output,   width = 8,                .tuser
		.vid_clock_clk          (vid_clock_clk),          //   input,   width = 1,       vid_clock.clk
		.vid_reset_reset        (vid_reset_reset)         //   input,   width = 1,       vid_reset.reset
	);

endmodule
