// vvp_1d_lut_0_intel_vvp_1d_lut_2450_oyu3gby.v

// This file was auto-generated from intel_vvp_1d_lut_hw.tcl.  If you edit it your changes
// will probably be lost.
// 
// Generated using ACDS version 25.3 109

`timescale 1 ps / 1 ps
module vvp_1d_lut_0_intel_vvp_1d_lut_2450_oyu3gby #(
		parameter EXTERNAL_MODE          = 1,
		parameter PIPELINE_READY         = 1,
		parameter MAX_WIDTH              = 4096,
		parameter MAX_HEIGHT             = 4096,
		parameter RUNTIME_CONTROL        = 1,
		parameter NUMBER_OF_COLOR_PLANES = 3,
		parameter PIXELS_IN_PARALLEL     = 4
	) (
		input  wire        main_clock_clk,                    //          main_clock.clk,          Clock Input
		input  wire        main_reset_reset,                  //          main_reset.reset
		input  wire [95:0] axi4s_vid_in_tdata,                //        axi4s_vid_in.tdata
		input  wire        axi4s_vid_in_tvalid,               //                    .tvalid
		output wire        axi4s_vid_in_tready,               //                    .tready
		input  wire        axi4s_vid_in_tlast,                //                    .tlast
		input  wire [11:0] axi4s_vid_in_tuser,                //                    .tuser
		output wire [95:0] axi4s_vid_out_tdata,               //       axi4s_vid_out.tdata
		output wire        axi4s_vid_out_tvalid,              //                    .tvalid
		input  wire        axi4s_vid_out_tready,              //                    .tready
		output wire        axi4s_vid_out_tlast,               //                    .tlast
		output wire [11:0] axi4s_vid_out_tuser,               //                    .tuser
		input  wire        agent_clock_clk,                   //         agent_clock.clk,          Clock Input
		input  wire        agent_reset_reset,                 //         agent_reset.reset
		input  wire [9:0]  av_mm_control_agent_address,       // av_mm_control_agent.address
		input  wire        av_mm_control_agent_write,         //                    .write
		input  wire [3:0]  av_mm_control_agent_byteenable,    //                    .byteenable
		input  wire [31:0] av_mm_control_agent_writedata,     //                    .writedata
		input  wire        av_mm_control_agent_read,          //                    .read
		output wire [31:0] av_mm_control_agent_readdata,      //                    .readdata
		output wire        av_mm_control_agent_readdatavalid, //                    .readdatavalid
		output wire        av_mm_control_agent_waitrequest    //                    .waitrequest
	);

	wire         main_rst_bridge_out_reset_reset;                          // main_rst_bridge:out_rst -> [algo_comp:rst, in_bridge:rst, mm_interconnect_0:slave_interface_av_mm_master_translator_reset_reset_bridge_in_reset_reset, mm_interconnect_1:slave_interface_av_mm_data_master_translator_reset_reset_bridge_in_reset_reset, out_bridge:rst, scheduler:rst, slave_interface:main_reset_reset]
	wire         in_bridge_axi_st_data_out_tvalid;                         // in_bridge:axi_st_data_out_tvalid -> algo_comp:axi_st_data_in_tvalid
	wire  [11:0] in_bridge_axi_st_data_out_tuser;                          // in_bridge:axi_st_data_out_tuser -> algo_comp:axi_st_data_in_tuser
	wire         in_bridge_axi_st_data_out_tready;                         // algo_comp:axi_st_data_in_tready -> in_bridge:axi_st_data_out_tready
	wire  [95:0] in_bridge_axi_st_data_out_tdata;                          // in_bridge:axi_st_data_out_tdata -> algo_comp:axi_st_data_in_tdata
	wire         in_bridge_axi_st_data_out_tlast;                          // in_bridge:axi_st_data_out_tlast -> algo_comp:axi_st_data_in_tlast
	wire         in_bridge_axi_st_ctrl_out_tvalid;                         // in_bridge:axi_st_ctrl_out_tvalid -> scheduler:axi_st_ctrl_in_tvalid
	wire   [1:0] in_bridge_axi_st_ctrl_out_tuser;                          // in_bridge:axi_st_ctrl_out_tuser -> scheduler:axi_st_ctrl_in_tuser
	wire         in_bridge_axi_st_ctrl_out_tready;                         // scheduler:axi_st_ctrl_in_tready -> in_bridge:axi_st_ctrl_out_tready
	wire  [15:0] in_bridge_axi_st_ctrl_out_tdata;                          // in_bridge:axi_st_ctrl_out_tdata -> scheduler:axi_st_ctrl_in_tdata
	wire         in_bridge_axi_st_ctrl_out_tlast;                          // in_bridge:axi_st_ctrl_out_tlast -> scheduler:axi_st_ctrl_in_tlast
	wire         scheduler_axi_st_ctrl_out_tvalid;                         // scheduler:axi_st_ctrl_out_tvalid -> out_bridge:axi_st_ctrl_in_tvalid
	wire   [1:0] scheduler_axi_st_ctrl_out_tuser;                          // scheduler:axi_st_ctrl_out_tuser -> out_bridge:axi_st_ctrl_in_tuser
	wire         scheduler_axi_st_ctrl_out_tready;                         // out_bridge:axi_st_ctrl_in_tready -> scheduler:axi_st_ctrl_out_tready
	wire  [15:0] scheduler_axi_st_ctrl_out_tdata;                          // scheduler:axi_st_ctrl_out_tdata -> out_bridge:axi_st_ctrl_in_tdata
	wire         scheduler_axi_st_ctrl_out_tlast;                          // scheduler:axi_st_ctrl_out_tlast -> out_bridge:axi_st_ctrl_in_tlast
	wire         scheduler_axi_st_alg_core_cmd_tvalid;                     // scheduler:axi_st_alg_core_cmd_tvalid -> algo_comp:axi_st_cmd_tvalid
	wire         scheduler_axi_st_alg_core_cmd_tready;                     // algo_comp:axi_st_cmd_tready -> scheduler:axi_st_alg_core_cmd_tready
	wire  [71:0] scheduler_axi_st_alg_core_cmd_tdata;                      // scheduler:axi_st_alg_core_cmd_tdata -> algo_comp:axi_st_cmd_tdata
	wire         algo_comp_axi_st_resp_tvalid;                             // algo_comp:axi_st_resp_tvalid -> scheduler:axi_st_alg_core_resp_tvalid
	wire         algo_comp_axi_st_resp_tready;                             // scheduler:axi_st_alg_core_resp_tready -> algo_comp:axi_st_resp_tready
	wire   [7:0] algo_comp_axi_st_resp_tdata;                              // algo_comp:axi_st_resp_tdata -> scheduler:axi_st_alg_core_resp_tdata
	wire         algo_comp_axi_st_data_out_tvalid;                         // algo_comp:axi_st_data_out_tvalid -> out_bridge:axi_st_data_in_tvalid
	wire  [11:0] algo_comp_axi_st_data_out_tuser;                          // algo_comp:axi_st_data_out_tuser -> out_bridge:axi_st_data_in_tuser
	wire         algo_comp_axi_st_data_out_tready;                         // out_bridge:axi_st_data_in_tready -> algo_comp:axi_st_data_out_tready
	wire  [95:0] algo_comp_axi_st_data_out_tdata;                          // algo_comp:axi_st_data_out_tdata -> out_bridge:axi_st_data_in_tdata
	wire         algo_comp_axi_st_data_out_tlast;                          // algo_comp:axi_st_data_out_tlast -> out_bridge:axi_st_data_in_tlast
	wire         slave_interface_av_mm_master_waitrequest;                 // mm_interconnect_0:slave_interface_av_mm_master_waitrequest -> slave_interface:av_mm_master_waitrequest
	wire  [31:0] slave_interface_av_mm_master_readdata;                    // mm_interconnect_0:slave_interface_av_mm_master_readdata -> slave_interface:av_mm_master_readdata
	wire   [7:0] slave_interface_av_mm_master_address;                     // slave_interface:av_mm_master_address -> mm_interconnect_0:slave_interface_av_mm_master_address
	wire   [3:0] slave_interface_av_mm_master_byteenable;                  // slave_interface:av_mm_master_byteenable -> mm_interconnect_0:slave_interface_av_mm_master_byteenable
	wire         slave_interface_av_mm_master_read;                        // slave_interface:av_mm_master_read -> mm_interconnect_0:slave_interface_av_mm_master_read
	wire         slave_interface_av_mm_master_readdatavalid;               // mm_interconnect_0:slave_interface_av_mm_master_readdatavalid -> slave_interface:av_mm_master_readdatavalid
	wire         slave_interface_av_mm_master_write;                       // slave_interface:av_mm_master_write -> mm_interconnect_0:slave_interface_av_mm_master_write
	wire  [31:0] slave_interface_av_mm_master_writedata;                   // slave_interface:av_mm_master_writedata -> mm_interconnect_0:slave_interface_av_mm_master_writedata
	wire  [31:0] mm_interconnect_0_scheduler_av_mm_slave_readdata;         // scheduler:av_mm_slave_readdata -> mm_interconnect_0:scheduler_av_mm_slave_readdata
	wire         mm_interconnect_0_scheduler_av_mm_slave_waitrequest;      // scheduler:av_mm_slave_waitrequest -> mm_interconnect_0:scheduler_av_mm_slave_waitrequest
	wire   [5:0] mm_interconnect_0_scheduler_av_mm_slave_address;          // mm_interconnect_0:scheduler_av_mm_slave_address -> scheduler:av_mm_slave_address
	wire         mm_interconnect_0_scheduler_av_mm_slave_read;             // mm_interconnect_0:scheduler_av_mm_slave_read -> scheduler:av_mm_slave_read
	wire   [3:0] mm_interconnect_0_scheduler_av_mm_slave_byteenable;       // mm_interconnect_0:scheduler_av_mm_slave_byteenable -> scheduler:av_mm_slave_byteenable
	wire         mm_interconnect_0_scheduler_av_mm_slave_readdatavalid;    // scheduler:av_mm_slave_readdatavalid -> mm_interconnect_0:scheduler_av_mm_slave_readdatavalid
	wire         mm_interconnect_0_scheduler_av_mm_slave_write;            // mm_interconnect_0:scheduler_av_mm_slave_write -> scheduler:av_mm_slave_write
	wire  [31:0] mm_interconnect_0_scheduler_av_mm_slave_writedata;        // mm_interconnect_0:scheduler_av_mm_slave_writedata -> scheduler:av_mm_slave_writedata
	wire         slave_interface_av_mm_data_master_waitrequest;            // mm_interconnect_1:slave_interface_av_mm_data_master_waitrequest -> slave_interface:av_mm_data_master_waitrequest
	wire  [11:0] slave_interface_av_mm_data_master_address;                // slave_interface:av_mm_data_master_address -> mm_interconnect_1:slave_interface_av_mm_data_master_address
	wire   [3:0] slave_interface_av_mm_data_master_byteenable;             // slave_interface:av_mm_data_master_byteenable -> mm_interconnect_1:slave_interface_av_mm_data_master_byteenable
	wire         slave_interface_av_mm_data_master_write;                  // slave_interface:av_mm_data_master_write -> mm_interconnect_1:slave_interface_av_mm_data_master_write
	wire  [31:0] slave_interface_av_mm_data_master_writedata;              // slave_interface:av_mm_data_master_writedata -> mm_interconnect_1:slave_interface_av_mm_data_master_writedata
	wire         mm_interconnect_1_algo_comp_av_mm_data_slave_waitrequest; // algo_comp:av_mm_data_slave_waitrequest -> mm_interconnect_1:algo_comp_av_mm_data_slave_waitrequest
	wire   [9:0] mm_interconnect_1_algo_comp_av_mm_data_slave_address;     // mm_interconnect_1:algo_comp_av_mm_data_slave_address -> algo_comp:av_mm_data_slave_address
	wire   [3:0] mm_interconnect_1_algo_comp_av_mm_data_slave_byteenable;  // mm_interconnect_1:algo_comp_av_mm_data_slave_byteenable -> algo_comp:av_mm_data_slave_byteenable
	wire         mm_interconnect_1_algo_comp_av_mm_data_slave_write;       // mm_interconnect_1:algo_comp_av_mm_data_slave_write -> algo_comp:av_mm_data_slave_write
	wire  [31:0] mm_interconnect_1_algo_comp_av_mm_data_slave_writedata;   // mm_interconnect_1:algo_comp_av_mm_data_slave_writedata -> algo_comp:av_mm_data_slave_writedata

	generate
		// If any of the display statements (or deliberately broken
		// instantiations) within this generate block triggers then this module
		// has been instantiated this module with a set of parameters different
		// from those it was generated for.  This will usually result in a
		// non-functioning system.
		if (EXTERNAL_MODE != 1)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					external_mode_check ( .error(1'b1) );
		end
		if (PIPELINE_READY != 1)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					pipeline_ready_check ( .error(1'b1) );
		end
		if (MAX_WIDTH != 4096)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					max_width_check ( .error(1'b1) );
		end
		if (MAX_HEIGHT != 4096)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					max_height_check ( .error(1'b1) );
		end
		if (RUNTIME_CONTROL != 1)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					runtime_control_check ( .error(1'b1) );
		end
		if (NUMBER_OF_COLOR_PLANES != 3)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					number_of_color_planes_check ( .error(1'b1) );
		end
		if (PIXELS_IN_PARALLEL != 4)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					pixels_in_parallel_check ( .error(1'b1) );
		end
	endgenerate

	intel_vvp_reset_sync #(
		.SYNC_LEN (3)
	) main_rst_bridge (
		.clk     (main_clock_clk),                  //   input,  width = 1,       clk.clk
		.in_rst  (main_reset_reset),                //   input,  width = 1,  in_reset.reset
		.out_rst (main_rst_bridge_out_reset_reset)  //  output,  width = 1, out_reset.reset
	);

	intel_vvp_input_interface_bridge #(
		.BPS                    (8),
		.NUMBER_OF_COLOR_PLANES (3),
		.PIXELS_IN_PARALLEL     (4),
		.PIPELINE_READY         (1),
		.EXTERNAL_MODE          (1)
	) in_bridge (
		.clk                    (main_clock_clk),                   //   input,   width = 1,      main_clock.clk
		.rst                    (main_rst_bridge_out_reset_reset),  //   input,   width = 1,      main_reset.reset
		.axi_st_ccd_in_tdata    (axi4s_vid_in_tdata),               //   input,  width = 96,   axi_st_ccd_in.tdata
		.axi_st_ccd_in_tvalid   (axi4s_vid_in_tvalid),              //   input,   width = 1,                .tvalid
		.axi_st_ccd_in_tready   (axi4s_vid_in_tready),              //  output,   width = 1,                .tready
		.axi_st_ccd_in_tlast    (axi4s_vid_in_tlast),               //   input,   width = 1,                .tlast
		.axi_st_ccd_in_tuser    (axi4s_vid_in_tuser),               //   input,  width = 12,                .tuser
		.axi_st_ctrl_out_tdata  (in_bridge_axi_st_ctrl_out_tdata),  //  output,  width = 16, axi_st_ctrl_out.tdata
		.axi_st_ctrl_out_tvalid (in_bridge_axi_st_ctrl_out_tvalid), //  output,   width = 1,                .tvalid
		.axi_st_ctrl_out_tready (in_bridge_axi_st_ctrl_out_tready), //   input,   width = 1,                .tready
		.axi_st_ctrl_out_tlast  (in_bridge_axi_st_ctrl_out_tlast),  //  output,   width = 1,                .tlast
		.axi_st_ctrl_out_tuser  (in_bridge_axi_st_ctrl_out_tuser),  //  output,   width = 2,                .tuser
		.axi_st_data_out_tdata  (in_bridge_axi_st_data_out_tdata),  //  output,  width = 96, axi_st_data_out.tdata
		.axi_st_data_out_tvalid (in_bridge_axi_st_data_out_tvalid), //  output,   width = 1,                .tvalid
		.axi_st_data_out_tready (in_bridge_axi_st_data_out_tready), //   input,   width = 1,                .tready
		.axi_st_data_out_tlast  (in_bridge_axi_st_data_out_tlast),  //  output,   width = 1,                .tlast
		.axi_st_data_out_tuser  (in_bridge_axi_st_data_out_tuser)   //  output,  width = 12,                .tuser
	);

	intel_vvp_output_interface_bridge #(
		.BPS                    (8),
		.NUMBER_OF_COLOR_PLANES (3),
		.PIXELS_IN_PARALLEL     (4),
		.PIPELINE_READY         (1),
		.EXTERNAL_MODE          (1)
	) out_bridge (
		.clk                   (main_clock_clk),                   //   input,   width = 1,     main_clock.clk
		.rst                   (main_rst_bridge_out_reset_reset),  //   input,   width = 1,     main_reset.reset
		.axi_st_ctrl_in_tdata  (scheduler_axi_st_ctrl_out_tdata),  //   input,  width = 16, axi_st_ctrl_in.tdata
		.axi_st_ctrl_in_tvalid (scheduler_axi_st_ctrl_out_tvalid), //   input,   width = 1,               .tvalid
		.axi_st_ctrl_in_tready (scheduler_axi_st_ctrl_out_tready), //  output,   width = 1,               .tready
		.axi_st_ctrl_in_tlast  (scheduler_axi_st_ctrl_out_tlast),  //   input,   width = 1,               .tlast
		.axi_st_ctrl_in_tuser  (scheduler_axi_st_ctrl_out_tuser),  //   input,   width = 2,               .tuser
		.axi_st_data_in_tdata  (algo_comp_axi_st_data_out_tdata),  //   input,  width = 96, axi_st_data_in.tdata
		.axi_st_data_in_tvalid (algo_comp_axi_st_data_out_tvalid), //   input,   width = 1,               .tvalid
		.axi_st_data_in_tready (algo_comp_axi_st_data_out_tready), //  output,   width = 1,               .tready
		.axi_st_data_in_tlast  (algo_comp_axi_st_data_out_tlast),  //   input,   width = 1,               .tlast
		.axi_st_data_in_tuser  (algo_comp_axi_st_data_out_tuser),  //   input,  width = 12,               .tuser
		.axi_st_ccd_out_tdata  (axi4s_vid_out_tdata),              //  output,  width = 96, axi_st_ccd_out.tdata
		.axi_st_ccd_out_tvalid (axi4s_vid_out_tvalid),             //  output,   width = 1,               .tvalid
		.axi_st_ccd_out_tready (axi4s_vid_out_tready),             //   input,   width = 1,               .tready
		.axi_st_ccd_out_tlast  (axi4s_vid_out_tlast),              //  output,   width = 1,               .tlast
		.axi_st_ccd_out_tuser  (axi4s_vid_out_tuser)               //  output,  width = 12,               .tuser
	);

	intel_vvp_1d_lut_scheduler #(
		.EXTERNAL_MODE          (1),
		.MAX_WIDTH              (4096),
		.NO_BLANKING            (1),
		.V_TAPS                 (1),
		.RUNTIME_CONTROL        (1),
		.ENABLE_DEBUG           (1),
		.P_UPDATE_CMD_SUPPORTED (0),
		.P_CORE_CTRL_ID         (0),
		.PIPELINE_READY         (1),
		.SLAVE_ADDRESS_WIDTH    (6)
	) scheduler (
		.clk                         (main_clock_clk),                                        //   input,   width = 1,           main_clock.clk
		.rst                         (main_rst_bridge_out_reset_reset),                       //   input,   width = 1,           main_reset.reset
		.axi_st_ctrl_in_tdata        (in_bridge_axi_st_ctrl_out_tdata),                       //   input,  width = 16,       axi_st_ctrl_in.tdata
		.axi_st_ctrl_in_tvalid       (in_bridge_axi_st_ctrl_out_tvalid),                      //   input,   width = 1,                     .tvalid
		.axi_st_ctrl_in_tready       (in_bridge_axi_st_ctrl_out_tready),                      //  output,   width = 1,                     .tready
		.axi_st_ctrl_in_tlast        (in_bridge_axi_st_ctrl_out_tlast),                       //   input,   width = 1,                     .tlast
		.axi_st_ctrl_in_tuser        (in_bridge_axi_st_ctrl_out_tuser),                       //   input,   width = 2,                     .tuser
		.axi_st_ctrl_out_tdata       (scheduler_axi_st_ctrl_out_tdata),                       //  output,  width = 16,      axi_st_ctrl_out.tdata
		.axi_st_ctrl_out_tvalid      (scheduler_axi_st_ctrl_out_tvalid),                      //  output,   width = 1,                     .tvalid
		.axi_st_ctrl_out_tready      (scheduler_axi_st_ctrl_out_tready),                      //   input,   width = 1,                     .tready
		.axi_st_ctrl_out_tlast       (scheduler_axi_st_ctrl_out_tlast),                       //  output,   width = 1,                     .tlast
		.axi_st_ctrl_out_tuser       (scheduler_axi_st_ctrl_out_tuser),                       //  output,   width = 2,                     .tuser
		.axi_st_alg_core_resp_tdata  (algo_comp_axi_st_resp_tdata),                           //   input,   width = 8, axi_st_alg_core_resp.tdata
		.axi_st_alg_core_resp_tvalid (algo_comp_axi_st_resp_tvalid),                          //   input,   width = 1,                     .tvalid
		.axi_st_alg_core_resp_tready (algo_comp_axi_st_resp_tready),                          //  output,   width = 1,                     .tready
		.axi_st_alg_core_cmd_tdata   (scheduler_axi_st_alg_core_cmd_tdata),                   //  output,  width = 72,  axi_st_alg_core_cmd.tdata
		.axi_st_alg_core_cmd_tvalid  (scheduler_axi_st_alg_core_cmd_tvalid),                  //  output,   width = 1,                     .tvalid
		.axi_st_alg_core_cmd_tready  (scheduler_axi_st_alg_core_cmd_tready),                  //   input,   width = 1,                     .tready
		.av_mm_slave_address         (mm_interconnect_0_scheduler_av_mm_slave_address),       //   input,   width = 6,          av_mm_slave.address
		.av_mm_slave_write           (mm_interconnect_0_scheduler_av_mm_slave_write),         //   input,   width = 1,                     .write
		.av_mm_slave_byteenable      (mm_interconnect_0_scheduler_av_mm_slave_byteenable),    //   input,   width = 4,                     .byteenable
		.av_mm_slave_writedata       (mm_interconnect_0_scheduler_av_mm_slave_writedata),     //   input,  width = 32,                     .writedata
		.av_mm_slave_read            (mm_interconnect_0_scheduler_av_mm_slave_read),          //   input,   width = 1,                     .read
		.av_mm_slave_readdata        (mm_interconnect_0_scheduler_av_mm_slave_readdata),      //  output,  width = 32,                     .readdata
		.av_mm_slave_readdatavalid   (mm_interconnect_0_scheduler_av_mm_slave_readdatavalid), //  output,   width = 1,                     .readdatavalid
		.av_mm_slave_waitrequest     (mm_interconnect_0_scheduler_av_mm_slave_waitrequest),   //  output,   width = 1,                     .waitrequest
		.axi_st_lb_resp_tdata        (8'b00000000),                                           // (terminated),                                   
		.axi_st_lb_resp_tvalid       (1'b0),                                                  // (terminated),                                   
		.axi_st_lb_resp_tready       (),                                                      // (terminated),                                   
		.axi_st_lb_cmd_tdata         (),                                                      // (terminated),                                   
		.axi_st_lb_cmd_tvalid        (),                                                      // (terminated),                                   
		.axi_st_lb_cmd_tready        (1'b0)                                                   // (terminated),                                   
	);

	vvp_1d_lut_0_intel_vvp_1d_lut_algo_comp_2450_3h7a4ca algo_comp (
		.clk                            (main_clock_clk),                                           //   input,   width = 1,       main_clock.clk
		.rst                            (main_rst_bridge_out_reset_reset),                          //   input,   width = 1,       main_reset.reset
		.axi_st_cmd_tdata               (scheduler_axi_st_alg_core_cmd_tdata),                      //   input,  width = 72,       axi_st_cmd.tdata
		.axi_st_cmd_tvalid              (scheduler_axi_st_alg_core_cmd_tvalid),                     //   input,   width = 1,                 .tvalid
		.axi_st_cmd_tready              (scheduler_axi_st_alg_core_cmd_tready),                     //  output,   width = 1,                 .tready
		.axi_st_resp_tdata              (algo_comp_axi_st_resp_tdata),                              //  output,   width = 8,      axi_st_resp.tdata
		.axi_st_resp_tvalid             (algo_comp_axi_st_resp_tvalid),                             //  output,   width = 1,                 .tvalid
		.axi_st_resp_tready             (algo_comp_axi_st_resp_tready),                             //   input,   width = 1,                 .tready
		.axi_st_data_in_tdata           (in_bridge_axi_st_data_out_tdata),                          //   input,  width = 96,   axi_st_data_in.tdata
		.axi_st_data_in_tvalid          (in_bridge_axi_st_data_out_tvalid),                         //   input,   width = 1,                 .tvalid
		.axi_st_data_in_tready          (in_bridge_axi_st_data_out_tready),                         //  output,   width = 1,                 .tready
		.axi_st_data_in_tlast           (in_bridge_axi_st_data_out_tlast),                          //   input,   width = 1,                 .tlast
		.axi_st_data_in_tuser           (in_bridge_axi_st_data_out_tuser),                          //   input,  width = 12,                 .tuser
		.axi_st_data_out_tdata          (algo_comp_axi_st_data_out_tdata),                          //  output,  width = 96,  axi_st_data_out.tdata
		.axi_st_data_out_tvalid         (algo_comp_axi_st_data_out_tvalid),                         //  output,   width = 1,                 .tvalid
		.axi_st_data_out_tready         (algo_comp_axi_st_data_out_tready),                         //   input,   width = 1,                 .tready
		.axi_st_data_out_tlast          (algo_comp_axi_st_data_out_tlast),                          //  output,   width = 1,                 .tlast
		.axi_st_data_out_tuser          (algo_comp_axi_st_data_out_tuser),                          //  output,  width = 12,                 .tuser
		.av_mm_data_slave_address       (mm_interconnect_1_algo_comp_av_mm_data_slave_address),     //   input,  width = 10, av_mm_data_slave.address
		.av_mm_data_slave_write         (mm_interconnect_1_algo_comp_av_mm_data_slave_write),       //   input,   width = 1,                 .write
		.av_mm_data_slave_byteenable    (mm_interconnect_1_algo_comp_av_mm_data_slave_byteenable),  //   input,   width = 4,                 .byteenable
		.av_mm_data_slave_writedata     (mm_interconnect_1_algo_comp_av_mm_data_slave_writedata),   //   input,  width = 32,                 .writedata
		.av_mm_data_slave_waitrequest   (mm_interconnect_1_algo_comp_av_mm_data_slave_waitrequest), //  output,   width = 1,                 .waitrequest
		.av_mm_data_slave_read          (1'b0),                                                     // (terminated),                               
		.av_mm_data_slave_readdata      (),                                                         // (terminated),                               
		.av_mm_data_slave_readdatavalid ()                                                          // (terminated),                               
	);

	vvp_1d_lut_0_intel_vvp_slave_front_end_2450_v2jnpvy #(
		.AV_MAX_PENDING_READS (8)
	) slave_interface (
		.main_clock_clk                (main_clock_clk),                                //   input,   width = 1,        main_clock.clk
		.main_reset_reset              (main_rst_bridge_out_reset_reset),               //   input,   width = 1,        main_reset.reset
		.slave_clock_clk               (agent_clock_clk),                               //   input,   width = 1,       slave_clock.clk
		.slave_reset_reset             (agent_reset_reset),                             //   input,   width = 1,       slave_reset.reset
		.av_mm_master_address          (slave_interface_av_mm_master_address),          //  output,   width = 8,      av_mm_master.address
		.av_mm_master_waitrequest      (slave_interface_av_mm_master_waitrequest),      //   input,   width = 1,                  .waitrequest
		.av_mm_master_write            (slave_interface_av_mm_master_write),            //  output,   width = 1,                  .write
		.av_mm_master_writedata        (slave_interface_av_mm_master_writedata),        //  output,  width = 32,                  .writedata
		.av_mm_master_byteenable       (slave_interface_av_mm_master_byteenable),       //  output,   width = 4,                  .byteenable
		.av_mm_master_read             (slave_interface_av_mm_master_read),             //  output,   width = 1,                  .read
		.av_mm_master_readdata         (slave_interface_av_mm_master_readdata),         //   input,  width = 32,                  .readdata
		.av_mm_master_readdatavalid    (slave_interface_av_mm_master_readdatavalid),    //   input,   width = 1,                  .readdatavalid
		.av_mm_data_master_address     (slave_interface_av_mm_data_master_address),     //  output,  width = 12, av_mm_data_master.address
		.av_mm_data_master_waitrequest (slave_interface_av_mm_data_master_waitrequest), //   input,   width = 1,                  .waitrequest
		.av_mm_data_master_write       (slave_interface_av_mm_data_master_write),       //  output,   width = 1,                  .write
		.av_mm_data_master_writedata   (slave_interface_av_mm_data_master_writedata),   //  output,  width = 32,                  .writedata
		.av_mm_data_master_byteenable  (slave_interface_av_mm_data_master_byteenable),  //  output,   width = 4,                  .byteenable
		.av_mm_slave_address           (av_mm_control_agent_address),                   //   input,  width = 10,       av_mm_slave.address
		.av_mm_slave_write             (av_mm_control_agent_write),                     //   input,   width = 1,                  .write
		.av_mm_slave_byteenable        (av_mm_control_agent_byteenable),                //   input,   width = 4,                  .byteenable
		.av_mm_slave_writedata         (av_mm_control_agent_writedata),                 //   input,  width = 32,                  .writedata
		.av_mm_slave_read              (av_mm_control_agent_read),                      //   input,   width = 1,                  .read
		.av_mm_slave_readdata          (av_mm_control_agent_readdata),                  //  output,  width = 32,                  .readdata
		.av_mm_slave_readdatavalid     (av_mm_control_agent_readdatavalid),             //  output,   width = 1,                  .readdatavalid
		.av_mm_slave_waitrequest       (av_mm_control_agent_waitrequest)                //  output,   width = 1,                  .waitrequest
	);

	vvp_1d_lut_0_altera_mm_interconnect_1920_p6rpahq mm_interconnect_0 (
		.slave_interface_av_mm_master_address                                      (slave_interface_av_mm_master_address),                  //   input,   width = 8,                                        slave_interface_av_mm_master.address
		.slave_interface_av_mm_master_waitrequest                                  (slave_interface_av_mm_master_waitrequest),              //  output,   width = 1,                                                                    .waitrequest
		.slave_interface_av_mm_master_byteenable                                   (slave_interface_av_mm_master_byteenable),               //   input,   width = 4,                                                                    .byteenable
		.slave_interface_av_mm_master_read                                         (slave_interface_av_mm_master_read),                     //   input,   width = 1,                                                                    .read
		.slave_interface_av_mm_master_readdata                                     (slave_interface_av_mm_master_readdata),                 //  output,  width = 32,                                                                    .readdata
		.slave_interface_av_mm_master_readdatavalid                                (slave_interface_av_mm_master_readdatavalid),            //  output,   width = 1,                                                                    .readdatavalid
		.slave_interface_av_mm_master_write                                        (slave_interface_av_mm_master_write),                    //   input,   width = 1,                                                                    .write
		.slave_interface_av_mm_master_writedata                                    (slave_interface_av_mm_master_writedata),                //   input,  width = 32,                                                                    .writedata
		.scheduler_av_mm_slave_address                                             (mm_interconnect_0_scheduler_av_mm_slave_address),       //  output,   width = 6,                                               scheduler_av_mm_slave.address
		.scheduler_av_mm_slave_write                                               (mm_interconnect_0_scheduler_av_mm_slave_write),         //  output,   width = 1,                                                                    .write
		.scheduler_av_mm_slave_read                                                (mm_interconnect_0_scheduler_av_mm_slave_read),          //  output,   width = 1,                                                                    .read
		.scheduler_av_mm_slave_readdata                                            (mm_interconnect_0_scheduler_av_mm_slave_readdata),      //   input,  width = 32,                                                                    .readdata
		.scheduler_av_mm_slave_writedata                                           (mm_interconnect_0_scheduler_av_mm_slave_writedata),     //  output,  width = 32,                                                                    .writedata
		.scheduler_av_mm_slave_byteenable                                          (mm_interconnect_0_scheduler_av_mm_slave_byteenable),    //  output,   width = 4,                                                                    .byteenable
		.scheduler_av_mm_slave_readdatavalid                                       (mm_interconnect_0_scheduler_av_mm_slave_readdatavalid), //   input,   width = 1,                                                                    .readdatavalid
		.scheduler_av_mm_slave_waitrequest                                         (mm_interconnect_0_scheduler_av_mm_slave_waitrequest),   //   input,   width = 1,                                                                    .waitrequest
		.slave_interface_av_mm_master_translator_reset_reset_bridge_in_reset_reset (main_rst_bridge_out_reset_reset),                       //   input,   width = 1, slave_interface_av_mm_master_translator_reset_reset_bridge_in_reset.reset
		.main_clk_bridge_out_clk_clk                                               (main_clock_clk)                                         //   input,   width = 1,                                             main_clk_bridge_out_clk.clk
	);

	vvp_1d_lut_0_altera_mm_interconnect_1920_4o3ihky mm_interconnect_1 (
		.slave_interface_av_mm_data_master_address                                      (slave_interface_av_mm_data_master_address),                //   input,  width = 12,                                        slave_interface_av_mm_data_master.address
		.slave_interface_av_mm_data_master_waitrequest                                  (slave_interface_av_mm_data_master_waitrequest),            //  output,   width = 1,                                                                         .waitrequest
		.slave_interface_av_mm_data_master_byteenable                                   (slave_interface_av_mm_data_master_byteenable),             //   input,   width = 4,                                                                         .byteenable
		.slave_interface_av_mm_data_master_write                                        (slave_interface_av_mm_data_master_write),                  //   input,   width = 1,                                                                         .write
		.slave_interface_av_mm_data_master_writedata                                    (slave_interface_av_mm_data_master_writedata),              //   input,  width = 32,                                                                         .writedata
		.algo_comp_av_mm_data_slave_address                                             (mm_interconnect_1_algo_comp_av_mm_data_slave_address),     //  output,  width = 10,                                               algo_comp_av_mm_data_slave.address
		.algo_comp_av_mm_data_slave_write                                               (mm_interconnect_1_algo_comp_av_mm_data_slave_write),       //  output,   width = 1,                                                                         .write
		.algo_comp_av_mm_data_slave_writedata                                           (mm_interconnect_1_algo_comp_av_mm_data_slave_writedata),   //  output,  width = 32,                                                                         .writedata
		.algo_comp_av_mm_data_slave_byteenable                                          (mm_interconnect_1_algo_comp_av_mm_data_slave_byteenable),  //  output,   width = 4,                                                                         .byteenable
		.algo_comp_av_mm_data_slave_waitrequest                                         (mm_interconnect_1_algo_comp_av_mm_data_slave_waitrequest), //   input,   width = 1,                                                                         .waitrequest
		.slave_interface_av_mm_data_master_translator_reset_reset_bridge_in_reset_reset (main_rst_bridge_out_reset_reset),                          //   input,   width = 1, slave_interface_av_mm_data_master_translator_reset_reset_bridge_in_reset.reset
		.main_clk_bridge_out_clk_clk                                                    (main_clock_clk)                                            //   input,   width = 1,                                                  main_clk_bridge_out_clk.clk
	);

endmodule
