// interrupt_reader_interface_0.v

// Generated using ACDS version 25.3 109

`timescale 1 ps / 1 ps
module interrupt_reader_interface_0 (
		input  wire        clk,               //       clk.clk
		input  wire        reset,             //     reset.reset
		output wire [31:0] avm_address,       //    master.address
		output wire        avm_read,          //          .read
		input  wire [31:0] avm_readdata,      //          .readdata
		input  wire        avm_waitrequest,   //          .waitrequest
		input  wire        avm_readdatavalid, //          .readdatavalid
		input  wire        irq,               //       irq.irq
		output wire [31:0] result_data,       //    result.result_data
		output wire        result_valid,      //          .result_valid
		output wire [31:0] cycle_count,       // cycle_cnt.cycle_count
		output wire        cycle_count_valid, //          .cycle_count_valid
		output wire        error_timeout,     //     error.error_timeout
		input  wire        error_clear        //          .error_clear
	);

	interrupt_reader_interface interrupt_reader_interface_0 (
		.clk               (clk),               //   input,   width = 1,       clk.clk
		.reset             (reset),             //   input,   width = 1,     reset.reset
		.avm_address       (avm_address),       //  output,  width = 32,    master.address
		.avm_read          (avm_read),          //  output,   width = 1,          .read
		.avm_readdata      (avm_readdata),      //   input,  width = 32,          .readdata
		.avm_waitrequest   (avm_waitrequest),   //   input,   width = 1,          .waitrequest
		.avm_readdatavalid (avm_readdatavalid), //   input,   width = 1,          .readdatavalid
		.irq               (irq),               //   input,   width = 1,       irq.irq
		.result_data       (result_data),       //  output,  width = 32,    result.result_data
		.result_valid      (result_valid),      //  output,   width = 1,          .result_valid
		.cycle_count       (cycle_count),       //  output,  width = 32, cycle_cnt.cycle_count
		.cycle_count_valid (cycle_count_valid), //  output,   width = 1,          .cycle_count_valid
		.error_timeout     (error_timeout),     //  output,   width = 1,     error.error_timeout
		.error_clear       (error_clear)        //   input,   width = 1,          .error_clear
	);

endmodule
