// csi2_dphy_sys.v

// Generated using ACDS version 25.3 109

`timescale 1 ps / 1 ps
module csi2_dphy_sys (
		output wire        csi2_rx_o_d0_ppi_rx_err_ErrSotHS,                  //                       csi2_rx_o_d0_ppi_rx_err.ErrSotHS
		output wire        csi2_rx_o_d0_ppi_rx_err_ErrSotSyncHS,              //                                              .ErrSotSyncHS
		output wire        csi2_rx_o_d0_ppi_rx_err_ErrEsc,                    //                                              .ErrEsc
		output wire        csi2_rx_o_d0_ppi_rx_err_ErrSyncEsc,                //                                              .ErrSyncEsc
		output wire        csi2_rx_o_d0_ppi_rx_err_ErrControl,                //                                              .ErrControl
		output wire        csi2_rx_o_d0_ppi_rx_err_ErrContentionLP0,          //                                              .ErrContentionLP0
		output wire        csi2_rx_o_d0_ppi_rx_err_ErrContentionLP1,          //                                              .ErrContentionLP1
		output wire        csi2_rx_o_d1_ppi_rx_err_ErrSotHS,                  //                       csi2_rx_o_d1_ppi_rx_err.ErrSotHS
		output wire        csi2_rx_o_d1_ppi_rx_err_ErrSotSyncHS,              //                                              .ErrSotSyncHS
		output wire        csi2_rx_o_d1_ppi_rx_err_ErrEsc,                    //                                              .ErrEsc
		output wire        csi2_rx_o_d1_ppi_rx_err_ErrSyncEsc,                //                                              .ErrSyncEsc
		output wire        csi2_rx_o_d1_ppi_rx_err_ErrControl,                //                                              .ErrControl
		output wire        csi2_rx_o_d1_ppi_rx_err_ErrContentionLP0,          //                                              .ErrContentionLP0
		output wire        csi2_rx_o_d1_ppi_rx_err_ErrContentionLP1,          //                                              .ErrContentionLP1
		output wire        csi2_rx_o_ck_ppi_rx_err_ErrSotHS,                  //                       csi2_rx_o_ck_ppi_rx_err.ErrSotHS
		output wire        csi2_rx_o_ck_ppi_rx_err_ErrSotSyncHS,              //                                              .ErrSotSyncHS
		output wire        csi2_rx_o_ck_ppi_rx_err_ErrEsc,                    //                                              .ErrEsc
		output wire        csi2_rx_o_ck_ppi_rx_err_ErrSyncEsc,                //                                              .ErrSyncEsc
		output wire        csi2_rx_o_ck_ppi_rx_err_ErrControl,                //                                              .ErrControl
		output wire        csi2_rx_o_ck_ppi_rx_err_ErrContentionLP0,          //                                              .ErrContentionLP0
		output wire        csi2_rx_o_ck_ppi_rx_err_ErrContentionLP1,          //                                              .ErrContentionLP1
		output wire [63:0] csi2_rx_video_streaming_interface_0_tdata,         //           csi2_rx_video_streaming_interface_0.tdata
		output wire        csi2_rx_video_streaming_interface_0_tvalid,        //                                              .tvalid
		input  wire        csi2_rx_video_streaming_interface_0_tready,        //                                              .tready
		output wire        csi2_rx_video_streaming_interface_0_tlast,         //                                              .tlast
		output wire [7:0]  csi2_rx_video_streaming_interface_0_tuser,         //                                              .tuser
		input  wire        csi2_rx_avalon_mm_control_interface_write,         //           csi2_rx_avalon_mm_control_interface.write
		input  wire        csi2_rx_avalon_mm_control_interface_read,          //                                              .read
		input  wire [9:0]  csi2_rx_avalon_mm_control_interface_address,       //                                              .address
		input  wire [31:0] csi2_rx_avalon_mm_control_interface_writedata,     //                                              .writedata
		output wire [31:0] csi2_rx_avalon_mm_control_interface_readdata,      //                                              .readdata
		output wire        csi2_rx_avalon_mm_control_interface_readdatavalid, //                                              .readdatavalid
		output wire        csi2_rx_avalon_mm_control_interface_waitrequest,   //                                              .waitrequest
		input  wire [3:0]  csi2_rx_avalon_mm_control_interface_byteenable,    //                                              .byteenable
		output wire        csi2_rx_avalon_mm_control_interface_interrupt_irq, // csi2_rx_avalon_mm_control_interface_interrupt.irq
		input  wire        mipi_dphy_rzq_rzq,                                 //                                 mipi_dphy_rzq.rzq
		input  wire        mipi_dphy_ref_clk_0_clk,                           //                           mipi_dphy_ref_clk_0.clk
		output wire        mipi_dphy_LINK0_link_core_srst_reset_n,            //                mipi_dphy_LINK0_link_core_srst.reset_n
		output wire        mipi_dphy_LINK0_link_core_arst_reset_n,            //                mipi_dphy_LINK0_link_core_arst.reset_n
		input  wire [11:0] mipi_dphy_axi_lite_awaddr,                         //                            mipi_dphy_axi_lite.awaddr
		input  wire        mipi_dphy_axi_lite_awvalid,                        //                                              .awvalid
		output wire        mipi_dphy_axi_lite_awready,                        //                                              .awready
		input  wire [31:0] mipi_dphy_axi_lite_wdata,                          //                                              .wdata
		input  wire [3:0]  mipi_dphy_axi_lite_wstrb,                          //                                              .wstrb
		input  wire        mipi_dphy_axi_lite_wvalid,                         //                                              .wvalid
		output wire        mipi_dphy_axi_lite_wready,                         //                                              .wready
		output wire [1:0]  mipi_dphy_axi_lite_bresp,                          //                                              .bresp
		output wire        mipi_dphy_axi_lite_bvalid,                         //                                              .bvalid
		input  wire        mipi_dphy_axi_lite_bready,                         //                                              .bready
		input  wire [11:0] mipi_dphy_axi_lite_araddr,                         //                                              .araddr
		input  wire        mipi_dphy_axi_lite_arvalid,                        //                                              .arvalid
		output wire        mipi_dphy_axi_lite_arready,                        //                                              .arready
		output wire [31:0] mipi_dphy_axi_lite_rdata,                          //                                              .rdata
		output wire [1:0]  mipi_dphy_axi_lite_rresp,                          //                                              .rresp
		output wire        mipi_dphy_axi_lite_rvalid,                         //                                              .rvalid
		input  wire        mipi_dphy_axi_lite_rready,                         //                                              .rready
		input  wire [2:0]  mipi_dphy_axi_lite_arprot,                         //                                              .arprot
		input  wire [2:0]  mipi_dphy_axi_lite_awprot,                         //                                              .awprot
		input  wire [1:0]  mipi_dphy_LINK0_dphy_io_dphy_link_dp,              //                       mipi_dphy_LINK0_dphy_io.dphy_link_dp
		input  wire [1:0]  mipi_dphy_LINK0_dphy_io_dphy_link_dn,              //                                              .dphy_link_dn
		input  wire        mipi_dphy_LINK0_dphy_io_dphy_link_cp,              //                                              .dphy_link_cp
		input  wire        mipi_dphy_LINK0_dphy_io_dphy_link_cn,              //                                              .dphy_link_cn
		output wire        mipi_dphy_reg_bus_reg_wr_en_o,                     //                             mipi_dphy_reg_bus.reg_wr_en_o
		output wire        mipi_dphy_reg_bus_reg_rd_en_o,                     //                                              .reg_rd_en_o
		output wire [10:0] mipi_dphy_reg_bus_reg_raddr_o,                     //                                              .reg_raddr_o
		output wire [10:0] mipi_dphy_reg_bus_reg_waddr_o,                     //                                              .reg_waddr_o
		output wire [3:0]  mipi_dphy_reg_bus_reg_be_o,                        //                                              .reg_be_o
		output wire [31:0] mipi_dphy_reg_bus_reg_din_o,                       //                                              .reg_din_o
		input  wire [31:0] mipi_dphy_reg_bus_reg_dout_i,                      //                                              .reg_dout_i
		input  wire        rx_axi4s_clk_bridge_in_clk_clk                     //                    rx_axi4s_clk_bridge_in_clk.clk
	);

	wire         mipi_dphy_link0_ck_ppi_rx_hs_clk_clk;           // mipi_dphy:LINK0_CK_RxWordClkHS -> csi2_rx:rx_word_clk_hs_ck
	wire         mipi_dphy_link0_d0_ppi_rx_hs_clk_clk;           // mipi_dphy:LINK0_D0_RxWordClkHS -> csi2_rx:rx_word_clk_hs_d0
	wire         mipi_dphy_link0_d1_ppi_rx_hs_clk_clk;           // mipi_dphy:LINK0_D1_RxWordClkHS -> csi2_rx:rx_word_clk_hs_d1
	wire         mipi_dphy_link0_link_core_clk_clk;              // mipi_dphy:LINK0_link_core_clk -> [mipi_dphy:axil_clk, rst_controller_001:clk]
	wire         rx_axi4s_clk_bridge_out_clk_clk;                // rx_axi4s_clk_bridge:out_clk -> [csi2_rx:axi4s_clk, rst_controller:clk]
	wire         csi2_rx_ck_ppi_ctrl_turndisable;                // csi2_rx:turn_disable_ck -> mipi_dphy:LINK0_CK_TurnDisable
	wire         csi2_rx_ck_ppi_ctrl_alpmode;                    // csi2_rx:alp_mode_ck -> mipi_dphy:LINK0_CK_AlpMode
	wire         csi2_rx_ck_ppi_ctrl_forcerxmode;                // csi2_rx:force_rx_mode_ck -> mipi_dphy:LINK0_CK_ForceRxmode
	wire         csi2_rx_ck_ppi_ctrl_forcetxstopmode;            // csi2_rx:force_tx_stop_mode_ck -> mipi_dphy:LINK0_CK_ForceTxStopmode
	wire         mipi_dphy_link0_ck_ppi_ctrl_direction;          // mipi_dphy:LINK0_CK_Direction -> csi2_rx:direction_ck
	wire         csi2_rx_ck_ppi_ctrl_turnrequest;                // csi2_rx:turn_request_ck -> mipi_dphy:LINK0_CK_TurnRequest
	wire         mipi_dphy_link0_ck_ppi_ctrl_ulpsactivenot;      // mipi_dphy:LINK0_CK_UlpsActiveNot -> csi2_rx:ulps_active_not_ck
	wire         mipi_dphy_link0_ck_ppi_ctrl_rxulpsclknot;       // mipi_dphy:LINK0_CK_RxUlpsClkNot -> csi2_rx:rx_ulps_clk_not_ck
	wire         csi2_rx_ck_ppi_ctrl_txhsidleclkhs;              // csi2_rx:tx_hsidle_clk_hs_ck -> mipi_dphy:LINK0_CK_TxHSIdleClkHS
	wire         csi2_rx_ck_ppi_ctrl_enable;                     // csi2_rx:enable_ck -> mipi_dphy:LINK0_CK_Enable
	wire         mipi_dphy_link0_ck_ppi_ctrl_stopstate;          // mipi_dphy:LINK0_CK_Stopstate -> csi2_rx:stop_state_ck
	wire         csi2_rx_ck_ppi_ctrl_txulpsclk;                  // csi2_rx:tx_ulps_clk_ck -> mipi_dphy:LINK0_CK_TxUlpsClk
	wire         mipi_dphy_link0_ck_ppi_ctrl_txhsidleclkreadyhs; // mipi_dphy:LINK0_CK_TxHSIdleClkReadyHS -> csi2_rx:tx_hsidle_clk_ready_hs_ck
	wire         csi2_rx_d0_ppi_ctrl_turndisable;                // csi2_rx:turn_disable_d0 -> mipi_dphy:LINK0_D0_TurnDisable
	wire         csi2_rx_d0_ppi_ctrl_alpmode;                    // csi2_rx:alp_mode_d0 -> mipi_dphy:LINK0_D0_AlpMode
	wire         csi2_rx_d0_ppi_ctrl_forcerxmode;                // csi2_rx:force_rx_mode_d0 -> mipi_dphy:LINK0_D0_ForceRxmode
	wire         csi2_rx_d0_ppi_ctrl_forcetxstopmode;            // csi2_rx:force_tx_stop_mode_d0 -> mipi_dphy:LINK0_D0_ForceTxStopmode
	wire         mipi_dphy_link0_d0_ppi_ctrl_direction;          // mipi_dphy:LINK0_D0_Direction -> csi2_rx:direction_d0
	wire         csi2_rx_d0_ppi_ctrl_turnrequest;                // csi2_rx:turn_request_d0 -> mipi_dphy:LINK0_D0_TurnRequest
	wire         mipi_dphy_link0_d0_ppi_ctrl_ulpsactivenot;      // mipi_dphy:LINK0_D0_UlpsActiveNot -> csi2_rx:ulps_active_not_d0
	wire         mipi_dphy_link0_d0_ppi_ctrl_rxulpsclknot;       // mipi_dphy:LINK0_D0_RxUlpsClkNot -> csi2_rx:rx_ulps_clk_not_d0
	wire         csi2_rx_d0_ppi_ctrl_txhsidleclkhs;              // csi2_rx:tx_hsidle_clk_hs_d0 -> mipi_dphy:LINK0_D0_TxHSIdleClkHS
	wire         csi2_rx_d0_ppi_ctrl_enable;                     // csi2_rx:enable_d0 -> mipi_dphy:LINK0_D0_Enable
	wire         mipi_dphy_link0_d0_ppi_ctrl_stopstate;          // mipi_dphy:LINK0_D0_Stopstate -> csi2_rx:stop_state_d0
	wire         csi2_rx_d0_ppi_ctrl_txulpsclk;                  // csi2_rx:tx_ulps_clk_d0 -> mipi_dphy:LINK0_D0_TxUlpsClk
	wire         mipi_dphy_link0_d0_ppi_ctrl_txhsidleclkreadyhs; // mipi_dphy:LINK0_D0_TxHSIdleClkReadyHS -> csi2_rx:tx_hsidle_clk_ready_hs_d0
	wire         csi2_rx_d1_ppi_ctrl_turndisable;                // csi2_rx:turn_disable_d1 -> mipi_dphy:LINK0_D1_TurnDisable
	wire         csi2_rx_d1_ppi_ctrl_alpmode;                    // csi2_rx:alp_mode_d1 -> mipi_dphy:LINK0_D1_AlpMode
	wire         csi2_rx_d1_ppi_ctrl_forcerxmode;                // csi2_rx:force_rx_mode_d1 -> mipi_dphy:LINK0_D1_ForceRxmode
	wire         csi2_rx_d1_ppi_ctrl_forcetxstopmode;            // csi2_rx:force_tx_stop_mode_d1 -> mipi_dphy:LINK0_D1_ForceTxStopmode
	wire         mipi_dphy_link0_d1_ppi_ctrl_direction;          // mipi_dphy:LINK0_D1_Direction -> csi2_rx:direction_d1
	wire         csi2_rx_d1_ppi_ctrl_turnrequest;                // csi2_rx:turn_request_d1 -> mipi_dphy:LINK0_D1_TurnRequest
	wire         mipi_dphy_link0_d1_ppi_ctrl_ulpsactivenot;      // mipi_dphy:LINK0_D1_UlpsActiveNot -> csi2_rx:ulps_active_not_d1
	wire         mipi_dphy_link0_d1_ppi_ctrl_rxulpsclknot;       // mipi_dphy:LINK0_D1_RxUlpsClkNot -> csi2_rx:rx_ulps_clk_not_d1
	wire         csi2_rx_d1_ppi_ctrl_txhsidleclkhs;              // csi2_rx:tx_hsidle_clk_hs_d1 -> mipi_dphy:LINK0_D1_TxHSIdleClkHS
	wire         csi2_rx_d1_ppi_ctrl_enable;                     // csi2_rx:enable_d1 -> mipi_dphy:LINK0_D1_Enable
	wire         mipi_dphy_link0_d1_ppi_ctrl_stopstate;          // mipi_dphy:LINK0_D1_Stopstate -> csi2_rx:stop_state_d1
	wire         csi2_rx_d1_ppi_ctrl_txulpsclk;                  // csi2_rx:tx_ulps_clk_d1 -> mipi_dphy:LINK0_D1_TxUlpsClk
	wire         mipi_dphy_link0_d1_ppi_ctrl_txhsidleclkreadyhs; // mipi_dphy:LINK0_D1_TxHSIdleClkReadyHS -> csi2_rx:tx_hsidle_clk_ready_hs_d1
	wire         csi2_rx_ck_ppi_hs_rxdetecteobhs;                // csi2_rx:rx_detect_eob_hs_ck -> mipi_dphy:LINK0_CK_RxDetectEobHS
	wire         mipi_dphy_link0_ck_ppi_rx_hs_rxddrclkhs;        // mipi_dphy:LINK0_CK_RxDDRClkHS -> csi2_rx:rx_ddr_clk_hs_ck
	wire   [1:0] csi2_rx_ck_ppi_hs_rxdatawidthhs;                // csi2_rx:rx_data_width_hs_ck -> mipi_dphy:LINK0_CK_RxDataWidthHS
	wire         mipi_dphy_link0_ck_ppi_rx_hs_rxsynchs;          // mipi_dphy:LINK0_CK_RxSyncHS -> csi2_rx:rx_sync_hs_ck
	wire         mipi_dphy_link0_ck_ppi_rx_hs_rxskewcalhs;       // mipi_dphy:LINK0_CK_RxSkewCalHS -> csi2_rx:rx_skew_cal_hs_ck
	wire         mipi_dphy_link0_ck_ppi_rx_hs_rxactivehs;        // mipi_dphy:LINK0_CK_RxActiveHS -> csi2_rx:rx_active_hs_ck
	wire   [1:0] mipi_dphy_link0_ck_ppi_rx_hs_rxvalidhs;         // mipi_dphy:LINK0_CK_RxValidHS -> csi2_rx:rx_valid_hs_ck
	wire         mipi_dphy_link0_ck_ppi_rx_hs_rxerrorcalhs;      // mipi_dphy:LINK0_CK_RxErrorCalHS -> csi2_rx:rx_error_cal_hs_ck
	wire  [15:0] mipi_dphy_link0_ck_ppi_rx_hs_rxdatahs;          // mipi_dphy:LINK0_CK_RxDataHS -> csi2_rx:rx_data_hs_ck
	wire         mipi_dphy_link0_ck_ppi_rx_hs_rxclkactivehs;     // mipi_dphy:LINK0_CK_RxClkActiveHS -> csi2_rx:rx_clk_active_hs_ck
	wire         mipi_dphy_link0_ck_ppi_rx_hs_rxalternatecalhs;  // mipi_dphy:LINK0_CK_RxAlternateCalHS -> csi2_rx:rx_alternate_cal_hs_ck
	wire         mipi_dphy_link0_ck_ppi_rx_lp_rxulpsesc;         // mipi_dphy:LINK0_CK_RxUlpsEsc -> csi2_rx:rx_ulps_esc_ck
	wire   [3:0] mipi_dphy_link0_ck_ppi_rx_lp_rxtriggeresc;      // mipi_dphy:LINK0_CK_RxTriggerEsc -> csi2_rx:rx_trigger_esc_ck
	wire         mipi_dphy_link0_ck_ppi_rx_lp_rxvalidesc;        // mipi_dphy:LINK0_CK_RxValidEsc -> csi2_rx:rx_valid_esc_ck
	wire   [7:0] mipi_dphy_link0_ck_ppi_rx_lp_rxdataesc;         // mipi_dphy:LINK0_CK_RxDataEsc -> csi2_rx:rx_data_esc_ck
	wire         mipi_dphy_link0_ck_ppi_rx_lp_rxlpdtesc;         // mipi_dphy:LINK0_CK_RxLpdtEsc -> csi2_rx:rx_lpdt_esc_ck
	wire         mipi_dphy_link0_ck_ppi_rx_lp_rxclkesc;          // mipi_dphy:LINK0_CK_RxClkEsc -> csi2_rx:rx_clk_esc_ck
	wire         mipi_dphy_link0_ck_ppi_rx_lp_rxwakeup;          // mipi_dphy:LINK0_CK_RxWakeup -> csi2_rx:rx_wake_up_ck
	wire         csi2_rx_d0_ppi_hs_rxdetecteobhs;                // csi2_rx:rx_detect_eob_hs_d0 -> mipi_dphy:LINK0_D0_RxDetectEobHS
	wire         mipi_dphy_link0_d0_ppi_rx_hs_rxddrclkhs;        // mipi_dphy:LINK0_D0_RxDDRClkHS -> csi2_rx:rx_ddr_clk_hs_d0
	wire   [1:0] csi2_rx_d0_ppi_hs_rxdatawidthhs;                // csi2_rx:rx_data_width_hs_d0 -> mipi_dphy:LINK0_D0_RxDataWidthHS
	wire         mipi_dphy_link0_d0_ppi_rx_hs_rxsynchs;          // mipi_dphy:LINK0_D0_RxSyncHS -> csi2_rx:rx_sync_hs_d0
	wire         mipi_dphy_link0_d0_ppi_rx_hs_rxskewcalhs;       // mipi_dphy:LINK0_D0_RxSkewCalHS -> csi2_rx:rx_skew_cal_hs_d0
	wire         mipi_dphy_link0_d0_ppi_rx_hs_rxactivehs;        // mipi_dphy:LINK0_D0_RxActiveHS -> csi2_rx:rx_active_hs_d0
	wire   [1:0] mipi_dphy_link0_d0_ppi_rx_hs_rxvalidhs;         // mipi_dphy:LINK0_D0_RxValidHS -> csi2_rx:rx_valid_hs_d0
	wire         mipi_dphy_link0_d0_ppi_rx_hs_rxerrorcalhs;      // mipi_dphy:LINK0_D0_RxErrorCalHS -> csi2_rx:rx_error_cal_hs_d0
	wire  [15:0] mipi_dphy_link0_d0_ppi_rx_hs_rxdatahs;          // mipi_dphy:LINK0_D0_RxDataHS -> csi2_rx:rx_data_hs_d0
	wire         mipi_dphy_link0_d0_ppi_rx_hs_rxclkactivehs;     // mipi_dphy:LINK0_D0_RxClkActiveHS -> csi2_rx:rx_clk_active_hs_d0
	wire         mipi_dphy_link0_d0_ppi_rx_hs_rxalternatecalhs;  // mipi_dphy:LINK0_D0_RxAlternateCalHS -> csi2_rx:rx_alternate_cal_hs_d0
	wire         mipi_dphy_link0_d0_ppi_rx_lp_rxulpsesc;         // mipi_dphy:LINK0_D0_RxUlpsEsc -> csi2_rx:rx_ulps_esc_d0
	wire   [3:0] mipi_dphy_link0_d0_ppi_rx_lp_rxtriggeresc;      // mipi_dphy:LINK0_D0_RxTriggerEsc -> csi2_rx:rx_trigger_esc_d0
	wire         mipi_dphy_link0_d0_ppi_rx_lp_rxvalidesc;        // mipi_dphy:LINK0_D0_RxValidEsc -> csi2_rx:rx_valid_esc_d0
	wire   [7:0] mipi_dphy_link0_d0_ppi_rx_lp_rxdataesc;         // mipi_dphy:LINK0_D0_RxDataEsc -> csi2_rx:rx_data_esc_d0
	wire         mipi_dphy_link0_d0_ppi_rx_lp_rxlpdtesc;         // mipi_dphy:LINK0_D0_RxLpdtEsc -> csi2_rx:rx_lpdt_esc_d0
	wire         mipi_dphy_link0_d0_ppi_rx_lp_rxclkesc;          // mipi_dphy:LINK0_D0_RxClkEsc -> csi2_rx:rx_clk_esc_d0
	wire         mipi_dphy_link0_d0_ppi_rx_lp_rxwakeup;          // mipi_dphy:LINK0_D0_RxWakeup -> csi2_rx:rx_wake_up_d0
	wire         csi2_rx_d1_ppi_hs_rxdetecteobhs;                // csi2_rx:rx_detect_eob_hs_d1 -> mipi_dphy:LINK0_D1_RxDetectEobHS
	wire         mipi_dphy_link0_d1_ppi_rx_hs_rxddrclkhs;        // mipi_dphy:LINK0_D1_RxDDRClkHS -> csi2_rx:rx_ddr_clk_hs_d1
	wire   [1:0] csi2_rx_d1_ppi_hs_rxdatawidthhs;                // csi2_rx:rx_data_width_hs_d1 -> mipi_dphy:LINK0_D1_RxDataWidthHS
	wire         mipi_dphy_link0_d1_ppi_rx_hs_rxsynchs;          // mipi_dphy:LINK0_D1_RxSyncHS -> csi2_rx:rx_sync_hs_d1
	wire         mipi_dphy_link0_d1_ppi_rx_hs_rxskewcalhs;       // mipi_dphy:LINK0_D1_RxSkewCalHS -> csi2_rx:rx_skew_cal_hs_d1
	wire         mipi_dphy_link0_d1_ppi_rx_hs_rxactivehs;        // mipi_dphy:LINK0_D1_RxActiveHS -> csi2_rx:rx_active_hs_d1
	wire   [1:0] mipi_dphy_link0_d1_ppi_rx_hs_rxvalidhs;         // mipi_dphy:LINK0_D1_RxValidHS -> csi2_rx:rx_valid_hs_d1
	wire         mipi_dphy_link0_d1_ppi_rx_hs_rxerrorcalhs;      // mipi_dphy:LINK0_D1_RxErrorCalHS -> csi2_rx:rx_error_cal_hs_d1
	wire  [15:0] mipi_dphy_link0_d1_ppi_rx_hs_rxdatahs;          // mipi_dphy:LINK0_D1_RxDataHS -> csi2_rx:rx_data_hs_d1
	wire         mipi_dphy_link0_d1_ppi_rx_hs_rxclkactivehs;     // mipi_dphy:LINK0_D1_RxClkActiveHS -> csi2_rx:rx_clk_active_hs_d1
	wire         mipi_dphy_link0_d1_ppi_rx_hs_rxalternatecalhs;  // mipi_dphy:LINK0_D1_RxAlternateCalHS -> csi2_rx:rx_alternate_cal_hs_d1
	wire         mipi_dphy_link0_d1_ppi_rx_lp_rxulpsesc;         // mipi_dphy:LINK0_D1_RxUlpsEsc -> csi2_rx:rx_ulps_esc_d1
	wire   [3:0] mipi_dphy_link0_d1_ppi_rx_lp_rxtriggeresc;      // mipi_dphy:LINK0_D1_RxTriggerEsc -> csi2_rx:rx_trigger_esc_d1
	wire         mipi_dphy_link0_d1_ppi_rx_lp_rxvalidesc;        // mipi_dphy:LINK0_D1_RxValidEsc -> csi2_rx:rx_valid_esc_d1
	wire   [7:0] mipi_dphy_link0_d1_ppi_rx_lp_rxdataesc;         // mipi_dphy:LINK0_D1_RxDataEsc -> csi2_rx:rx_data_esc_d1
	wire         mipi_dphy_link0_d1_ppi_rx_lp_rxlpdtesc;         // mipi_dphy:LINK0_D1_RxLpdtEsc -> csi2_rx:rx_lpdt_esc_d1
	wire         mipi_dphy_link0_d1_ppi_rx_lp_rxclkesc;          // mipi_dphy:LINK0_D1_RxClkEsc -> csi2_rx:rx_clk_esc_d1
	wire         mipi_dphy_link0_d1_ppi_rx_lp_rxwakeup;          // mipi_dphy:LINK0_D1_RxWakeup -> csi2_rx:rx_wake_up_d1
	wire         mipi_dphy_link0_ck_ppi_rx_err_errcontrol;       // mipi_dphy:LINK0_CK_ErrControl -> csi2_rx:i_err_control_ck
	wire         mipi_dphy_link0_ck_ppi_rx_err_errsyncesc;       // mipi_dphy:LINK0_CK_ErrSyncEsc -> csi2_rx:i_err_sync_ck
	wire         mipi_dphy_link0_ck_ppi_rx_err_errsotsynchs;     // mipi_dphy:LINK0_CK_ErrSotSyncHS -> csi2_rx:i_err_sot_sync_hs_ck
	wire         mipi_dphy_link0_ck_ppi_rx_err_erresc;           // mipi_dphy:LINK0_CK_ErrEsc -> csi2_rx:i_err_esc_ck
	wire         mipi_dphy_link0_ck_ppi_rx_err_errsoths;         // mipi_dphy:LINK0_CK_ErrSotHS -> csi2_rx:i_err_sot_hs_ck
	wire         mipi_dphy_link0_ck_ppi_rx_err_errcontentionlp1; // mipi_dphy:LINK0_CK_ErrContentionLP1 -> csi2_rx:i_err_contention_lp1_ck
	wire         mipi_dphy_link0_ck_ppi_rx_err_errcontentionlp0; // mipi_dphy:LINK0_CK_ErrContentionLP0 -> csi2_rx:i_err_contention_lp0_ck
	wire         mipi_dphy_link0_d0_ppi_rx_err_errcontrol;       // mipi_dphy:LINK0_D0_ErrControl -> csi2_rx:i_err_control_d0
	wire         mipi_dphy_link0_d0_ppi_rx_err_errsyncesc;       // mipi_dphy:LINK0_D0_ErrSyncEsc -> csi2_rx:i_err_sync_d0
	wire         mipi_dphy_link0_d0_ppi_rx_err_errsotsynchs;     // mipi_dphy:LINK0_D0_ErrSotSyncHS -> csi2_rx:i_err_sot_sync_hs_d0
	wire         mipi_dphy_link0_d0_ppi_rx_err_erresc;           // mipi_dphy:LINK0_D0_ErrEsc -> csi2_rx:i_err_esc_d0
	wire         mipi_dphy_link0_d0_ppi_rx_err_errsoths;         // mipi_dphy:LINK0_D0_ErrSotHS -> csi2_rx:i_err_sot_hs_d0
	wire         mipi_dphy_link0_d0_ppi_rx_err_errcontentionlp1; // mipi_dphy:LINK0_D0_ErrContentionLP1 -> csi2_rx:i_err_contention_lp1_d0
	wire         mipi_dphy_link0_d0_ppi_rx_err_errcontentionlp0; // mipi_dphy:LINK0_D0_ErrContentionLP0 -> csi2_rx:i_err_contention_lp0_d0
	wire         mipi_dphy_link0_d1_ppi_rx_err_errcontrol;       // mipi_dphy:LINK0_D1_ErrControl -> csi2_rx:i_err_control_d1
	wire         mipi_dphy_link0_d1_ppi_rx_err_errsyncesc;       // mipi_dphy:LINK0_D1_ErrSyncEsc -> csi2_rx:i_err_sync_d1
	wire         mipi_dphy_link0_d1_ppi_rx_err_errsotsynchs;     // mipi_dphy:LINK0_D1_ErrSotSyncHS -> csi2_rx:i_err_sot_sync_hs_d1
	wire         mipi_dphy_link0_d1_ppi_rx_err_erresc;           // mipi_dphy:LINK0_D1_ErrEsc -> csi2_rx:i_err_esc_d1
	wire         mipi_dphy_link0_d1_ppi_rx_err_errsoths;         // mipi_dphy:LINK0_D1_ErrSotHS -> csi2_rx:i_err_sot_hs_d1
	wire         mipi_dphy_link0_d1_ppi_rx_err_errcontentionlp1; // mipi_dphy:LINK0_D1_ErrContentionLP1 -> csi2_rx:i_err_contention_lp1_d1
	wire         mipi_dphy_link0_d1_ppi_rx_err_errcontentionlp0; // mipi_dphy:LINK0_D1_ErrContentionLP0 -> csi2_rx:i_err_contention_lp0_d1
	wire         mipi_dphy_link0_ck_ppi_rx_hs_srst_reset;        // mipi_dphy:LINK0_CK_RxSRst_n -> csi2_rx:rx_srst_n_ck
	wire         mipi_dphy_link0_d0_ppi_rx_hs_srst_reset;        // mipi_dphy:LINK0_D0_RxSRst_n -> csi2_rx:rx_srst_n_d0
	wire         mipi_dphy_link0_d1_ppi_rx_hs_srst_reset;        // mipi_dphy:LINK0_D1_RxSRst_n -> csi2_rx:rx_srst_n_d1
	wire         reset_release_0_ninit_done_reset;               // reset_release_0:ninit_done -> [mipi_dphy:arst_n, rst_controller:reset_in0, rst_controller_001:reset_in0]
	wire         rst_controller_reset_out_reset;                 // rst_controller:reset_out -> csi2_rx:axi4s_rst
	wire         rst_controller_001_reset_out_reset;             // rst_controller_001:reset_out -> mipi_dphy:srst_axil_n

	csi2_dphy_sys_csi2_rx csi2_rx (
		.rx_srst_n_d0              (mipi_dphy_link0_d0_ppi_rx_hs_srst_reset),           //   input,   width = 1,                     d0_ppi_rx_hs_srst.reset_n
		.rx_word_clk_hs_d0         (mipi_dphy_link0_d0_ppi_rx_hs_clk_clk),              //   input,   width = 1,                         d0_ppi_hs_clk.clk
		.rx_data_width_hs_d0       (csi2_rx_d0_ppi_hs_rxdatawidthhs),                   //  output,   width = 2,                             d0_ppi_hs.RxDataWidthHS
		.rx_data_hs_d0             (mipi_dphy_link0_d0_ppi_rx_hs_rxdatahs),             //   input,  width = 16,                                      .RxDataHS
		.rx_valid_hs_d0            (mipi_dphy_link0_d0_ppi_rx_hs_rxvalidhs),            //   input,   width = 2,                                      .RxValidHS
		.rx_active_hs_d0           (mipi_dphy_link0_d0_ppi_rx_hs_rxactivehs),           //   input,   width = 1,                                      .RxActiveHS
		.rx_sync_hs_d0             (mipi_dphy_link0_d0_ppi_rx_hs_rxsynchs),             //   input,   width = 1,                                      .RxSyncHS
		.rx_detect_eob_hs_d0       (csi2_rx_d0_ppi_hs_rxdetecteobhs),                   //  output,   width = 1,                                      .RxDetectEobHS
		.rx_clk_active_hs_d0       (mipi_dphy_link0_d0_ppi_rx_hs_rxclkactivehs),        //   input,   width = 1,                                      .RxClkActiveHS
		.rx_ddr_clk_hs_d0          (mipi_dphy_link0_d0_ppi_rx_hs_rxddrclkhs),           //   input,   width = 1,                                      .RxDDRClkHS
		.rx_skew_cal_hs_d0         (mipi_dphy_link0_d0_ppi_rx_hs_rxskewcalhs),          //   input,   width = 1,                                      .RxSkewCalHS
		.rx_alternate_cal_hs_d0    (mipi_dphy_link0_d0_ppi_rx_hs_rxalternatecalhs),     //   input,   width = 1,                                      .RxAlternateCalHS
		.rx_error_cal_hs_d0        (mipi_dphy_link0_d0_ppi_rx_hs_rxerrorcalhs),         //   input,   width = 1,                                      .RxErrorCalHS
		.rx_clk_esc_d0             (mipi_dphy_link0_d0_ppi_rx_lp_rxclkesc),             //   input,   width = 1,                             d0_ppi_lp.RxClkEsc
		.rx_lpdt_esc_d0            (mipi_dphy_link0_d0_ppi_rx_lp_rxlpdtesc),            //   input,   width = 1,                                      .RxLpdtEsc
		.rx_ulps_esc_d0            (mipi_dphy_link0_d0_ppi_rx_lp_rxulpsesc),            //   input,   width = 1,                                      .RxUlpsEsc
		.rx_trigger_esc_d0         (mipi_dphy_link0_d0_ppi_rx_lp_rxtriggeresc),         //   input,   width = 4,                                      .RxTriggerEsc
		.rx_wake_up_d0             (mipi_dphy_link0_d0_ppi_rx_lp_rxwakeup),             //   input,   width = 1,                                      .RxWakeup
		.rx_data_esc_d0            (mipi_dphy_link0_d0_ppi_rx_lp_rxdataesc),            //   input,   width = 8,                                      .RxDataEsc
		.rx_valid_esc_d0           (mipi_dphy_link0_d0_ppi_rx_lp_rxvalidesc),           //   input,   width = 1,                                      .RxValidEsc
		.turn_request_d0           (csi2_rx_d0_ppi_ctrl_turnrequest),                   //  output,   width = 1,                           d0_ppi_ctrl.TurnRequest
		.direction_d0              (mipi_dphy_link0_d0_ppi_ctrl_direction),             //   input,   width = 1,                                      .Direction
		.turn_disable_d0           (csi2_rx_d0_ppi_ctrl_turndisable),                   //  output,   width = 1,                                      .TurnDisable
		.force_rx_mode_d0          (csi2_rx_d0_ppi_ctrl_forcerxmode),                   //  output,   width = 1,                                      .ForceRxmode
		.force_tx_stop_mode_d0     (csi2_rx_d0_ppi_ctrl_forcetxstopmode),               //  output,   width = 1,                                      .ForceTxStopmode
		.stop_state_d0             (mipi_dphy_link0_d0_ppi_ctrl_stopstate),             //   input,   width = 1,                                      .Stopstate
		.enable_d0                 (csi2_rx_d0_ppi_ctrl_enable),                        //  output,   width = 1,                                      .Enable
		.alp_mode_d0               (csi2_rx_d0_ppi_ctrl_alpmode),                       //  output,   width = 1,                                      .AlpMode
		.tx_ulps_clk_d0            (csi2_rx_d0_ppi_ctrl_txulpsclk),                     //  output,   width = 1,                                      .TxUlpsClk
		.rx_ulps_clk_not_d0        (mipi_dphy_link0_d0_ppi_ctrl_rxulpsclknot),          //   input,   width = 1,                                      .RxUlpsClkNot
		.ulps_active_not_d0        (mipi_dphy_link0_d0_ppi_ctrl_ulpsactivenot),         //   input,   width = 1,                                      .UlpsActiveNot
		.tx_hsidle_clk_hs_d0       (csi2_rx_d0_ppi_ctrl_txhsidleclkhs),                 //  output,   width = 1,                                      .TxHSIdleClkHS
		.tx_hsidle_clk_ready_hs_d0 (mipi_dphy_link0_d0_ppi_ctrl_txhsidleclkreadyhs),    //   input,   width = 1,                                      .TxHSIdleClkReadyHS
		.i_err_sot_hs_d0           (mipi_dphy_link0_d0_ppi_rx_err_errsoths),            //   input,   width = 1,                       i_d0_ppi_rx_err.ErrSotHS
		.i_err_sot_sync_hs_d0      (mipi_dphy_link0_d0_ppi_rx_err_errsotsynchs),        //   input,   width = 1,                                      .ErrSotSyncHS
		.i_err_esc_d0              (mipi_dphy_link0_d0_ppi_rx_err_erresc),              //   input,   width = 1,                                      .ErrEsc
		.i_err_sync_d0             (mipi_dphy_link0_d0_ppi_rx_err_errsyncesc),          //   input,   width = 1,                                      .ErrSyncEsc
		.i_err_control_d0          (mipi_dphy_link0_d0_ppi_rx_err_errcontrol),          //   input,   width = 1,                                      .ErrControl
		.i_err_contention_lp0_d0   (mipi_dphy_link0_d0_ppi_rx_err_errcontentionlp0),    //   input,   width = 1,                                      .ErrContentionLP0
		.i_err_contention_lp1_d0   (mipi_dphy_link0_d0_ppi_rx_err_errcontentionlp1),    //   input,   width = 1,                                      .ErrContentionLP1
		.o_err_sot_hs_d0           (csi2_rx_o_d0_ppi_rx_err_ErrSotHS),                  //  output,   width = 1,                       o_d0_ppi_rx_err.ErrSotHS
		.o_err_sot_sync_hs_d0      (csi2_rx_o_d0_ppi_rx_err_ErrSotSyncHS),              //  output,   width = 1,                                      .ErrSotSyncHS
		.o_err_esc_d0              (csi2_rx_o_d0_ppi_rx_err_ErrEsc),                    //  output,   width = 1,                                      .ErrEsc
		.o_err_sync_d0             (csi2_rx_o_d0_ppi_rx_err_ErrSyncEsc),                //  output,   width = 1,                                      .ErrSyncEsc
		.o_err_control_d0          (csi2_rx_o_d0_ppi_rx_err_ErrControl),                //  output,   width = 1,                                      .ErrControl
		.o_err_contention_lp0_d0   (csi2_rx_o_d0_ppi_rx_err_ErrContentionLP0),          //  output,   width = 1,                                      .ErrContentionLP0
		.o_err_contention_lp1_d0   (csi2_rx_o_d0_ppi_rx_err_ErrContentionLP1),          //  output,   width = 1,                                      .ErrContentionLP1
		.rx_srst_n_d1              (mipi_dphy_link0_d1_ppi_rx_hs_srst_reset),           //   input,   width = 1,                     d1_ppi_rx_hs_srst.reset_n
		.rx_word_clk_hs_d1         (mipi_dphy_link0_d1_ppi_rx_hs_clk_clk),              //   input,   width = 1,                         d1_ppi_hs_clk.clk
		.rx_data_width_hs_d1       (csi2_rx_d1_ppi_hs_rxdatawidthhs),                   //  output,   width = 2,                             d1_ppi_hs.RxDataWidthHS
		.rx_data_hs_d1             (mipi_dphy_link0_d1_ppi_rx_hs_rxdatahs),             //   input,  width = 16,                                      .RxDataHS
		.rx_valid_hs_d1            (mipi_dphy_link0_d1_ppi_rx_hs_rxvalidhs),            //   input,   width = 2,                                      .RxValidHS
		.rx_active_hs_d1           (mipi_dphy_link0_d1_ppi_rx_hs_rxactivehs),           //   input,   width = 1,                                      .RxActiveHS
		.rx_sync_hs_d1             (mipi_dphy_link0_d1_ppi_rx_hs_rxsynchs),             //   input,   width = 1,                                      .RxSyncHS
		.rx_detect_eob_hs_d1       (csi2_rx_d1_ppi_hs_rxdetecteobhs),                   //  output,   width = 1,                                      .RxDetectEobHS
		.rx_clk_active_hs_d1       (mipi_dphy_link0_d1_ppi_rx_hs_rxclkactivehs),        //   input,   width = 1,                                      .RxClkActiveHS
		.rx_ddr_clk_hs_d1          (mipi_dphy_link0_d1_ppi_rx_hs_rxddrclkhs),           //   input,   width = 1,                                      .RxDDRClkHS
		.rx_skew_cal_hs_d1         (mipi_dphy_link0_d1_ppi_rx_hs_rxskewcalhs),          //   input,   width = 1,                                      .RxSkewCalHS
		.rx_alternate_cal_hs_d1    (mipi_dphy_link0_d1_ppi_rx_hs_rxalternatecalhs),     //   input,   width = 1,                                      .RxAlternateCalHS
		.rx_error_cal_hs_d1        (mipi_dphy_link0_d1_ppi_rx_hs_rxerrorcalhs),         //   input,   width = 1,                                      .RxErrorCalHS
		.rx_clk_esc_d1             (mipi_dphy_link0_d1_ppi_rx_lp_rxclkesc),             //   input,   width = 1,                             d1_ppi_lp.RxClkEsc
		.rx_lpdt_esc_d1            (mipi_dphy_link0_d1_ppi_rx_lp_rxlpdtesc),            //   input,   width = 1,                                      .RxLpdtEsc
		.rx_ulps_esc_d1            (mipi_dphy_link0_d1_ppi_rx_lp_rxulpsesc),            //   input,   width = 1,                                      .RxUlpsEsc
		.rx_trigger_esc_d1         (mipi_dphy_link0_d1_ppi_rx_lp_rxtriggeresc),         //   input,   width = 4,                                      .RxTriggerEsc
		.rx_wake_up_d1             (mipi_dphy_link0_d1_ppi_rx_lp_rxwakeup),             //   input,   width = 1,                                      .RxWakeup
		.rx_data_esc_d1            (mipi_dphy_link0_d1_ppi_rx_lp_rxdataesc),            //   input,   width = 8,                                      .RxDataEsc
		.rx_valid_esc_d1           (mipi_dphy_link0_d1_ppi_rx_lp_rxvalidesc),           //   input,   width = 1,                                      .RxValidEsc
		.turn_request_d1           (csi2_rx_d1_ppi_ctrl_turnrequest),                   //  output,   width = 1,                           d1_ppi_ctrl.TurnRequest
		.direction_d1              (mipi_dphy_link0_d1_ppi_ctrl_direction),             //   input,   width = 1,                                      .Direction
		.turn_disable_d1           (csi2_rx_d1_ppi_ctrl_turndisable),                   //  output,   width = 1,                                      .TurnDisable
		.force_rx_mode_d1          (csi2_rx_d1_ppi_ctrl_forcerxmode),                   //  output,   width = 1,                                      .ForceRxmode
		.force_tx_stop_mode_d1     (csi2_rx_d1_ppi_ctrl_forcetxstopmode),               //  output,   width = 1,                                      .ForceTxStopmode
		.stop_state_d1             (mipi_dphy_link0_d1_ppi_ctrl_stopstate),             //   input,   width = 1,                                      .Stopstate
		.enable_d1                 (csi2_rx_d1_ppi_ctrl_enable),                        //  output,   width = 1,                                      .Enable
		.alp_mode_d1               (csi2_rx_d1_ppi_ctrl_alpmode),                       //  output,   width = 1,                                      .AlpMode
		.tx_ulps_clk_d1            (csi2_rx_d1_ppi_ctrl_txulpsclk),                     //  output,   width = 1,                                      .TxUlpsClk
		.rx_ulps_clk_not_d1        (mipi_dphy_link0_d1_ppi_ctrl_rxulpsclknot),          //   input,   width = 1,                                      .RxUlpsClkNot
		.ulps_active_not_d1        (mipi_dphy_link0_d1_ppi_ctrl_ulpsactivenot),         //   input,   width = 1,                                      .UlpsActiveNot
		.tx_hsidle_clk_hs_d1       (csi2_rx_d1_ppi_ctrl_txhsidleclkhs),                 //  output,   width = 1,                                      .TxHSIdleClkHS
		.tx_hsidle_clk_ready_hs_d1 (mipi_dphy_link0_d1_ppi_ctrl_txhsidleclkreadyhs),    //   input,   width = 1,                                      .TxHSIdleClkReadyHS
		.i_err_sot_hs_d1           (mipi_dphy_link0_d1_ppi_rx_err_errsoths),            //   input,   width = 1,                       i_d1_ppi_rx_err.ErrSotHS
		.i_err_sot_sync_hs_d1      (mipi_dphy_link0_d1_ppi_rx_err_errsotsynchs),        //   input,   width = 1,                                      .ErrSotSyncHS
		.i_err_esc_d1              (mipi_dphy_link0_d1_ppi_rx_err_erresc),              //   input,   width = 1,                                      .ErrEsc
		.i_err_sync_d1             (mipi_dphy_link0_d1_ppi_rx_err_errsyncesc),          //   input,   width = 1,                                      .ErrSyncEsc
		.i_err_control_d1          (mipi_dphy_link0_d1_ppi_rx_err_errcontrol),          //   input,   width = 1,                                      .ErrControl
		.i_err_contention_lp0_d1   (mipi_dphy_link0_d1_ppi_rx_err_errcontentionlp0),    //   input,   width = 1,                                      .ErrContentionLP0
		.i_err_contention_lp1_d1   (mipi_dphy_link0_d1_ppi_rx_err_errcontentionlp1),    //   input,   width = 1,                                      .ErrContentionLP1
		.o_err_sot_hs_d1           (csi2_rx_o_d1_ppi_rx_err_ErrSotHS),                  //  output,   width = 1,                       o_d1_ppi_rx_err.ErrSotHS
		.o_err_sot_sync_hs_d1      (csi2_rx_o_d1_ppi_rx_err_ErrSotSyncHS),              //  output,   width = 1,                                      .ErrSotSyncHS
		.o_err_esc_d1              (csi2_rx_o_d1_ppi_rx_err_ErrEsc),                    //  output,   width = 1,                                      .ErrEsc
		.o_err_sync_d1             (csi2_rx_o_d1_ppi_rx_err_ErrSyncEsc),                //  output,   width = 1,                                      .ErrSyncEsc
		.o_err_control_d1          (csi2_rx_o_d1_ppi_rx_err_ErrControl),                //  output,   width = 1,                                      .ErrControl
		.o_err_contention_lp0_d1   (csi2_rx_o_d1_ppi_rx_err_ErrContentionLP0),          //  output,   width = 1,                                      .ErrContentionLP0
		.o_err_contention_lp1_d1   (csi2_rx_o_d1_ppi_rx_err_ErrContentionLP1),          //  output,   width = 1,                                      .ErrContentionLP1
		.rx_srst_n_ck              (mipi_dphy_link0_ck_ppi_rx_hs_srst_reset),           //   input,   width = 1,                     ck_ppi_rx_hs_srst.reset_n
		.rx_word_clk_hs_ck         (mipi_dphy_link0_ck_ppi_rx_hs_clk_clk),              //   input,   width = 1,                         ck_ppi_hs_clk.clk
		.rx_data_width_hs_ck       (csi2_rx_ck_ppi_hs_rxdatawidthhs),                   //  output,   width = 2,                             ck_ppi_hs.RxDataWidthHS
		.rx_data_hs_ck             (mipi_dphy_link0_ck_ppi_rx_hs_rxdatahs),             //   input,  width = 16,                                      .RxDataHS
		.rx_valid_hs_ck            (mipi_dphy_link0_ck_ppi_rx_hs_rxvalidhs),            //   input,   width = 2,                                      .RxValidHS
		.rx_active_hs_ck           (mipi_dphy_link0_ck_ppi_rx_hs_rxactivehs),           //   input,   width = 1,                                      .RxActiveHS
		.rx_sync_hs_ck             (mipi_dphy_link0_ck_ppi_rx_hs_rxsynchs),             //   input,   width = 1,                                      .RxSyncHS
		.rx_detect_eob_hs_ck       (csi2_rx_ck_ppi_hs_rxdetecteobhs),                   //  output,   width = 1,                                      .RxDetectEobHS
		.rx_clk_active_hs_ck       (mipi_dphy_link0_ck_ppi_rx_hs_rxclkactivehs),        //   input,   width = 1,                                      .RxClkActiveHS
		.rx_ddr_clk_hs_ck          (mipi_dphy_link0_ck_ppi_rx_hs_rxddrclkhs),           //   input,   width = 1,                                      .RxDDRClkHS
		.rx_skew_cal_hs_ck         (mipi_dphy_link0_ck_ppi_rx_hs_rxskewcalhs),          //   input,   width = 1,                                      .RxSkewCalHS
		.rx_alternate_cal_hs_ck    (mipi_dphy_link0_ck_ppi_rx_hs_rxalternatecalhs),     //   input,   width = 1,                                      .RxAlternateCalHS
		.rx_error_cal_hs_ck        (mipi_dphy_link0_ck_ppi_rx_hs_rxerrorcalhs),         //   input,   width = 1,                                      .RxErrorCalHS
		.rx_clk_esc_ck             (mipi_dphy_link0_ck_ppi_rx_lp_rxclkesc),             //   input,   width = 1,                             ck_ppi_lp.RxClkEsc
		.rx_lpdt_esc_ck            (mipi_dphy_link0_ck_ppi_rx_lp_rxlpdtesc),            //   input,   width = 1,                                      .RxLpdtEsc
		.rx_ulps_esc_ck            (mipi_dphy_link0_ck_ppi_rx_lp_rxulpsesc),            //   input,   width = 1,                                      .RxUlpsEsc
		.rx_trigger_esc_ck         (mipi_dphy_link0_ck_ppi_rx_lp_rxtriggeresc),         //   input,   width = 4,                                      .RxTriggerEsc
		.rx_wake_up_ck             (mipi_dphy_link0_ck_ppi_rx_lp_rxwakeup),             //   input,   width = 1,                                      .RxWakeup
		.rx_data_esc_ck            (mipi_dphy_link0_ck_ppi_rx_lp_rxdataesc),            //   input,   width = 8,                                      .RxDataEsc
		.rx_valid_esc_ck           (mipi_dphy_link0_ck_ppi_rx_lp_rxvalidesc),           //   input,   width = 1,                                      .RxValidEsc
		.turn_request_ck           (csi2_rx_ck_ppi_ctrl_turnrequest),                   //  output,   width = 1,                           ck_ppi_ctrl.TurnRequest
		.direction_ck              (mipi_dphy_link0_ck_ppi_ctrl_direction),             //   input,   width = 1,                                      .Direction
		.turn_disable_ck           (csi2_rx_ck_ppi_ctrl_turndisable),                   //  output,   width = 1,                                      .TurnDisable
		.force_rx_mode_ck          (csi2_rx_ck_ppi_ctrl_forcerxmode),                   //  output,   width = 1,                                      .ForceRxmode
		.force_tx_stop_mode_ck     (csi2_rx_ck_ppi_ctrl_forcetxstopmode),               //  output,   width = 1,                                      .ForceTxStopmode
		.stop_state_ck             (mipi_dphy_link0_ck_ppi_ctrl_stopstate),             //   input,   width = 1,                                      .Stopstate
		.enable_ck                 (csi2_rx_ck_ppi_ctrl_enable),                        //  output,   width = 1,                                      .Enable
		.alp_mode_ck               (csi2_rx_ck_ppi_ctrl_alpmode),                       //  output,   width = 1,                                      .AlpMode
		.tx_ulps_clk_ck            (csi2_rx_ck_ppi_ctrl_txulpsclk),                     //  output,   width = 1,                                      .TxUlpsClk
		.rx_ulps_clk_not_ck        (mipi_dphy_link0_ck_ppi_ctrl_rxulpsclknot),          //   input,   width = 1,                                      .RxUlpsClkNot
		.ulps_active_not_ck        (mipi_dphy_link0_ck_ppi_ctrl_ulpsactivenot),         //   input,   width = 1,                                      .UlpsActiveNot
		.tx_hsidle_clk_hs_ck       (csi2_rx_ck_ppi_ctrl_txhsidleclkhs),                 //  output,   width = 1,                                      .TxHSIdleClkHS
		.tx_hsidle_clk_ready_hs_ck (mipi_dphy_link0_ck_ppi_ctrl_txhsidleclkreadyhs),    //   input,   width = 1,                                      .TxHSIdleClkReadyHS
		.i_err_sot_hs_ck           (mipi_dphy_link0_ck_ppi_rx_err_errsoths),            //   input,   width = 1,                       i_ck_ppi_rx_err.ErrSotHS
		.i_err_sot_sync_hs_ck      (mipi_dphy_link0_ck_ppi_rx_err_errsotsynchs),        //   input,   width = 1,                                      .ErrSotSyncHS
		.i_err_esc_ck              (mipi_dphy_link0_ck_ppi_rx_err_erresc),              //   input,   width = 1,                                      .ErrEsc
		.i_err_sync_ck             (mipi_dphy_link0_ck_ppi_rx_err_errsyncesc),          //   input,   width = 1,                                      .ErrSyncEsc
		.i_err_control_ck          (mipi_dphy_link0_ck_ppi_rx_err_errcontrol),          //   input,   width = 1,                                      .ErrControl
		.i_err_contention_lp0_ck   (mipi_dphy_link0_ck_ppi_rx_err_errcontentionlp0),    //   input,   width = 1,                                      .ErrContentionLP0
		.i_err_contention_lp1_ck   (mipi_dphy_link0_ck_ppi_rx_err_errcontentionlp1),    //   input,   width = 1,                                      .ErrContentionLP1
		.o_err_sot_hs_ck           (csi2_rx_o_ck_ppi_rx_err_ErrSotHS),                  //  output,   width = 1,                       o_ck_ppi_rx_err.ErrSotHS
		.o_err_sot_sync_hs_ck      (csi2_rx_o_ck_ppi_rx_err_ErrSotSyncHS),              //  output,   width = 1,                                      .ErrSotSyncHS
		.o_err_esc_ck              (csi2_rx_o_ck_ppi_rx_err_ErrEsc),                    //  output,   width = 1,                                      .ErrEsc
		.o_err_sync_ck             (csi2_rx_o_ck_ppi_rx_err_ErrSyncEsc),                //  output,   width = 1,                                      .ErrSyncEsc
		.o_err_control_ck          (csi2_rx_o_ck_ppi_rx_err_ErrControl),                //  output,   width = 1,                                      .ErrControl
		.o_err_contention_lp0_ck   (csi2_rx_o_ck_ppi_rx_err_ErrContentionLP0),          //  output,   width = 1,                                      .ErrContentionLP0
		.o_err_contention_lp1_ck   (csi2_rx_o_ck_ppi_rx_err_ErrContentionLP1),          //  output,   width = 1,                                      .ErrContentionLP1
		.axi4s_clk                 (rx_axi4s_clk_bridge_out_clk_clk),                   //   input,   width = 1,                             axi4s_clk.clk
		.axi4s_rst                 (rst_controller_reset_out_reset),                    //   input,   width = 1,                             axi4s_rst.reset
		.axi4s_vid_out_0_tdata     (csi2_rx_video_streaming_interface_0_tdata),         //  output,  width = 64,           video_streaming_interface_0.tdata
		.axi4s_vid_out_0_tvalid    (csi2_rx_video_streaming_interface_0_tvalid),        //  output,   width = 1,                                      .tvalid
		.axi4s_vid_out_0_tready    (csi2_rx_video_streaming_interface_0_tready),        //   input,   width = 1,                                      .tready
		.axi4s_vid_out_0_tlast     (csi2_rx_video_streaming_interface_0_tlast),         //  output,   width = 1,                                      .tlast
		.axi4s_vid_out_0_tuser     (csi2_rx_video_streaming_interface_0_tuser),         //  output,   width = 8,                                      .tuser
		.control_write             (csi2_rx_avalon_mm_control_interface_write),         //   input,   width = 1,           avalon_mm_control_interface.write
		.control_read              (csi2_rx_avalon_mm_control_interface_read),          //   input,   width = 1,                                      .read
		.control_address           (csi2_rx_avalon_mm_control_interface_address),       //   input,  width = 10,                                      .address
		.control_writedata         (csi2_rx_avalon_mm_control_interface_writedata),     //   input,  width = 32,                                      .writedata
		.control_readdata          (csi2_rx_avalon_mm_control_interface_readdata),      //  output,  width = 32,                                      .readdata
		.control_readdatavalid     (csi2_rx_avalon_mm_control_interface_readdatavalid), //  output,   width = 1,                                      .readdatavalid
		.control_waitrequest       (csi2_rx_avalon_mm_control_interface_waitrequest),   //  output,   width = 1,                                      .waitrequest
		.control_byteenable        (csi2_rx_avalon_mm_control_interface_byteenable),    //   input,   width = 4,                                      .byteenable
		.control_irq               (csi2_rx_avalon_mm_control_interface_interrupt_irq)  //  output,   width = 1, avalon_mm_control_interface_interrupt.irq
	);

	csi2_dphy_sys_mipi_dphy mipi_dphy (
		.rzq                         (mipi_dphy_rzq_rzq),                              //   input,   width = 1,                     rzq.rzq
		.ref_clk_0_p                 (mipi_dphy_ref_clk_0_clk),                        //   input,   width = 1,               ref_clk_0.clk
		.arst_n                      (~reset_release_0_ninit_done_reset),              //   input,   width = 1,                    arst.reset_n
		.LINK0_link_core_clk         (mipi_dphy_link0_link_core_clk_clk),              //  output,   width = 1,     LINK0_link_core_clk.clk
		.LINK0_link_srst_n           (mipi_dphy_LINK0_link_core_srst_reset_n),         //  output,   width = 1,    LINK0_link_core_srst.reset_n
		.LINK0_link_arst_n           (mipi_dphy_LINK0_link_core_arst_reset_n),         //  output,   width = 1,    LINK0_link_core_arst.reset_n
		.axil_clk                    (mipi_dphy_link0_link_core_clk_clk),              //   input,   width = 1,                 reg_clk.clk
		.srst_axil_n                 (~rst_controller_001_reset_out_reset),            //   input,   width = 1,                reg_srst.reset_n
		.axi_lite_awaddr             (mipi_dphy_axi_lite_awaddr),                      //   input,  width = 12,                axi_lite.awaddr
		.axi_lite_awvalid            (mipi_dphy_axi_lite_awvalid),                     //   input,   width = 1,                        .awvalid
		.axi_lite_awready            (mipi_dphy_axi_lite_awready),                     //  output,   width = 1,                        .awready
		.axi_lite_wdata              (mipi_dphy_axi_lite_wdata),                       //   input,  width = 32,                        .wdata
		.axi_lite_wstrb              (mipi_dphy_axi_lite_wstrb),                       //   input,   width = 4,                        .wstrb
		.axi_lite_wvalid             (mipi_dphy_axi_lite_wvalid),                      //   input,   width = 1,                        .wvalid
		.axi_lite_wready             (mipi_dphy_axi_lite_wready),                      //  output,   width = 1,                        .wready
		.axi_lite_bresp              (mipi_dphy_axi_lite_bresp),                       //  output,   width = 2,                        .bresp
		.axi_lite_bvalid             (mipi_dphy_axi_lite_bvalid),                      //  output,   width = 1,                        .bvalid
		.axi_lite_bready             (mipi_dphy_axi_lite_bready),                      //   input,   width = 1,                        .bready
		.axi_lite_araddr             (mipi_dphy_axi_lite_araddr),                      //   input,  width = 12,                        .araddr
		.axi_lite_arvalid            (mipi_dphy_axi_lite_arvalid),                     //   input,   width = 1,                        .arvalid
		.axi_lite_arready            (mipi_dphy_axi_lite_arready),                     //  output,   width = 1,                        .arready
		.axi_lite_rdata              (mipi_dphy_axi_lite_rdata),                       //  output,  width = 32,                        .rdata
		.axi_lite_rresp              (mipi_dphy_axi_lite_rresp),                       //  output,   width = 2,                        .rresp
		.axi_lite_rvalid             (mipi_dphy_axi_lite_rvalid),                      //  output,   width = 1,                        .rvalid
		.axi_lite_rready             (mipi_dphy_axi_lite_rready),                      //   input,   width = 1,                        .rready
		.axi_lite_arprot             (mipi_dphy_axi_lite_arprot),                      //   input,   width = 3,                        .arprot
		.axi_lite_awprot             (mipi_dphy_axi_lite_awprot),                      //   input,   width = 3,                        .awprot
		.LINK0_D0_RxWordClkHS        (mipi_dphy_link0_d0_ppi_rx_hs_clk_clk),           //  output,   width = 1,  LINK0_D0_ppi_rx_hs_clk.clk
		.LINK0_D1_RxWordClkHS        (mipi_dphy_link0_d1_ppi_rx_hs_clk_clk),           //  output,   width = 1,  LINK0_D1_ppi_rx_hs_clk.clk
		.LINK0_CK_RxWordClkHS        (mipi_dphy_link0_ck_ppi_rx_hs_clk_clk),           //  output,   width = 1,  LINK0_CK_ppi_rx_hs_clk.clk
		.LINK0_D0_RxSRst_n           (mipi_dphy_link0_d0_ppi_rx_hs_srst_reset),        //  output,   width = 1, LINK0_D0_ppi_rx_hs_srst.reset_n
		.LINK0_D1_RxSRst_n           (mipi_dphy_link0_d1_ppi_rx_hs_srst_reset),        //  output,   width = 1, LINK0_D1_ppi_rx_hs_srst.reset_n
		.LINK0_CK_RxSRst_n           (mipi_dphy_link0_ck_ppi_rx_hs_srst_reset),        //  output,   width = 1, LINK0_CK_ppi_rx_hs_srst.reset_n
		.LINK0_D0_RxDataWidthHS      (csi2_rx_d0_ppi_hs_rxdatawidthhs),                //   input,   width = 2,      LINK0_D0_ppi_rx_hs.RxDataWidthHS
		.LINK0_D0_RxDataHS           (mipi_dphy_link0_d0_ppi_rx_hs_rxdatahs),          //  output,  width = 16,                        .RxDataHS
		.LINK0_D0_RxValidHS          (mipi_dphy_link0_d0_ppi_rx_hs_rxvalidhs),         //  output,   width = 2,                        .RxValidHS
		.LINK0_D0_RxActiveHS         (mipi_dphy_link0_d0_ppi_rx_hs_rxactivehs),        //  output,   width = 1,                        .RxActiveHS
		.LINK0_D0_RxSyncHS           (mipi_dphy_link0_d0_ppi_rx_hs_rxsynchs),          //  output,   width = 1,                        .RxSyncHS
		.LINK0_D0_RxDetectEobHS      (csi2_rx_d0_ppi_hs_rxdetecteobhs),                //   input,   width = 1,                        .RxDetectEobHS
		.LINK0_D0_RxClkActiveHS      (mipi_dphy_link0_d0_ppi_rx_hs_rxclkactivehs),     //  output,   width = 1,                        .RxClkActiveHS
		.LINK0_D0_RxDDRClkHS         (mipi_dphy_link0_d0_ppi_rx_hs_rxddrclkhs),        //  output,   width = 1,                        .RxDDRClkHS
		.LINK0_D0_RxSkewCalHS        (mipi_dphy_link0_d0_ppi_rx_hs_rxskewcalhs),       //  output,   width = 1,                        .RxSkewCalHS
		.LINK0_D0_RxAlternateCalHS   (mipi_dphy_link0_d0_ppi_rx_hs_rxalternatecalhs),  //  output,   width = 1,                        .RxAlternateCalHS
		.LINK0_D0_RxErrorCalHS       (mipi_dphy_link0_d0_ppi_rx_hs_rxerrorcalhs),      //  output,   width = 1,                        .RxErrorCalHS
		.LINK0_D1_RxDataWidthHS      (csi2_rx_d1_ppi_hs_rxdatawidthhs),                //   input,   width = 2,      LINK0_D1_ppi_rx_hs.RxDataWidthHS
		.LINK0_D1_RxDataHS           (mipi_dphy_link0_d1_ppi_rx_hs_rxdatahs),          //  output,  width = 16,                        .RxDataHS
		.LINK0_D1_RxValidHS          (mipi_dphy_link0_d1_ppi_rx_hs_rxvalidhs),         //  output,   width = 2,                        .RxValidHS
		.LINK0_D1_RxActiveHS         (mipi_dphy_link0_d1_ppi_rx_hs_rxactivehs),        //  output,   width = 1,                        .RxActiveHS
		.LINK0_D1_RxSyncHS           (mipi_dphy_link0_d1_ppi_rx_hs_rxsynchs),          //  output,   width = 1,                        .RxSyncHS
		.LINK0_D1_RxDetectEobHS      (csi2_rx_d1_ppi_hs_rxdetecteobhs),                //   input,   width = 1,                        .RxDetectEobHS
		.LINK0_D1_RxClkActiveHS      (mipi_dphy_link0_d1_ppi_rx_hs_rxclkactivehs),     //  output,   width = 1,                        .RxClkActiveHS
		.LINK0_D1_RxDDRClkHS         (mipi_dphy_link0_d1_ppi_rx_hs_rxddrclkhs),        //  output,   width = 1,                        .RxDDRClkHS
		.LINK0_D1_RxSkewCalHS        (mipi_dphy_link0_d1_ppi_rx_hs_rxskewcalhs),       //  output,   width = 1,                        .RxSkewCalHS
		.LINK0_D1_RxAlternateCalHS   (mipi_dphy_link0_d1_ppi_rx_hs_rxalternatecalhs),  //  output,   width = 1,                        .RxAlternateCalHS
		.LINK0_D1_RxErrorCalHS       (mipi_dphy_link0_d1_ppi_rx_hs_rxerrorcalhs),      //  output,   width = 1,                        .RxErrorCalHS
		.LINK0_CK_RxDataWidthHS      (csi2_rx_ck_ppi_hs_rxdatawidthhs),                //   input,   width = 2,      LINK0_CK_ppi_rx_hs.RxDataWidthHS
		.LINK0_CK_RxDataHS           (mipi_dphy_link0_ck_ppi_rx_hs_rxdatahs),          //  output,  width = 16,                        .RxDataHS
		.LINK0_CK_RxValidHS          (mipi_dphy_link0_ck_ppi_rx_hs_rxvalidhs),         //  output,   width = 2,                        .RxValidHS
		.LINK0_CK_RxActiveHS         (mipi_dphy_link0_ck_ppi_rx_hs_rxactivehs),        //  output,   width = 1,                        .RxActiveHS
		.LINK0_CK_RxSyncHS           (mipi_dphy_link0_ck_ppi_rx_hs_rxsynchs),          //  output,   width = 1,                        .RxSyncHS
		.LINK0_CK_RxDetectEobHS      (csi2_rx_ck_ppi_hs_rxdetecteobhs),                //   input,   width = 1,                        .RxDetectEobHS
		.LINK0_CK_RxClkActiveHS      (mipi_dphy_link0_ck_ppi_rx_hs_rxclkactivehs),     //  output,   width = 1,                        .RxClkActiveHS
		.LINK0_CK_RxDDRClkHS         (mipi_dphy_link0_ck_ppi_rx_hs_rxddrclkhs),        //  output,   width = 1,                        .RxDDRClkHS
		.LINK0_CK_RxSkewCalHS        (mipi_dphy_link0_ck_ppi_rx_hs_rxskewcalhs),       //  output,   width = 1,                        .RxSkewCalHS
		.LINK0_CK_RxAlternateCalHS   (mipi_dphy_link0_ck_ppi_rx_hs_rxalternatecalhs),  //  output,   width = 1,                        .RxAlternateCalHS
		.LINK0_CK_RxErrorCalHS       (mipi_dphy_link0_ck_ppi_rx_hs_rxerrorcalhs),      //  output,   width = 1,                        .RxErrorCalHS
		.LINK0_D0_RxClkEsc           (mipi_dphy_link0_d0_ppi_rx_lp_rxclkesc),          //  output,   width = 1,      LINK0_D0_ppi_rx_lp.RxClkEsc
		.LINK0_D0_RxLpdtEsc          (mipi_dphy_link0_d0_ppi_rx_lp_rxlpdtesc),         //  output,   width = 1,                        .RxLpdtEsc
		.LINK0_D0_RxUlpsEsc          (mipi_dphy_link0_d0_ppi_rx_lp_rxulpsesc),         //  output,   width = 1,                        .RxUlpsEsc
		.LINK0_D0_RxTriggerEsc       (mipi_dphy_link0_d0_ppi_rx_lp_rxtriggeresc),      //  output,   width = 4,                        .RxTriggerEsc
		.LINK0_D0_RxWakeup           (mipi_dphy_link0_d0_ppi_rx_lp_rxwakeup),          //  output,   width = 1,                        .RxWakeup
		.LINK0_D0_RxDataEsc          (mipi_dphy_link0_d0_ppi_rx_lp_rxdataesc),         //  output,   width = 8,                        .RxDataEsc
		.LINK0_D0_RxValidEsc         (mipi_dphy_link0_d0_ppi_rx_lp_rxvalidesc),        //  output,   width = 1,                        .RxValidEsc
		.LINK0_D1_RxClkEsc           (mipi_dphy_link0_d1_ppi_rx_lp_rxclkesc),          //  output,   width = 1,      LINK0_D1_ppi_rx_lp.RxClkEsc
		.LINK0_D1_RxLpdtEsc          (mipi_dphy_link0_d1_ppi_rx_lp_rxlpdtesc),         //  output,   width = 1,                        .RxLpdtEsc
		.LINK0_D1_RxUlpsEsc          (mipi_dphy_link0_d1_ppi_rx_lp_rxulpsesc),         //  output,   width = 1,                        .RxUlpsEsc
		.LINK0_D1_RxTriggerEsc       (mipi_dphy_link0_d1_ppi_rx_lp_rxtriggeresc),      //  output,   width = 4,                        .RxTriggerEsc
		.LINK0_D1_RxWakeup           (mipi_dphy_link0_d1_ppi_rx_lp_rxwakeup),          //  output,   width = 1,                        .RxWakeup
		.LINK0_D1_RxDataEsc          (mipi_dphy_link0_d1_ppi_rx_lp_rxdataesc),         //  output,   width = 8,                        .RxDataEsc
		.LINK0_D1_RxValidEsc         (mipi_dphy_link0_d1_ppi_rx_lp_rxvalidesc),        //  output,   width = 1,                        .RxValidEsc
		.LINK0_CK_RxClkEsc           (mipi_dphy_link0_ck_ppi_rx_lp_rxclkesc),          //  output,   width = 1,      LINK0_CK_ppi_rx_lp.RxClkEsc
		.LINK0_CK_RxLpdtEsc          (mipi_dphy_link0_ck_ppi_rx_lp_rxlpdtesc),         //  output,   width = 1,                        .RxLpdtEsc
		.LINK0_CK_RxUlpsEsc          (mipi_dphy_link0_ck_ppi_rx_lp_rxulpsesc),         //  output,   width = 1,                        .RxUlpsEsc
		.LINK0_CK_RxTriggerEsc       (mipi_dphy_link0_ck_ppi_rx_lp_rxtriggeresc),      //  output,   width = 4,                        .RxTriggerEsc
		.LINK0_CK_RxWakeup           (mipi_dphy_link0_ck_ppi_rx_lp_rxwakeup),          //  output,   width = 1,                        .RxWakeup
		.LINK0_CK_RxDataEsc          (mipi_dphy_link0_ck_ppi_rx_lp_rxdataesc),         //  output,   width = 8,                        .RxDataEsc
		.LINK0_CK_RxValidEsc         (mipi_dphy_link0_ck_ppi_rx_lp_rxvalidesc),        //  output,   width = 1,                        .RxValidEsc
		.LINK0_D0_TurnRequest        (csi2_rx_d0_ppi_ctrl_turnrequest),                //   input,   width = 1,       LINK0_D0_ppi_ctrl.TurnRequest
		.LINK0_D0_Direction          (mipi_dphy_link0_d0_ppi_ctrl_direction),          //  output,   width = 1,                        .Direction
		.LINK0_D0_TurnDisable        (csi2_rx_d0_ppi_ctrl_turndisable),                //   input,   width = 1,                        .TurnDisable
		.LINK0_D0_ForceRxmode        (csi2_rx_d0_ppi_ctrl_forcerxmode),                //   input,   width = 1,                        .ForceRxmode
		.LINK0_D0_ForceTxStopmode    (csi2_rx_d0_ppi_ctrl_forcetxstopmode),            //   input,   width = 1,                        .ForceTxStopmode
		.LINK0_D0_Stopstate          (mipi_dphy_link0_d0_ppi_ctrl_stopstate),          //  output,   width = 1,                        .Stopstate
		.LINK0_D0_Enable             (csi2_rx_d0_ppi_ctrl_enable),                     //   input,   width = 1,                        .Enable
		.LINK0_D0_AlpMode            (csi2_rx_d0_ppi_ctrl_alpmode),                    //   input,   width = 1,                        .AlpMode
		.LINK0_D0_TxUlpsClk          (csi2_rx_d0_ppi_ctrl_txulpsclk),                  //   input,   width = 1,                        .TxUlpsClk
		.LINK0_D0_RxUlpsClkNot       (mipi_dphy_link0_d0_ppi_ctrl_rxulpsclknot),       //  output,   width = 1,                        .RxUlpsClkNot
		.LINK0_D0_UlpsActiveNot      (mipi_dphy_link0_d0_ppi_ctrl_ulpsactivenot),      //  output,   width = 1,                        .UlpsActiveNot
		.LINK0_D0_TxHSIdleClkHS      (csi2_rx_d0_ppi_ctrl_txhsidleclkhs),              //   input,   width = 1,                        .TxHSIdleClkHS
		.LINK0_D0_TxHSIdleClkReadyHS (mipi_dphy_link0_d0_ppi_ctrl_txhsidleclkreadyhs), //  output,   width = 1,                        .TxHSIdleClkReadyHS
		.LINK0_D1_TurnRequest        (csi2_rx_d1_ppi_ctrl_turnrequest),                //   input,   width = 1,       LINK0_D1_ppi_ctrl.TurnRequest
		.LINK0_D1_Direction          (mipi_dphy_link0_d1_ppi_ctrl_direction),          //  output,   width = 1,                        .Direction
		.LINK0_D1_TurnDisable        (csi2_rx_d1_ppi_ctrl_turndisable),                //   input,   width = 1,                        .TurnDisable
		.LINK0_D1_ForceRxmode        (csi2_rx_d1_ppi_ctrl_forcerxmode),                //   input,   width = 1,                        .ForceRxmode
		.LINK0_D1_ForceTxStopmode    (csi2_rx_d1_ppi_ctrl_forcetxstopmode),            //   input,   width = 1,                        .ForceTxStopmode
		.LINK0_D1_Stopstate          (mipi_dphy_link0_d1_ppi_ctrl_stopstate),          //  output,   width = 1,                        .Stopstate
		.LINK0_D1_Enable             (csi2_rx_d1_ppi_ctrl_enable),                     //   input,   width = 1,                        .Enable
		.LINK0_D1_AlpMode            (csi2_rx_d1_ppi_ctrl_alpmode),                    //   input,   width = 1,                        .AlpMode
		.LINK0_D1_TxUlpsClk          (csi2_rx_d1_ppi_ctrl_txulpsclk),                  //   input,   width = 1,                        .TxUlpsClk
		.LINK0_D1_RxUlpsClkNot       (mipi_dphy_link0_d1_ppi_ctrl_rxulpsclknot),       //  output,   width = 1,                        .RxUlpsClkNot
		.LINK0_D1_UlpsActiveNot      (mipi_dphy_link0_d1_ppi_ctrl_ulpsactivenot),      //  output,   width = 1,                        .UlpsActiveNot
		.LINK0_D1_TxHSIdleClkHS      (csi2_rx_d1_ppi_ctrl_txhsidleclkhs),              //   input,   width = 1,                        .TxHSIdleClkHS
		.LINK0_D1_TxHSIdleClkReadyHS (mipi_dphy_link0_d1_ppi_ctrl_txhsidleclkreadyhs), //  output,   width = 1,                        .TxHSIdleClkReadyHS
		.LINK0_CK_TurnRequest        (csi2_rx_ck_ppi_ctrl_turnrequest),                //   input,   width = 1,       LINK0_CK_ppi_ctrl.TurnRequest
		.LINK0_CK_Direction          (mipi_dphy_link0_ck_ppi_ctrl_direction),          //  output,   width = 1,                        .Direction
		.LINK0_CK_TurnDisable        (csi2_rx_ck_ppi_ctrl_turndisable),                //   input,   width = 1,                        .TurnDisable
		.LINK0_CK_ForceRxmode        (csi2_rx_ck_ppi_ctrl_forcerxmode),                //   input,   width = 1,                        .ForceRxmode
		.LINK0_CK_ForceTxStopmode    (csi2_rx_ck_ppi_ctrl_forcetxstopmode),            //   input,   width = 1,                        .ForceTxStopmode
		.LINK0_CK_Stopstate          (mipi_dphy_link0_ck_ppi_ctrl_stopstate),          //  output,   width = 1,                        .Stopstate
		.LINK0_CK_Enable             (csi2_rx_ck_ppi_ctrl_enable),                     //   input,   width = 1,                        .Enable
		.LINK0_CK_AlpMode            (csi2_rx_ck_ppi_ctrl_alpmode),                    //   input,   width = 1,                        .AlpMode
		.LINK0_CK_TxUlpsClk          (csi2_rx_ck_ppi_ctrl_txulpsclk),                  //   input,   width = 1,                        .TxUlpsClk
		.LINK0_CK_RxUlpsClkNot       (mipi_dphy_link0_ck_ppi_ctrl_rxulpsclknot),       //  output,   width = 1,                        .RxUlpsClkNot
		.LINK0_CK_UlpsActiveNot      (mipi_dphy_link0_ck_ppi_ctrl_ulpsactivenot),      //  output,   width = 1,                        .UlpsActiveNot
		.LINK0_CK_TxHSIdleClkHS      (csi2_rx_ck_ppi_ctrl_txhsidleclkhs),              //   input,   width = 1,                        .TxHSIdleClkHS
		.LINK0_CK_TxHSIdleClkReadyHS (mipi_dphy_link0_ck_ppi_ctrl_txhsidleclkreadyhs), //  output,   width = 1,                        .TxHSIdleClkReadyHS
		.LINK0_D0_ErrSotHS           (mipi_dphy_link0_d0_ppi_rx_err_errsoths),         //  output,   width = 1,     LINK0_D0_ppi_rx_err.ErrSotHS
		.LINK0_D0_ErrSotSyncHS       (mipi_dphy_link0_d0_ppi_rx_err_errsotsynchs),     //  output,   width = 1,                        .ErrSotSyncHS
		.LINK0_D0_ErrEsc             (mipi_dphy_link0_d0_ppi_rx_err_erresc),           //  output,   width = 1,                        .ErrEsc
		.LINK0_D0_ErrSyncEsc         (mipi_dphy_link0_d0_ppi_rx_err_errsyncesc),       //  output,   width = 1,                        .ErrSyncEsc
		.LINK0_D0_ErrControl         (mipi_dphy_link0_d0_ppi_rx_err_errcontrol),       //  output,   width = 1,                        .ErrControl
		.LINK0_D0_ErrContentionLP0   (mipi_dphy_link0_d0_ppi_rx_err_errcontentionlp0), //  output,   width = 1,                        .ErrContentionLP0
		.LINK0_D0_ErrContentionLP1   (mipi_dphy_link0_d0_ppi_rx_err_errcontentionlp1), //  output,   width = 1,                        .ErrContentionLP1
		.LINK0_D1_ErrSotHS           (mipi_dphy_link0_d1_ppi_rx_err_errsoths),         //  output,   width = 1,     LINK0_D1_ppi_rx_err.ErrSotHS
		.LINK0_D1_ErrSotSyncHS       (mipi_dphy_link0_d1_ppi_rx_err_errsotsynchs),     //  output,   width = 1,                        .ErrSotSyncHS
		.LINK0_D1_ErrEsc             (mipi_dphy_link0_d1_ppi_rx_err_erresc),           //  output,   width = 1,                        .ErrEsc
		.LINK0_D1_ErrSyncEsc         (mipi_dphy_link0_d1_ppi_rx_err_errsyncesc),       //  output,   width = 1,                        .ErrSyncEsc
		.LINK0_D1_ErrControl         (mipi_dphy_link0_d1_ppi_rx_err_errcontrol),       //  output,   width = 1,                        .ErrControl
		.LINK0_D1_ErrContentionLP0   (mipi_dphy_link0_d1_ppi_rx_err_errcontentionlp0), //  output,   width = 1,                        .ErrContentionLP0
		.LINK0_D1_ErrContentionLP1   (mipi_dphy_link0_d1_ppi_rx_err_errcontentionlp1), //  output,   width = 1,                        .ErrContentionLP1
		.LINK0_CK_ErrSotHS           (mipi_dphy_link0_ck_ppi_rx_err_errsoths),         //  output,   width = 1,     LINK0_CK_ppi_rx_err.ErrSotHS
		.LINK0_CK_ErrSotSyncHS       (mipi_dphy_link0_ck_ppi_rx_err_errsotsynchs),     //  output,   width = 1,                        .ErrSotSyncHS
		.LINK0_CK_ErrEsc             (mipi_dphy_link0_ck_ppi_rx_err_erresc),           //  output,   width = 1,                        .ErrEsc
		.LINK0_CK_ErrSyncEsc         (mipi_dphy_link0_ck_ppi_rx_err_errsyncesc),       //  output,   width = 1,                        .ErrSyncEsc
		.LINK0_CK_ErrControl         (mipi_dphy_link0_ck_ppi_rx_err_errcontrol),       //  output,   width = 1,                        .ErrControl
		.LINK0_CK_ErrContentionLP0   (mipi_dphy_link0_ck_ppi_rx_err_errcontentionlp0), //  output,   width = 1,                        .ErrContentionLP0
		.LINK0_CK_ErrContentionLP1   (mipi_dphy_link0_ck_ppi_rx_err_errcontentionlp1), //  output,   width = 1,                        .ErrContentionLP1
		.LINK0_dphy_link_dp          (mipi_dphy_LINK0_dphy_io_dphy_link_dp),           //   input,   width = 2,           LINK0_dphy_io.dphy_link_dp
		.LINK0_dphy_link_dn          (mipi_dphy_LINK0_dphy_io_dphy_link_dn),           //   input,   width = 2,                        .dphy_link_dn
		.LINK0_dphy_link_cp          (mipi_dphy_LINK0_dphy_io_dphy_link_cp),           //   input,   width = 1,                        .dphy_link_cp
		.LINK0_dphy_link_cn          (mipi_dphy_LINK0_dphy_io_dphy_link_cn),           //   input,   width = 1,                        .dphy_link_cn
		.reg_wr_en_o                 (mipi_dphy_reg_bus_reg_wr_en_o),                  //  output,   width = 1,                 reg_bus.reg_wr_en_o
		.reg_rd_en_o                 (mipi_dphy_reg_bus_reg_rd_en_o),                  //  output,   width = 1,                        .reg_rd_en_o
		.reg_raddr_o                 (mipi_dphy_reg_bus_reg_raddr_o),                  //  output,  width = 11,                        .reg_raddr_o
		.reg_waddr_o                 (mipi_dphy_reg_bus_reg_waddr_o),                  //  output,  width = 11,                        .reg_waddr_o
		.reg_be_o                    (mipi_dphy_reg_bus_reg_be_o),                     //  output,   width = 4,                        .reg_be_o
		.reg_din_o                   (mipi_dphy_reg_bus_reg_din_o),                    //  output,  width = 32,                        .reg_din_o
		.reg_dout_i                  (mipi_dphy_reg_bus_reg_dout_i)                    //   input,  width = 32,                        .reg_dout_i
	);

	csi2_dphy_sys_reset_release_0 reset_release_0 (
		.ninit_done (reset_release_0_ninit_done_reset)  //  output,  width = 1, ninit_done.reset
	);

	csi2_dphy_sys_rx_axi4s_clk_bridge rx_axi4s_clk_bridge (
		.in_clk  (rx_axi4s_clk_bridge_in_clk_clk),  //   input,  width = 1,  in_clk.clk
		.out_clk (rx_axi4s_clk_bridge_out_clk_clk)  //  output,  width = 1, out_clk.clk
	);

	altera_reset_controller #(
		.NUM_RESET_INPUTS          (1),
		.OUTPUT_RESET_SYNC_EDGES   ("deassert"),
		.SYNC_DEPTH                (2),
		.RESET_REQUEST_PRESENT     (0),
		.RESET_REQ_WAIT_TIME       (1),
		.MIN_RST_ASSERTION_TIME    (3),
		.RESET_REQ_EARLY_DSRT_TIME (1),
		.USE_RESET_REQUEST_IN0     (0),
		.USE_RESET_REQUEST_IN1     (0),
		.USE_RESET_REQUEST_IN2     (0),
		.USE_RESET_REQUEST_IN3     (0),
		.USE_RESET_REQUEST_IN4     (0),
		.USE_RESET_REQUEST_IN5     (0),
		.USE_RESET_REQUEST_IN6     (0),
		.USE_RESET_REQUEST_IN7     (0),
		.USE_RESET_REQUEST_IN8     (0),
		.USE_RESET_REQUEST_IN9     (0),
		.USE_RESET_REQUEST_IN10    (0),
		.USE_RESET_REQUEST_IN11    (0),
		.USE_RESET_REQUEST_IN12    (0),
		.USE_RESET_REQUEST_IN13    (0),
		.USE_RESET_REQUEST_IN14    (0),
		.USE_RESET_REQUEST_IN15    (0),
		.ADAPT_RESET_REQUEST       (0)
	) rst_controller (
		.reset_in0      (reset_release_0_ninit_done_reset), //   input,  width = 1, reset_in0.reset
		.clk            (rx_axi4s_clk_bridge_out_clk_clk),  //   input,  width = 1,       clk.clk
		.reset_out      (rst_controller_reset_out_reset),   //  output,  width = 1, reset_out.reset
		.reset_req      (),                                 // (terminated),                       
		.reset_req_in0  (1'b0),                             // (terminated),                       
		.reset_in1      (1'b0),                             // (terminated),                       
		.reset_req_in1  (1'b0),                             // (terminated),                       
		.reset_in2      (1'b0),                             // (terminated),                       
		.reset_req_in2  (1'b0),                             // (terminated),                       
		.reset_in3      (1'b0),                             // (terminated),                       
		.reset_req_in3  (1'b0),                             // (terminated),                       
		.reset_in4      (1'b0),                             // (terminated),                       
		.reset_req_in4  (1'b0),                             // (terminated),                       
		.reset_in5      (1'b0),                             // (terminated),                       
		.reset_req_in5  (1'b0),                             // (terminated),                       
		.reset_in6      (1'b0),                             // (terminated),                       
		.reset_req_in6  (1'b0),                             // (terminated),                       
		.reset_in7      (1'b0),                             // (terminated),                       
		.reset_req_in7  (1'b0),                             // (terminated),                       
		.reset_in8      (1'b0),                             // (terminated),                       
		.reset_req_in8  (1'b0),                             // (terminated),                       
		.reset_in9      (1'b0),                             // (terminated),                       
		.reset_req_in9  (1'b0),                             // (terminated),                       
		.reset_in10     (1'b0),                             // (terminated),                       
		.reset_req_in10 (1'b0),                             // (terminated),                       
		.reset_in11     (1'b0),                             // (terminated),                       
		.reset_req_in11 (1'b0),                             // (terminated),                       
		.reset_in12     (1'b0),                             // (terminated),                       
		.reset_req_in12 (1'b0),                             // (terminated),                       
		.reset_in13     (1'b0),                             // (terminated),                       
		.reset_req_in13 (1'b0),                             // (terminated),                       
		.reset_in14     (1'b0),                             // (terminated),                       
		.reset_req_in14 (1'b0),                             // (terminated),                       
		.reset_in15     (1'b0),                             // (terminated),                       
		.reset_req_in15 (1'b0)                              // (terminated),                       
	);

	altera_reset_controller #(
		.NUM_RESET_INPUTS          (1),
		.OUTPUT_RESET_SYNC_EDGES   ("deassert"),
		.SYNC_DEPTH                (2),
		.RESET_REQUEST_PRESENT     (0),
		.RESET_REQ_WAIT_TIME       (1),
		.MIN_RST_ASSERTION_TIME    (3),
		.RESET_REQ_EARLY_DSRT_TIME (1),
		.USE_RESET_REQUEST_IN0     (0),
		.USE_RESET_REQUEST_IN1     (0),
		.USE_RESET_REQUEST_IN2     (0),
		.USE_RESET_REQUEST_IN3     (0),
		.USE_RESET_REQUEST_IN4     (0),
		.USE_RESET_REQUEST_IN5     (0),
		.USE_RESET_REQUEST_IN6     (0),
		.USE_RESET_REQUEST_IN7     (0),
		.USE_RESET_REQUEST_IN8     (0),
		.USE_RESET_REQUEST_IN9     (0),
		.USE_RESET_REQUEST_IN10    (0),
		.USE_RESET_REQUEST_IN11    (0),
		.USE_RESET_REQUEST_IN12    (0),
		.USE_RESET_REQUEST_IN13    (0),
		.USE_RESET_REQUEST_IN14    (0),
		.USE_RESET_REQUEST_IN15    (0),
		.ADAPT_RESET_REQUEST       (0)
	) rst_controller_001 (
		.reset_in0      (reset_release_0_ninit_done_reset),   //   input,  width = 1, reset_in0.reset
		.clk            (mipi_dphy_link0_link_core_clk_clk),  //   input,  width = 1,       clk.clk
		.reset_out      (rst_controller_001_reset_out_reset), //  output,  width = 1, reset_out.reset
		.reset_req      (),                                   // (terminated),                       
		.reset_req_in0  (1'b0),                               // (terminated),                       
		.reset_in1      (1'b0),                               // (terminated),                       
		.reset_req_in1  (1'b0),                               // (terminated),                       
		.reset_in2      (1'b0),                               // (terminated),                       
		.reset_req_in2  (1'b0),                               // (terminated),                       
		.reset_in3      (1'b0),                               // (terminated),                       
		.reset_req_in3  (1'b0),                               // (terminated),                       
		.reset_in4      (1'b0),                               // (terminated),                       
		.reset_req_in4  (1'b0),                               // (terminated),                       
		.reset_in5      (1'b0),                               // (terminated),                       
		.reset_req_in5  (1'b0),                               // (terminated),                       
		.reset_in6      (1'b0),                               // (terminated),                       
		.reset_req_in6  (1'b0),                               // (terminated),                       
		.reset_in7      (1'b0),                               // (terminated),                       
		.reset_req_in7  (1'b0),                               // (terminated),                       
		.reset_in8      (1'b0),                               // (terminated),                       
		.reset_req_in8  (1'b0),                               // (terminated),                       
		.reset_in9      (1'b0),                               // (terminated),                       
		.reset_req_in9  (1'b0),                               // (terminated),                       
		.reset_in10     (1'b0),                               // (terminated),                       
		.reset_req_in10 (1'b0),                               // (terminated),                       
		.reset_in11     (1'b0),                               // (terminated),                       
		.reset_req_in11 (1'b0),                               // (terminated),                       
		.reset_in12     (1'b0),                               // (terminated),                       
		.reset_req_in12 (1'b0),                               // (terminated),                       
		.reset_in13     (1'b0),                               // (terminated),                       
		.reset_req_in13 (1'b0),                               // (terminated),                       
		.reset_in14     (1'b0),                               // (terminated),                       
		.reset_req_in14 (1'b0),                               // (terminated),                       
		.reset_in15     (1'b0),                               // (terminated),                       
		.reset_req_in15 (1'b0)                                // (terminated),                       
	);

endmodule
