// csi2_dphy_sys_csi2_tx_intel_mipi_csi2_intel_axi2cv_300_s44gidq.v

// Generated using ACDS version 25.3 109

`timescale 1 ps / 1 ps
module csi2_dphy_sys_csi2_tx_intel_mipi_csi2_intel_axi2cv_300_s44gidq #(
		parameter FAMILY                               = "Agilex 5",
		parameter PROTOCOL                             = 1,
		parameter USE_ACTUAL_VID_CLK                   = 0,
		parameter CLOCKS_ARE_SAME                      = 0,
		parameter USE_CONTROL                          = 1,
		parameter NUMBER_OF_COLOUR_PLANES              = 3,
		parameter PIXELS_IN_PARALLEL                   = 2,
		parameter BPS                                  = 8,
		parameter NUMBER_OF_VIDEO_STREAMING_INTERFACES = 1,
		parameter H_ACTIVE_PIXELS                      = 1920,
		parameter H_BLANK                              = 0,
		parameter H_FRONT_PORCH                        = 88,
		parameter H_SYNC_LENGTH                        = 44,
		parameter H_BACK_PORCH                         = 148,
		parameter V_ACTIVE_LINES                       = 1200,
		parameter V_BLANK                              = 0,
		parameter V_FRONT_PORCH                        = 4,
		parameter V_SYNC_LENGTH                        = 5,
		parameter V_BACK_PORCH                         = 36,
		parameter AP_LINE                              = 0,
		parameter F_RISING_EDGE                        = 0,
		parameter F_FALLING_EDGE                       = 0,
		parameter FIELD0_V_RISING_EDGE                 = 0,
		parameter FIELD0_V_BLANK                       = 0,
		parameter FIELD0_V_FRONT_PORCH                 = 0,
		parameter FIELD0_V_SYNC_LENGTH                 = 0,
		parameter FIELD0_V_BACK_PORCH                  = 0,
		parameter FIFO_DEPTH                           = 1920,
		parameter SUPPORT_6G_12G_SDI                   = 0,
		parameter USE_EMBEDDED_SYNCS                   = 0,
		parameter ANC_LINE                             = 0,
		parameter FIELD0_ANC_LINE                      = 0,
		parameter DEFAULT_VID_STD                      = 3,
		parameter STD_WIDTH                            = 1,
		parameter GENERATE_SYNC                        = 0,
		parameter ACCEPT_SYNC                          = 0,
		parameter COUNT_STEP_IS_PIP_VALUE              = 0,
		parameter AUX_DATA_WIDTH                       = 32,
		parameter MIPI_VIDEO_INTERFACE_MODE            = "simple",
		parameter MIPI_TUSER_WIDTH                     = 1,
		parameter ENABLE_DEBUG                         = 1
	) (
		input  wire        axi4s_clock_clk,       //          axi4s_clock.clk,          Clock Input
		input  wire        axi4s_reset_reset,     //          axi4s_reset.reset,        Reset Input
		input  wire [47:0] axi4s_vid_in_0_tdata,  //       axi4s_vid_in_0.tdata
		input  wire        axi4s_vid_in_0_tvalid, //                     .tvalid
		output wire        axi4s_vid_in_0_tready, //                     .tready
		input  wire        axi4s_vid_in_0_tlast,  //                     .tlast
		input  wire [5:0]  axi4s_vid_in_0_tuser,  //                     .tuser
		input  wire        cv_vid_clk,            //           cv_vid_clk.clk
		output wire [47:0] cv_vid_out_data,       //      cv_vid_out_data.export
		output wire        cv_vid_out_datavalid,  // cv_vid_out_datavalid.export
		input  wire        cv_vid_out_ready,      //     cv_vid_out_ready.export
		output wire [1:0]  cv_vid_out_de,         //        cv_vid_out_de.export
		output wire [1:0]  cv_vid_out_eol,        //       cv_vid_out_eol.export
		output wire [5:0]  cv_vid_out_dt,         //        cv_vid_out_dt.export
		output wire [3:0]  cv_vid_out_vc,         //        cv_vid_out_vc.export
		output wire        cv_vid_out_even,       //      cv_vid_out_even.export
		output wire [31:0] cv_aux_out_data,       //      cv_aux_out_data.export
		output wire [3:0]  cv_aux_out_de,         //        cv_aux_out_de.export
		output wire        cv_aux_out_valid,      //     cv_aux_out_valid.export
		output wire        cv_aux_out_sop,        //       cv_aux_out_sop.export
		output wire        cv_aux_out_eop,        //       cv_aux_out_eop.export
		output wire [5:0]  cv_aux_out_dt,         //        cv_aux_out_dt.export
		output wire [3:0]  cv_aux_out_vc,         //        cv_aux_out_vc.export
		output wire [1:0]  cv_aux_out_type,       //      cv_aux_out_type.export
		output wire [2:0]  cv_aux_out_empty,      //     cv_aux_out_empty.export
		input  wire        cv_aux_out_ready,      //     cv_aux_out_ready.export
		input  wire [8:0]  csr_address,           //                  csr.address
		input  wire        csr_write,             //                     .write
		input  wire [3:0]  csr_byteenable,        //                     .byteenable
		input  wire [31:0] csr_writedata,         //                     .writedata
		input  wire        csr_read,              //                     .read
		output wire [31:0] csr_readdata,          //                     .readdata
		output wire        csr_readdatavalid,     //                     .readdatavalid
		output wire        csr_waitrequest,       //                     .waitrequest
		input  wire        csr_clock_clk          //            csr_clock.clk,          Clock Input
	);

	generate
		// If any of the display statements (or deliberately broken
		// instantiations) within this generate block triggers then this module
		// has been instantiated this module with a set of parameters different
		// from those it was generated for.  This will usually result in a
		// non-functioning system.
		if (FAMILY != "Agilex 5")
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					family_check ( .error(1'b1) );
		end
		if (PROTOCOL != 1)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					protocol_check ( .error(1'b1) );
		end
		if (USE_CONTROL != 1)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					use_control_check ( .error(1'b1) );
		end
		if (NUMBER_OF_COLOUR_PLANES != 3)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					number_of_colour_planes_check ( .error(1'b1) );
		end
		if (PIXELS_IN_PARALLEL != 2)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					pixels_in_parallel_check ( .error(1'b1) );
		end
		if (BPS != 8)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					bps_check ( .error(1'b1) );
		end
		if (NUMBER_OF_VIDEO_STREAMING_INTERFACES != 1)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					number_of_video_streaming_interfaces_check ( .error(1'b1) );
		end
		if (USE_EMBEDDED_SYNCS != 0)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					use_embedded_syncs_check ( .error(1'b1) );
		end
		if (GENERATE_SYNC != 0)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					generate_sync_check ( .error(1'b1) );
		end
		if (ACCEPT_SYNC != 0)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					accept_sync_check ( .error(1'b1) );
		end
		if (AUX_DATA_WIDTH != 32)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					aux_data_width_check ( .error(1'b1) );
		end
		if (MIPI_VIDEO_INTERFACE_MODE != "simple")
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					mipi_video_interface_mode_check ( .error(1'b1) );
		end
		if (MIPI_TUSER_WIDTH != 1)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					mipi_tuser_width_check ( .error(1'b1) );
		end
		if (ENABLE_DEBUG != 1)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					enable_debug_check ( .error(1'b1) );
		end
	endgenerate

	csi2_dphy_sys_csi2_tx_intel_axi2cv_2140_33bhxrq #(
		.FAMILY                               ("Agilex 5"),
		.PROTOCOL                             (1),
		.USE_ACTUAL_VID_CLK                   (USE_ACTUAL_VID_CLK),
		.CLOCKS_ARE_SAME                      (CLOCKS_ARE_SAME),
		.USE_CONTROL                          (1),
		.NUMBER_OF_COLOUR_PLANES              (3),
		.PIXELS_IN_PARALLEL                   (2),
		.BPS                                  (8),
		.NUMBER_OF_VIDEO_STREAMING_INTERFACES (1),
		.H_ACTIVE_PIXELS                      (H_ACTIVE_PIXELS),
		.H_BLANK                              (H_BLANK),
		.H_FRONT_PORCH                        (H_FRONT_PORCH),
		.H_SYNC_LENGTH                        (H_SYNC_LENGTH),
		.H_BACK_PORCH                         (H_BACK_PORCH),
		.V_ACTIVE_LINES                       (V_ACTIVE_LINES),
		.V_BLANK                              (V_BLANK),
		.V_FRONT_PORCH                        (V_FRONT_PORCH),
		.V_SYNC_LENGTH                        (V_SYNC_LENGTH),
		.V_BACK_PORCH                         (V_BACK_PORCH),
		.AP_LINE                              (AP_LINE),
		.F_RISING_EDGE                        (F_RISING_EDGE),
		.F_FALLING_EDGE                       (F_FALLING_EDGE),
		.FIELD0_V_RISING_EDGE                 (FIELD0_V_RISING_EDGE),
		.FIELD0_V_BLANK                       (FIELD0_V_BLANK),
		.FIELD0_V_FRONT_PORCH                 (FIELD0_V_FRONT_PORCH),
		.FIELD0_V_SYNC_LENGTH                 (FIELD0_V_SYNC_LENGTH),
		.FIELD0_V_BACK_PORCH                  (FIELD0_V_BACK_PORCH),
		.FIFO_DEPTH                           (FIFO_DEPTH),
		.SUPPORT_6G_12G_SDI                   (SUPPORT_6G_12G_SDI),
		.USE_EMBEDDED_SYNCS                   (0),
		.ANC_LINE                             (ANC_LINE),
		.FIELD0_ANC_LINE                      (FIELD0_ANC_LINE),
		.DEFAULT_VID_STD                      (DEFAULT_VID_STD),
		.STD_WIDTH                            (STD_WIDTH),
		.GENERATE_SYNC                        (0),
		.ACCEPT_SYNC                          (0),
		.COUNT_STEP_IS_PIP_VALUE              (COUNT_STEP_IS_PIP_VALUE),
		.AUX_DATA_WIDTH                       (32),
		.MIPI_VIDEO_INTERFACE_MODE            ("simple"),
		.MIPI_TUSER_WIDTH                     (1),
		.ENABLE_DEBUG                         (1)
	) axi2cv (
		.axi4s_clock_clk       (axi4s_clock_clk),       //   input,   width = 1,          axi4s_clock.clk
		.axi4s_reset_reset     (axi4s_reset_reset),     //   input,   width = 1,          axi4s_reset.reset
		.axi4s_vid_in_0_tdata  (axi4s_vid_in_0_tdata),  //   input,  width = 48,       axi4s_vid_in_0.tdata
		.axi4s_vid_in_0_tvalid (axi4s_vid_in_0_tvalid), //   input,   width = 1,                     .tvalid
		.axi4s_vid_in_0_tready (axi4s_vid_in_0_tready), //  output,   width = 1,                     .tready
		.axi4s_vid_in_0_tlast  (axi4s_vid_in_0_tlast),  //   input,   width = 1,                     .tlast
		.axi4s_vid_in_0_tuser  (axi4s_vid_in_0_tuser),  //   input,   width = 6,                     .tuser
		.cv_vid_clk            (cv_vid_clk),            //   input,   width = 1,           cv_vid_clk.clk
		.cv_vid_out_data       (cv_vid_out_data),       //  output,  width = 48,      cv_vid_out_data.export
		.cv_vid_out_datavalid  (cv_vid_out_datavalid),  //  output,   width = 1, cv_vid_out_datavalid.export
		.cv_vid_out_ready      (cv_vid_out_ready),      //   input,   width = 1,     cv_vid_out_ready.export
		.cv_vid_out_de         (cv_vid_out_de),         //  output,   width = 2,        cv_vid_out_de.export
		.cv_vid_out_eol        (cv_vid_out_eol),        //  output,   width = 2,       cv_vid_out_eol.export
		.cv_vid_out_dt         (cv_vid_out_dt),         //  output,   width = 6,        cv_vid_out_dt.export
		.cv_vid_out_vc         (cv_vid_out_vc),         //  output,   width = 4,        cv_vid_out_vc.export
		.cv_vid_out_even       (cv_vid_out_even),       //  output,   width = 1,      cv_vid_out_even.export
		.cv_aux_out_data       (cv_aux_out_data),       //  output,  width = 32,      cv_aux_out_data.export
		.cv_aux_out_de         (cv_aux_out_de),         //  output,   width = 4,        cv_aux_out_de.export
		.cv_aux_out_valid      (cv_aux_out_valid),      //  output,   width = 1,     cv_aux_out_valid.export
		.cv_aux_out_sop        (cv_aux_out_sop),        //  output,   width = 1,       cv_aux_out_sop.export
		.cv_aux_out_eop        (cv_aux_out_eop),        //  output,   width = 1,       cv_aux_out_eop.export
		.cv_aux_out_dt         (cv_aux_out_dt),         //  output,   width = 6,        cv_aux_out_dt.export
		.cv_aux_out_vc         (cv_aux_out_vc),         //  output,   width = 4,        cv_aux_out_vc.export
		.cv_aux_out_type       (cv_aux_out_type),       //  output,   width = 2,      cv_aux_out_type.export
		.cv_aux_out_empty      (cv_aux_out_empty),      //  output,   width = 3,     cv_aux_out_empty.export
		.cv_aux_out_ready      (cv_aux_out_ready),      //   input,   width = 1,     cv_aux_out_ready.export
		.csr_address           (csr_address),           //   input,   width = 9,                  csr.address
		.csr_write             (csr_write),             //   input,   width = 1,                     .write
		.csr_byteenable        (csr_byteenable),        //   input,   width = 4,                     .byteenable
		.csr_writedata         (csr_writedata),         //   input,  width = 32,                     .writedata
		.csr_read              (csr_read),              //   input,   width = 1,                     .read
		.csr_readdata          (csr_readdata),          //  output,  width = 32,                     .readdata
		.csr_readdatavalid     (csr_readdatavalid),     //  output,   width = 1,                     .readdatavalid
		.csr_waitrequest       (csr_waitrequest),       //  output,   width = 1,                     .waitrequest
		.csr_clock_clk         (csr_clock_clk)          //   input,   width = 1,            csr_clock.clk
	);

endmodule
