// one_ai_interface_0.v

// Generated using ACDS version 25.3 109

`timescale 1 ps / 1 ps
module one_ai_interface_0 #(
		parameter[31:0] BUFFER_BASE_ADDR = 32'b00000000000010000000000000000000
	) (
		input  wire        clk,               //              clock.clk
		input  wire        reset_n,           //              reset.reset_n
		output wire [31:0] avm_address,       //    avalon_master_0.address
		output wire        avm_read,          //                   .read
		input  wire [31:0] avm_readdata,      //                   .readdata
		input  wire        avm_waitrequest,   //                   .waitrequest
		input  wire        avm_readdatavalid, //                   .readdatavalid
		output wire [7:0]  avm_burstcount,    //                   .burstcount
		input  wire [7:0]  avs_address,       //     avalon_slave_0.address
		input  wire        avs_read,          //                   .read
		output wire [31:0] avs_readdata,      //                   .readdata
		input  wire        avs_write,         //                   .write
		input  wire [31:0] avs_writedata,     //                   .writedata
		input  wire        frame_writer_irq   // interrupt_receiver.irq
	);

	ONE_AI_Interface #(
		.BUFFER_BASE_ADDR     (BUFFER_BASE_ADDR),
		.USE_COMPRESSED_INPUT (1)
	) one_ai_interface_0 (
		.clk               (clk),               //   input,   width = 1,              clock.clk
		.reset_n           (reset_n),           //   input,   width = 1,              reset.reset_n
		.avm_address       (avm_address),       //  output,  width = 32,    avalon_master_0.address
		.avm_read          (avm_read),          //  output,   width = 1,                   .read
		.avm_readdata      (avm_readdata),      //   input,  width = 32,                   .readdata
		.avm_waitrequest   (avm_waitrequest),   //   input,   width = 1,                   .waitrequest
		.avm_readdatavalid (avm_readdatavalid), //   input,   width = 1,                   .readdatavalid
		.avm_burstcount    (avm_burstcount),    //  output,   width = 8,                   .burstcount
		.avs_address       (avs_address),       //   input,   width = 8,     avalon_slave_0.address
		.avs_read          (avs_read),          //   input,   width = 1,                   .read
		.avs_readdata      (avs_readdata),      //  output,  width = 32,                   .readdata
		.avs_write         (avs_write),         //   input,   width = 1,                   .write
		.avs_writedata     (avs_writedata),     //   input,  width = 32,                   .writedata
		.frame_writer_irq  (frame_writer_irq)   //   input,   width = 1, interrupt_receiver.irq
	);

endmodule
